export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped xDAI";
        readonly address: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d";
        readonly symbol: "WXDAI";
        readonly oracleId: "WXDAI";
        readonly decimals: 18;
        readonly chainId: 100;
        readonly website: "https://www.gnosis.io/";
        readonly description: "xDai is the native currency built on the Gnosis blockchain, it is generated when a Dai is sent to the xDai bridge, the bridge validators mint the xDai as part of the Gnosis reward native contract.";
        readonly bridge: "gnosis-canonical";
        readonly documentation: "https://docs.gnosischain.com/about/tokens/xdai";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly FEES: {
        readonly name: "Wrapped xDAI";
        readonly address: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d";
        readonly symbol: "WXDAI";
        readonly oracleId: "WXDAI";
        readonly decimals: 18;
        readonly chainId: 100;
        readonly website: "https://www.gnosis.io/";
        readonly description: "xDai is the native currency built on the Gnosis blockchain, it is generated when a Dai is sent to the xDai bridge, the bridge validators mint the xDai as part of the Gnosis reward native contract.";
        readonly bridge: "gnosis-canonical";
        readonly documentation: "https://docs.gnosischain.com/about/tokens/xdai";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly xDAI: {
        readonly name: "Wrapped xDAI";
        readonly address: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d";
        readonly symbol: "WXDAI";
        readonly oracleId: "WXDAI";
        readonly decimals: 18;
        readonly chainId: 100;
        readonly website: "https://www.gnosis.io/";
        readonly description: "xDai is the native currency built on the Gnosis blockchain, it is generated when a Dai is sent to the xDai bridge, the bridge validators mint the xDai as part of the Gnosis reward native contract.";
        readonly bridge: "gnosis-canonical";
        readonly documentation: "https://docs.gnosischain.com/about/tokens/xdai";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly WXDAI: {
        readonly name: "Wrapped xDAI";
        readonly address: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d";
        readonly symbol: "WXDAI";
        readonly oracleId: "WXDAI";
        readonly decimals: 18;
        readonly chainId: 100;
        readonly website: "https://www.gnosis.io/";
        readonly description: "xDai is the native currency built on the Gnosis blockchain, it is generated when a Dai is sent to the xDai bridge, the bridge validators mint the xDai as part of the Gnosis reward native contract.";
        readonly bridge: "gnosis-canonical";
        readonly documentation: "https://docs.gnosischain.com/about/tokens/xdai";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly AURA: {
        readonly name: "Aura";
        readonly symbol: "AURA";
        readonly oracleId: "AURA";
        readonly address: "0x1509706a6c66CA549ff0cB464de88231DDBe213B";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://aura.finance/";
        readonly description: "Aura Finance is a protocol built on top of the Balancer system to provide maximum incentives to Balancer liquidity providers and BAL stakers (into veBAL) through social aggregation of BAL deposits and Aura’s native token. For BAL stakers, Aura provides a seamless onboarding process to veBAL, by creating a tokenised wrapper token called auraBAL that represents the 80/20 BPT locked up for the maximum time in VotingEscrow (read more about what this means). This can be staked to receive existing rewards (BAL and bbaUSD) from Balancer, in addition to a share of any BAL earned by Aura (read more about the fees), and additional AURA. This minting process is irreversible however users can trade their auraBAL back to BAL through an incentivised liquidity pool.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.aura.finance/";
    };
    readonly wstETH: {
        readonly name: "Lido Wrapped Staked ETH";
        readonly symbol: "wstETH";
        readonly oracleId: "wstETH";
        readonly address: "0x6C76971f98945AE98dD7d4DFcA8711ebea946eA6";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://lido.fi/";
        readonly description: "Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.";
        readonly bridge: "gnosis-canonical";
        readonly documentation: "https://docs.lido.fi/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly BAL: {
        readonly name: "Balancer";
        readonly symbol: "BAL";
        readonly oracleId: "BAL";
        readonly address: "0x7eF541E2a22058048904fE5744f9c7E4C57AF717";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://balancer.fi/";
        readonly description: "Balancer turns the concept of an index fund on its head: instead of a paying fees to portfolio managers to rebalance your portfolio, you collect fees from traders, who rebalance your portfolio by following arbitrage opportunities. ";
        readonly documentation: "https://docs.balancer.fi/";
        readonly bridge: "gnosis-canonical";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly WETH: {
        readonly name: "Wrapped Ether";
        readonly address: "0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 100;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "gnosis-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly USDT: {
        readonly name: "USDT";
        readonly symbol: "USDT";
        readonly oracleId: "USDT";
        readonly address: "0x4ECaBa5870353805a9F068101A40E0f32ed605C6";
        readonly chainId: 100;
        readonly decimals: 6;
        readonly website: "https://tether.to/";
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly bridge: "gnosis-canonical";
        readonly documentation: "https://tether.to/en/how-it-works";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly USDC: {
        readonly name: "USD Coin";
        readonly address: "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83";
        readonly symbol: "USDC";
        readonly oracleId: "USDC";
        readonly decimals: 6;
        readonly website: "https://www.centre.io/";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly chainId: 100;
        readonly documentation: "https://www.circle.com/en/usdc-multichain/arbitrum";
        readonly bridge: "gnosis-canonical";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly EURe: {
        readonly name: "Monerium EURe emoney";
        readonly symbol: "EURe";
        readonly oracleId: "EURe";
        readonly address: "0xcB444e90D8198415266c6a2724b7900fb12FC56E";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://monerium.com/";
        readonly bridge: "gnosis-canonical";
        readonly documentation: "https://monerium.dev/";
        readonly description: "EURe is a Euro stable-coin from Monerium. Monerium is the first company authorized to issue money on blockchains under European financial regulation. They have issued EUR, USD, GBP, and ISK as e-money tokens on Ethereum and EUR on Algorand. Monerium also operates a gateway for instant transfers of EUR between bank accounts and blockchain wallets/smart contracts.";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly sDAI: {
        readonly name: "Savings xDAI";
        readonly symbol: "sDAI";
        readonly oracleId: "gsDAI";
        readonly address: "0xaf204776c7245bF4147c2612BF6e5972Ee483701";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://spark.fi/";
        readonly documentation: "https://docs.spark.fi/";
        readonly bridge: "gnosis-canonical";
        readonly description: "Savings Dai (sDAI) is an ERC-4626 representation/wrapper of DAI in the Dai Savings Rate (DSR) module. sDAI allows users to deposit DAI to receive the yield generated by the Maker protocol while still being able to transfer, stake, lend and use it in any way you want.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly GNO: {
        readonly chainId: 100;
        readonly address: "0x9C58BAcC331c9aa871AFD802DB6379a98e80CEdb";
        readonly decimals: 18;
        readonly name: "Gnosis Token";
        readonly symbol: "GNO";
        readonly oracleId: "GNO";
        readonly website: "https://www.gnosis.io/";
        readonly documentation: "https://www.gnosis.io/developers";
        readonly bridge: "gnosis-canonical";
        readonly description: "Gnosis is a community-run chain that is created by nodes run by thousands of ordinary people around the globe. As a distributed network, a diverse set of nodes ensure that the network is resilient to technical failures. A diversity of nodes run across many countries ensures the network can remain credibly neutral infrastructure.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly COW: {
        readonly chainId: 100;
        readonly address: "0x177127622c4A00F3d409B75571e12cB3c8973d3c";
        readonly decimals: 18;
        readonly name: "CoW Protocol";
        readonly symbol: "COW";
        readonly oracleId: "COW";
        readonly website: "https://cow.fi/";
        readonly documentation: "https://docs.cow.fi/";
        readonly bridge: "gnosis-canonical";
        readonly description: "CoW Protocol finds the lowest price for your trade across all exchanges and aggregators, such as Uniswap and 1inch – and protects you from MEV, unlike the others.";
    };
    readonly crvUSD: {
        readonly name: "Curve USD Stablecoin";
        readonly symbol: "crvUSD";
        readonly oracleId: "crvUSD";
        readonly address: "0xaBEf652195F98A91E490f047A5006B71c85f058d";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://curve.finance/crvusd";
        readonly description: "crvUSD is a collateralized-debt-position (CDP) stablecoin pegged to the US Dollar";
        readonly documentation: "https://docs.curve.finance/crvUSD/crvUSD/";
        readonly bridge: "gnosis-canonical";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly USDCe: {
        readonly name: "Bridged USDC (Gnosis)";
        readonly symbol: "USDCe";
        readonly oracleId: "gUSDCe";
        readonly address: "0x2a22f9c3b484c3629090FeED35F17Ff8F88f76F0";
        readonly chainId: 100;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/en/usdc";
        readonly description: "USDC.e on the Gnosis Chain follows the Circle standard. Issued by regulated financial institutions, it is backed by fully reserved assets and is redeemable on a 1:1 basis for US dollars. This version facilitates future bridging via Circle’s Cross-Chain Transfer Protocol (CCTP).";
        readonly documentation: "https://docs.gnosischain.com/bridges/About%20Token%20Bridges/omnibridge#usdce-a-usdc-token-on-gnosis-chain-that-complies-with-circle-standard";
        readonly bridge: "gnosis-canonical";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly EURA: {
        readonly name: "EURA (previously agEUR)";
        readonly symbol: "EURA";
        readonly oracleId: "agEUR";
        readonly address: "0x4b1E2c2762667331Bc91648052F646d1b0d35984";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://app.angle.money/";
        readonly description: "EURA (previously agEUR) is pegged to the value of the Euro (€) and is a product of Angle, a decentralized, capital-efficient and over-collateralized stablecoins protocol.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.angle.money/";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly stEUR: {
        readonly name: "Staked EURA";
        readonly symbol: "stEUR";
        readonly oracleId: "stEUR";
        readonly address: "0x004626A008B1aCdC4c74ab51644093b155e59A23";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://app.angle.money/";
        readonly description: "stEUR is a yield-bearing stablecoin received when depositing EURA into the Angle savings solution, with its value increasing over time due to earned yield. It is an ERC20 token, liquid, and tradeable on decentralized exchanges, allowing automatic yield earnings.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.angle.money/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly rETH: {
        readonly name: "Rocket Pool ETH from Mainnet";
        readonly symbol: "rETH";
        readonly oracleId: "rETH";
        readonly address: "0xc791240D1F2dEf5938E2031364Ff4ed887133C3d";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://rocketpool.net/";
        readonly description: "As a Rocket Pool staker, your role is to deposit ETH into the deposit pool which will enable a node operator to create a new Beacon Chain validator. You can stake as little as 0.01 ETH. In doing so, you will be given a token called rETH. rETH represents both how much ETH you deposited, and when you deposited it.";
        readonly bridge: "gnosis-canonical";
        readonly documentation: "https://docs.rocketpool.net/guides/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly agGNO: {
        readonly name: "Aave GNO";
        readonly symbol: "agGNO";
        readonly oracleId: "agGNO";
        readonly address: "0xA1Fa064A85266E2Ca82DEe5C5CcEC84DF445760e";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Aave interest bearing GNO.";
    };
    readonly wagGNO: {
        readonly name: "Wrapped Aave GNO";
        readonly symbol: "wagGNO";
        readonly oracleId: "wagGNO";
        readonly address: "0x7c16F0185A26Db0AE7a9377f23BC18ea7ce5d644";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Wrapped Aave interest bearing GNO.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly agwstETH: {
        readonly name: "Aave wstETH";
        readonly symbol: "agwstETH";
        readonly oracleId: "agwstETH";
        readonly address: "0x23e4E76D01B2002BE436CE8d6044b0aA2f68B68a";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Aave interest bearing wstETH.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly wagwstETH: {
        readonly name: "Wrapped Aave wstETH";
        readonly symbol: "wagwstETH";
        readonly oracleId: "wagwstETH";
        readonly address: "0x773CDA0CADe2A3d86E6D4e30699d40bB95174ff2";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Wrapped Aave interest bearing wstETH.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly agETH: {
        readonly name: "Aave ETH";
        readonly symbol: "agETH";
        readonly oracleId: "agETH";
        readonly address: "0xa818F1B57c201E092C4A2017A91815034326Efd1";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Aave interest bearing ETH .";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly wagETH: {
        readonly name: "Wrapped Aave ETH";
        readonly symbol: "wagETH";
        readonly oracleId: "wagETH";
        readonly address: "0x57f664882F762FA37903FC864e2B633D384B411A";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Wrapped Aave interest bearing ETH.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly SAFE: {
        readonly name: "SAFE Token";
        readonly symbol: "SAFE";
        readonly oracleId: "SAFE";
        readonly address: "0x4d18815D14fe5c3304e87B3FA18318baa5c23820";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://safe.global/token";
        readonly documentation: "https://safe.global/blog/safe-tokenomics";
        readonly description: "SAFE Token acts as your key to participate in web3’s transition to smart accounts. Token holders tap into a diverse and ever-evolving ecosystem and govern the future of Safe.";
        readonly bridge: "gnosis-canonical";
    };
    readonly bCSPX: {
        readonly name: "Backed CSPX Core S&P 500";
        readonly symbol: "bCSPX";
        readonly oracleId: "bCSPX";
        readonly address: "0x1e2C4fb7eDE391d116E6B41cD0608260e8801D59";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://assets.backed.fi/products/bcspx";
        readonly documentation: "https://cdn.prod.website-files.com/655f3efc4be468487052e35a/6751b3cb9df2755163702cde_KID%20bCSPX%20-%20EN.pdf";
        readonly description: "The Backed CSPX Core S&P 500 (ticker symbol: bCSPX) is a tracker certificate issued as an ERC-20 token. bCSPX tracks the price of the iShares Core S&P 500 UCITS ETF USD (the underlying). The investment objective of the underlying is to deliver the net total return performance of S&P 500 index, less the fees and expenses of the fund. bCSPX is designed to give eligible cryptocurrency market participants regulatory-compliant access to the S&P 500’s performance, whilst maintaining the benefits of blockchain technology.";
        readonly bridge: "gnosis-canonical";
    };
    readonly wbTSLA: {
        readonly name: "Wrapped Backed Tesla Inc";
        readonly symbol: "wbTSLA";
        readonly oracleId: "wbTSLA";
        readonly address: "0x1f82284C1658Ad71C576f7230E6C2DEE7901c1FA";
        readonly chainId: 100;
        readonly decimals: 18;
        readonly website: "https://assets.backed.fi/products/btsla";
        readonly documentation: "https://cdn.prod.website-files.com/655f3efc4be468487052e35a/6751b142345d4106258dcdc6_KID%20-%20bTSLA%20-%20EN.pdf";
        readonly description: "Backed Tesla (bTSLA) is a tracker certificate issued as an ERC-20 token. bTSLA tracks the price of Tesla Inc. (the underlying). bTSLA is designed to give eligible cryptocurrency market participants regulatory-compliant access to the stock price of Tesla Inc.";
    };
};
