export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped S";
        readonly address: "0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38";
        readonly symbol: "wS";
        readonly oracleId: "WS";
        readonly decimals: 18;
        readonly chainId: 146;
        readonly website: "https://www.soniclabs.com/";
        readonly description: "Wrapped S, (S) Sonic is an EVM layer-1 platform that offers developers attractive incentives and powerful infrastructure.";
        readonly bridge: "sonic-canonical";
        readonly documentation: "https://www.soniclabs.com/developer-resources";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly FEES: {
        readonly name: "Wrapped S";
        readonly address: "0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38";
        readonly symbol: "wS";
        readonly oracleId: "WS";
        readonly decimals: 18;
        readonly chainId: 146;
        readonly website: "https://www.soniclabs.com/";
        readonly description: "Wrapped S, (S) Sonic is an EVM layer-1 platform that offers developers attractive incentives and powerful infrastructure.";
        readonly bridge: "sonic-canonical";
        readonly documentation: "https://www.soniclabs.com/developer-resources";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly S: {
        readonly name: "Wrapped S";
        readonly address: "0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38";
        readonly symbol: "wS";
        readonly oracleId: "WS";
        readonly decimals: 18;
        readonly chainId: 146;
        readonly website: "https://www.soniclabs.com/";
        readonly description: "Wrapped S, (S) Sonic is an EVM layer-1 platform that offers developers attractive incentives and powerful infrastructure.";
        readonly bridge: "sonic-canonical";
        readonly documentation: "https://www.soniclabs.com/developer-resources";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly WS: {
        readonly name: "Wrapped S";
        readonly address: "0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38";
        readonly symbol: "wS";
        readonly oracleId: "WS";
        readonly decimals: 18;
        readonly chainId: 146;
        readonly website: "https://www.soniclabs.com/";
        readonly description: "Wrapped S, (S) Sonic is an EVM layer-1 platform that offers developers attractive incentives and powerful infrastructure.";
        readonly bridge: "sonic-canonical";
        readonly documentation: "https://www.soniclabs.com/developer-resources";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly EQUAL: {
        readonly name: "Equalizer on Sonic";
        readonly symbol: "EQUAL";
        readonly oracleId: "EQUAL";
        readonly address: "0xddF26B42C1d903De8962d3F79a74a501420d5F19";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://sonic.equalizer.exchange/";
        readonly description: "Equalizer Exchange is the fastest liquidity hub providing optimized trading and earning opportunities.";
        readonly documentation: "";
        readonly bridge: "native";
    };
    readonly USDCe: {
        readonly name: "USDC";
        readonly symbol: "USDC";
        readonly oracleId: "sUSDCe";
        readonly address: "0x29219dd400f2Bf60E5a23d13Be72B486D4038894";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://www.usdc.com/";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly documentation: "";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly USDT: {
        readonly name: "Bridged USDT (Sonic Labs)";
        readonly symbol: "USDT";
        readonly oracleId: "sUSDT";
        readonly address: "0x6047828dc181963ba44974801FF68e538dA5eaF9";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://tether.to/";
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly documentation: "https://tether.to/en/how-it-works";
        readonly bridge: "sonic-canonical";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly WETH: {
        readonly name: "Wrapped Ether on Sonic";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly address: "0x50c42dEAcD8Fc9773493ED674b675bE577f2634b";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "sonic-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly stS: {
        readonly name: "Beets Staked Sonic";
        readonly symbol: "stS";
        readonly oracleId: "stS";
        readonly address: "0xE5DA20F15420aD15DE0fa650600aFc998bbE3955";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://beets.fi/stake";
        readonly description: "stS is a liquid-staked token that users receive when they stake $S on the Beets platform. The value of stS naturally appreciates in relation to $S thanks to native network staking rewards from validator delegation being automatically compounded within the token.";
        readonly documentation: "https://docs.beets.fi/";
        readonly bridge: "native";
    };
    readonly OS: {
        readonly name: "Origin Sonic";
        readonly symbol: "OS";
        readonly oracleId: "OS";
        readonly address: "0xb1e25689D55734FD3ffFc939c4C3Eb52DFf8A794";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://app.originprotocol.com/#/os/";
        readonly description: "Origin Sonic (OS) is a liquid staking token on the Sonic network designed to offer enhanced security, higher yield, and a tighter peg to S when compared to other Sonic LSTs. ";
        readonly documentation: "https://docs.originprotocol.com/protocol/os";
        readonly bridge: "native";
    };
    readonly wOS: {
        readonly name: "Wrapped Origin Sonic";
        readonly symbol: "wOS";
        readonly oracleId: "wOS";
        readonly address: "0x9F0dF7799f6FDAd409300080cfF680f5A23df4b1";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://app.originprotocol.com/#/os/";
        readonly description: "Origin Sonic (OS) is a liquid staking token on the Sonic network designed to offer enhanced security, higher yield, and a tighter peg to S when compared to other Sonic LSTs. ";
        readonly documentation: "https://docs.originprotocol.com/protocol/os";
        readonly bridge: "native";
    };
    readonly scUSD: {
        readonly name: "Sonic USD";
        readonly symbol: "scUSD";
        readonly oracleId: "scUSD";
        readonly address: "0xd3DCe716f3eF535C5Ff8d041c1A41C3bd89b97aE";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://rings.money/";
        readonly description: "Rings is a meta-stablecoin for USD & ETH offering competitive yield for stakers, providing deep liquidity for Sonic DeFi, and funding Sonic DeFi projects via its lockers.";
        readonly documentation: "https://docs.rings.money/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC", "CURATED"];
    };
    readonly stkscUSD: {
        readonly name: "Staked Sonic USD";
        readonly symbol: "stkscUSD";
        readonly oracleId: "stkscUSD";
        readonly address: "0x4D85bA8c3918359c78Ed09581E5bc7578ba932ba";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://rings.money/";
        readonly description: "Rings is a meta-stablecoin for USD & ETH offering competitive yield for stakers, providing deep liquidity for Sonic DeFi, and funding Sonic DeFi projects via its lockers.";
        readonly documentation: "https://docs.rings.money/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC", "CURATED"];
    };
    readonly wstkscUSD: {
        readonly name: "Wrapped stkscUSD";
        readonly symbol: "wstkscUSD";
        readonly oracleId: "wstkscUSD";
        readonly address: "0x9fb76f7ce5FCeAA2C42887ff441D46095E494206";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://rings.money/";
        readonly description: "Rings is a meta-stablecoin for USD & ETH offering competitive yield for stakers, providing deep liquidity for Sonic DeFi, and funding Sonic DeFi projects via its lockers.";
        readonly documentation: "https://docs.rings.money/";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC", "CURATED"];
    };
    readonly BRUSH: {
        readonly name: "PaintSwap";
        readonly symbol: "BRUSH";
        readonly oracleId: "BRUSH";
        readonly address: "0xE51EE9868C1f0d6cd968A8B8C8376Dc2991BFE44";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://paintswap.io/";
        readonly description: "PaintSwap is a decentralized finance powerhouse, combining an open NFT marketplace with a dedicated financial NFT marketplace.";
        readonly documentation: "https://docs.paintswap.finance/tokenomics/brush";
        readonly bridge: "layer-zero";
    };
    readonly LUDWIG: {
        readonly name: "LUDWIG";
        readonly symbol: "LUDWIG";
        readonly oracleId: "LUDWIG";
        readonly address: "0xe6cc4D855B4fD4A9D02F46B9adae4C5EfB1764B5";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://ludwigonsonic.com/";
        readonly description: "Ludwig On Sonic (LUDWIG) is your meme gateway to exploring Balancer technology on the Sonic network. The phrase \"High Speed, Perfect Beets\" highlights the Sonic network’s lightning-fast performance, while \"Beets\" refers to the DEX where our primary pools and liquidity are hosted.";
        readonly bridge: "native";
        readonly tags: readonly ["MEMECOIN"];
    };
    readonly BEETS: {
        readonly name: "BEETS";
        readonly symbol: "BEETS";
        readonly oracleId: "BEETS";
        readonly address: "0x2D0E0814E62D80056181F5cd932274405966e4f0";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://beets.fi/";
        readonly bridge: "native";
        readonly description: "BEETS is the governance token for the Beethoven X protocol. Built on Balancer V2, Beethoven X is the first next-generation AMM protocol on Fantom.";
        readonly documentation: "https://docs.beets.fi/beets/tokenomics";
    };
    readonly SHADOW: {
        readonly name: "SHADOW";
        readonly symbol: "SHADOW";
        readonly oracleId: "SHADOW";
        readonly address: "0x3333b97138D4b086720b5aE8A7844b1345a33333";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://www.shadow.so/";
        readonly bridge: "native";
        readonly description: "SHADOW is the governance token for the Shadow Exchange. Shadow Exchange is a concentrated liquidity layer and exchange built on the Sonic network, powered by x(3,3) — a more fluid and accessible incentive model.";
        readonly documentation: "https://docs.shadow.so/";
        readonly tags: readonly ["LARGE_HOLDERS"];
    };
    readonly xSHADOW: {
        readonly name: "xSHADOW";
        readonly symbol: "xSHADOW";
        readonly oracleId: "xSHADOW";
        readonly address: "0x5050bc082FF4A74Fb6B0B04385dEfdDB114b2424";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://www.shadow.so/";
        readonly bridge: "native";
        readonly description: "SHADOW is the governance token for the Shadow Exchange. Shadow Exchange is a concentrated liquidity layer and exchange built on the Sonic network, powered by x(3,3) — a more fluid and accessible incentive model.";
        readonly documentation: "https://docs.shadow.so/";
        readonly tags: readonly ["LARGE_HOLDERS"];
    };
    readonly x33: {
        readonly name: "x33";
        readonly symbol: "x33";
        readonly oracleId: "x33";
        readonly address: "0x3333111A391cC08fa51353E9195526A70b333333";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://www.shadow.so/";
        readonly bridge: "native";
        readonly description: "x33 is the liquid-staking wrapper for SHADOW, the governance token for the Shadow Exchange. Shadow Exchange is a concentrated liquidity layer and exchange built on the Sonic network, powered by x(3,3) — a more fluid and accessible incentive model.";
        readonly documentation: "https://docs.shadow.so/";
        readonly tags: readonly ["NO_TIMELOCK", "LARGE_HOLDERS"];
    };
    readonly SWPx: {
        readonly name: "SwapX";
        readonly symbol: "SWPx";
        readonly oracleId: "SWPx";
        readonly address: "0xA04BC7140c26fc9BB1F36B1A604C7A5a88fb0E70";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://swapx.fi/";
        readonly bridge: "native";
        readonly description: "SWPx is the governance token for the SwapX. SwapX is a decentralized exchange (DEX) which aims to become the leading platform for native concentrated liquidity on Sonic Blockchain.";
        readonly documentation: "https://swapxfi.gitbook.io/swapx-docs";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly mooBIFI: {
        readonly name: "Bridged BIFI Vault Receipt";
        readonly symbol: "mooBIFI";
        readonly oracleId: "smooBIFI";
        readonly address: "0xc55E93C62874D8100dBd2DfE307EDc1036ad5434";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://beefy.com";
        readonly description: "The incentive-bearing Beefy Token (mooBIFI) applies the magic of Beefy's autocompounding technology to the BIFI token. It is the vault token for the BIFI Vault, which automatically claims and swaps governance incentives into more BIFI, and redeposits to unlock exponential growth. On chains other than Ethereum, mooBIFI is a bridged copy of the native Ethereum token, and cannot be returned to BIFI without first bridging back to Ethereum. mooBIFI holders on all chains retain their full voting power corresponding to the underlying amount of BIFI deposited and compounding on Ethereum.";
        readonly documentation: "https://docs.beefy.finance/";
        readonly bridge: "beefy";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly scETH: {
        readonly name: "Sonic ETH";
        readonly symbol: "scETH";
        readonly oracleId: "scETH";
        readonly address: "0x3bcE5CB273F0F148010BbEa2470e7b5df84C7812";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://rings.money/";
        readonly description: "Rings is a meta-stablecoin for USD & ETH offering competitive yield for stakers, providing deep liquidity for Sonic DeFi, and funding Sonic DeFi projects via its lockers.";
        readonly documentation: "https://docs.rings.money/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["CURATED", "SYNTHETIC"];
    };
    readonly wstkscETH: {
        readonly name: "Wrapped stkscETH";
        readonly symbol: "wstkscETH";
        readonly oracleId: "wstkscETH";
        readonly address: "0xE8a41c62BB4d5863C6eadC96792cFE90A1f37C47";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://rings.money/";
        readonly description: "Rings is a meta-stablecoin for USD & ETH offering competitive yield for stakers, providing deep liquidity for Sonic DeFi, and funding Sonic DeFi projects via its lockers.";
        readonly documentation: "https://docs.rings.money/";
        readonly bridge: "native";
        readonly tags: readonly ["CURATED"];
    };
    readonly frxETH: {
        readonly name: "Frax Ether";
        readonly symbol: "frxETH";
        readonly oracleId: "frxETH";
        readonly address: "0x43eDD7f3831b08FE70B7555ddD373C8bF65a9050";
        readonly decimals: 18;
        readonly chainId: 146;
        readonly website: "https://app.frax.finance/frxeth/mint";
        readonly description: "frxETH acts as a stablecoin loosely pegged to ETH, so that 1 frxETH always represents 1 ETH and the amount of frxETH in circulation matches the amount of ETH in the Frax ETH system. When ETH is sent to the frxETHMinter, an equivalent amount of frxETH is minted. Holding frxETH on its own is not eligible for staking yield and should be thought of as analogous as holding ETH.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth";
    };
    readonly sfrxETH: {
        readonly name: "Staked Frax Ether";
        readonly symbol: "sfrxETH";
        readonly oracleId: "sfrxETH";
        readonly address: "0x3Ec3849C33291a9eF4c5dB86De593EB4A37fDe45";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://app.frax.finance/frxeth/mint";
        readonly documentation: "https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth";
        readonly description: "sfrxETH is a ERC-4626 vault designed to accrue the staking yield of the Frax ETH validators. At any time, frxETH can be exchanged for sfrxETH by depositing it into the sfrxETH vault, which allows users to earn staking yield on their frxETH. Over time, as validators accrue staking yield, an equivalent amount of frxETH is minted and added to the vault, allowing users to redeem their sfrxETH for an greater amount of frxETH than they deposited.";
        readonly bridge: "layer-zero";
    };
    readonly frxUSD: {
        readonly name: "Frax USD";
        readonly symbol: "frxUSD";
        readonly oracleId: "frxUSD";
        readonly chainId: 146;
        readonly address: "0x80Eede496655FB9047dd39d9f418d5483ED600df";
        readonly decimals: 18;
        readonly website: "https://frax.finance/";
        readonly description: "frxUSD is a dollar-pegged stablecoin that uses “Algorithmic Market Operation” (AMO) smart contracts and permissionless, non-custodial subprotocols as stability mechanisms.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.frax.finance/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly sfrxUSD: {
        readonly name: "Staked Frax USD";
        readonly symbol: "sfrxUSD";
        readonly oracleId: "sFRAX";
        readonly chainId: 146;
        readonly address: "0x5Bff88cA1442c2496f7E475E9e7786383Bc070c0";
        readonly decimals: 18;
        readonly website: "https://frax.finance/";
        readonly description: "Staked Frax USD (sfrxUSD) is an ERC4626 staking vault that distributes part of the Frax Protocol yield weekly to stakers denominated in frxUSD stablecoins. The sfrxUSD token represents pro rata deposits within the vault and is always withdrawable for frxUSD stablecoins at the pro rata rate at all times. sfrxUSD APY attempts to roughly track the interest on reserve balances (IORB) rate of the United States Federal Reserve using the IORB oracle. This benchmark rate is generally accepted as the “risk free rate” of the US Dollar. The frxUSD staking vault attempts, but does not guarantee in any way, to target this rate.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.frax.finance/";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly mooSiloSonicUSDCe: {
        readonly name: "Moo Silo Sonic USDCe";
        readonly symbol: "USDC.e (Silo vault)";
        readonly oracleId: "mooSiloSonicUSDCe";
        readonly address: "0xdb6E5dC4C6748EcECb97b565F6C074f24384fD07";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://beefy.com";
        readonly description: "USDC.e staked into the Silo (wS Market) vault.";
        readonly documentation: "https://docs.beefy.finance/";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly WBTC: {
        readonly name: "Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "WBTC";
        readonly address: "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c";
        readonly chainId: 146;
        readonly decimals: 8;
        readonly website: "https://wbtc.network/";
        readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
        readonly documentation: "";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly scBTC: {
        readonly name: "Sonic BTC";
        readonly symbol: "scBTC";
        readonly oracleId: "scBTC";
        readonly address: "0xBb30e76d9Bb2CC9631F7fC5Eb8e87B5Aff32bFbd";
        readonly chainId: 146;
        readonly decimals: 8;
        readonly website: "https://rings.money/";
        readonly description: "Rings is a meta-stablecoin for USD, ETH & BTC offering competitive yield for stakers, providing deep liquidity for Sonic DeFi, and funding Sonic DeFi projects via its lockers.";
        readonly documentation: "https://docs.rings.money/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["CURATED", "SYNTHETIC"];
    };
    readonly GEMS: {
        readonly name: "Shadow wrapped Gems";
        readonly symbol: "GEMS";
        readonly oracleId: "GEMS";
        readonly address: "0x5555b2733602DEd58D47b8D3D989E631CBee5555";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://www.shadow.so/";
        readonly description: "Shadow wrapped GEMS";
        readonly documentation: "";
        readonly bridge: "native";
    };
    readonly 'bUSDCe-20': {
        readonly name: "Silo Finance Borrowable USDC.e Deposit, SiloId: 20";
        readonly symbol: "bUSDCe-20";
        readonly oracleId: "bUSDCe-20";
        readonly address: "0x322e1d5384aa4ED66AeCa770B95686271de61dc3";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://www.silo.finance/";
        readonly description: "Silo Finance borrowable USDC.e deposit token, reflecting USDC.e deposited into Silo. Deposit tokens are issued at a ratio of 1,000 tokens per dollar deposited (or $0.001 per dollar deposited).";
        readonly documentation: "https://devdocs.silo.finance/";
        readonly bridge: "native";
    };
    readonly SILO: {
        readonly name: "Silo";
        readonly symbol: "SILO";
        readonly oracleId: "SILO";
        readonly address: "0x53f753E4B17F4075D6fa2c6909033d224b81e698";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://www.silo.finance/";
        readonly description: "Silo is a non-custodial lending protocol to borrow any crypto asset with another.";
        readonly documentation: "https://devdocs.silo.finance/";
        readonly bridge: "sonic-canonical";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly beS: {
        readonly name: "beSonic";
        readonly symbol: "beS";
        readonly oracleId: "beS";
        readonly address: "0x871A101Dcf22fE4fE37be7B654098c801CBA1c88";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://www.beefy.com/";
        readonly description: "Beefy-escrowed Sonic (beS) is a liquid staking derivative of Sonic (S). It automatically stakes a user’s wS tokens to earn staking rewards. Each beS token represents a proportional share of the staked wS, including any rewards accrued over time. Users can convert beS back to wS with a 14-day unbonding period, or freely trade beS on the open market.";
        readonly documentation: "https://docs.beefy.finance/beefy-products/beefy-escrowed-tokens/bes";
        readonly bridge: "native";
    };
    readonly FIVE: {
        readonly name: "FIVE";
        readonly symbol: "FIVE";
        readonly oracleId: "FIVE";
        readonly address: "0xb0695ce12c56AAe40894235e2d1888D0b62Dd110";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://defive.com/";
        readonly description: "DeFive, previously known as WigoSwap on Fantom (with over $1 billion in transaction volume), is a redefined and progressive DeFi platform built on Sonic.";
        readonly documentation: "https://docs.defive.com/overview";
        readonly bridge: "native";
    };
    readonly EURC: {
        readonly name: "EURC";
        readonly symbol: "EURC";
        readonly oracleId: "EURC";
        readonly address: "0xe715cbA7B5cCb33790ceBFF1436809d36cb17E57";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/en/eurc";
        readonly description: "EURC is a euro-backed stablecoin that’s accessible globally on Avalanche, Ethereum, Base and Stellar. Similar to USDC, EURC is issued by Circle under a full-reserve model.";
        readonly documentation: "https://www.circle.com/en/eurc";
        readonly bridge: "sonic-canonical";
    };
    readonly aSonUSDC: {
        readonly name: "Aave Sonic USDC";
        readonly symbol: "aSonUSDC";
        readonly oracleId: "aSonUSDC";
        readonly address: "0x578Ee1ca3a8E1b54554Da1Bf7C583506C4CD11c6";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Aave interest bearing USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly staked: true;
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly waSonUSDC: {
        readonly name: "Aave Sonic USDC";
        readonly symbol: "aSonUSDC";
        readonly oracleId: "aSonUSDC";
        readonly address: "0x6646248971427B80ce531bdD793e2Eb859347E55";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Aave interest bearing USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly bridge: "native";
    };
    readonly SiloScUSD: {
        readonly name: "Silo scUSDC";
        readonly symbol: "SiloScUSD";
        readonly oracleId: "SiloScUSD";
        readonly address: "0xe6605932e4a686534D19005BB9dB0FBA1F101272";
        readonly chainId: 146;
        readonly decimals: 6;
        readonly website: "https://rings.money/";
        readonly description: "Silo scUSD market. Rings is a meta-stablecoin for USD & ETH offering competitive yield for stakers, providing deep liquidity for Sonic DeFi, and funding Sonic DeFi projects via its lockers.";
        readonly documentation: "https://docs.rings.money/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["CURATED", "SYNTHETIC", "STABLECOIN"];
    };
    readonly SiloWETH: {
        readonly name: "Silo wETH";
        readonly symbol: "SiloWETH";
        readonly oracleId: "SiloWETH";
        readonly address: "0x08C320A84a59c6f533e0DcA655cf497594BCa1F9";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "native";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
    };
    readonly SiloScETH: {
        readonly name: "Silo scETH";
        readonly symbol: "SiloScETH";
        readonly oracleId: "SiloScETH";
        readonly address: "0x24c74B30d1a4261608E84Bf5a618693032681DAc";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://rings.money/";
        readonly description: "Silo scETH market. Rings is a meta-stablecoin for USD & ETH offering competitive yield for stakers, providing deep liquidity for Sonic DeFi, and funding Sonic DeFi projects via its lockers.";
        readonly documentation: "https://docs.rings.money/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["CURATED", "SYNTHETIC"];
    };
    readonly beGEMS1: {
        readonly name: "Beefy Gems Season 1";
        readonly symbol: "beGEMS1";
        readonly oracleId: "beGEMS1";
        readonly address: "0xd70c020c48403295100884ee47db80d51BAA9d87";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://app.beefy.com/campaigns/begems";
        readonly description: "beGEMS are a liquid ERC-20 token issued by Beefy that represent its share of Sonic Gems airdrop rewards, earned by users through boosting vaults, providing liquidity, or voting for beS pairs across Sonic exchanges.";
        readonly documentation: "https://docs.beefy.com/";
        readonly bridge: "native";
    };
    readonly STRIKE: {
        readonly name: "Search for Animera";
        readonly symbol: "STRIKE";
        readonly oracleId: "STRIKE";
        readonly address: "0x8Bb21B10f32a10bed94041746ffD32003bAd6534";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://animera.world/";
        readonly description: "Display your prowess in Search For Animera: Star Siege, a Free-To-Play cosmic shooter where adversaries from every corner of the galaxy vie for glory, fame, and lucrative rewards.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "LARGE_HOLDERS"];
    };
    readonly wawS: {
        readonly name: "Wrapped Aave wS";
        readonly symbol: "wawS";
        readonly oracleId: "wawS";
        readonly address: "0x18B7B8695165290f2767BC63c36D3dFEa4C0F9bB";
        readonly chainId: 146;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Wrapped Aave interest bearing wS.";
    };
};
