import * as platforms from './platforms/index.js';
export declare const zksync: {
    readonly platforms: typeof platforms;
    readonly tokens: {
        readonly WNATIVE: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 324;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly FEES: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 324;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly ETH: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 324;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly WETH: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 324;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly oldBIFI: {
            readonly name: "Beefy.Finance";
            readonly symbol: "oldBIFI";
            readonly oracleId: "oldBIFI";
            readonly address: "0x44AA3eEDD3214Ddd02E8b3FE1E8AE4cAC452a2E0";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://www.beefy.finance/";
            readonly documentation: "https://docs.beefy.finance/";
            readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
        };
        readonly VS: {
            readonly name: "veSync";
            readonly symbol: "VS";
            readonly oracleId: "VS";
            readonly address: "0x5756A28E2aAe01F600FC2C01358395F5C1f8ad3A";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://app.vesync.finance/swap";
            readonly description: "veSync is a community-driven, ve(3,3) Decentralized Exchange (DEX) built on the zkSync network, providing a powerful and efficient platform for DeFi liquidity.";
            readonly documentation: "https://docs.vesync.finance/";
        };
        readonly wTBT: {
            readonly name: "wTBT Pool";
            readonly symbol: "wTBT";
            readonly oracleId: "wTBT";
            readonly address: "0xd90764041DA2720396863836E9f78dDaee140533";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://www.tprotocol.io/";
            readonly description: "The launch of TProtocol will drastically alter the current DeFi picture and add an important missing piece, making DeFi users able to benefit from the mid-term interest rate gap between the stables and rising treasury. TProtocol will provide permissionless interest bearing tokens backed by the treasury with short duration. The redemption price of this treasury token will increase over time as interest from treasury accrues into the tokens.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://tprotocol.gitbook.io/tprotocol-documentation/white-paper/tprotocol-documentation";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly VC: {
            readonly name: "Velocore";
            readonly symbol: "VC";
            readonly oracleId: "VC";
            readonly address: "0x85D84c774CF8e9fF85342684b0E795Df72A24908";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://app.velocore.xyz/swap";
            readonly description: "Velocore is a key DeFi component of the zkSync era ecosystem, designed to reward users for providing liquidity. Built upon the strong foundation established by Solidly and Velodrome Finance, Velocore aims to foster growth and innovation within zkSync era. As part of our grand vision, we plan to expand Velocores capabilities by launching a lending market and supporting other builders. This strategic development will enable us to build powerful money legos on zkSync era, further enhancing the DeFi landscape.";
            readonly bridge: "native";
            readonly documentation: "https://docs.velocore.xyz/";
        };
        readonly USDCe: {
            readonly name: "Bridged USD Coin";
            readonly symbol: "USDCe";
            readonly oracleId: "USDC";
            readonly address: "0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4";
            readonly chainId: 324;
            readonly decimals: 6;
            readonly website: "https://www.circle.com/usdc";
            readonly documentation: "https://developers.circle.com/docs";
            readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly bridge: "zksync-canonical";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly BUSD: {
            readonly name: "Binance USD";
            readonly symbol: "BUSD";
            readonly oracleId: "BUSD";
            readonly address: "0x2039bb4116B4EFc145Ec4f0e2eA75012D6C0f181";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://www.binance.com/en/busd";
            readonly description: "Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos), Approved and regulated by the New York State Department of Financial Services (NYDFS), The BUSD Monthly Audit Report can be viewed from the official website.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly 'USD+': {
            readonly name: "USD+";
            readonly symbol: "USD+";
            readonly oracleId: "zkUSD+";
            readonly address: "0x8E86e46278518EFc1C5CEd245cBA2C7e3ef11557";
            readonly chainId: 324;
            readonly decimals: 6;
            readonly website: "https://overnight.fi/";
            readonly description: "USD+ is USDC that pays you yield daily via rebase. It is 100% collateralized with assets immediately convertible into USDC. Yield is generated via strategies such as lending and stable-to-stable pools. Initial strategies include Aave, Rubicon, and Pika.";
            readonly documentation: "https://docs.overnight.fi/";
            readonly tags: readonly ["CURATED", "STABLECOIN"];
        };
        readonly WBTC: {
            readonly name: "Wrapped BTC";
            readonly symbol: "WBTC";
            readonly oracleId: "WBTC";
            readonly address: "0xBBeB516fb02a01611cBBE0453Fe3c580D7281011";
            readonly chainId: 324;
            readonly decimals: 8;
            readonly website: "https://wbtc.network/";
            readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
            readonly bridge: "zksync-canonical";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly FANG: {
            readonly name: "Dracula";
            readonly symbol: "FANG";
            readonly oracleId: "FANG";
            readonly address: "0x160e07e42ADbC1FCE92D505B579Bcd8a3fBEa77d";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://draculafi.xyz/";
            readonly description: "DraculaFi is a cutting-edge DeFi protocol built on zkSync Era with a proven ve(3,3) model and game-changing mechanisms that aim to provide increased rewards and stability for users.";
            readonly documentation: "https://draculafi.gitbook.io/draculafi/";
        };
        readonly ZK: {
            readonly name: "zkSync";
            readonly symbol: "ZK";
            readonly oracleId: "ZK";
            readonly address: "0x5A7d6b2F92C77FAD6CCaBd7EE0624E64907Eaf3E";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://zksync.io/";
            readonly description: "zkSync Era is a Layer-2 protocol that scales Ethereum with cutting-edge ZK tech. zkSync's mission is not only to merely increase Ethereum's throughput, but to fully preserve its foundational values: freedom, self-sovereignty, decentralization at scale.";
            readonly documentation: "https://zksync.io/explore";
            readonly bridge: "native";
        };
        readonly USDC: {
            readonly name: "USD Coin";
            readonly symbol: "USDC";
            readonly oracleId: "USDC";
            readonly address: "0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4";
            readonly chainId: 324;
            readonly decimals: 6;
            readonly website: "https://www.circle.com/usdc";
            readonly documentation: "https://developers.circle.com/docs";
            readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly bridge: "native";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly USDT: {
            readonly name: "Tether USD";
            readonly symbol: "USDT";
            readonly oracleId: "USDT";
            readonly address: "0x493257fD37EDB34451f62EDf8D2a0C418852bA4C";
            readonly chainId: 324;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly description: "Tether converts cash into digital currency, to anchor or tether the value to the price of national currencies like the US dollar, the Euro, and the offshore Chinese yuan.";
            readonly bridge: "zksync-canonical";
            readonly tags: readonly ["STABLECOIN"];
        };
    };
    readonly tokenAddressMap: import("../../util/convertSymbolTokenMapToAddressTokenMap.js").AddressToTokenMap<{
        readonly WNATIVE: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 324;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly FEES: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 324;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly ETH: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 324;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly WETH: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 324;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly oldBIFI: {
            readonly name: "Beefy.Finance";
            readonly symbol: "oldBIFI";
            readonly oracleId: "oldBIFI";
            readonly address: "0x44AA3eEDD3214Ddd02E8b3FE1E8AE4cAC452a2E0";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://www.beefy.finance/";
            readonly documentation: "https://docs.beefy.finance/";
            readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
        };
        readonly VS: {
            readonly name: "veSync";
            readonly symbol: "VS";
            readonly oracleId: "VS";
            readonly address: "0x5756A28E2aAe01F600FC2C01358395F5C1f8ad3A";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://app.vesync.finance/swap";
            readonly description: "veSync is a community-driven, ve(3,3) Decentralized Exchange (DEX) built on the zkSync network, providing a powerful and efficient platform for DeFi liquidity.";
            readonly documentation: "https://docs.vesync.finance/";
        };
        readonly wTBT: {
            readonly name: "wTBT Pool";
            readonly symbol: "wTBT";
            readonly oracleId: "wTBT";
            readonly address: "0xd90764041DA2720396863836E9f78dDaee140533";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://www.tprotocol.io/";
            readonly description: "The launch of TProtocol will drastically alter the current DeFi picture and add an important missing piece, making DeFi users able to benefit from the mid-term interest rate gap between the stables and rising treasury. TProtocol will provide permissionless interest bearing tokens backed by the treasury with short duration. The redemption price of this treasury token will increase over time as interest from treasury accrues into the tokens.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "https://tprotocol.gitbook.io/tprotocol-documentation/white-paper/tprotocol-documentation";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly VC: {
            readonly name: "Velocore";
            readonly symbol: "VC";
            readonly oracleId: "VC";
            readonly address: "0x85D84c774CF8e9fF85342684b0E795Df72A24908";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://app.velocore.xyz/swap";
            readonly description: "Velocore is a key DeFi component of the zkSync era ecosystem, designed to reward users for providing liquidity. Built upon the strong foundation established by Solidly and Velodrome Finance, Velocore aims to foster growth and innovation within zkSync era. As part of our grand vision, we plan to expand Velocores capabilities by launching a lending market and supporting other builders. This strategic development will enable us to build powerful money legos on zkSync era, further enhancing the DeFi landscape.";
            readonly bridge: "native";
            readonly documentation: "https://docs.velocore.xyz/";
        };
        readonly USDCe: {
            readonly name: "Bridged USD Coin";
            readonly symbol: "USDCe";
            readonly oracleId: "USDC";
            readonly address: "0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4";
            readonly chainId: 324;
            readonly decimals: 6;
            readonly website: "https://www.circle.com/usdc";
            readonly documentation: "https://developers.circle.com/docs";
            readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly bridge: "zksync-canonical";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly BUSD: {
            readonly name: "Binance USD";
            readonly symbol: "BUSD";
            readonly oracleId: "BUSD";
            readonly address: "0x2039bb4116B4EFc145Ec4f0e2eA75012D6C0f181";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://www.binance.com/en/busd";
            readonly description: "Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos), Approved and regulated by the New York State Department of Financial Services (NYDFS), The BUSD Monthly Audit Report can be viewed from the official website.";
            readonly bridge: "zksync-canonical";
            readonly documentation: "";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly 'USD+': {
            readonly name: "USD+";
            readonly symbol: "USD+";
            readonly oracleId: "zkUSD+";
            readonly address: "0x8E86e46278518EFc1C5CEd245cBA2C7e3ef11557";
            readonly chainId: 324;
            readonly decimals: 6;
            readonly website: "https://overnight.fi/";
            readonly description: "USD+ is USDC that pays you yield daily via rebase. It is 100% collateralized with assets immediately convertible into USDC. Yield is generated via strategies such as lending and stable-to-stable pools. Initial strategies include Aave, Rubicon, and Pika.";
            readonly documentation: "https://docs.overnight.fi/";
            readonly tags: readonly ["CURATED", "STABLECOIN"];
        };
        readonly WBTC: {
            readonly name: "Wrapped BTC";
            readonly symbol: "WBTC";
            readonly oracleId: "WBTC";
            readonly address: "0xBBeB516fb02a01611cBBE0453Fe3c580D7281011";
            readonly chainId: 324;
            readonly decimals: 8;
            readonly website: "https://wbtc.network/";
            readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
            readonly bridge: "zksync-canonical";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly FANG: {
            readonly name: "Dracula";
            readonly symbol: "FANG";
            readonly oracleId: "FANG";
            readonly address: "0x160e07e42ADbC1FCE92D505B579Bcd8a3fBEa77d";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://draculafi.xyz/";
            readonly description: "DraculaFi is a cutting-edge DeFi protocol built on zkSync Era with a proven ve(3,3) model and game-changing mechanisms that aim to provide increased rewards and stability for users.";
            readonly documentation: "https://draculafi.gitbook.io/draculafi/";
        };
        readonly ZK: {
            readonly name: "zkSync";
            readonly symbol: "ZK";
            readonly oracleId: "ZK";
            readonly address: "0x5A7d6b2F92C77FAD6CCaBd7EE0624E64907Eaf3E";
            readonly chainId: 324;
            readonly decimals: 18;
            readonly website: "https://zksync.io/";
            readonly description: "zkSync Era is a Layer-2 protocol that scales Ethereum with cutting-edge ZK tech. zkSync's mission is not only to merely increase Ethereum's throughput, but to fully preserve its foundational values: freedom, self-sovereignty, decentralization at scale.";
            readonly documentation: "https://zksync.io/explore";
            readonly bridge: "native";
        };
        readonly USDC: {
            readonly name: "USD Coin";
            readonly symbol: "USDC";
            readonly oracleId: "USDC";
            readonly address: "0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4";
            readonly chainId: 324;
            readonly decimals: 6;
            readonly website: "https://www.circle.com/usdc";
            readonly documentation: "https://developers.circle.com/docs";
            readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly bridge: "native";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly USDT: {
            readonly name: "Tether USD";
            readonly symbol: "USDT";
            readonly oracleId: "USDT";
            readonly address: "0x493257fD37EDB34451f62EDf8D2a0C418852bA4C";
            readonly chainId: 324;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly description: "Tether converts cash into digital currency, to anchor or tether the value to the price of national currencies like the US dollar, the Euro, and the offshore Chinese yuan.";
            readonly bridge: "zksync-canonical";
            readonly tags: readonly ["STABLECOIN"];
        };
    }>;
    readonly native: {
        readonly symbol: "ETH";
        readonly oracleId: "ETH";
    };
};
