import * as platforms from './platforms/index.js';
export declare const scroll: {
    readonly platforms: typeof platforms;
    readonly tokens: {
        readonly WNATIVE: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5300000000000000000000000000000000000004";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 534352;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly FEES: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5300000000000000000000000000000000000004";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 534352;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly ETH: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5300000000000000000000000000000000000004";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 534352;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly WETH: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5300000000000000000000000000000000000004";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 534352;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly USDC: {
            readonly name: "USD Coin";
            readonly address: "0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4";
            readonly symbol: "USDC";
            readonly oracleId: "USDC";
            readonly decimals: 6;
            readonly website: "https://www.centre.io/";
            readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly bridge: "scroll-canonical";
            readonly chainId: 534352;
            readonly documentation: "https://www.circle.com/en/usdc-multichain/arbitrum";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly WBTC: {
            readonly chainId: 534352;
            readonly address: "0x3C1BCa5a656e69edCD0D4E36BEbb3FcDAcA60Cf1";
            readonly decimals: 8;
            readonly name: "Wrapped BTC";
            readonly symbol: "WBTC";
            readonly oracleId: "WBTC";
            readonly website: "https://wbtc.network/";
            readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
            readonly bridge: "scroll-canonical";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly USDT: {
            readonly name: "USDT";
            readonly symbol: "USDT";
            readonly oracleId: "USDT";
            readonly address: "0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df";
            readonly chainId: 534352;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly NURI: {
            readonly name: "NURI Token";
            readonly symbol: "NURI";
            readonly oracleId: "NURI";
            readonly address: "0xAAAE8378809bb8815c08D3C59Eb0c7D1529aD769";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://www.nuri.exchange/";
            readonly description: "NURI takes concentrated liquidity to the next level, optimizing for high frequency LPs and Layer 2 cost structures. The result is a hyper-efficient liquidity layer designed to attract the most effective liquidity providers, while delivering a clean and simple UX for traders.";
            readonly documentation: "https://docs.nuri.exchange/";
            readonly bridge: "native";
        };
        readonly loreUSD: {
            readonly name: "Lore USD";
            readonly symbol: "loreUSD";
            readonly oracleId: "loreUSD";
            readonly address: "0x77fbf86399ed764A084F77B9acCb049F3DbC32d2";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://www.lore.finance/";
            readonly description: "Lore is a decentralized non-custodial liquidity market protocol on Scroll where users can participate as depositors or borrowers. Depositors provide liquidity to the market to earn a passive income, while borrowers are able to borrow in an overcollateralized (perpetually) or undercollateralized (one-block liquidity) fashion.";
            readonly documentation: "https://docs.lore.finance/";
            readonly bridge: "native";
            readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
        };
        readonly LORE: {
            readonly name: "Lore Token";
            readonly symbol: "LORE";
            readonly oracleId: "LORE";
            readonly address: "0x549423E69576b80E91dC836ae37e04209660c4ec";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://www.lore.finance/";
            readonly description: "Lore is a decentralized non-custodial liquidity market protocol on Scroll where users can participate as depositors or borrowers. Depositors provide liquidity to the market to earn a passive income, while borrowers are able to borrow in an overcollateralized (perpetually) or undercollateralized (one-block liquidity) fashion.";
            readonly documentation: "https://docs.lore.finance/";
            readonly bridge: "native";
        };
        readonly TKN: {
            readonly name: "Tokan";
            readonly symbol: "TKN";
            readonly oracleId: "TKN";
            readonly address: "0x1a2fCB585b327fAdec91f55D45829472B15f17a4";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://www.tokan.exchange/";
            readonly description: "Tokan is a DEX and Liquidity Layer driven by the community and centered around the ecosystem. Built on the Scroll network, Tokan serves as the exchange layer and addresses liquidity issues at the protocol level within the network.";
            readonly documentation: "https://docs.tokan.exchange/";
            readonly bridge: "native";
            readonly tags: readonly ["NO_TIMELOCK"];
        };
        readonly wstETH: {
            readonly name: "Wrapped liquid staked Ether 2.0";
            readonly symbol: "wstETH";
            readonly oracleId: "wstETH";
            readonly address: "0xf610A9dfB7C89644979b4A0f27063E9e7d7Cda32";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://lido.fi/";
            readonly description: "Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.";
            readonly documentation: "https://docs.lido.fi/";
            readonly bridge: "scroll-canonical";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly SCR: {
            readonly name: "Scroll";
            readonly symbol: "SCR";
            readonly oracleId: "SCR";
            readonly address: "0xd29687c813D741E2F938F4aC377128810E217b1b";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://scroll.io/";
            readonly description: "Scroll is the leading zero-knowledge rollup. Scaling Ethereum for good.";
            readonly documentation: "https://docs.scroll.io/en/home/";
            readonly bridge: "native";
        };
    };
    readonly tokenAddressMap: import("../../util/convertSymbolTokenMapToAddressTokenMap.js").AddressToTokenMap<{
        readonly WNATIVE: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5300000000000000000000000000000000000004";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 534352;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly FEES: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5300000000000000000000000000000000000004";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 534352;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly ETH: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5300000000000000000000000000000000000004";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 534352;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly WETH: {
            readonly name: "Wrapped Ether";
            readonly address: "0x5300000000000000000000000000000000000004";
            readonly symbol: "WETH";
            readonly oracleId: "WETH";
            readonly decimals: 18;
            readonly chainId: 534352;
            readonly website: "https://weth.io/";
            readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly USDC: {
            readonly name: "USD Coin";
            readonly address: "0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4";
            readonly symbol: "USDC";
            readonly oracleId: "USDC";
            readonly decimals: 6;
            readonly website: "https://www.centre.io/";
            readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly bridge: "scroll-canonical";
            readonly chainId: 534352;
            readonly documentation: "https://www.circle.com/en/usdc-multichain/arbitrum";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly WBTC: {
            readonly chainId: 534352;
            readonly address: "0x3C1BCa5a656e69edCD0D4E36BEbb3FcDAcA60Cf1";
            readonly decimals: 8;
            readonly name: "Wrapped BTC";
            readonly symbol: "WBTC";
            readonly oracleId: "WBTC";
            readonly website: "https://wbtc.network/";
            readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
            readonly bridge: "scroll-canonical";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly USDT: {
            readonly name: "USDT";
            readonly symbol: "USDT";
            readonly oracleId: "USDT";
            readonly address: "0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df";
            readonly chainId: 534352;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
            readonly bridge: "scroll-canonical";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly NURI: {
            readonly name: "NURI Token";
            readonly symbol: "NURI";
            readonly oracleId: "NURI";
            readonly address: "0xAAAE8378809bb8815c08D3C59Eb0c7D1529aD769";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://www.nuri.exchange/";
            readonly description: "NURI takes concentrated liquidity to the next level, optimizing for high frequency LPs and Layer 2 cost structures. The result is a hyper-efficient liquidity layer designed to attract the most effective liquidity providers, while delivering a clean and simple UX for traders.";
            readonly documentation: "https://docs.nuri.exchange/";
            readonly bridge: "native";
        };
        readonly loreUSD: {
            readonly name: "Lore USD";
            readonly symbol: "loreUSD";
            readonly oracleId: "loreUSD";
            readonly address: "0x77fbf86399ed764A084F77B9acCb049F3DbC32d2";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://www.lore.finance/";
            readonly description: "Lore is a decentralized non-custodial liquidity market protocol on Scroll where users can participate as depositors or borrowers. Depositors provide liquidity to the market to earn a passive income, while borrowers are able to borrow in an overcollateralized (perpetually) or undercollateralized (one-block liquidity) fashion.";
            readonly documentation: "https://docs.lore.finance/";
            readonly bridge: "native";
            readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
        };
        readonly LORE: {
            readonly name: "Lore Token";
            readonly symbol: "LORE";
            readonly oracleId: "LORE";
            readonly address: "0x549423E69576b80E91dC836ae37e04209660c4ec";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://www.lore.finance/";
            readonly description: "Lore is a decentralized non-custodial liquidity market protocol on Scroll where users can participate as depositors or borrowers. Depositors provide liquidity to the market to earn a passive income, while borrowers are able to borrow in an overcollateralized (perpetually) or undercollateralized (one-block liquidity) fashion.";
            readonly documentation: "https://docs.lore.finance/";
            readonly bridge: "native";
        };
        readonly TKN: {
            readonly name: "Tokan";
            readonly symbol: "TKN";
            readonly oracleId: "TKN";
            readonly address: "0x1a2fCB585b327fAdec91f55D45829472B15f17a4";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://www.tokan.exchange/";
            readonly description: "Tokan is a DEX and Liquidity Layer driven by the community and centered around the ecosystem. Built on the Scroll network, Tokan serves as the exchange layer and addresses liquidity issues at the protocol level within the network.";
            readonly documentation: "https://docs.tokan.exchange/";
            readonly bridge: "native";
            readonly tags: readonly ["NO_TIMELOCK"];
        };
        readonly wstETH: {
            readonly name: "Wrapped liquid staked Ether 2.0";
            readonly symbol: "wstETH";
            readonly oracleId: "wstETH";
            readonly address: "0xf610A9dfB7C89644979b4A0f27063E9e7d7Cda32";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://lido.fi/";
            readonly description: "Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.";
            readonly documentation: "https://docs.lido.fi/";
            readonly bridge: "scroll-canonical";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly SCR: {
            readonly name: "Scroll";
            readonly symbol: "SCR";
            readonly oracleId: "SCR";
            readonly address: "0xd29687c813D741E2F938F4aC377128810E217b1b";
            readonly chainId: 534352;
            readonly decimals: 18;
            readonly website: "https://scroll.io/";
            readonly description: "Scroll is the leading zero-knowledge rollup. Scaling Ethereum for good.";
            readonly documentation: "https://docs.scroll.io/en/home/";
            readonly bridge: "native";
        };
    }>;
    readonly native: {
        readonly symbol: "ETH";
        readonly oracleId: "ETH";
    };
};
