import type { Token } from '../../../types/token.js';

const ETH = {
  name: 'Wrapped Ether',
  address: '0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73',
  symbol: 'WETH',
  oracleId: 'WETH',
  decimals: 18,
  chainId: 4663,
  website: 'https://weth.io/',
  description: 'Ether or ETH is the native currency built on the Ethereum blockchain.',
  bridge: 'robinhood-canonical',
  documentation: 'https://ethereum.org/en/developers/docs/',
  tags: ['BLUECHIP'],
} as const satisfies Token;

const UP = {
  name: 'up',
  symbol: 'UP33',
  oracleId: 'UP33',
  address: '0x57C0E45cB534413D1C20A4240955d6bB250BB4F1',
  chainId: 4663,
  decimals: 18,
  website: 'https://up33.xyz/',
  description:
    'UP is the protocol token of Up Protocol on Robinhood. It is what emissions pay, what incentives buy votes with, and what trades freely on up. When locked as veUP, it becomes a governance token whose voting power equals the locked amount scaled by the remaining lock time, up to four years.',
  documentation: 'https://up33.xyz/docs',
  bridge: 'native',
} as const satisfies Token;

export const tokens = {
  WNATIVE: ETH,
  FEES: ETH,
  ETH,
  WETH: ETH,
  USDG: {
    name: 'Global Dollar',
    address: '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168',
    symbol: 'USDG',
    oracleId: 'USDG',
    decimals: 6,
    chainId: 4663,
    website: 'https://globaldollar.com/',
    description:
      'Global Dollar (USDG) is a single-currency stablecoin pegged to the US dollar, issued by Paxos. Built for payments, settlements and treasury, USDG can be used as an interoperable building block for open-source smart contracts.',
    bridge: 'layer-zero',
    documentation: 'https://docs.paxos.com/guides/stablecoin/usdg',
    tags: ['STABLECOIN'],
  },
  GMErh: {
    name: 'GameStop • Robinhood Token',
    address: '0x1b0E319c6A659F002271B69dB8A7df2F911c153E',
    symbol: 'GME',
    oracleId: 'GMErh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'GameStop Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to GameStop shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_gamestop.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  USOrh: {
    name: 'United States Oil Fund • Robinhood Token',
    address: '0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344',
    symbol: 'USO',
    oracleId: 'USOrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'United States Oil Fund Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to United States Oil Fund shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_united_states_oil_fund.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  AAPLrh: {
    name: 'Apple • Robinhood Token',
    address: '0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9',
    symbol: 'AAPL',
    oracleId: 'AAPLrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Apple Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Apple shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_apple.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  TSLArh: {
    name: 'Tesla • Robinhood Token',
    address: '0x322F0929c4625eD5bAd873c95208D54E1c003b2d',
    symbol: 'TSLA',
    oracleId: 'TSLArh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Tesla Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Tesla shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_tesla.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  MSFTrh: {
    name: 'Microsoft • Robinhood Token',
    address: '0xe93237C50D904957Cf27E7B1133b510C669c2e74',
    symbol: 'MSFT',
    oracleId: 'MSFTrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Microsoft Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Microsoft shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_microsoft.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  RDDTrh: {
    name: 'Reddit • Robinhood Token',
    address: '0x05b37Fb53A299a1b874A619e1c4C404D52C36F4C',
    symbol: 'RDDT',
    oracleId: 'RDDTrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Reddit Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Reddit shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_reddit.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  CASHCAT: {
    name: 'Cash Cat',
    address: '0x020bfC650A365f8BB26819deAAbF3E21291018b4',
    symbol: 'CASHCAT',
    oracleId: 'CASHCAT',
    decimals: 18,
    chainId: 4663,
    website: 'https://cashcattoken.xyz/',
    description:
      'The cat that became a hood. The mascot of the movement before the movement had a logo. $CASHCAT honors the origin story of Robinhood Chain.',
    bridge: 'native',
    documentation: 'https://cashcattoken.xyz/#tokenomics',
    tags: ['MEMECOIN'],
  },
  TENDIES: {
    name: 'TENDIES',
    address: '0x45242320DBB855EeA8Fd36804C6487E10E97FCF9',
    symbol: 'TENDIES',
    oracleId: 'TENDIES',
    decimals: 18,
    chainId: 4663,
    description:
      'Tendies is a community/meme token. There is no team, there is no supply hoarding.',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  STONKBROKER: {
    name: 'StonkBroker',
    address: '0xe934e36A439C94017B64a3FecE66AF12099aBF50',
    symbol: 'STONKBROKER',
    oracleId: 'STONKBROKER',
    decimals: 18,
    chainId: 4663,
    website: 'https://stonkbrokers.cash/',
    description: 'StonkBroker is a community/meme token on Robinhood Chain.',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  FRONG: {
    name: 'frong',
    address: '0x6245e67affA44a23077f0Ea7f981a8DC743a0c47',
    symbol: 'FRONG',
    oracleId: 'FRONG',
    decimals: 18,
    chainId: 4663,
    description: "it's frong, baby",
    documentation:
      'https://developers.uniswap.org/docs/liquidity/liquidity-launchpad/concepts/token-factory',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  UP,
  UP33: UP,
  PONS: {
    name: 'Pons',
    symbol: 'PONS',
    oracleId: 'PONS',
    address: '0x39dBED3a2bd333467115dE45665cC57F813C4571',
    chainId: 4663,
    decimals: 18,
    website: 'https://www.ponsfamily.com/launchpad',
    description: 'Launchpad token for Pons 100% of fees go back to Pons',
    documentation: '',
    bridge: 'native',
  },
  VIRTUAL: {
    name: 'VIRTUAL',
    symbol: 'VIRTUAL',
    oracleId: 'rhVIRTUAL',
    address: '0xc6911796042b15d7Fa4F6CDe69e245DdCd3d9c31',
    chainId: 4663,
    decimals: 18,
    description:
      'Virtuals Protocol is building the co-ownership layer for AI agents in gaming and entertainment. These agents can operate across a wide range of applications and games, significantly expanding their revenue surface area.',
    website: 'https://www.virtuals.io/',
    documentation: 'https://whitepaper.virtuals.io/',
    bridge: 'chainlink-ccip',
    tags: ['LARGE_HOLDERS', 'NO_TIMELOCK'],
  },
} as const satisfies Record<string, Token>;
