import type { Token } from '../../../types/token.js';

const ETH = {
  name: 'Wrapped Ether',
  address: '0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73',
  symbol: 'WETH',
  oracleId: 'WETH',
  decimals: 18,
  chainId: 4663,
  website: 'https://weth.io/',
  description: 'Ether or ETH is the native currency built on the Ethereum blockchain.',
  bridge: 'robinhood-canonical',
  documentation: 'https://ethereum.org/en/developers/docs/',
  tags: ['BLUECHIP'],
} as const satisfies Token;

const UP = {
  name: 'up',
  symbol: 'UP33',
  oracleId: 'UP33',
  address: '0x57C0E45cB534413D1C20A4240955d6bB250BB4F1',
  chainId: 4663,
  decimals: 18,
  website: 'https://up33.xyz/',
  description:
    'UP is the protocol token of Up Protocol on Robinhood. It is what emissions pay, what incentives buy votes with, and what trades freely on up. When locked as veUP, it becomes a governance token whose voting power equals the locked amount scaled by the remaining lock time, up to four years.',
  documentation: 'https://up33.xyz/docs',
  bridge: 'native',
} as const satisfies Token;

export const tokens = {
  WNATIVE: ETH,
  FEES: ETH,
  ETH,
  WETH: ETH,
  USDG: {
    name: 'Global Dollar',
    address: '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168',
    symbol: 'USDG',
    oracleId: 'USDG',
    decimals: 6,
    chainId: 4663,
    website: 'https://globaldollar.com/',
    description:
      'Global Dollar (USDG) is a single-currency stablecoin pegged to the US dollar, issued by Paxos. Built for payments, settlements and treasury, USDG can be used as an interoperable building block for open-source smart contracts.',
    bridge: 'layer-zero',
    documentation: 'https://docs.paxos.com/guides/stablecoin/usdg',
    tags: ['STABLECOIN'],
  },
  GMErh: {
    name: 'GameStop • Robinhood Token',
    address: '0x1b0E319c6A659F002271B69dB8A7df2F911c153E',
    symbol: 'GME',
    oracleId: 'GMErh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'GameStop Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to GameStop shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_gamestop.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  USOrh: {
    name: 'United States Oil Fund • Robinhood Token',
    address: '0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344',
    symbol: 'USO',
    oracleId: 'USOrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'United States Oil Fund Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to United States Oil Fund shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_united_states_oil_fund.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  AAPLrh: {
    name: 'Apple • Robinhood Token',
    address: '0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9',
    symbol: 'AAPL',
    oracleId: 'AAPLrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Apple Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Apple shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_apple.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  TSLArh: {
    name: 'Tesla • Robinhood Token',
    address: '0x322F0929c4625eD5bAd873c95208D54E1c003b2d',
    symbol: 'TSLA',
    oracleId: 'TSLArh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Tesla Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Tesla shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_tesla.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  MSFTrh: {
    name: 'Microsoft • Robinhood Token',
    address: '0xe93237C50D904957Cf27E7B1133b510C669c2e74',
    symbol: 'MSFT',
    oracleId: 'MSFTrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Microsoft Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Microsoft shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_microsoft.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  RDDTrh: {
    name: 'Reddit • Robinhood Token',
    address: '0x05b37Fb53A299a1b874A619e1c4C404D52C36F4C',
    symbol: 'RDDT',
    oracleId: 'RDDTrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Reddit Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Reddit shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_reddit.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  AMZNrh: {
    name: 'Amazon • Robinhood Token',
    address: '0x12f190a9F9d7D37a250758b26824B97CE941bF54',
    symbol: 'AMZN',
    oracleId: 'AMZNrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Amazon Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Amazon shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_amazon.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  NFLXrh: {
    name: 'Netflix • Robinhood Token',
    address: '0xE0444EF8BF4eD74f74FD73686e2ddF4C1c5591E8',
    symbol: 'NFLX',
    oracleId: 'NFLXrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Netflix Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Netflix shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_netflix.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  COSTrh: {
    name: 'Costco • Robinhood Token',
    address: '0x4EA005168D7F09a7A0Ba9D1DEf21a479950E44C2',
    symbol: 'COST',
    oracleId: 'COSTrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Costco Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Costco shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_costco.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  METArh: {
    name: 'Meta Platforms • Robinhood Token',
    address: '0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35',
    symbol: 'META',
    oracleId: 'METArh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Meta Platforms Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Meta Platforms shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_meta_platforms.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  RBLXrh: {
    name: 'Roblox Corporation • Robinhood Token',
    address: '0xF0C4BF4C582cb3836e98394b1d4e7B7281101bE8',
    symbol: 'RBLX',
    oracleId: 'RBLXrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Roblox Corporation Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Roblox Corporation shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_roblox.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  TTWOrh: {
    name: 'Take-Two Interactive Software • Robinhood Token',
    address: '0x5e81213613b6B86EaB4c6c50d718d34359459786',
    symbol: 'TTWO',
    oracleId: 'TTWOrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Take-Two Interactive Software Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Take-Two Interactive Software shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_take_two_interactive_software.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  HIMSrh: {
    name: 'Hims & Hers Health • Robinhood Token',
    address: '0xCceE82fE024c36fA15E1005edE3E9e4787e23D09',
    symbol: 'HIMS',
    oracleId: 'HIMSrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Hims & Hers Health Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Hims & Hers Health shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_hims_and_hers_health_inc.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  RCATrh: {
    name: 'Red Cat Holdings • Robinhood Token',
    address: '0xFDE6b5d9BB419B10C23268c74e369AbFF39C0460',
    symbol: 'RCAT',
    oracleId: 'RCATrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Red Cat Holdings Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Red Cat Holdings shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_red_cat_holdings_inc.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  PLTRrh: {
    name: 'Palantir Technologies • Robinhood Token',
    address: '0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A',
    symbol: 'PLTR',
    oracleId: 'PLTRrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Palantir Technologies Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Palantir Technologies shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_palantir_technologies.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  CASHCAT: {
    name: 'Cash Cat',
    address: '0x020bfC650A365f8BB26819deAAbF3E21291018b4',
    symbol: 'CASHCAT',
    oracleId: 'CASHCAT',
    decimals: 18,
    chainId: 4663,
    website: 'https://cashcattoken.xyz/',
    description:
      'The cat that became a hood. The mascot of the movement before the movement had a logo. $CASHCAT honors the origin story of Robinhood Chain.',
    bridge: 'native',
    documentation: 'https://cashcattoken.xyz/#tokenomics',
    tags: ['MEMECOIN'],
  },
  TENDIES: {
    name: 'TENDIES',
    address: '0x45242320DBB855EeA8Fd36804C6487E10E97FCF9',
    symbol: 'TENDIES',
    oracleId: 'TENDIES',
    decimals: 18,
    chainId: 4663,
    description:
      'Tendies is a community/meme token. There is no team, there is no supply hoarding.',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  STONKBROKER: {
    name: 'StonkBroker',
    address: '0xe934e36A439C94017B64a3FecE66AF12099aBF50',
    symbol: 'STONKBROKER',
    oracleId: 'STONKBROKER',
    decimals: 18,
    chainId: 4663,
    website: 'https://stonkbrokers.cash/',
    description: 'StonkBroker is a community/meme token on Robinhood Chain.',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  FRONG: {
    name: 'frong',
    address: '0x6245e67affA44a23077f0Ea7f981a8DC743a0c47',
    symbol: 'FRONG',
    oracleId: 'FRONG',
    decimals: 18,
    chainId: 4663,
    description: "it's frong, baby",
    documentation:
      'https://developers.uniswap.org/docs/liquidity/liquidity-launchpad/concepts/token-factory',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  AI: {
    name: 'Artificial Inu',
    address: '0x2E8c31162b855A2ffa90F6F8634643Ad6F111e18',
    symbol: 'AI',
    oracleId: 'AI',
    decimals: 18,
    chainId: 4663,
    website: 'https://artificialinu.com/',
    description: 'Where speculative markets meet productive capital. The INU stays artificial.',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  BONER: {
    name: 'Boner Coin',
    address: '0x98096d17e191B3dA1d5f99a6D7b3584351b11E18',
    symbol: 'BONER',
    oracleId: 'BONER',
    decimals: 18,
    chainId: 4663,
    website: 'https://x.com/bonercoinlong',
    description: 'Hard money.',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  UP,
  UP33: UP,
  PONS: {
    name: 'Pons',
    symbol: 'PONS',
    oracleId: 'PONS',
    address: '0x39dBED3a2bd333467115dE45665cC57F813C4571',
    chainId: 4663,
    decimals: 18,
    website: 'https://www.ponsfamily.com/launchpad',
    description: 'Launchpad token for Pons 100% of fees go back to Pons',
    documentation: '',
    bridge: 'native',
  },
  VIRTUAL: {
    name: 'VIRTUAL',
    symbol: 'VIRTUAL',
    oracleId: 'rhVIRTUAL',
    address: '0xc6911796042b15d7Fa4F6CDe69e245DdCd3d9c31',
    chainId: 4663,
    decimals: 18,
    description:
      'Virtuals Protocol is building the co-ownership layer for AI agents in gaming and entertainment. These agents can operate across a wide range of applications and games, significantly expanding their revenue surface area.',
    website: 'https://www.virtuals.io/',
    documentation: 'https://whitepaper.virtuals.io/',
    bridge: 'chainlink-ccip',
    tags: ['LARGE_HOLDERS', 'NO_TIMELOCK'],
  },
  NVDArh: {
    name: 'NVIDIA • Robinhood Token',
    symbol: 'NVDA',
    oracleId: 'NVDArh',
    address: '0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'NVIDIA Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to NVIDIA shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_nvidia.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  INTCrh: {
    name: 'Intel • Robinhood Token',
    symbol: 'INTC',
    oracleId: 'INTCrh',
    address: '0xc72b96e0E48ecd4DC75E1e45396e26300BC39681',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Intel Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Intel shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_intel.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  MSTRrh: {
    name: 'Strategy Inc. • Robinhood Token',
    symbol: 'MSTR',
    oracleId: 'MSTRrh',
    address: '0xec262a75e413fAfD0dF80480274532C79D42da09',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Strategy Inc. Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Strategy Inc. shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  SPCXrh: {
    name: 'SpaceX • Robinhood Token',
    address: '0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa',
    symbol: 'SPCX',
    oracleId: 'SPCXrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'SpaceX Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Class A common stock of Space Exploration Technologies Corp. without conferring ownership or shareholder rights.',
    bridge: 'native',
    tags: ['STOCK'],
  },
  SPYrh: {
    name: 'SPDR S&P 500 ETF Trust • Robinhood Token',
    address: '0x117cc2133c37B721F49dE2A7a74833232B3B4C0C',
    symbol: 'SPY',
    oracleId: 'SPYrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'SPY Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to shares of the SPDR S&P 500 ETF Trust without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  COINrh: {
    name: 'Coinbase • Robinhood Token',
    address: '0x6330D8C3178a418788dF01a47479c0ce7CCF450b',
    symbol: 'COIN',
    oracleId: 'COINrh',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Coinbase Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Coinbase Global shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_coinbase.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  MUrh: {
    name: 'Micron Technology • Robinhood Token',
    symbol: 'MU',
    oracleId: 'MUrh',
    address: '0xfF080c8ce2E5feadaCa0Da81314Ae59D232d4afD',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Micron Technology Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Micron Technology shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  AMDrh: {
    name: 'AMD • Robinhood Token',
    symbol: 'AMD',
    oracleId: 'AMDrh',
    address: '0x86923f96303D656E4aa86D9d42D1e57ad2023fdC',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'AMD Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to AMD shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  SNDKrh: {
    name: 'Sandisk Corporation • Robinhood Token',
    symbol: 'SNDK',
    oracleId: 'SNDKrh',
    address: '0xB90A19fF0Af67f7779afF50A882A9CfF42446400',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Sandisk Corporation Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Sandisk Corporation shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  TSMrh: {
    name: 'Taiwan Semiconductor Manufacturing • Robinhood Token',
    symbol: 'TSM',
    oracleId: 'TSMrh',
    address: '0x58FfE4a942d3885bAa22D7520691F611EF09e7AA',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Taiwan Semiconductor Manufacturing Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Taiwan Semiconductor Manufacturing shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  GLDrh: {
    name: 'SPDR Gold Trust • Robinhood Token',
    symbol: 'GLD',
    oracleId: 'GLDrh',
    address: '0xC9a981FEE1F9DEc688bb123ccDeCc63D0deBFC4e',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'SPDR Gold Trust Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to SPDR Gold Trust shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  SLVrh: {
    name: 'iShares Silver Trust • Robinhood Token',
    symbol: 'SLV',
    oracleId: 'SLVrh',
    address: '0x411eFb0E7f985935DAec3D4C3ebaEa0d0AD7D89f',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'iShares Silver Trust Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to iShares Silver Trust shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  rhcbBTC: {
    name: 'Coinbase Wrapped BTC',
    symbol: 'cbBTC',
    oracleId: 'rhcbBTC',
    address: '0xCEC185eB182c47d1bA1EFc84e6959e18cd620Be4',
    chainId: 4663,
    decimals: 8,
    website: 'https://www.coinbase.com/',
    description:
      'Coinbase Wrapped Bitcoin (cbBTC) is backed 1:1 with Bitcoin, custodied with Coinbase.',
    documentation: 'https://www.coinbase.com/blog/coinbase-wrapped-btc-cbbtc-is-now-live',
    bridge: 'chainlink-ccip',
  },
  CRCLrh: {
    name: 'Circle Internet Group • Robinhood Token',
    symbol: 'CRCL',
    oracleId: 'CRCLrh',
    address: '0xdF0992E440dD0be65BD8439b609d6D4366bf1CB5',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Circle Internet Group • Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Circle Internet Group shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  USARrh: {
    name: 'USA Rare Earth • Robinhood Token',
    symbol: 'USAR',
    oracleId: 'USARrh',
    address: '0xd917B029C761D264c6A312BBbcDA868658eF86a6',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'USA Rare Earth • Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to USA Rare Earth shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  QQQrh: {
    name: 'Invesco QQQ • Robinhood Token',
    symbol: 'QQQ',
    oracleId: 'QQQrh',
    address: '0xD5f3879160bc7c32ebb4dC785F8a4F505888de68',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Invesco QQQ • Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Invesco QQQ shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
  DJTrh: {
    name: 'Trump Media & Technology Group • Robinhood Token',
    symbol: 'DJT',
    oracleId: 'DJTrh',
    address: '0x1D11f0496982706C5e14A514D4E79F2e6BdE4516',
    chainId: 4663,
    decimals: 18,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Trump Media & Technology Group • Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Trump Media & Technology Group shares without conferring ownership or shareholder rights.',
    documentation: 'https://docs.robinhood.com/chain/stock-tokens/',
    bridge: 'native',
    tags: ['STOCK'],
  },
} as const satisfies Record<string, Token>;
