import type { Token } from '../../../types/token.js';

const ETH = {
  name: 'Wrapped Ether',
  address: '0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73',
  symbol: 'WETH',
  oracleId: 'WETH',
  decimals: 18,
  chainId: 4663,
  website: 'https://weth.io/',
  description: 'Ether or ETH is the native currency built on the Ethereum blockchain.',
  bridge: 'robinhood-canonical',
  documentation: 'https://ethereum.org/en/developers/docs/',
  tags: ['BLUECHIP'],
} as const satisfies Token;

const UP = {
  name: 'up',
  symbol: 'UP33',
  oracleId: 'UP33',
  address: '0x57C0E45cB534413D1C20A4240955d6bB250BB4F1',
  chainId: 4663,
  decimals: 18,
  website: 'https://up33.xyz/',
  description:
    'UP is the protocol token of Up Protocol on Robinhood. It is what emissions pay, what incentives buy votes with, and what trades freely on up. When locked as veUP, it becomes a governance token whose voting power equals the locked amount scaled by the remaining lock time, up to four years.',
  documentation: 'https://up33.xyz/docs',
  bridge: 'native',
} as const satisfies Token;

export const tokens = {
  WNATIVE: ETH,
  FEES: ETH,
  ETH,
  WETH: ETH,
  USDG: {
    name: 'Global Dollar',
    address: '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168',
    symbol: 'USDG',
    oracleId: 'USDG',
    decimals: 6,
    chainId: 4663,
    website: 'https://globaldollar.com/',
    description:
      'Global Dollar (USDG) is a single-currency stablecoin pegged to the US dollar, issued by Paxos. Built for payments, settlements and treasury, USDG can be used as an interoperable building block for open-source smart contracts.',
    bridge: 'layer-zero',
    documentation: 'https://docs.paxos.com/guides/stablecoin/usdg',
    tags: ['STABLECOIN'],
  },
  rhGME: {
    name: 'GameStop • Robinhood Token',
    address: '0x1b0E319c6A659F002271B69dB8A7df2F911c153E',
    symbol: 'GME',
    oracleId: 'rhGME',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'GameStop Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to GameStop shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_gamestop.pdf',
    bridge: 'native',
    tags: ['LARGE_HOLDERS', 'STOCK'],
  },
  rhSPCX: {
    name: 'SpaceX • Robinhood Token',
    address: '0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa',
    symbol: 'SPCX',
    oracleId: 'rhSPCX',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'SpaceX Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Class A common stock of Space Exploration Technologies Corp. without conferring ownership or shareholder rights.',
    bridge: 'native',
    tags: ['STOCK'],
  },
  rhSPY: {
    name: 'SPDR S&P 500 ETF Trust • Robinhood Token',
    address: '0x117cc2133c37B721F49dE2A7a74833232B3B4C0C',
    symbol: 'SPY',
    oracleId: 'rhSPY',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'SPY Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to shares of the SPDR S&P 500 ETF Trust without conferring ownership or shareholder rights.',
    bridge: 'native',
    tags: ['STOCK'],
  },
  rhCOIN: {
    name: 'Coinbase • Robinhood Token',
    address: '0x6330D8C3178a418788dF01a47479c0ce7CCF450b',
    symbol: 'COIN',
    oracleId: 'rhCOIN',
    decimals: 18,
    chainId: 4663,
    website: 'https://robinhood.com/rhj/stocktokens/',
    description:
      'Coinbase Robinhood Token is a tokenized debt security issued by Robinhood Assets (Jersey) Limited that provides price exposure to Coinbase Global shares without conferring ownership or shareholder rights.',
    documentation:
      'https://cdn.robinhood.com/assets/robinhood/legal/rhj_final_terms_for_tokenised_debt_securities_linked_to_coinbase.pdf',
    bridge: 'native',
    tags: ['STOCK'],
  },
  CASHCAT: {
    name: 'Cash Cat',
    address: '0x020bfC650A365f8BB26819deAAbF3E21291018b4',
    symbol: 'CASHCAT',
    oracleId: 'CASHCAT',
    decimals: 18,
    chainId: 4663,
    website: 'https://cashcattoken.xyz/',
    description:
      'The cat that became a hood. The mascot of the movement before the movement had a logo. $CASHCAT honors the origin story of Robinhood Chain.',
    bridge: 'native',
    documentation: 'https://cashcattoken.xyz/#tokenomics',
    tags: ['MEMECOIN'],
  },
  TENDIES: {
    name: 'TENDIES',
    address: '0x45242320DBB855EeA8Fd36804C6487E10E97FCF9',
    symbol: 'TENDIES',
    oracleId: 'TENDIES',
    decimals: 18,
    chainId: 4663,
    description:
      'Tendies is a community/meme token. There is no team, there is no supply hoarding.',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  STONKBROKER: {
    name: 'StonkBroker',
    address: '0xe934e36A439C94017B64a3FecE66AF12099aBF50',
    symbol: 'STONKBROKER',
    oracleId: 'STONKBROKER',
    decimals: 18,
    chainId: 4663,
    website: 'https://stonkbrokers.cash/',
    description: 'StonkBroker is a community/meme token on Robinhood Chain.',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  FRONG: {
    name: 'frong',
    address: '0x6245e67affA44a23077f0Ea7f981a8DC743a0c47',
    symbol: 'FRONG',
    oracleId: 'FRONG',
    decimals: 18,
    chainId: 4663,
    description: "it's frong, baby",
    documentation:
      'https://developers.uniswap.org/docs/liquidity/liquidity-launchpad/concepts/token-factory',
    bridge: 'native',
    tags: ['MEMECOIN'],
  },
  UP,
  UP33: UP,
  PONS: {
    name: 'Pons',
    symbol: 'PONS',
    oracleId: 'PONS',
    address: '0x39dBED3a2bd333467115dE45665cC57F813C4571',
    chainId: 4663,
    decimals: 18,
    website: 'https://www.ponsfamily.com/launchpad',
    description: 'Launchpad token for Pons 100% of fees go back to Pons',
    documentation: '',
    bridge: 'native',
  },
} as const satisfies Record<string, Token>;
