export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped Re.Al Ether";
        readonly address: "0x90c6E93849E06EC7478ba24522329d14A5954Df4";
        readonly symbol: "WREETH";
        readonly oracleId: "reETH";
        readonly decimals: 18;
        readonly chainId: 111188;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "real-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly FEES: {
        readonly name: "Wrapped Re.Al Ether";
        readonly address: "0x90c6E93849E06EC7478ba24522329d14A5954Df4";
        readonly symbol: "WREETH";
        readonly oracleId: "reETH";
        readonly decimals: 18;
        readonly chainId: 111188;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "real-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly ETH: {
        readonly name: "Wrapped Re.Al Ether";
        readonly address: "0x90c6E93849E06EC7478ba24522329d14A5954Df4";
        readonly symbol: "WREETH";
        readonly oracleId: "reETH";
        readonly decimals: 18;
        readonly chainId: 111188;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "real-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly reETH: {
        readonly name: "Wrapped Re.Al Ether";
        readonly address: "0x90c6E93849E06EC7478ba24522329d14A5954Df4";
        readonly symbol: "WREETH";
        readonly oracleId: "reETH";
        readonly decimals: 18;
        readonly chainId: 111188;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "real-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly WREETH: {
        readonly name: "Wrapped Re.Al Ether";
        readonly address: "0x90c6E93849E06EC7478ba24522329d14A5954Df4";
        readonly symbol: "WREETH";
        readonly oracleId: "reETH";
        readonly decimals: 18;
        readonly chainId: 111188;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "real-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly USDC: {
        readonly name: "USD Coin";
        readonly address: "0xc518A88c67CECA8B3f24c4562CB71deeB2AF86B7";
        readonly symbol: "USDC";
        readonly oracleId: "USDC";
        readonly decimals: 6;
        readonly website: "https://www.centre.io/";
        readonly description: "Arbitrum-based USDC bridged via the official re.al Bridge.";
        readonly bridge: "real-canonical";
        readonly chainId: 111188;
        readonly documentation: "https://developers.circle.com/docs";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly DAI: {
        readonly name: "DAI Stablecoin";
        readonly symbol: "DAI";
        readonly oracleId: "DAI";
        readonly address: "0x75d0cBF342060b14c2fC756fd6E717dFeb5B1B70";
        readonly chainId: 111188;
        readonly decimals: 18;
        readonly website: "https://makerdao.com/en/";
        readonly bridge: "real-canonical";
        readonly documentation: "https://docs.makerdao.com/smart-contract-modules/dai-module/dai-detailed-documentation";
        readonly description: "Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly arcUSD: {
        readonly name: "arcUSD";
        readonly address: "0xAEC9e50e3397f9ddC635C6c429C8C7eca418a143";
        readonly symbol: "arcUSD";
        readonly oracleId: "arcUSD";
        readonly decimals: 18;
        readonly website: "https://arcana.finance/";
        readonly documentation: "https://docs.arcana.finance/";
        readonly description: "Arcana distributes the yield generated from delta-neutral strategies through arcUSD, a rebasing token soft-pegged to the dollar. The yield is distributed to arcUSD holders in the form of daily rebases, increasing their balance each period. On top of the rebases, arcUSD can be deployed in DeFi to unlock additional reward composability.";
        readonly bridge: "native";
        readonly chainId: 111188;
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly UKRE: {
        readonly name: "UK Real Estate";
        readonly address: "0x835d3E1C0aA079C6164AAd21DCb23E60eb71AF48";
        readonly symbol: "UKRE";
        readonly oracleId: "UKRE";
        readonly decimals: 18;
        readonly website: "https://www.tangible.store/";
        readonly documentation: "https://docs.tangible.store/";
        readonly description: "UKRE is a Tangible Basket token backed by tokenized real estate in the UK. Tangible Baskets are permissionless, rebasing ERC-20 tokens—100% backed by tokenized, yield-generating real estate—that distributed yield back to token holders via daily rebase. Baskets price is soft-pegged to the TPV (true property value) of the assets in the pool and will fluctuate based on market demand and the activity of arbitrageurs. With Baskets, anyone, anywhere, at any budget can invest in income-producing real estate with just a few clicks.";
        readonly bridge: "native";
        readonly chainId: 111188;
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly USTB: {
        readonly name: "US T-Bill";
        readonly address: "0x83feDBc0B85c6e29B589aA6BdefB1Cc581935ECD";
        readonly symbol: "USTB";
        readonly oracleId: "USTB";
        readonly decimals: 18;
        readonly website: "https://www.tangible.store/ustb";
        readonly documentation: "https://docs.tangible.store/ustb/ustb-token";
        readonly description: "USTB is a fully permissionless, cross-chain, rebasing dollar-pegged stablecoin. USTB is a wrapped version of USDM, with USDM supplying 100% of the backing for USTB. USDM is backed by Mountain Protocol's reserves of short-duration US Treasuries (T-Bills) having an average duration of less than 3 months or less.";
        readonly bridge: "layer-zero";
        readonly chainId: 111188;
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly PEARL: {
        readonly name: "Pearl";
        readonly address: "0xCE1581d7b4bA40176f0e219b2CaC30088Ad50C7A";
        readonly symbol: "PEARL";
        readonly oracleId: "PEARL";
        readonly decimals: 18;
        readonly website: "https://www.pearl.exchange/";
        readonly documentation: "https://docs.pearl.exchange/";
        readonly description: "Pearl is the native liquidity layer for RWAs on re.al blockchain. Pearl provides a liquidity solution for both new and existing RWA protocols, solving initial liquidity challenges while also serving as an efficient solution to long-term liquidity incentivization.";
        readonly bridge: "native";
        readonly chainId: 111188;
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly RWA: {
        readonly name: "re.al";
        readonly address: "0x4644066f535Ead0cde82D209dF78d94572fCbf14";
        readonly symbol: "RWA";
        readonly oracleId: "RWA";
        readonly decimals: 18;
        readonly website: "https://re.al/";
        readonly documentation: "https://docs.re.al/";
        readonly description: "The RWA token is the governance token to the re.al ecosystem. RWA will exist unlocked as RWA (ERC-20) and locked as veRWA (ERC-721). When locked into veRWA it will provide holders two primary benefits: Value Accrual and Governance Rights";
        readonly bridge: "native";
        readonly chainId: 111188;
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly stRWA: {
        readonly name: "Liquid Staked RWA";
        readonly address: "0x154F5DB4950d2cd4a7Af425E11865215F90DdB07";
        readonly symbol: "stRWA";
        readonly oracleId: "stRWA";
        readonly decimals: 18;
        readonly website: "https://re.al/";
        readonly documentation: "https://docs.re.al/";
        readonly description: "stRWA is a liquid version of veRWA that rebases to distribute accrued yield, making veRWA liquid and composable with DeFi protocols.";
        readonly bridge: "native";
        readonly chainId: 111188;
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly MORE: {
        readonly name: "MORE";
        readonly address: "0x25ea98ac87A38142561eA70143fd44c4772A16b6";
        readonly symbol: "MORE";
        readonly oracleId: "MORE";
        readonly decimals: 18;
        readonly website: "https://stackmore.xyz/";
        readonly documentation: "https://docs.stackmore.xyz/";
        readonly description: "Stack’s $MORE token is a non-algorithmic, collateral-backed stablecoin. This means that every $1 USD of $MORE should have more than $1 USD of collateral backing. Stack considers $MORE to be worth $1 however at times it may not trade at this value. In these instances, Stack has several options at its disposal to regain the $1 USD peg.";
        readonly bridge: "native";
        readonly chainId: 111188;
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
};
