import { Abi } from 'abitype';

export const sonicStakingAbi = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    inputs: [{ internalType: 'address', name: 'target', type: 'address' }],
    name: 'AddressEmptyCode',
    type: 'error',
  },
  { inputs: [], name: 'AlreadyRedirected', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'ERC1967InvalidImplementation',
    type: 'error',
  },
  { inputs: [], name: 'ERC1967NonPayable', type: 'error' },
  { inputs: [], name: 'FailedCall', type: 'error' },
  { inputs: [], name: 'InsufficientSelfStake', type: 'error' },
  { inputs: [], name: 'InvalidInitialization', type: 'error' },
  { inputs: [], name: 'MalformedPubkey', type: 'error' },
  { inputs: [], name: 'NoUnresolvedTreasuryFees', type: 'error' },
  { inputs: [], name: 'NotAuthorized', type: 'error' },
  { inputs: [], name: 'NotDeactivatedStatus', type: 'error' },
  { inputs: [], name: 'NotDriverAuth', type: 'error' },
  { inputs: [], name: 'NotEnoughEpochsPassed', type: 'error' },
  { inputs: [], name: 'NotEnoughTimePassed', type: 'error' },
  { inputs: [], name: 'NotInitializing', type: 'error' },
  { inputs: [], name: 'NothingToStash', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  { inputs: [], name: 'PubkeyUsedByOtherValidator', type: 'error' },
  { inputs: [], name: 'Redirected', type: 'error' },
  { inputs: [], name: 'RefundRatioTooHigh', type: 'error' },
  { inputs: [], name: 'RequestExists', type: 'error' },
  { inputs: [], name: 'RequestNotExists', type: 'error' },
  { inputs: [], name: 'SameAddress', type: 'error' },
  { inputs: [], name: 'SameRedirectionAuthorizer', type: 'error' },
  { inputs: [], name: 'StakeIsFullySlashed', type: 'error' },
  { inputs: [], name: 'StakeSubscriberFailed', type: 'error' },
  { inputs: [], name: 'TransferFailed', type: 'error' },
  { inputs: [], name: 'TransfersNotAllowed', type: 'error' },
  { inputs: [], name: 'TreasuryNotSet', type: 'error' },
  { inputs: [], name: 'UUPSUnauthorizedCallContext', type: 'error' },
  {
    inputs: [{ internalType: 'bytes32', name: 'slot', type: 'bytes32' }],
    name: 'UUPSUnsupportedProxiableUUID',
    type: 'error',
  },
  { inputs: [], name: 'ValidatorDelegationLimitExceeded', type: 'error' },
  { inputs: [], name: 'ValidatorExists', type: 'error' },
  { inputs: [], name: 'ValidatorNotActive', type: 'error' },
  { inputs: [], name: 'ValidatorNotExists', type: 'error' },
  { inputs: [], name: 'ValidatorNotSlashed', type: 'error' },
  { inputs: [], name: 'ValueTooLarge', type: 'error' },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  { inputs: [], name: 'ZeroAmount', type: 'error' },
  { inputs: [], name: 'ZeroRewards', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
    ],
    name: 'AnnouncedRedirection',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'BurntNativeTokens',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'status', type: 'uint256' },
    ],
    name: 'ChangedValidatorStatus',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'delegator', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'rewards', type: 'uint256' },
    ],
    name: 'ClaimedRewards',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'auth', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'createdEpoch', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'createdTime', type: 'uint256' },
    ],
    name: 'CreatedValidator',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'deactivatedEpoch', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'deactivatedTime', type: 'uint256' },
    ],
    name: 'DeactivatedValidator',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'delegator', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'Delegated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint64', name: 'version', type: 'uint64' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'delegator', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'RefundedSlashedLegacyDelegation',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'delegator', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'rewards', type: 'uint256' },
    ],
    name: 'RestakedRewards',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'TreasuryFeesResolved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'delegator', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
      { indexed: true, internalType: 'uint256', name: 'wrID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'Undelegated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'refundRatio', type: 'uint256' },
    ],
    name: 'UpdatedSlashingRefundRatio',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'Upgraded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'delegator', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
      { indexed: true, internalType: 'uint256', name: 'wrID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'penalty', type: 'uint256' },
    ],
    name: 'Withdrawn',
    type: 'event',
  },
  {
    inputs: [],
    name: 'UPGRADE_INTERFACE_VERSION',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { internalType: 'bool', name: 'syncPubkey', type: 'bool' },
    ],
    name: '_syncValidator',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'to', type: 'address' }],
    name: 'announceRedirection',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'burnNativeTokens', outputs: [], stateMutability: 'payable', type: 'function' },
  {
    inputs: [{ internalType: 'uint256', name: 'toValidatorID', type: 'uint256' }],
    name: 'claimRewards',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'constsAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes', name: 'pubkey', type: 'bytes' }],
    name: 'createValidator',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'currentEpoch',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'currentSealedEpoch',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { internalType: 'uint256', name: 'status', type: 'uint256' },
    ],
    name: 'deactivateValidator',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'toValidatorID', type: 'uint256' }],
    name: 'delegate',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'epoch', type: 'uint256' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'getEpochAccumulatedOriginatedTxsFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'epoch', type: 'uint256' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'getEpochAccumulatedRewardPerToken',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'epoch', type: 'uint256' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'getEpochAccumulatedUptime',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'epoch', type: 'uint256' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'getEpochAverageUptime',
    outputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'epoch', type: 'uint256' }],
    name: 'getEpochEndBlock',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'epoch', type: 'uint256' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'getEpochOfflineBlocks',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'epoch', type: 'uint256' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'getEpochOfflineTime',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'epoch', type: 'uint256' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'getEpochReceivedStake',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'epoch', type: 'uint256' }],
    name: 'getEpochSnapshot',
    outputs: [
      { internalType: 'uint256', name: 'endTime', type: 'uint256' },
      { internalType: 'uint256', name: 'endBlock', type: 'uint256' },
      { internalType: 'uint256', name: 'epochFee', type: 'uint256' },
      { internalType: 'uint256', name: 'baseRewardPerSecond', type: 'uint256' },
      { internalType: 'uint256', name: 'totalStake', type: 'uint256' },
      { internalType: 'uint256', name: 'totalSupply', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'epoch', type: 'uint256' }],
    name: 'getEpochValidatorIDs',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'delegator', type: 'address' }],
    name: 'getRedirection',
    outputs: [{ internalType: 'address', name: 'receiver', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'delegator', type: 'address' }],
    name: 'getRedirectionRequest',
    outputs: [{ internalType: 'address', name: 'receiver', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'validatorID', type: 'uint256' }],
    name: 'getSelfStake',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'delegator', type: 'address' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'getStake',
    outputs: [{ internalType: 'uint256', name: 'stake', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'validatorID', type: 'uint256' }],
    name: 'getValidator',
    outputs: [
      { internalType: 'uint256', name: 'status', type: 'uint256' },
      { internalType: 'uint256', name: 'receivedStake', type: 'uint256' },
      { internalType: 'address', name: 'auth', type: 'address' },
      { internalType: 'uint256', name: 'createdEpoch', type: 'uint256' },
      { internalType: 'uint256', name: 'createdTime', type: 'uint256' },
      { internalType: 'uint256', name: 'deactivatedTime', type: 'uint256' },
      { internalType: 'uint256', name: 'deactivatedEpoch', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'auth', type: 'address' }],
    name: 'getValidatorID',
    outputs: [{ internalType: 'uint256', name: 'validatorID', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'validatorID', type: 'uint256' }],
    name: 'getValidatorPubkey',
    outputs: [{ internalType: 'bytes', name: 'pubkey', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'delegator', type: 'address' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { internalType: 'uint256', name: 'wrID', type: 'uint256' },
    ],
    name: 'getWithdrawalRequest',
    outputs: [
      { internalType: 'uint256', name: 'epoch', type: 'uint256' },
      { internalType: 'uint256', name: 'time', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'sealedEpoch', type: 'uint256' },
      { internalType: 'uint256', name: '_totalSupply', type: 'uint256' },
      { internalType: 'address', name: 'nodeDriver', type: 'address' },
      { internalType: 'address', name: '_c', type: 'address' },
      { internalType: 'address', name: 'owner', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'address', name: 'to', type: 'address' },
    ],
    name: 'initiateRedirection',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'validatorID', type: 'uint256' }],
    name: 'isSlashed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'issueTokens',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'lastValidatorID',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'delegator', type: 'address' },
      { internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
    ],
    name: 'pendingRewards',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'pubkeyAddress', type: 'address' }],
    name: 'pubkeyAddressToValidatorID',
    outputs: [{ internalType: 'uint256', name: 'validatorID', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'to', type: 'address' }],
    name: 'redirect',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'redirectionAuthorizer',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [], name: 'resolveTreasuryFees', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'uint256', name: 'toValidatorID', type: 'uint256' }],
    name: 'restakeRewards',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'delegator', type: 'address' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'rewardsStash',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'offlineTime', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'offlineBlocks', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'uptimes', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'originatedTxsFee', type: 'uint256[]' },
    ],
    name: 'sealEpoch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256[]', name: 'nextValidatorIDs', type: 'uint256[]' }],
    name: 'sealEpochValidators',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'delegator', type: 'address' },
      { internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
      { internalType: 'uint256', name: 'stake', type: 'uint256' },
    ],
    name: 'setGenesisDelegation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'auth', type: 'address' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { internalType: 'bytes', name: 'pubkey', type: 'bytes' },
      { internalType: 'uint256', name: 'createdTime', type: 'uint256' },
    ],
    name: 'setGenesisValidator',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'v', type: 'address' }],
    name: 'setRedirectionAuthorizer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'validatorID', type: 'uint256' }],
    name: 'slashingRefundRatio',
    outputs: [{ internalType: 'uint256', name: 'refundRatio', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stakeSubscriberAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'delegator', type: 'address' },
      { internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
    ],
    name: 'stashRewards',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'delegator', type: 'address' },
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
    ],
    name: 'stashedRewardsUntilEpoch',
    outputs: [{ internalType: 'uint256', name: 'epoch', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalActiveStake',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalStake',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'treasuryAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
      { internalType: 'uint256', name: 'wrID', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'undelegate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'unresolvedTreasuryFees',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'v', type: 'address' }],
    name: 'updateConstsAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'validatorID', type: 'uint256' },
      { internalType: 'uint256', name: 'refundRatio', type: 'uint256' },
    ],
    name: 'updateSlashingRefundRatio',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'v', type: 'address' }],
    name: 'updateStakeSubscriberAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'v', type: 'address' }],
    name: 'updateTreasuryAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'newImplementation', type: 'address' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'version',
    outputs: [{ internalType: 'bytes3', name: '', type: 'bytes3' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'toValidatorID', type: 'uint256' },
      { internalType: 'uint256', name: 'wrID', type: 'uint256' },
    ],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
] as const satisfies Abi;
