import * as platforms from './platforms/index.js';
export declare const kava: {
    readonly platforms: typeof platforms;
    readonly tokens: {
        readonly WNATIVE: {
            readonly name: "Wrapped KAVA";
            readonly address: "0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b";
            readonly symbol: "WKAVA";
            readonly oracleId: "WKAVA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://www.kava.io/";
            readonly description: "The Kava Network is the first Layer-1 blockchain to combine the speed and scalability of the Cosmos SDK with the developer support of Ethereum. The Kava Network will empower developers to build for Web3 and next-gen blockchain technologies through its unique co-chain architecture. KAVA is the native governance and staking token of the Kava Network, enabling its decentralization and security. ";
            readonly documentation: "https://docs.kava.io/docs/intro/";
            readonly bridge: "native";
        };
        readonly FEES: {
            readonly name: "Wrapped KAVA";
            readonly address: "0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b";
            readonly symbol: "WKAVA";
            readonly oracleId: "WKAVA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://www.kava.io/";
            readonly description: "The Kava Network is the first Layer-1 blockchain to combine the speed and scalability of the Cosmos SDK with the developer support of Ethereum. The Kava Network will empower developers to build for Web3 and next-gen blockchain technologies through its unique co-chain architecture. KAVA is the native governance and staking token of the Kava Network, enabling its decentralization and security. ";
            readonly documentation: "https://docs.kava.io/docs/intro/";
            readonly bridge: "native";
        };
        readonly KAVA: {
            readonly name: "Wrapped KAVA";
            readonly address: "0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b";
            readonly symbol: "WKAVA";
            readonly oracleId: "WKAVA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://www.kava.io/";
            readonly description: "The Kava Network is the first Layer-1 blockchain to combine the speed and scalability of the Cosmos SDK with the developer support of Ethereum. The Kava Network will empower developers to build for Web3 and next-gen blockchain technologies through its unique co-chain architecture. KAVA is the native governance and staking token of the Kava Network, enabling its decentralization and security. ";
            readonly documentation: "https://docs.kava.io/docs/intro/";
            readonly bridge: "native";
        };
        readonly WKAVA: {
            readonly name: "Wrapped KAVA";
            readonly address: "0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b";
            readonly symbol: "WKAVA";
            readonly oracleId: "WKAVA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://www.kava.io/";
            readonly description: "The Kava Network is the first Layer-1 blockchain to combine the speed and scalability of the Cosmos SDK with the developer support of Ethereum. The Kava Network will empower developers to build for Web3 and next-gen blockchain technologies through its unique co-chain architecture. KAVA is the native governance and staking token of the Kava Network, enabling its decentralization and security. ";
            readonly documentation: "https://docs.kava.io/docs/intro/";
            readonly bridge: "native";
        };
        readonly kmultiUSDC: {
            readonly name: "USD Coin";
            readonly symbol: "kmultiUSDC";
            readonly oracleId: "kmultiUSDC";
            readonly address: "0xfA9343C3897324496A05fC75abeD6bAC29f8A40f";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://www.circle.com/usdc";
            readonly description: "USDC (Multichain) is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly documentation: "https://developers.circle.com/docs";
            readonly bridge: "multichain";
            readonly tags: readonly ["SYNTHETIC"];
        };
        readonly multichainUSDT: {
            readonly name: "USDT";
            readonly symbol: "USDT";
            readonly oracleId: "multichainUSDT";
            readonly address: "0xB44a9B6905aF7c801311e8F4E76932ee959c663C";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly description: "Multichain Bridged Token. Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
            readonly bridge: "multichain";
            readonly tags: readonly ["SYNTHETIC"];
        };
        readonly USDT: {
            readonly name: "USDT";
            readonly symbol: "USDT";
            readonly oracleId: "USDT";
            readonly address: "0x919C1c267BC06a7039e03fcc2eF738525769109c";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
            readonly bridge: "native";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly DAI: {
            readonly name: "Dai Stablecoin";
            readonly address: "0x765277EebeCA2e31912C9946eAe1021199B39C61";
            readonly symbol: "DAI";
            readonly oracleId: "DAI";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://makerdao.com/";
            readonly documentation: "https://docs.makerdao.com/";
            readonly description: "Multi-Collateral Dai, brings a lot of new and exciting features, such as support for new CDP collateral types and Dai Savings Rate.";
            readonly bridge: "multichain";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly SUSHI: {
            readonly name: "Sushi";
            readonly address: "0x7C598c96D02398d89FbCb9d41Eab3DF0C16F227D";
            readonly symbol: "SUSHI";
            readonly oracleId: "SUSHI";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://sushi.com/";
            readonly description: "Sushi is the home of DeFi. Their community is building a comprehensive, decentralized trading platform for the future of finance. Swap, earn, stack yields, lend, borrow, leverage all on one decentralized, community driven platform.";
            readonly bridge: "multichain";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly WBTC: {
            readonly name: "Wrapped BTC";
            readonly address: "0x818ec0A7Fe18Ff94269904fCED6AE3DaE6d6dC0b";
            readonly symbol: "kmultiWBTC";
            readonly oracleId: "WBTC";
            readonly decimals: 8;
            readonly website: "https://wbtc.network/";
            readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
            readonly chainId: 2222;
            readonly bridge: "multichain";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly ETH: {
            readonly name: "Ether";
            readonly address: "0xE3F5a90F9cb311505cd691a46596599aA1A0AD7D";
            readonly symbol: "kmultiETH";
            readonly oracleId: "ETH";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://ethereum.org/";
            readonly description: "The native currency that flows within the Ethereum economy is called Ether (ETH). Ether is typically used to pay for transaction fees called Gas, and it is the base currency of the network.";
            readonly bridge: "multichain";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly axlUSDC: {
            readonly name: "Axelar USD Coin ";
            readonly symbol: "axlUSDC";
            readonly oracleId: "axlUSDC";
            readonly address: "0xEB466342C4d449BC9f53A865D5Cb90586f405215";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://www.axelar.network/";
            readonly bridge: "axelar";
            readonly description: "axlUSDC is a cross-chain representation of USDC, secured by a validator set using delegated Proof-of-Stake and multi-party cryptography. It allows USDC to move seamlessly across different blockchain ecosystems, minted by depositing USDC into an Axelar Gateway on Ethereum, and can be acquired through DEXs, cross-chain swaps via Squid, or bridging via Satellite.money.";
            readonly documentation: "https://docs.axelar.dev/learn/axlusdc";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly axlUSDT: {
            readonly name: "USDT";
            readonly symbol: "axlUSDT";
            readonly oracleId: "axlUSDT";
            readonly address: "0x7f5373AE26c3E8FfC4c77b7255DF7eC1A9aF52a6";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://www.axelar.network/";
            readonly documentation: "https://docs.axelar.dev/";
            readonly description: "axlUSDT is a cross-chain representation of USDT, secured by a validator set using delegated Proof-of-Stake and multi-party cryptography. It allows USDT to move seamlessly across different blockchain ecosystems, minted by depositing USDT into an Axelar Gateway on Ethereum, and can be acquired through DEXs, cross-chain swaps via Squid, or bridging via Satellite.money.";
            readonly bridge: "axelar";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly axlDAI: {
            readonly name: "Axelar Dai Stablecoin";
            readonly address: "0x5C7e299CF531eb66f2A1dF637d37AbB78e6200C7";
            readonly symbol: "axlDAI";
            readonly oracleId: "axlDAI";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://makerdao.com/";
            readonly documentation: "https://docs.axelar.dev/";
            readonly description: "Multi-Collateral Dai, brings a lot of new and exciting features, such as support for new CDP collateral types and Dai Savings Rate.";
            readonly bridge: "axelar";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly VARA: {
            readonly name: "VARA";
            readonly address: "0xE1da44C0dA55B075aE8E2e4b6986AdC76Ac77d73";
            readonly symbol: "VARA";
            readonly oracleId: "VARA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://equilibrefinance.com//";
            readonly documentation: "https://equilibre-finance.gitbook.io/equilibre-finance/about-us/welcome";
            readonly description: "Équilibre is an ve(3.3) AMM (Automatic Market Maker) based on Velodrome, and designed to provide large liquidity & low swapping fees.";
            readonly bridge: "native";
        };
        readonly oldBIFI: {
            readonly name: "Beefy.Finance";
            readonly symbol: "kmultioldBIFI";
            readonly oracleId: "oldBIFI";
            readonly address: "0xC19281F22A075E0F10351cd5D6Ea9f0AC63d4327";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://beefy.com";
            readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
            readonly documentation: "https://docs.beefy.finance/";
            readonly bridge: "multichain";
        };
        readonly MAI: {
            readonly name: "Mai Stablecoin";
            readonly symbol: "MAI";
            readonly oracleId: "kMAI";
            readonly address: "0xb84Df10966a5D7e1ab46D9276F55d57bD336AFC7";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://www.mai.finance/";
            readonly description: "MAI is a stablecoin collateralized by your crypto holdings. It's powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.";
            readonly documentation: "https://docs.mai.finance/";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly BNB: {
            readonly name: "Binance Chain";
            readonly symbol: "kmultiBNB";
            readonly oracleId: "BNB";
            readonly address: "0xABd380327Fe66724FFDa91A87c772FB8D00bE488";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://www.binance.com/";
            readonly description: "Binance Coin (BNB) is an exchange-based token created and issued by the cryptocurrency exchange Binance. Initially created on the Ethereum blockchain as an ERC-20 token in July 2017, BNB was migrated over to Binance Chain in February 2019 and became the native coin of the Binance Chain.";
            readonly bridge: "multichain";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly axlATOM: {
            readonly name: "Axelar Wrapped ATOM";
            readonly symbol: "axlATOM";
            readonly oracleId: "axlATOM";
            readonly address: "0x06beE9E7238a331B68D83Df3B5B9B16d5DBa83ff";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://cosmos.network/";
            readonly description: "The Internet of Blockchains. Cosmos is an ever-expanding ecosystem of interconnected apps and services, built for a decentralized future.";
            readonly documentation: "https://docs.axelar.dev/resources/wrapped-tokens";
            readonly bridge: "axelar";
        };
        readonly MARE: {
            readonly name: "Mare Finance";
            readonly symbol: "MARE";
            readonly oracleId: "MARE";
            readonly address: "0xd86C8d4279CCaFbec840c782BcC50D201f277419";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://mare.finance/";
            readonly description: "Mare Finance is an EVM compatible lending/borrowing protocol that launched on Kava EVM. Mare Finance provides peer-to-peer lending solutions that are fully decentralized, transparent and non-custodial.";
            readonly documentation: "https://docs.mare.finance/";
            readonly bridge: "native";
        };
        readonly MIM: {
            readonly name: "Magic Internet Money";
            readonly address: "0x471EE749bA270eb4c1165B5AD95E614947f6fCeb";
            readonly symbol: "MIM";
            readonly oracleId: "MIM";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://abracadabra.money/";
            readonly description: "You, the Spellcaster, can provide collateral in the form of various interest bearing crypto assets such as yvYFI, yvUSDT, yvUSDC, xSUSHI and more. With this, you can borrow magic internet money (MIM) which is a stable coin that you can swap for any other traditional stable coin.";
            readonly documentation: "https://docs.abracadabra.money/";
            readonly bridge: "layer-zero";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly axlETH: {
            readonly name: "Axelar Wrapped ETH";
            readonly symbol: "axlETH";
            readonly oracleId: "axlETH";
            readonly address: "0xb829b68f57CC546dA7E5806A929e53bE32a4625D";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://axelar.network/";
            readonly description: "Axelar Wrapped ETH (axlETH) is an ERC-20 token that represents a wrapped version of native Ethereum (ETH) cryptocurrency, allowing for cross-chain transfers and compatibility with the Ethereum ecosystem.";
            readonly documentation: "https://docs.axelar.dev/resources/wrapped-tokens";
            readonly bridge: "axelar";
        };
        readonly axlWBTC: {
            readonly name: "Axelar Wrapped WBTC";
            readonly symbol: "axlWBTC";
            readonly oracleId: "axlWBTC";
            readonly address: "0x1a35EE4640b0A3B87705B0A4B45D227Ba60Ca2ad";
            readonly chainId: 2222;
            readonly decimals: 8;
            readonly website: "https://axelar.network/";
            readonly description: "Axelar Wrapped WBTC (axlWBTC) is an ERC-20 token that represents a 1:1 pegged version of Bitcoin, allowing users to access Bitcoin's value and liquidity within the Kava ecosystem.";
            readonly documentation: "https://docs.axelar.dev/resources/wrapped-tokens";
            readonly bridge: "axelar";
        };
        readonly ATOM: {
            readonly name: "ATOM";
            readonly symbol: "ATOM";
            readonly oracleId: "ATOM";
            readonly address: "0x15932E26f5BD4923d46a2b205191C4b5d5f43FE3";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://cosmos.network/";
            readonly description: "The Internet of Blockchains. Cosmos is an ever-expanding ecosystem of interconnected apps and services, built for a decentralized future.";
            readonly bridge: "ibc";
            readonly documentation: "https://docs.cosmos.network/main";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly lzETH: {
            readonly name: "LayerZero Wrapped ETH";
            readonly symbol: "lzETH";
            readonly oracleId: "WETH";
            readonly address: "0x2DfD4dE5AE386Cd3f4fC8e2cb39240852E47F5E8";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://layerzero.network/";
            readonly description: "LayerZero Wrapped ETH (lzETH) is an ERC-20 token that represents a wrapped version of native Ethereum (ETH) cryptocurrency, allowing for cross-chain transfers and compatibility with the Ethereum ecosystem.";
            readonly bridge: "layer-zero";
        };
        readonly lzWBTC: {
            readonly name: "LayerZero Wrapped WBTC";
            readonly symbol: "lzWBTC";
            readonly oracleId: "WBTC";
            readonly address: "0xb5c4423a65B953905949548276654C96fcaE6992";
            readonly chainId: 2222;
            readonly decimals: 8;
            readonly website: "https://layerzero.network/";
            readonly description: "LayerZero Wrapped WBTC (lzWBTC) is an ERC-20 token that represents a 1:1 pegged version of Bitcoin, allowing users to access Bitcoin's value and liquidity within the Kava ecosystem.";
            readonly bridge: "layer-zero";
        };
    };
    readonly tokenAddressMap: import("../../util/convertSymbolTokenMapToAddressTokenMap.js").AddressToTokenMap<{
        readonly WNATIVE: {
            readonly name: "Wrapped KAVA";
            readonly address: "0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b";
            readonly symbol: "WKAVA";
            readonly oracleId: "WKAVA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://www.kava.io/";
            readonly description: "The Kava Network is the first Layer-1 blockchain to combine the speed and scalability of the Cosmos SDK with the developer support of Ethereum. The Kava Network will empower developers to build for Web3 and next-gen blockchain technologies through its unique co-chain architecture. KAVA is the native governance and staking token of the Kava Network, enabling its decentralization and security. ";
            readonly documentation: "https://docs.kava.io/docs/intro/";
            readonly bridge: "native";
        };
        readonly FEES: {
            readonly name: "Wrapped KAVA";
            readonly address: "0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b";
            readonly symbol: "WKAVA";
            readonly oracleId: "WKAVA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://www.kava.io/";
            readonly description: "The Kava Network is the first Layer-1 blockchain to combine the speed and scalability of the Cosmos SDK with the developer support of Ethereum. The Kava Network will empower developers to build for Web3 and next-gen blockchain technologies through its unique co-chain architecture. KAVA is the native governance and staking token of the Kava Network, enabling its decentralization and security. ";
            readonly documentation: "https://docs.kava.io/docs/intro/";
            readonly bridge: "native";
        };
        readonly KAVA: {
            readonly name: "Wrapped KAVA";
            readonly address: "0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b";
            readonly symbol: "WKAVA";
            readonly oracleId: "WKAVA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://www.kava.io/";
            readonly description: "The Kava Network is the first Layer-1 blockchain to combine the speed and scalability of the Cosmos SDK with the developer support of Ethereum. The Kava Network will empower developers to build for Web3 and next-gen blockchain technologies through its unique co-chain architecture. KAVA is the native governance and staking token of the Kava Network, enabling its decentralization and security. ";
            readonly documentation: "https://docs.kava.io/docs/intro/";
            readonly bridge: "native";
        };
        readonly WKAVA: {
            readonly name: "Wrapped KAVA";
            readonly address: "0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b";
            readonly symbol: "WKAVA";
            readonly oracleId: "WKAVA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://www.kava.io/";
            readonly description: "The Kava Network is the first Layer-1 blockchain to combine the speed and scalability of the Cosmos SDK with the developer support of Ethereum. The Kava Network will empower developers to build for Web3 and next-gen blockchain technologies through its unique co-chain architecture. KAVA is the native governance and staking token of the Kava Network, enabling its decentralization and security. ";
            readonly documentation: "https://docs.kava.io/docs/intro/";
            readonly bridge: "native";
        };
        readonly kmultiUSDC: {
            readonly name: "USD Coin";
            readonly symbol: "kmultiUSDC";
            readonly oracleId: "kmultiUSDC";
            readonly address: "0xfA9343C3897324496A05fC75abeD6bAC29f8A40f";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://www.circle.com/usdc";
            readonly description: "USDC (Multichain) is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly documentation: "https://developers.circle.com/docs";
            readonly bridge: "multichain";
            readonly tags: readonly ["SYNTHETIC"];
        };
        readonly multichainUSDT: {
            readonly name: "USDT";
            readonly symbol: "USDT";
            readonly oracleId: "multichainUSDT";
            readonly address: "0xB44a9B6905aF7c801311e8F4E76932ee959c663C";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly description: "Multichain Bridged Token. Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
            readonly bridge: "multichain";
            readonly tags: readonly ["SYNTHETIC"];
        };
        readonly USDT: {
            readonly name: "USDT";
            readonly symbol: "USDT";
            readonly oracleId: "USDT";
            readonly address: "0x919C1c267BC06a7039e03fcc2eF738525769109c";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
            readonly bridge: "native";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly DAI: {
            readonly name: "Dai Stablecoin";
            readonly address: "0x765277EebeCA2e31912C9946eAe1021199B39C61";
            readonly symbol: "DAI";
            readonly oracleId: "DAI";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://makerdao.com/";
            readonly documentation: "https://docs.makerdao.com/";
            readonly description: "Multi-Collateral Dai, brings a lot of new and exciting features, such as support for new CDP collateral types and Dai Savings Rate.";
            readonly bridge: "multichain";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly SUSHI: {
            readonly name: "Sushi";
            readonly address: "0x7C598c96D02398d89FbCb9d41Eab3DF0C16F227D";
            readonly symbol: "SUSHI";
            readonly oracleId: "SUSHI";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://sushi.com/";
            readonly description: "Sushi is the home of DeFi. Their community is building a comprehensive, decentralized trading platform for the future of finance. Swap, earn, stack yields, lend, borrow, leverage all on one decentralized, community driven platform.";
            readonly bridge: "multichain";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly WBTC: {
            readonly name: "Wrapped BTC";
            readonly address: "0x818ec0A7Fe18Ff94269904fCED6AE3DaE6d6dC0b";
            readonly symbol: "kmultiWBTC";
            readonly oracleId: "WBTC";
            readonly decimals: 8;
            readonly website: "https://wbtc.network/";
            readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
            readonly chainId: 2222;
            readonly bridge: "multichain";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly ETH: {
            readonly name: "Ether";
            readonly address: "0xE3F5a90F9cb311505cd691a46596599aA1A0AD7D";
            readonly symbol: "kmultiETH";
            readonly oracleId: "ETH";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://ethereum.org/";
            readonly description: "The native currency that flows within the Ethereum economy is called Ether (ETH). Ether is typically used to pay for transaction fees called Gas, and it is the base currency of the network.";
            readonly bridge: "multichain";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly axlUSDC: {
            readonly name: "Axelar USD Coin ";
            readonly symbol: "axlUSDC";
            readonly oracleId: "axlUSDC";
            readonly address: "0xEB466342C4d449BC9f53A865D5Cb90586f405215";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://www.axelar.network/";
            readonly bridge: "axelar";
            readonly description: "axlUSDC is a cross-chain representation of USDC, secured by a validator set using delegated Proof-of-Stake and multi-party cryptography. It allows USDC to move seamlessly across different blockchain ecosystems, minted by depositing USDC into an Axelar Gateway on Ethereum, and can be acquired through DEXs, cross-chain swaps via Squid, or bridging via Satellite.money.";
            readonly documentation: "https://docs.axelar.dev/learn/axlusdc";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly axlUSDT: {
            readonly name: "USDT";
            readonly symbol: "axlUSDT";
            readonly oracleId: "axlUSDT";
            readonly address: "0x7f5373AE26c3E8FfC4c77b7255DF7eC1A9aF52a6";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://www.axelar.network/";
            readonly documentation: "https://docs.axelar.dev/";
            readonly description: "axlUSDT is a cross-chain representation of USDT, secured by a validator set using delegated Proof-of-Stake and multi-party cryptography. It allows USDT to move seamlessly across different blockchain ecosystems, minted by depositing USDT into an Axelar Gateway on Ethereum, and can be acquired through DEXs, cross-chain swaps via Squid, or bridging via Satellite.money.";
            readonly bridge: "axelar";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly axlDAI: {
            readonly name: "Axelar Dai Stablecoin";
            readonly address: "0x5C7e299CF531eb66f2A1dF637d37AbB78e6200C7";
            readonly symbol: "axlDAI";
            readonly oracleId: "axlDAI";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://makerdao.com/";
            readonly documentation: "https://docs.axelar.dev/";
            readonly description: "Multi-Collateral Dai, brings a lot of new and exciting features, such as support for new CDP collateral types and Dai Savings Rate.";
            readonly bridge: "axelar";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly VARA: {
            readonly name: "VARA";
            readonly address: "0xE1da44C0dA55B075aE8E2e4b6986AdC76Ac77d73";
            readonly symbol: "VARA";
            readonly oracleId: "VARA";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://equilibrefinance.com//";
            readonly documentation: "https://equilibre-finance.gitbook.io/equilibre-finance/about-us/welcome";
            readonly description: "Équilibre is an ve(3.3) AMM (Automatic Market Maker) based on Velodrome, and designed to provide large liquidity & low swapping fees.";
            readonly bridge: "native";
        };
        readonly oldBIFI: {
            readonly name: "Beefy.Finance";
            readonly symbol: "kmultioldBIFI";
            readonly oracleId: "oldBIFI";
            readonly address: "0xC19281F22A075E0F10351cd5D6Ea9f0AC63d4327";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://beefy.com";
            readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
            readonly documentation: "https://docs.beefy.finance/";
            readonly bridge: "multichain";
        };
        readonly MAI: {
            readonly name: "Mai Stablecoin";
            readonly symbol: "MAI";
            readonly oracleId: "kMAI";
            readonly address: "0xb84Df10966a5D7e1ab46D9276F55d57bD336AFC7";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://www.mai.finance/";
            readonly description: "MAI is a stablecoin collateralized by your crypto holdings. It's powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.";
            readonly documentation: "https://docs.mai.finance/";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly BNB: {
            readonly name: "Binance Chain";
            readonly symbol: "kmultiBNB";
            readonly oracleId: "BNB";
            readonly address: "0xABd380327Fe66724FFDa91A87c772FB8D00bE488";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://www.binance.com/";
            readonly description: "Binance Coin (BNB) is an exchange-based token created and issued by the cryptocurrency exchange Binance. Initially created on the Ethereum blockchain as an ERC-20 token in July 2017, BNB was migrated over to Binance Chain in February 2019 and became the native coin of the Binance Chain.";
            readonly bridge: "multichain";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly axlATOM: {
            readonly name: "Axelar Wrapped ATOM";
            readonly symbol: "axlATOM";
            readonly oracleId: "axlATOM";
            readonly address: "0x06beE9E7238a331B68D83Df3B5B9B16d5DBa83ff";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://cosmos.network/";
            readonly description: "The Internet of Blockchains. Cosmos is an ever-expanding ecosystem of interconnected apps and services, built for a decentralized future.";
            readonly documentation: "https://docs.axelar.dev/resources/wrapped-tokens";
            readonly bridge: "axelar";
        };
        readonly MARE: {
            readonly name: "Mare Finance";
            readonly symbol: "MARE";
            readonly oracleId: "MARE";
            readonly address: "0xd86C8d4279CCaFbec840c782BcC50D201f277419";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://mare.finance/";
            readonly description: "Mare Finance is an EVM compatible lending/borrowing protocol that launched on Kava EVM. Mare Finance provides peer-to-peer lending solutions that are fully decentralized, transparent and non-custodial.";
            readonly documentation: "https://docs.mare.finance/";
            readonly bridge: "native";
        };
        readonly MIM: {
            readonly name: "Magic Internet Money";
            readonly address: "0x471EE749bA270eb4c1165B5AD95E614947f6fCeb";
            readonly symbol: "MIM";
            readonly oracleId: "MIM";
            readonly decimals: 18;
            readonly chainId: 2222;
            readonly website: "https://abracadabra.money/";
            readonly description: "You, the Spellcaster, can provide collateral in the form of various interest bearing crypto assets such as yvYFI, yvUSDT, yvUSDC, xSUSHI and more. With this, you can borrow magic internet money (MIM) which is a stable coin that you can swap for any other traditional stable coin.";
            readonly documentation: "https://docs.abracadabra.money/";
            readonly bridge: "layer-zero";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly axlETH: {
            readonly name: "Axelar Wrapped ETH";
            readonly symbol: "axlETH";
            readonly oracleId: "axlETH";
            readonly address: "0xb829b68f57CC546dA7E5806A929e53bE32a4625D";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://axelar.network/";
            readonly description: "Axelar Wrapped ETH (axlETH) is an ERC-20 token that represents a wrapped version of native Ethereum (ETH) cryptocurrency, allowing for cross-chain transfers and compatibility with the Ethereum ecosystem.";
            readonly documentation: "https://docs.axelar.dev/resources/wrapped-tokens";
            readonly bridge: "axelar";
        };
        readonly axlWBTC: {
            readonly name: "Axelar Wrapped WBTC";
            readonly symbol: "axlWBTC";
            readonly oracleId: "axlWBTC";
            readonly address: "0x1a35EE4640b0A3B87705B0A4B45D227Ba60Ca2ad";
            readonly chainId: 2222;
            readonly decimals: 8;
            readonly website: "https://axelar.network/";
            readonly description: "Axelar Wrapped WBTC (axlWBTC) is an ERC-20 token that represents a 1:1 pegged version of Bitcoin, allowing users to access Bitcoin's value and liquidity within the Kava ecosystem.";
            readonly documentation: "https://docs.axelar.dev/resources/wrapped-tokens";
            readonly bridge: "axelar";
        };
        readonly ATOM: {
            readonly name: "ATOM";
            readonly symbol: "ATOM";
            readonly oracleId: "ATOM";
            readonly address: "0x15932E26f5BD4923d46a2b205191C4b5d5f43FE3";
            readonly chainId: 2222;
            readonly decimals: 6;
            readonly website: "https://cosmos.network/";
            readonly description: "The Internet of Blockchains. Cosmos is an ever-expanding ecosystem of interconnected apps and services, built for a decentralized future.";
            readonly bridge: "ibc";
            readonly documentation: "https://docs.cosmos.network/main";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly lzETH: {
            readonly name: "LayerZero Wrapped ETH";
            readonly symbol: "lzETH";
            readonly oracleId: "WETH";
            readonly address: "0x2DfD4dE5AE386Cd3f4fC8e2cb39240852E47F5E8";
            readonly chainId: 2222;
            readonly decimals: 18;
            readonly website: "https://layerzero.network/";
            readonly description: "LayerZero Wrapped ETH (lzETH) is an ERC-20 token that represents a wrapped version of native Ethereum (ETH) cryptocurrency, allowing for cross-chain transfers and compatibility with the Ethereum ecosystem.";
            readonly bridge: "layer-zero";
        };
        readonly lzWBTC: {
            readonly name: "LayerZero Wrapped WBTC";
            readonly symbol: "lzWBTC";
            readonly oracleId: "WBTC";
            readonly address: "0xb5c4423a65B953905949548276654C96fcaE6992";
            readonly chainId: 2222;
            readonly decimals: 8;
            readonly website: "https://layerzero.network/";
            readonly description: "LayerZero Wrapped WBTC (lzWBTC) is an ERC-20 token that represents a 1:1 pegged version of Bitcoin, allowing users to access Bitcoin's value and liquidity within the Kava ecosystem.";
            readonly bridge: "layer-zero";
        };
    }>;
    readonly native: {
        readonly symbol: "KAVA";
        readonly oracleId: "KAVA";
    };
};
