export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Moonbeam";
        readonly address: "0xAcc15dC74880C9944775448304B263D191c6077F";
        readonly symbol: "WGLMR";
        readonly oracleId: "WGLMR";
        readonly decimals: 18;
        readonly chainId: 1284;
        readonly website: "https://moonbeam.network/networks/moonbeam/";
        readonly description: "A Polkadot Parachain Designed for Developers Moonbeam simplifies the developer experience by combining full Ethereum compatibility with the power of Polkadot, including scalability, cross-chain integrations, and on-chain governance.";
        readonly bridge: "native";
        readonly documentation: "https://moonbeam.foundation/glimmer-token/";
    };
    readonly FEES: {
        readonly name: "Moonbeam";
        readonly address: "0xAcc15dC74880C9944775448304B263D191c6077F";
        readonly symbol: "WGLMR";
        readonly oracleId: "WGLMR";
        readonly decimals: 18;
        readonly chainId: 1284;
        readonly website: "https://moonbeam.network/networks/moonbeam/";
        readonly description: "A Polkadot Parachain Designed for Developers Moonbeam simplifies the developer experience by combining full Ethereum compatibility with the power of Polkadot, including scalability, cross-chain integrations, and on-chain governance.";
        readonly bridge: "native";
        readonly documentation: "https://moonbeam.foundation/glimmer-token/";
    };
    readonly GLMR: {
        readonly name: "Moonbeam";
        readonly address: "0xAcc15dC74880C9944775448304B263D191c6077F";
        readonly symbol: "WGLMR";
        readonly oracleId: "WGLMR";
        readonly decimals: 18;
        readonly chainId: 1284;
        readonly website: "https://moonbeam.network/networks/moonbeam/";
        readonly description: "A Polkadot Parachain Designed for Developers Moonbeam simplifies the developer experience by combining full Ethereum compatibility with the power of Polkadot, including scalability, cross-chain integrations, and on-chain governance.";
        readonly bridge: "native";
        readonly documentation: "https://moonbeam.foundation/glimmer-token/";
    };
    readonly WGLMR: {
        readonly name: "Moonbeam";
        readonly address: "0xAcc15dC74880C9944775448304B263D191c6077F";
        readonly symbol: "WGLMR";
        readonly oracleId: "WGLMR";
        readonly decimals: 18;
        readonly chainId: 1284;
        readonly website: "https://moonbeam.network/networks/moonbeam/";
        readonly description: "A Polkadot Parachain Designed for Developers Moonbeam simplifies the developer experience by combining full Ethereum compatibility with the power of Polkadot, including scalability, cross-chain integrations, and on-chain governance.";
        readonly bridge: "native";
        readonly documentation: "https://moonbeam.foundation/glimmer-token/";
    };
    readonly erc20GLMR: {
        readonly symbol: "GLMR";
        readonly address: "0x0000000000000000000000000000000000000802";
        readonly name: "Moonbeam";
        readonly oracleId: "WGLMR";
        readonly decimals: 18;
        readonly chainId: 1284;
        readonly website: "https://moonbeam.network/networks/moonbeam/";
        readonly description: "A Polkadot Parachain Designed for Developers Moonbeam simplifies the developer experience by combining full Ethereum compatibility with the power of Polkadot, including scalability, cross-chain integrations, and on-chain governance.";
        readonly bridge: "native";
        readonly documentation: "https://moonbeam.foundation/glimmer-token/";
    };
    readonly oldBIFI: {
        readonly name: "Beefy.Finance";
        readonly symbol: "oldBIFI";
        readonly oracleId: "oldBIFI";
        readonly address: "0x595c8481c48894771CE8FaDE54ac6Bf59093F9E8";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://www.beefy.finance/";
        readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
        readonly documentation: "https://docs.beefy.finance/";
    };
    readonly STELLA4POOL: {
        readonly name: "Stellaswap 4Pool";
        readonly symbol: "stella4pool";
        readonly oracleId: "stellaswap-4pool";
        readonly address: "0xB326b5189AA42Acaa3C649B120f084Ed8F4dCaA6";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://app.stellaswap.com/exchange/pool/stable";
        readonly description: "Stellaswap Base4Pool is a Stable Pool consisting of USDC.wh, USDt.xc, BUSD.wh, and FRAX tokens.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly wstDOT: {
        readonly name: "Wrapped liquid staked DOT";
        readonly symbol: "wstDOT";
        readonly oracleId: "wstDOT";
        readonly address: "0x191cf2602Ca2e534c5Ccae7BCBF4C46a704bb949";
        readonly chainId: 1284;
        readonly decimals: 10;
        readonly website: "https://polkadot.lido.fi/";
        readonly description: "Lido for Polkadot is a liquid staking solution for DOT backed by industry-leading staking providers. wstDOT is wrapped version of stDOT";
        readonly documentation: "https://docs.polkadot.lido.fi/";
    };
    readonly WBTCwh: {
        readonly name: "Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "WBTCwh";
        readonly address: "0xE57eBd2d67B462E9926e04a8e33f01cD0D64346D";
        readonly chainId: 1284;
        readonly decimals: 8;
        readonly website: "https://www.portalbridge.com/#/transfer";
        readonly description: "WBTCwh is a bridged version of WBTC from the Wormhole(Portal) portal. Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
        readonly documentation: "https://docs.wormhole.com/wormhole/";
        readonly bridge: "wormhole";
    };
    readonly WETHwh: {
        readonly name: "Wrapped Ether";
        readonly symbol: "WETH";
        readonly oracleId: "ETHwh";
        readonly address: "0xab3f0245B83feB11d15AAffeFD7AD465a59817eD";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://www.portalbridge.com/#/transfer";
        readonly description: "WETHwh is a bridged version of native ETH from the Wormhole(Portal) portal. ETH is the native currency that flows within the Ethereum ecosystem.";
        readonly documentation: "https://docs.wormhole.com/wormhole/";
        readonly bridge: "wormhole";
    };
    readonly USDCwh: {
        readonly name: "USD Coin";
        readonly symbol: "USDC.wh";
        readonly oracleId: "USDCwh";
        readonly address: "0x931715FEE2d06333043d11F658C8CE934aC61D0c";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://www.portalbridge.com/#/transfer";
        readonly description: "USDC bridged by Wormhole(Portal). USDC is a fully collateralized US dollar stablecoin. Native USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly documentation: "https://docs.wormhole.com/wormhole/";
        readonly bridge: "wormhole";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly POOP: {
        readonly name: "Raresama";
        readonly symbol: "POOP";
        readonly oracleId: "POOP";
        readonly address: "0xFFfffFFecB45aFD30a637967995394Cc88C0c194";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://raresama.com/";
        readonly description: "Raresama is an artist and community focused NFT marketplace with great ambitions to quickly become the leading marketplace on Moonbeam. POOP is the Raresama.com (NFT Marketplace) governance token.";
    };
    readonly xcACA: {
        readonly name: "Acala xcACA";
        readonly symbol: "xcACA";
        readonly oracleId: "xcACA";
        readonly address: "0xffffFFffa922Fef94566104a6e5A35a4fCDDAA9f";
        readonly chainId: 1284;
        readonly decimals: 12;
        readonly website: "https://acala.network/";
        readonly description: "The decentralized Stablecoin of Polkadot";
    };
    readonly xciBTC: {
        readonly name: "Interlay BTC";
        readonly symbol: "xciBTC";
        readonly oracleId: "xciBTC";
        readonly address: "0xFFFFFfFf5AC1f9A51A93F5C527385edF7Fe98A52";
        readonly chainId: 1284;
        readonly decimals: 8;
        readonly website: "https://interlay.io/";
        readonly description: "Use your Bitcoin. Anywhere. Anytime. Interlay is a decentralized bridge that allows you to use your Bitcoin on Ethereum and Polkadot.";
    };
    readonly xcINTR: {
        readonly name: "Interlay INTR";
        readonly symbol: "xcINTR";
        readonly oracleId: "xcINTR";
        readonly address: "0xFffFFFFF4C1cbCd97597339702436d4F18a375Ab";
        readonly chainId: 1284;
        readonly decimals: 10;
        readonly website: "https://interlay.io/";
        readonly description: "Use your Bitcoin. Anywhere. Anytime. Interlay is a decentralized bridge that allows you to use your Bitcoin on Ethereum and Polkadot.";
    };
    readonly WELL: {
        readonly name: "WELL";
        readonly symbol: "WELL";
        readonly oracleId: "WELL";
        readonly address: "0x511aB53F793683763E5a8829738301368a2411E3";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://moonwell.fi/";
        readonly description: "WELL is the native governance token of the Moonwell Artemis protocol";
        readonly bridge: "native";
        readonly documentation: "https://docs.moonwell.fi/moonwell/discover/about-moonwell";
    };
    readonly MAI: {
        readonly name: "Mai Stablecoin";
        readonly symbol: "MAI";
        readonly oracleId: "gMAI";
        readonly address: "0xdFA46478F9e5EA86d57387849598dbFB2e964b02";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://app.mai.finance/";
        readonly description: "MAI is a stablecoin collateralized by your crypto assets. It's powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly APE: {
        readonly name: "ApeCoin APE";
        readonly symbol: "APE";
        readonly oracleId: "APE";
        readonly address: "0x3D632d9e1a60a0880Dd45E61f279D919b5748377";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "http://apecoin.com/";
        readonly description: "ApeCoin is for the Web3 Economy. Culture has found new expression in web3 through art, gaming, entertainment, and events.";
    };
    readonly GLINT: {
        readonly name: "Beamswap Token";
        readonly symbol: "GLINT";
        readonly oracleId: "GLINT";
        readonly address: "0xcd3B51D98478D53F4515A306bE565c6EebeF1D58";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://beamswap.io/";
        readonly description: "Beamswap is a decentralized exchange (DEX) with an automated market maker (AMM), providing liquidity and peer-to-peer transactions. But it aims to be so much more than that. Supporting an array of services and features, it will allow you to swap crypto assets, both fungible and non-fungible, earn passive income from staking and yield farming, and even launch your own crypto projects on Moonbeam.";
    };
    readonly USDC: {
        readonly name: "USD Coin";
        readonly symbol: "USDC";
        readonly oracleId: "USDC";
        readonly address: "0x818ec0A7Fe18Ff94269904fCED6AE3DaE6d6dC0b";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://developers.circle.com/docs";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly USDCs: {
        readonly name: "USD Coin";
        readonly symbol: "USDCs";
        readonly oracleId: "USDCs";
        readonly address: "0x8f552a71EFE5eeFc207Bf75485b356A0b3f01eC9";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://www.nomad.xyz/";
        readonly description: "bridged USDC by Nomad. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly USDTs: {
        readonly name: "Tether USD";
        readonly symbol: "USDT";
        readonly oracleId: "USDTs";
        readonly address: "0x8e70cD5B4Ff3f62659049e74b6649c6603A0E594";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://www.nomad.xyz/";
        readonly description: "bridged USDT by Nomad. Tether converts cash into digital currency, to anchor or tether the value to the price of national currencies like the US dollar, the Euro, and the offshore Chinese yuan.";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly DAIs: {
        readonly name: "Dai Stablecoin";
        readonly symbol: "DAI";
        readonly oracleId: "DAIs";
        readonly address: "0xc234A67a4F840E61adE794be47de455361b52413";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://www.nomad.xyz/";
        readonly description: "bridged DAI by Nomad. Multi-Collateral Dai, brings a lot of new and exciting features, such as support for new CDP collateral types and Dai Savings Rate.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly FRAX: {
        readonly name: "Frax";
        readonly symbol: "FRAX";
        readonly oracleId: "FRAX";
        readonly address: "0x322E86852e492a7Ee17f28a78c663da38FB33bfb";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://frax.finance/";
        readonly description: "The Frax Protocol introduced the world to the concept of a cryptocurrency being partially backed by collateral and partially stabilized algorithmically.";
        readonly documentation: "https://docs.frax.finance/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly BUSD: {
        readonly name: "Binance-Peg BUSD Token";
        readonly symbol: "BUSD";
        readonly oracleId: "BUSD";
        readonly address: "0xA649325Aa7C5093d12D6F98EB4378deAe68CE23F";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/en/busd";
        readonly description: "Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos). BUSD is approved and regulated by the New York State Department of Financial Services (NYDFS). The BUSD Monthly Audit Report can be viewed from the official website.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly BUSDc: {
        readonly name: "Binance-Peg BUSD Token (Celer)";
        readonly symbol: "BUSD";
        readonly oracleId: "BUSDc";
        readonly address: "0xCb4A7569a61300C50Cf80A2be16329AD9F5F8F9e";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/en/busd";
        readonly description: "Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos). BUSD is approved and regulated by the New York State Department of Financial Services (NYDFS). The BUSD Monthly Audit Report can be viewed from the official website.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly BUSDwh: {
        readonly name: "Binance-Peg BUSD Token (Wormhole)";
        readonly symbol: "BUSD";
        readonly oracleId: "BUSDwh";
        readonly address: "0x692C57641fc054c2Ad6551Ccc6566EbA599de1BA";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/en/busd";
        readonly description: "BUSD bridged by Wormhole(Portal). Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos). BUSD is approved and regulated by the New York State Department of Financial Services (NYDFS). The BUSD Monthly Audit Report can be viewed from the official website.";
        readonly documentation: "https://docs.wormhole.com/wormhole/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly BNB: {
        readonly name: "Binance";
        readonly symbol: "BNB";
        readonly oracleId: "BNB";
        readonly address: "0xc9BAA8cfdDe8E328787E29b4B078abf2DaDc2055";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/";
        readonly description: "Binance Coin (BNB) is an exchange-based token created and issued by the cryptocurrency exchange Binance. Initially created on the Ethereum blockchain as an ERC-20 token in July 2017, BNB was migrated over to Binance Chain in February 2019 and became the native coin of the Binance Chain.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly BCMC: {
        readonly name: "Blockchain Monster Coin";
        readonly symbol: "BCMC";
        readonly oracleId: "BCMC";
        readonly address: "0x8ECE0D14d619fE26e2C14C4a92c2F9E8634A039E";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://bcmhunt.com/";
        readonly description: "Blockchain Monster Coin (BCMC) is the ultimate treasure facilitating all game activities that all BCMHunter seeks. This multichain token can be moved onto any chain with in-house bridging technology.";
    };
    readonly ETH: {
        readonly name: "Ethereum";
        readonly symbol: "ETH";
        readonly oracleId: "ETH";
        readonly address: "0xfA9343C3897324496A05fC75abeD6bAC29f8A40f";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://ethereum.org/";
        readonly description: "The native currency that flows within the Ethereum economy is called Ether (ETH). Ether is typically used to pay for transaction fees called Gas, and it is the base currency of the network.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly ETHs: {
        readonly name: "Ethereum";
        readonly symbol: "ETH";
        readonly oracleId: "ETHs";
        readonly address: "0x30D2a9F5FDf90ACe8c17952cbb4eE48a55D916A7";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://www.nomad.xyz/";
        readonly description: "Bridged ETH by Nomad. The native currency that flows within the Ethereum economy is called Ether (ETH). Ether is typically used to pay for transaction fees called Gas, and it is the base currency of the network.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly USDT: {
        readonly name: "Tether USD";
        readonly symbol: "USDT";
        readonly oracleId: "USDT";
        readonly address: "0xeFAeeE334F0Fd1712f9a8cc375f427D9Cdd40d73";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://tether.to/";
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly USDTc: {
        readonly name: "Tether USD (Celer)";
        readonly symbol: "USDTc";
        readonly oracleId: "USDTc";
        readonly address: "0x81ECac0D6Be0550A00FF064a4f9dd2400585FE9c";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://tether.to/";
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
    };
    readonly xcUSDT: {
        readonly name: "Tether USD";
        readonly symbol: "xcUSDT";
        readonly oracleId: "USDT";
        readonly address: "0xFFFFFFfFea09FB06d082fd1275CD48b191cbCD1d";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://tether.to/";
        readonly description: "Bridged by XCM from Kusama. Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly documentation: "https://moonbeam.network/news/polkadot-native-usdt-now-available-on-moonbeam";
        readonly bridge: "kusama";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly DAI: {
        readonly name: "Dai Stablecoin";
        readonly symbol: "DAI";
        readonly oracleId: "DAI";
        readonly address: "0x765277EebeCA2e31912C9946eAe1021199B39C61";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://makerdao.com/en/";
        readonly description: "DAI is an Ethereum-based stablecoin (stable-price cryptocurrency) whose issuance and development is managed by the Maker Protocol and the MakerDAO decentralized autonomous organization.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly FTM: {
        readonly name: "Fantom";
        readonly symbol: "FTM";
        readonly oracleId: "FTM";
        readonly address: "0xC19281F22A075E0F10351cd5D6Ea9f0AC63d4327";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://fantom.foundation/";
        readonly description: "Fantom is a fast, high-throughput open-source smart contract platform for digital assets and dApps.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly axlATOM: {
        readonly name: "Axelar Wrapped ATOM";
        readonly symbol: "axlATOM";
        readonly oracleId: "axlATOM";
        readonly address: "0x27292cf0016E5dF1d8b37306B2A98588aCbD6fCA";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://cosmos.network/";
        readonly description: "The ATOM is the Cosmos Hub's primary token and secures the Hub's valuable interchain services.";
    };
    readonly axlUST: {
        readonly name: "Axelar Wrapped UST";
        readonly symbol: "axlUST";
        readonly oracleId: "axlUST";
        readonly address: "0x085416975fe14C2A731a97eC38B9bF8135231F62";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://www.terra.money/";
        readonly description: "Terra stablecoins offer instant settlements, low fees and seamless cross-border exchange - loved by millions of users and merchants.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly MATIC: {
        readonly name: "Matic";
        readonly symbol: "MATIC";
        readonly oracleId: "MATIC";
        readonly address: "0x3405A1bd46B85c5C029483FbECf2F3E611026e45";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://polygon.technology/";
        readonly description: "Polygon believes in Web3 for all. Polygon is a decentralised Ethereum scaling platform that enables developers to build scalable user-friendly dApps with low transaction fees without ever sacrificing on security.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly AVAX: {
        readonly name: "Avalanche";
        readonly symbol: "AVAX";
        readonly oracleId: "AVAX";
        readonly address: "0x4792C1EcB969B036eb51330c63bD27899A13D84e";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://www.avalabs.org/";
        readonly description: "Avalanche is the fastest smart contracts platform in the blockchain industry, as measured by time-to-finality, and has the most validators securing its activity of any proof-of-stake protocol.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly FLARE: {
        readonly name: "Flare Token";
        readonly symbol: "FLARE";
        readonly oracleId: "FLARE";
        readonly address: "0xE3e43888fa7803cDC7BEA478aB327cF1A0dc11a7";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://app.solarflare.io/exchange/swap";
        readonly description: "Solarflare is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Moonbeam Network. The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.";
        readonly bridge: "native";
        readonly documentation: "https://docs.solarflare.io/tokenomics";
    };
    readonly STELLA: {
        readonly name: "Stella Token";
        readonly symbol: "STELLA";
        readonly oracleId: "STELLA";
        readonly address: "0x0E358838ce72d5e61E0018a2ffaC4bEC5F4c88d2";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://app.stellaswap.com/exchange/swap";
        readonly description: "Stellaswap is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Moonbeam Network.";
    };
    readonly xSTELLA: {
        readonly name: "xStella";
        readonly symbol: "xSTELLA";
        readonly oracleId: "xSTELLA";
        readonly address: "0x06A3b410b681c82417A906993aCeFb91bAB6A080";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://app.stellaswap.com/exchange/swap";
        readonly description: "Stellaswap is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Moonbeam Network.";
    };
    readonly xcDOT: {
        readonly name: "xcDOT";
        readonly symbol: "xcDOT";
        readonly oracleId: "xcDOT";
        readonly address: "0xFfFFfFff1FcaCBd218EDc0EbA20Fc2308C778080";
        readonly chainId: 1284;
        readonly decimals: 10;
        readonly website: "https://polkadot.network/";
        readonly description: "Polkadot is an open-source sharding multichain protocol that facilitates the cross-chain transfer of any data or asset types, not just tokens, thereby making a wide range of blockchains interoperable with each other.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly stDOTold: {
        readonly name: "Liquid staked DOT";
        readonly symbol: "stDOT";
        readonly oracleId: "stDOT";
        readonly address: "0xFA36Fe1dA08C89eC72Ea1F0143a35bFd5DAea108";
        readonly chainId: 1284;
        readonly decimals: 10;
        readonly website: "https://polkadot.lido.fi/";
        readonly description: "Lido for Polkadot is a liquid staking solution for DOT backed by industry-leading staking providers.";
    };
    readonly stDOT: {
        readonly name: "Stella stDOT";
        readonly symbol: "stDOT";
        readonly oracleId: "stDOT";
        readonly address: "0xbc7E02c4178a7dF7d3E564323a5c359dc96C4db4";
        readonly chainId: 1284;
        readonly decimals: 10;
        readonly website: "https://app.stellaswap.com/stdot";
        readonly description: "Stake DOT.xc for stDOT";
        readonly documentation: "https://docs.stellaswap.com/";
        readonly bridge: "native";
    };
    readonly veFLARE: {
        readonly name: "Vested Flare Token";
        readonly symbol: "veFLARE";
        readonly oracleId: "veFLARE";
        readonly address: "0x08c98AD2d4856BEC0a0EaF18C2a06E7201613F90";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://app.solarflare.io/exchange/swap";
        readonly description: "Solarflare is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Moonbeam Network. The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.";
    };
    readonly veSOLAR: {
        readonly name: "Vested SolarBeam Token";
        readonly symbol: "veSOLAR";
        readonly oracleId: "veSOLAR";
        readonly address: "0x0DB6729C03C85B0708166cA92801BcB5CAc781fC";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://app.solarbeam.io/exchange/swap";
        readonly description: "Solarbeam is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Moonriver Network. We are currently the leading DEX on the network. The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.";
    };
    readonly MOVR: {
        readonly name: "Moonriver";
        readonly symbol: "MOVR";
        readonly oracleId: "MOVR";
        readonly address: "0x1d4C2a246311bB9f827F4C768e277FF5787B7D7E";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://moonbeam.network/networks/moonriver/";
        readonly description: "Moonriver is a companion network to Moonbeam and provides a permanently incentivized canary network. New code ships to Moonriver first, where it can be tested and verified under real economic conditions. Once proven, the same code ships to Moonbeam on Polkadot.";
    };
    readonly WBTC: {
        readonly name: "Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "WBTC";
        readonly address: "0x1DC78Acda13a8BC4408B207c9E48CDBc096D95e0";
        readonly chainId: 1284;
        readonly decimals: 8;
        readonly website: "https://www.nomad.xyz/";
        readonly description: "WBTC bridged by Nomad. Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly aWBTC: {
        readonly name: "Anyswap Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "aWBTC";
        readonly address: "0x922D641a426DcFFaeF11680e5358F34d97d112E1";
        readonly chainId: 1284;
        readonly decimals: 8;
        readonly website: "https://wbtc.network/";
        readonly description: "Anyswap Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
    };
    readonly LUNA: {
        readonly name: "Axelar Wrapped LUNA";
        readonly symbol: "LUNA";
        readonly oracleId: "LUNA";
        readonly address: "0x31DAB3430f3081dfF3Ccd80F17AD98583437B213";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://www.terra.money/";
        readonly description: "Terra's native token, LUNA, is used to stabilize the price of the protocol's stablecoins. LUNA holders are also able to submit and vote on governance proposals, giving it the functionality of a governance token.";
        readonly tags: readonly ["MEMECOIN"];
    };
    readonly UST: {
        readonly name: "Axelar Wrapped UST";
        readonly symbol: "UST";
        readonly oracleId: "axlUST";
        readonly address: "0x085416975fe14C2A731a97eC38B9bF8135231F62";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://www.terra.money/";
        readonly description: "Terra stablecoins offer instant settlements, low fees and seamless cross-border exchange - loved by millions of users and merchants.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly xcaUSD: {
        readonly name: "xcaUSD";
        readonly symbol: "xcaUSD";
        readonly oracleId: "xcaUSD";
        readonly address: "0xfFfFFFFF52C56A9257bB97f4B2b6F7B2D624ecda";
        readonly chainId: 1284;
        readonly decimals: 12;
        readonly website: "https://acala.network/ausd";
        readonly description: "Acala USD (aUSD). The native decentralized stablecoin of Polkadot.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly LDO: {
        readonly name: "Lido DAO";
        readonly symbol: "LDO";
        readonly oracleId: "LDO";
        readonly address: "0x9Fda7cEeC4c18008096C2fE2B85F05dc300F94d0";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://stake.lido.fi/";
        readonly documentation: "https://docs.lido.fi/";
        readonly description: "Lido is a liquid staking solution for ETH 2.0 backed by industry-leading staking providers.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly stellaBase4pool: {
        readonly name: "stellaBase4pool";
        readonly symbol: "stellaswap-base4pool";
        readonly oracleId: "stellaswap-base4pool";
        readonly address: "0xdA782836B65edC4E6811c7702C5E21786203Ba9d";
        readonly chainId: 1284;
        readonly decimals: 18;
        readonly website: "https://stellaswap.com/";
        readonly description: "Stellaswap is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Moonbeam Network. The 4pool is a stable-swap LP consisting of USDC, USDT, DAI & FRAX.";
        readonly documentation: "https://docs.stellaswap.com/how-to-guides/swap-pool-and-farm/how-to-add-liquidity-in-stable-amm";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly xcUSDC: {
        readonly name: "USD Coin";
        readonly symbol: "xcUSDC";
        readonly oracleId: "USDC";
        readonly address: "0xFFfffffF7D2B0B761Af01Ca8e25242976ac0aD7D";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://developers.circle.com/docs";
        readonly bridge: "kusama";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly axlUSDC: {
        readonly name: "USD Coin";
        readonly symbol: "axlUSDC";
        readonly oracleId: "USDC";
        readonly address: "0xCa01a1D0993565291051daFF390892518ACfAD3A";
        readonly chainId: 1284;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://developers.circle.com/docs";
        readonly bridge: "axelar";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly tags: readonly ["STABLECOIN"];
    };
};
