import * as platforms from './platforms/index.js';
export declare const canto: {
    readonly platforms: typeof platforms;
    readonly tokens: {
        readonly WNATIVE: {
            readonly name: "Wrapped Canto";
            readonly address: "0x826551890Dc65655a0Aceca109aB11AbDbD7a07B";
            readonly symbol: "WCANTO";
            readonly oracleId: "WCANTO";
            readonly decimals: 18;
            readonly chainId: 7700;
            readonly website: "https://canto.io/";
            readonly description: "Canto is a permissionless general-purpose blockchain running the Ethereum Virtual Machine (EVM). It was built to deliver on the promise of DeFi – that through a post-traditional financial movement, new systems will be made accessible, transparent, decentralized, and free.";
            readonly bridge: "native";
            readonly documentation: "https://docs.canto.io/";
        };
        readonly FEES: {
            readonly name: "Wrapped Canto";
            readonly address: "0x826551890Dc65655a0Aceca109aB11AbDbD7a07B";
            readonly symbol: "WCANTO";
            readonly oracleId: "WCANTO";
            readonly decimals: 18;
            readonly chainId: 7700;
            readonly website: "https://canto.io/";
            readonly description: "Canto is a permissionless general-purpose blockchain running the Ethereum Virtual Machine (EVM). It was built to deliver on the promise of DeFi – that through a post-traditional financial movement, new systems will be made accessible, transparent, decentralized, and free.";
            readonly bridge: "native";
            readonly documentation: "https://docs.canto.io/";
        };
        readonly CANTO: {
            readonly name: "Wrapped Canto";
            readonly address: "0x826551890Dc65655a0Aceca109aB11AbDbD7a07B";
            readonly symbol: "WCANTO";
            readonly oracleId: "WCANTO";
            readonly decimals: 18;
            readonly chainId: 7700;
            readonly website: "https://canto.io/";
            readonly description: "Canto is a permissionless general-purpose blockchain running the Ethereum Virtual Machine (EVM). It was built to deliver on the promise of DeFi – that through a post-traditional financial movement, new systems will be made accessible, transparent, decentralized, and free.";
            readonly bridge: "native";
            readonly documentation: "https://docs.canto.io/";
        };
        readonly WCANTO: {
            readonly name: "Wrapped Canto";
            readonly address: "0x826551890Dc65655a0Aceca109aB11AbDbD7a07B";
            readonly symbol: "WCANTO";
            readonly oracleId: "WCANTO";
            readonly decimals: 18;
            readonly chainId: 7700;
            readonly website: "https://canto.io/";
            readonly description: "Canto is a permissionless general-purpose blockchain running the Ethereum Virtual Machine (EVM). It was built to deliver on the promise of DeFi – that through a post-traditional financial movement, new systems will be made accessible, transparent, decentralized, and free.";
            readonly bridge: "native";
            readonly documentation: "https://docs.canto.io/";
        };
        readonly oldBIFI: {
            readonly name: "Beefy.Finance";
            readonly symbol: "oldBIFI";
            readonly oracleId: "oldBIFI";
            readonly address: "0x765277EebeCA2e31912C9946eAe1021199B39C61";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.beefy.finance/";
            readonly documentation: "https://docs.beefy.finance/";
            readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
        };
        readonly ATOM: {
            readonly name: "Cosmos Token";
            readonly symbol: "ATOM";
            readonly oracleId: "ATOM";
            readonly address: "0xecEEEfCEE421D8062EF8d6b4D814efe4dc898265";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://cosmos.network/";
            readonly description: "Cosmos is an ever-expanding ecosystem of interconnected apps and services, built for a decentralized future.";
            readonly bridge: "gravity";
            readonly documentation: "https://docs.cosmos.network/main";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly ETH: {
            readonly name: "Ethereum";
            readonly symbol: "ETH";
            readonly oracleId: "ETH";
            readonly address: "0x5FD55A1B9FC24967C4dB09C513C3BA0DFa7FF687";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://ethereum.org/";
            readonly description: "The native currency that flows within the Ethereum economy is called Ether (ETH). Ether is typically used to pay for transaction fees called Gas, and it is the base currency of the network.";
            readonly bridge: "gravity";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly NOTE: {
            readonly name: "Note";
            readonly symbol: "NOTE";
            readonly oracleId: "NOTE";
            readonly address: "0x4e71A2E537B7f9D9413D3991D37958c0b5e1e503";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://canto.io/";
            readonly documentation: "https://docs.canto.io/overview/canto-unit-of-account-usdnote";
            readonly description: "$NOTE is the unit of account on Canto. $NOTE is an over-collateralized currency with a value perpetually rebalanced toward $1 through an algorithmic interest rate policy.";
            readonly bridge: "native";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly USDC: {
            readonly name: "USD Coin";
            readonly address: "0x80b5a32E4F032B2a058b4F29EC95EEfEEB87aDcd";
            readonly symbol: "USDC";
            readonly oracleId: "USDC";
            readonly decimals: 6;
            readonly website: "https://www.circle.com/usdc";
            readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly bridge: "gravity";
            readonly chainId: 7700;
            readonly documentation: "https://developers.circle.com/docs";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly USDT: {
            readonly name: "USDT";
            readonly symbol: "USDT";
            readonly oracleId: "USDT";
            readonly address: "0xd567B3d7B8FE3C79a1AD8dA978812cfC4Fa05e75";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
            readonly bridge: "gravity";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly FLOWV1: {
            readonly name: "Velocimeter";
            readonly symbol: "FLOWv1";
            readonly oracleId: "FLOWV1";
            readonly address: "0x2Baec546a92cA3469f71b7A091f7dF61e5569889";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://canto.velocimeter.xyz/home";
            readonly description: "Velocimeter addresses these issues and presents an attractive alternative by addressing the core issues in Solidly and adding its own improvements. To recall, the key innovation of Solidly was to align protocol emissions with fees generated, not simply liquidity. To do this, it would allow protocols and other large stakeholders to become veNFT \"voters\", using their locked voting power to direct future emissions and collecting fees (termed bribes in Solidly) from the pools they voted for.";
            readonly documentation: "https://docs.velocimeter.xyz/";
        };
        readonly GRAV: {
            readonly name: "Graviton";
            readonly symbol: "GRAV";
            readonly oracleId: "GRAV";
            readonly address: "0xc03345448969Dd8C00e9E4A85d2d9722d093aF8E";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://www.gravitybridge.net/";
            readonly description: "Cosmos Gravity Bridge™ is a purpose-built, fully decentralized, trustless blockchain which bridges assets between the Ethereum and Cosmos ecosystems. Ethereum and EVM compatible tokens can be transferred across the Gravity Bridge to a Cosmos wallet and then onto other Cosmos wallets or DEXs (such as Osmosis or Gravity DEX). Cosmos SDK based blockchains can similarly send tokens across Gravity Bridge to the Ethereum ecosystem, making them available for transfer or potentially trading on Uniswap or other ETH DEXs.";
            readonly documentation: "https://www.gravitybridge.net/post/how-gravity-works";
        };
        readonly FLOW: {
            readonly name: "Velocimeter";
            readonly symbol: "FLOW";
            readonly oracleId: "FLOW";
            readonly address: "0xB5b060055F0d1eF5174329913ef861bC3aDdF029";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://canto.velocimeter.xyz/home";
            readonly description: "Velocimeter addresses these issues and presents an attractive alternative by addressing the core issues in Solidly and adding its own improvements. To recall, the key innovation of Solidly was to align protocol emissions with fees generated, not simply liquidity. To do this, it would allow protocols and other large stakeholders to become veNFT \"voters\", using their locked voting power to direct future emissions and collecting fees (termed bribes in Solidly) from the pools they voted for.";
            readonly bridge: "native";
            readonly documentation: "https://docs.velocimeter.xyz/";
        };
        readonly SOMM: {
            readonly name: "Somm";
            readonly symbol: "SOMM";
            readonly oracleId: "SOMM";
            readonly address: "0xFA3C22C069B9556A4B2f7EcE1Ee3B467909f4864";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://app.sommelier.finance/";
            readonly description: "Sommelier is a DeFi blockchain protocol, built on the Cosmos SDK, and a bi-directional Ethereum bridge. Taken together, this collection serves as a co-processor to Ethereum - that is we are using a Cosmos chain to process as many of the calculations as possible off Ethereum. The protocol is powered by validators and LPs who can benefit from a wide array of transaction features, such as portfolio rebalancing and limit orders based on dynamically changing market conditions.";
            readonly bridge: "gravity";
            readonly documentation: "https://tricky-sand-5e6.notion.site/Sommelier-Documentation-006e748753e34a1299f9b1d6ae3a4544";
        };
        readonly multiBTC: {
            readonly name: "Multichain BTC";
            readonly symbol: "multiBTC";
            readonly oracleId: "multiBTC";
            readonly address: "0x80A16016cC4A2E6a2CACA8a4a498b1699fF0f844";
            readonly chainId: 7700;
            readonly decimals: 8;
            readonly website: "https://app.multichain.org/";
            readonly description: "Multichain supports to swap BTC to MultiBTC (Multichain BTC) 1:1.";
            readonly documentation: "https://docs.multichain.org/getting-started/introduction";
            readonly tags: readonly ["SYNTHETIC"];
        };
        readonly BNB: {
            readonly name: "Binance Chain";
            readonly symbol: "BNB";
            readonly oracleId: "BNB";
            readonly address: "0xFb7F77faaA3b69ef4C15d6305C79AD92B387C89F";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.binance.com/";
            readonly description: "Binance Coin (BNB) is an exchange-based token created and issued by the cryptocurrency exchange Binance. Initially created on the Ethereum blockchain as an ERC-20 token in July 2017, BNB was migrated over to Binance Chain in February 2019 and became the native coin of the Binance Chain.";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly BUSD: {
            readonly name: "Binance USD";
            readonly symbol: "BUSD";
            readonly oracleId: "BUSD";
            readonly address: "0x381Ea7A7EE6a1e2982e01E7b6837f775a1a4B07F";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.binance.com/en/busd";
            readonly description: "Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos), Approved and regulated by the New York State Department of Financial Services (NYDFS), The BUSD Monthly Audit Report can be viewed from the official website.";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly WBTC: {
            readonly name: "Wrapped BTC";
            readonly symbol: "WBTC";
            readonly oracleId: "WBTC";
            readonly address: "0x08638a74A8134c747Dce29B57472cc2B57F35653";
            readonly chainId: 7700;
            readonly decimals: 8;
            readonly website: "https://wbtc.network/";
            readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly cINU: {
            readonly name: "Canto Inu";
            readonly symbol: "cINU";
            readonly oracleId: "cINU";
            readonly address: "0x7264610A66EcA758A8ce95CF11Ff5741E1fd0455";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.cantoinu.com/";
            readonly description: "Following in the pawprints of Dogecoin and Shiba Inu, Canto Inu is the native breed token to the Canto Blockchain. It is provided solely for entertainment purposes.";
        };
        readonly CRE8R: {
            readonly name: "CRE8R DAO";
            readonly symbol: "CRE8R";
            readonly oracleId: "CRE8R";
            readonly address: "0xc9BAA8cfdDe8E328787E29b4B078abf2DaDc2055";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://cre8r.vip/";
            readonly description: "The world’s first & only decentralized Web3 content marketing agency DAO. Massively scalable. Fueled by DeFi.";
        };
        readonly wstETH: {
            readonly name: "Lido Wrapped Staked ETH";
            readonly symbol: "wstETH";
            readonly oracleId: "wstETH";
            readonly address: "0xc71aAf8e486e3F33841BB56Ca3FD2aC3fa8D29a8";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://lido.fi/";
            readonly description: "Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.";
            readonly documentation: "https://docs.lido.fi/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly stATOM: {
            readonly name: "Stride Staked ATOM";
            readonly symbol: "stATOM";
            readonly oracleId: "stATOM";
            readonly address: "0x4A2a90D444DbB7163B5861b772f882BbA394Ca67";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://stride.zone/";
            readonly description: "Using Stride’s liquid staked ATOM, you can earn both staking and DeFi yields across the Cosmos IBC ecosystem.";
            readonly documentation: "https://docs.stride.zone/docs";
        };
        readonly INJ: {
            readonly name: "Injective";
            readonly symbol: "INJ";
            readonly oracleId: "INJ";
            readonly address: "0x1D54EcB8583Ca25895c512A8308389fFD581F9c9";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://injective.com/";
            readonly description: "Injective is an open, interoperable layer-one blockchain for building powerful DeFi applications.";
            readonly documentation: "https://docs.injective.network/";
        };
        readonly PEPE: {
            readonly name: "Pepe";
            readonly symbol: "PEPE";
            readonly oracleId: "cantoPEPE";
            readonly address: "0xf390830DF829cf22c53c8840554B98eafC5dCBc2";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.pepe.vip/";
            readonly description: "Pepe is here to make memecoins great again. Launched stealth with no presale, zero taxes, LP burnt and contract renounced, $PEPE is a coin for the people, forever. Fueled by pure memetic power, let $PEPE show you the way.";
            readonly tags: readonly ["MEMECOIN"];
        };
        readonly sCANTO: {
            readonly name: "Liquid Staked Canto";
            readonly symbol: "sCANTO";
            readonly oracleId: "sCANTO";
            readonly address: "0x9F823D534954Fc119E31257b3dDBa0Db9E2Ff4ed";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.scanto.io/";
            readonly description: "By holding $sCANTO you are earning a prorata share of the validator rewards. When you stake $CANTO at scanto.io you get $sCANTO, a liquid staking derivative that can be used across a range of DeFi applications. Unlike staked $CANTO, the $sCANTO are freely transferable instead of locked as in the case of native staking.";
            readonly bridge: "native";
            readonly documentation: "https://docs.scanto.io/";
        };
        readonly BLOTR: {
            readonly name: "sCANTO BLOTR";
            readonly symbol: "BLOTR";
            readonly oracleId: "BLOTR";
            readonly address: "0xFf0BAF077e8035A3dA0dD2abeCECFbd98d8E63bE";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.scanto.io/";
            readonly description: "$BLOTR is the governance token for $sCANTO (Liquid Staked Canto) used to vote on protocol upgrades, incentivize $sCANTO liquidity pools, and for other future protocol mechanisms.";
            readonly bridge: "native";
            readonly documentation: "https://docs.scanto.io/governance-token";
        };
        readonly CVM: {
            readonly name: "Canto Velocimeter";
            readonly symbol: "CVM";
            readonly oracleId: "CVM";
            readonly address: "0xbAD86785eB08fe9d0948B7D9d24523000A177cD0";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://cantov3.velocimeter.xyz";
            readonly description: "CVM is the native token for Velocimeter on Canto (CVM), a project providing liquidity on the chain where it is needed most. The CVM token can be staked as or locked to earn rewards on the CVM platform.";
            readonly documentation: "https://docs.velocimeter.xyz/FVMtokenomics";
        };
        readonly oCVM: {
            readonly name: "Option to buy CVM";
            readonly symbol: "oCVM";
            readonly oracleId: "oCVM";
            readonly address: "0x5C2a258A169Fd683e784686E606E33f6D8c31b9a";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://cantov3.velocimeter.xyz";
            readonly description: "oCVM is an options token that helps to reduce sell pressure on the native CVM token. It is earned by liquidity providers (LPs) who provide liquidity to the CVM pools. oCVM can be redeemed for CVM at a discount, or it can be locked up for a period of time as veCVM. veCVM is a governance token that allows holders to vote on the distribution of emissions, as well as receive weekly bribes and fees.";
            readonly documentation: "https://docs.velocimeter.xyz/oFVMmech";
        };
    };
    readonly tokenAddressMap: import("../../util/convertSymbolTokenMapToAddressTokenMap.js").AddressToTokenMap<{
        readonly WNATIVE: {
            readonly name: "Wrapped Canto";
            readonly address: "0x826551890Dc65655a0Aceca109aB11AbDbD7a07B";
            readonly symbol: "WCANTO";
            readonly oracleId: "WCANTO";
            readonly decimals: 18;
            readonly chainId: 7700;
            readonly website: "https://canto.io/";
            readonly description: "Canto is a permissionless general-purpose blockchain running the Ethereum Virtual Machine (EVM). It was built to deliver on the promise of DeFi – that through a post-traditional financial movement, new systems will be made accessible, transparent, decentralized, and free.";
            readonly bridge: "native";
            readonly documentation: "https://docs.canto.io/";
        };
        readonly FEES: {
            readonly name: "Wrapped Canto";
            readonly address: "0x826551890Dc65655a0Aceca109aB11AbDbD7a07B";
            readonly symbol: "WCANTO";
            readonly oracleId: "WCANTO";
            readonly decimals: 18;
            readonly chainId: 7700;
            readonly website: "https://canto.io/";
            readonly description: "Canto is a permissionless general-purpose blockchain running the Ethereum Virtual Machine (EVM). It was built to deliver on the promise of DeFi – that through a post-traditional financial movement, new systems will be made accessible, transparent, decentralized, and free.";
            readonly bridge: "native";
            readonly documentation: "https://docs.canto.io/";
        };
        readonly CANTO: {
            readonly name: "Wrapped Canto";
            readonly address: "0x826551890Dc65655a0Aceca109aB11AbDbD7a07B";
            readonly symbol: "WCANTO";
            readonly oracleId: "WCANTO";
            readonly decimals: 18;
            readonly chainId: 7700;
            readonly website: "https://canto.io/";
            readonly description: "Canto is a permissionless general-purpose blockchain running the Ethereum Virtual Machine (EVM). It was built to deliver on the promise of DeFi – that through a post-traditional financial movement, new systems will be made accessible, transparent, decentralized, and free.";
            readonly bridge: "native";
            readonly documentation: "https://docs.canto.io/";
        };
        readonly WCANTO: {
            readonly name: "Wrapped Canto";
            readonly address: "0x826551890Dc65655a0Aceca109aB11AbDbD7a07B";
            readonly symbol: "WCANTO";
            readonly oracleId: "WCANTO";
            readonly decimals: 18;
            readonly chainId: 7700;
            readonly website: "https://canto.io/";
            readonly description: "Canto is a permissionless general-purpose blockchain running the Ethereum Virtual Machine (EVM). It was built to deliver on the promise of DeFi – that through a post-traditional financial movement, new systems will be made accessible, transparent, decentralized, and free.";
            readonly bridge: "native";
            readonly documentation: "https://docs.canto.io/";
        };
        readonly oldBIFI: {
            readonly name: "Beefy.Finance";
            readonly symbol: "oldBIFI";
            readonly oracleId: "oldBIFI";
            readonly address: "0x765277EebeCA2e31912C9946eAe1021199B39C61";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.beefy.finance/";
            readonly documentation: "https://docs.beefy.finance/";
            readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
        };
        readonly ATOM: {
            readonly name: "Cosmos Token";
            readonly symbol: "ATOM";
            readonly oracleId: "ATOM";
            readonly address: "0xecEEEfCEE421D8062EF8d6b4D814efe4dc898265";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://cosmos.network/";
            readonly description: "Cosmos is an ever-expanding ecosystem of interconnected apps and services, built for a decentralized future.";
            readonly bridge: "gravity";
            readonly documentation: "https://docs.cosmos.network/main";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly ETH: {
            readonly name: "Ethereum";
            readonly symbol: "ETH";
            readonly oracleId: "ETH";
            readonly address: "0x5FD55A1B9FC24967C4dB09C513C3BA0DFa7FF687";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://ethereum.org/";
            readonly description: "The native currency that flows within the Ethereum economy is called Ether (ETH). Ether is typically used to pay for transaction fees called Gas, and it is the base currency of the network.";
            readonly bridge: "gravity";
            readonly documentation: "https://ethereum.org/en/developers/docs/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly NOTE: {
            readonly name: "Note";
            readonly symbol: "NOTE";
            readonly oracleId: "NOTE";
            readonly address: "0x4e71A2E537B7f9D9413D3991D37958c0b5e1e503";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://canto.io/";
            readonly documentation: "https://docs.canto.io/overview/canto-unit-of-account-usdnote";
            readonly description: "$NOTE is the unit of account on Canto. $NOTE is an over-collateralized currency with a value perpetually rebalanced toward $1 through an algorithmic interest rate policy.";
            readonly bridge: "native";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly USDC: {
            readonly name: "USD Coin";
            readonly address: "0x80b5a32E4F032B2a058b4F29EC95EEfEEB87aDcd";
            readonly symbol: "USDC";
            readonly oracleId: "USDC";
            readonly decimals: 6;
            readonly website: "https://www.circle.com/usdc";
            readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
            readonly bridge: "gravity";
            readonly chainId: 7700;
            readonly documentation: "https://developers.circle.com/docs";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly USDT: {
            readonly name: "USDT";
            readonly symbol: "USDT";
            readonly oracleId: "USDT";
            readonly address: "0xd567B3d7B8FE3C79a1AD8dA978812cfC4Fa05e75";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://tether.to/";
            readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
            readonly bridge: "gravity";
            readonly documentation: "https://tether.to/en/how-it-works";
            readonly tags: readonly ["STABLECOIN"];
        };
        readonly FLOWV1: {
            readonly name: "Velocimeter";
            readonly symbol: "FLOWv1";
            readonly oracleId: "FLOWV1";
            readonly address: "0x2Baec546a92cA3469f71b7A091f7dF61e5569889";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://canto.velocimeter.xyz/home";
            readonly description: "Velocimeter addresses these issues and presents an attractive alternative by addressing the core issues in Solidly and adding its own improvements. To recall, the key innovation of Solidly was to align protocol emissions with fees generated, not simply liquidity. To do this, it would allow protocols and other large stakeholders to become veNFT \"voters\", using their locked voting power to direct future emissions and collecting fees (termed bribes in Solidly) from the pools they voted for.";
            readonly documentation: "https://docs.velocimeter.xyz/";
        };
        readonly GRAV: {
            readonly name: "Graviton";
            readonly symbol: "GRAV";
            readonly oracleId: "GRAV";
            readonly address: "0xc03345448969Dd8C00e9E4A85d2d9722d093aF8E";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://www.gravitybridge.net/";
            readonly description: "Cosmos Gravity Bridge™ is a purpose-built, fully decentralized, trustless blockchain which bridges assets between the Ethereum and Cosmos ecosystems. Ethereum and EVM compatible tokens can be transferred across the Gravity Bridge to a Cosmos wallet and then onto other Cosmos wallets or DEXs (such as Osmosis or Gravity DEX). Cosmos SDK based blockchains can similarly send tokens across Gravity Bridge to the Ethereum ecosystem, making them available for transfer or potentially trading on Uniswap or other ETH DEXs.";
            readonly documentation: "https://www.gravitybridge.net/post/how-gravity-works";
        };
        readonly FLOW: {
            readonly name: "Velocimeter";
            readonly symbol: "FLOW";
            readonly oracleId: "FLOW";
            readonly address: "0xB5b060055F0d1eF5174329913ef861bC3aDdF029";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://canto.velocimeter.xyz/home";
            readonly description: "Velocimeter addresses these issues and presents an attractive alternative by addressing the core issues in Solidly and adding its own improvements. To recall, the key innovation of Solidly was to align protocol emissions with fees generated, not simply liquidity. To do this, it would allow protocols and other large stakeholders to become veNFT \"voters\", using their locked voting power to direct future emissions and collecting fees (termed bribes in Solidly) from the pools they voted for.";
            readonly bridge: "native";
            readonly documentation: "https://docs.velocimeter.xyz/";
        };
        readonly SOMM: {
            readonly name: "Somm";
            readonly symbol: "SOMM";
            readonly oracleId: "SOMM";
            readonly address: "0xFA3C22C069B9556A4B2f7EcE1Ee3B467909f4864";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://app.sommelier.finance/";
            readonly description: "Sommelier is a DeFi blockchain protocol, built on the Cosmos SDK, and a bi-directional Ethereum bridge. Taken together, this collection serves as a co-processor to Ethereum - that is we are using a Cosmos chain to process as many of the calculations as possible off Ethereum. The protocol is powered by validators and LPs who can benefit from a wide array of transaction features, such as portfolio rebalancing and limit orders based on dynamically changing market conditions.";
            readonly bridge: "gravity";
            readonly documentation: "https://tricky-sand-5e6.notion.site/Sommelier-Documentation-006e748753e34a1299f9b1d6ae3a4544";
        };
        readonly multiBTC: {
            readonly name: "Multichain BTC";
            readonly symbol: "multiBTC";
            readonly oracleId: "multiBTC";
            readonly address: "0x80A16016cC4A2E6a2CACA8a4a498b1699fF0f844";
            readonly chainId: 7700;
            readonly decimals: 8;
            readonly website: "https://app.multichain.org/";
            readonly description: "Multichain supports to swap BTC to MultiBTC (Multichain BTC) 1:1.";
            readonly documentation: "https://docs.multichain.org/getting-started/introduction";
            readonly tags: readonly ["SYNTHETIC"];
        };
        readonly BNB: {
            readonly name: "Binance Chain";
            readonly symbol: "BNB";
            readonly oracleId: "BNB";
            readonly address: "0xFb7F77faaA3b69ef4C15d6305C79AD92B387C89F";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.binance.com/";
            readonly description: "Binance Coin (BNB) is an exchange-based token created and issued by the cryptocurrency exchange Binance. Initially created on the Ethereum blockchain as an ERC-20 token in July 2017, BNB was migrated over to Binance Chain in February 2019 and became the native coin of the Binance Chain.";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly BUSD: {
            readonly name: "Binance USD";
            readonly symbol: "BUSD";
            readonly oracleId: "BUSD";
            readonly address: "0x381Ea7A7EE6a1e2982e01E7b6837f775a1a4B07F";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.binance.com/en/busd";
            readonly description: "Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos), Approved and regulated by the New York State Department of Financial Services (NYDFS), The BUSD Monthly Audit Report can be viewed from the official website.";
            readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
        };
        readonly WBTC: {
            readonly name: "Wrapped BTC";
            readonly symbol: "WBTC";
            readonly oracleId: "WBTC";
            readonly address: "0x08638a74A8134c747Dce29B57472cc2B57F35653";
            readonly chainId: 7700;
            readonly decimals: 8;
            readonly website: "https://wbtc.network/";
            readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly cINU: {
            readonly name: "Canto Inu";
            readonly symbol: "cINU";
            readonly oracleId: "cINU";
            readonly address: "0x7264610A66EcA758A8ce95CF11Ff5741E1fd0455";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.cantoinu.com/";
            readonly description: "Following in the pawprints of Dogecoin and Shiba Inu, Canto Inu is the native breed token to the Canto Blockchain. It is provided solely for entertainment purposes.";
        };
        readonly CRE8R: {
            readonly name: "CRE8R DAO";
            readonly symbol: "CRE8R";
            readonly oracleId: "CRE8R";
            readonly address: "0xc9BAA8cfdDe8E328787E29b4B078abf2DaDc2055";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://cre8r.vip/";
            readonly description: "The world’s first & only decentralized Web3 content marketing agency DAO. Massively scalable. Fueled by DeFi.";
        };
        readonly wstETH: {
            readonly name: "Lido Wrapped Staked ETH";
            readonly symbol: "wstETH";
            readonly oracleId: "wstETH";
            readonly address: "0xc71aAf8e486e3F33841BB56Ca3FD2aC3fa8D29a8";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://lido.fi/";
            readonly description: "Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.";
            readonly documentation: "https://docs.lido.fi/";
            readonly tags: readonly ["BLUECHIP"];
        };
        readonly stATOM: {
            readonly name: "Stride Staked ATOM";
            readonly symbol: "stATOM";
            readonly oracleId: "stATOM";
            readonly address: "0x4A2a90D444DbB7163B5861b772f882BbA394Ca67";
            readonly chainId: 7700;
            readonly decimals: 6;
            readonly website: "https://stride.zone/";
            readonly description: "Using Stride’s liquid staked ATOM, you can earn both staking and DeFi yields across the Cosmos IBC ecosystem.";
            readonly documentation: "https://docs.stride.zone/docs";
        };
        readonly INJ: {
            readonly name: "Injective";
            readonly symbol: "INJ";
            readonly oracleId: "INJ";
            readonly address: "0x1D54EcB8583Ca25895c512A8308389fFD581F9c9";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://injective.com/";
            readonly description: "Injective is an open, interoperable layer-one blockchain for building powerful DeFi applications.";
            readonly documentation: "https://docs.injective.network/";
        };
        readonly PEPE: {
            readonly name: "Pepe";
            readonly symbol: "PEPE";
            readonly oracleId: "cantoPEPE";
            readonly address: "0xf390830DF829cf22c53c8840554B98eafC5dCBc2";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.pepe.vip/";
            readonly description: "Pepe is here to make memecoins great again. Launched stealth with no presale, zero taxes, LP burnt and contract renounced, $PEPE is a coin for the people, forever. Fueled by pure memetic power, let $PEPE show you the way.";
            readonly tags: readonly ["MEMECOIN"];
        };
        readonly sCANTO: {
            readonly name: "Liquid Staked Canto";
            readonly symbol: "sCANTO";
            readonly oracleId: "sCANTO";
            readonly address: "0x9F823D534954Fc119E31257b3dDBa0Db9E2Ff4ed";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.scanto.io/";
            readonly description: "By holding $sCANTO you are earning a prorata share of the validator rewards. When you stake $CANTO at scanto.io you get $sCANTO, a liquid staking derivative that can be used across a range of DeFi applications. Unlike staked $CANTO, the $sCANTO are freely transferable instead of locked as in the case of native staking.";
            readonly bridge: "native";
            readonly documentation: "https://docs.scanto.io/";
        };
        readonly BLOTR: {
            readonly name: "sCANTO BLOTR";
            readonly symbol: "BLOTR";
            readonly oracleId: "BLOTR";
            readonly address: "0xFf0BAF077e8035A3dA0dD2abeCECFbd98d8E63bE";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://www.scanto.io/";
            readonly description: "$BLOTR is the governance token for $sCANTO (Liquid Staked Canto) used to vote on protocol upgrades, incentivize $sCANTO liquidity pools, and for other future protocol mechanisms.";
            readonly bridge: "native";
            readonly documentation: "https://docs.scanto.io/governance-token";
        };
        readonly CVM: {
            readonly name: "Canto Velocimeter";
            readonly symbol: "CVM";
            readonly oracleId: "CVM";
            readonly address: "0xbAD86785eB08fe9d0948B7D9d24523000A177cD0";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://cantov3.velocimeter.xyz";
            readonly description: "CVM is the native token for Velocimeter on Canto (CVM), a project providing liquidity on the chain where it is needed most. The CVM token can be staked as or locked to earn rewards on the CVM platform.";
            readonly documentation: "https://docs.velocimeter.xyz/FVMtokenomics";
        };
        readonly oCVM: {
            readonly name: "Option to buy CVM";
            readonly symbol: "oCVM";
            readonly oracleId: "oCVM";
            readonly address: "0x5C2a258A169Fd683e784686E606E33f6D8c31b9a";
            readonly chainId: 7700;
            readonly decimals: 18;
            readonly website: "https://cantov3.velocimeter.xyz";
            readonly description: "oCVM is an options token that helps to reduce sell pressure on the native CVM token. It is earned by liquidity providers (LPs) who provide liquidity to the CVM pools. oCVM can be redeemed for CVM at a discount, or it can be locked up for a period of time as veCVM. veCVM is a governance token that allows holders to vote on the distribution of emissions, as well as receive weekly bribes and fees.";
            readonly documentation: "https://docs.velocimeter.xyz/oFVMmech";
        };
    }>;
    readonly native: {
        readonly symbol: "CANTO";
        readonly oracleId: "CANTO";
    };
};
