import type { Token } from '../../../types/token.js';

const ETH = {
  name: 'Wrapped Ether',
  address: '0x4200000000000000000000000000000000000006',
  symbol: 'WETH',
  oracleId: 'WETH',
  decimals: 18,
  chainId: 8453,
  website: 'https://weth.io/',
  description: 'Ether or ETH is the native currency built on the Ethereum blockchain.',
  bridge: 'base-canonical',
  logoURI: '',
  documentation: 'https://ethereum.org/en/developers/docs/',
} as const satisfies Token;

export const tokens = {
  ETH,
  WETH: ETH,
  WNATIVE: ETH,
  mooBIFI: {
    name: 'Bridged BIFI Vault Receipt',
    symbol: 'mooBIFI',
    oracleId: 'mooBIFI',
    address: '0xc55E93C62874D8100dBd2DfE307EDc1036ad5434',
    chainId: 8453,
    decimals: 18,
    website: 'https://beefy.com',
    description:
      "The incentive-bearing Beefy Token (mooBIFI) applies the magic of Beefy's autocompounding technology to the BIFI token. It is the vault token for the BIFI Vault, which automatically claims and swaps governance incentives into more BIFI, and redeposits to unlock exponential growth. On chains other than Ethereum, mooBIFI is a bridged copy of the native Ethereum token, and cannot be returned to BIFI without first bridging back to Ethereum. mooBIFI holders on all chains retain their full voting power corresponding to the underlying amount of BIFI deposited and compounding on Ethereum.",
    logoURI: 'https://beefy.com/icons/128/mooBIFI.png',
    documentation: 'https://docs.beefy.finance/',
    bridge: 'beefy',
  },
  BSX: {
    name: 'BSX',
    symbol: 'BSX',
    oracleId: 'BSX',
    address: '0xd5046B976188EB40f6DE40fB527F89c05b323385',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0xd5046B976188EB40f6DE40fB527F89c05b323385.svg',
    website: 'https://baseswap.fi/',
    description:
      'BSX is the incentives token of BaseSwap, rewarded to liquidity providers in the BaseSwap ecosystem. xBSX is the escrow version of BSX and can be vested over time.',
    documentation: 'https://base-swap-1.gitbook.io/baseswap/tokenomics/usdbsx-token',
    bridge: 'native',
  },
  BASO: {
    name: 'BASO',
    symbol: 'BASO',
    oracleId: 'BASO',
    address: '0x23E1A3BcDcEE4C59209d8871140eB7DD2bD9d1cE',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x23E1A3BcDcEE4C59209d8871140eB7DD2bD9d1cE.svg',
    website: 'https://www.baso.finance/',
    description:
      'BASO is the governance token of Baso Finance, a Velodrome inspired DEX. Liquidity providers are rewarded with BASO and veBASO holders vote on liquidity pools to receive bribes and trading fees.',
    documentation: 'https://basofinance.gitbook.io/basofinance/',
    bridge: 'native',
  },
  EURA: {
    name: 'EURA (previously agEUR)',
    symbol: 'EURA',
    oracleId: 'agEUR',
    address: '0xA61BeB4A3d02decb01039e378237032B351125B4',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://app.angle.money/',
    description:
      'EURA (previously agEUR) is pegged to the value of the Euro (€) and is a product of Angle, a decentralized, capital-efficient and over-collateralized stablecoins protocol.',
    bridge: 'layer-zero',
    documentation: 'https://docs.angle.money/',
  },
  USDA: {
    name: 'USDA',
    symbol: 'USDA',
    oracleId: 'USDA',
    address: '0x0000206329b97DB379d5E1Bf586BbDB969C63274',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://app.angle.money/',
    description:
      'USDA is pegged to the value of the Dollar ($) and is a product of Angle, a decentralized, capital-efficient and over-collateralized stablecoins protocol.',
    bridge: 'layer-zero',
    documentation: 'https://docs.angle.money/',
  },
  THALES: {
    name: 'Thales DAO Token',
    symbol: 'THALES',
    oracleId: 'THALES',
    address: '0xf34e0cff046e154CAfCae502C7541b9E5FD8C249',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://thalesmarket.io/markets',
    description:
      'Thales is an Ethereum protocol that allows the creation of peer-to-peer parimutuel markets that anyone can join.',
    documentation: 'https://docs.thalesmarket.io/',
    bridge: 'celer',
  },
  SONNE: {
    name: 'Sonne',
    symbol: 'SONNE',
    oracleId: 'SONNE',
    address: '0x22a2488fE295047Ba13BD8cCCdBC8361DBD8cf7c',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://sonne.finance/',
    description:
      'Sonne Finance is an EVM compatible lending/borrowing protocol that has launched on multiple chains. Sonne Finance provides peer-to-peer lending solutions that are fully decentralized, transparent and non-custodial.',
    documentation: 'https://docs.sonne.finance/',
    bridge: 'axelar',
  },
  UNIDX: {
    name: 'Unidex',
    symbol: 'UNIDX',
    oracleId: 'UNIDX',
    address: '0x6B4712AE9797C199edd44F897cA09BC57628a1CF',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x6B4712AE9797C199edd44F897cA09BC57628a1CF.svg',
    website: 'https://app.unidex.exchange/trading',
    description:
      'UniDex is building on top of the existing landscape by introducing a perpetual leverage trading platform that will allow any synthetic asset to be traded in a permissionless, transparent, and trader-focused platform for any person to tap into.',
    documentation: 'https://unidexexchange.gitbook.io/unidex/',
    bridge: 'synapse',
  },
  axlWBTC: {
    name: 'Axelar Wrapped WBTC',
    symbol: 'axlWBTC',
    oracleId: 'axlWBTC',
    address: '0x1a35EE4640b0A3B87705B0A4B45D227Ba60Ca2ad',
    chainId: 8453,
    decimals: 8,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x1a35EE4640b0A3B87705B0A4B45D227Ba60Ca2ad.svg',
    website: 'https://wbtc.network/',
    description: 'Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin.',
    documentation: 'https://wbtc.network/',
    bridge: 'axelar',
  },
  BASE: {
    name: 'BASE',
    symbol: 'BASE',
    oracleId: 'BASE',
    address: '0xd07379a755A8f11B57610154861D694b2A0f615a',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0xd07379a755A8f11B57610154861D694b2A0f615a.svg',
    website: 'https://swapbased.finance/#/',
    description: 'BASE is the governance token of SwapBased, a DEX built on the Base blockchain.',
    documentation: 'https://docs.swapbased.finance/',
    bridge: 'native',
  },
  WELL: {
    name: 'WELL',
    symbol: 'WELL.wh',
    oracleId: 'WELL',
    address: '0xFF8adeC2221f9f4D8dfbAFa6B9a297d17603493D',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x511aB53F793683763E5a8829738301368a2411E3.svg',
    website: 'https://moonwell.fi/',
    description: 'WELL is the native governance token of the Moonwell protocol',
    bridge: 'wormhole',
    documentation: 'https://docs.moonwell.fi/moonwell/discover/about-moonwell',
  },
  ALB: {
    name: 'Alien Base',
    symbol: 'ALB',
    oracleId: 'ALB',
    address: '0x1dd2d631c92b1aCdFCDd51A0F7145A50130050C4',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://app.alienbase.xyz/swap',
    description: 'Reward token for the Alien Base DEX on the base chain. Farm and stake tokens.',
    documentation: 'https://docs.alienbase.xyz/',
    bridge: 'native',
  },
  'USD+': {
    name: 'USD+',
    symbol: 'USD+',
    oracleId: 'baseUSD+',
    address: '0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376',
    chainId: 8453,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376.svg',
    website: 'https://overnight.fi/',
    description:
      'USD+ is USDC that pays you yield daily via rebase. It is 100% collateralized with assets immediately convertible into USDC. Yield is generated via strategies such as lending and stable-to-stable pools. Initial strategies include Aave, Rubicon, and Pika.',
    documentation: 'https://docs.overnight.fi/',
    bridge: 'native',
  },
  'DAI+': {
    name: 'DAI+',
    symbol: 'DAI+',
    oracleId: 'DAI+',
    address: '0x65a2508C429a6078a7BC2f7dF81aB575BD9D9275',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x65a2508C429a6078a7BC2f7dF81aB575BD9D9275.svg',
    website: 'https://overnight.fi/',
    description:
      'DAI+ is DAI that pays you yield daily via rebase.  It is 100% collateralized with assets immediately convertible into DAI.  Yield is generated via strategies such as lending and stable-to-stable pools. Initial strategies include Aave, Rubicon, and Pika.',
    documentation: 'https://docs.overnight.fi/',
    bridge: 'native',
  },
  OVN: {
    name: 'OVN',
    symbol: 'OVN',
    oracleId: 'baseOVN',
    address: '0xA3d1a8DEB97B111454B294E2324EfAD13a9d8396',
    chainId: 8453,
    decimals: 18,
    website: 'https://overnight.fi/',
    description:
      'OVN token is a utility token that serves multiple purposes in the Overnight protocol. It is used for bribes to promote USD+ and incentivize conservative risk decisions, as well as for voting rights to establish decentralized risk monitoring and management processes.',
    bridge: 'axelar',
    logoURI: '',
    documentation: 'https://docs.overnight.fi/',
  },
  MIM: {
    name: 'Magic Internet Money',
    symbol: 'MIM',
    oracleId: 'MIM',
    address: '0x4A3A6Dd60A34bB2Aba60D73B4C88315E9CeB6A3D',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4A3A6Dd60A34bB2Aba60D73B4C88315E9CeB6A3D.svg',
    website: 'https://docs.abracadabra.money/',
    description:
      'You, the Spellcaster, can provide collateral in the form of various interest bearing crypto assets such as yvYFI, yvUSDT, yvUSDC, xSUSHI and more. With this, you can borrow magic internet money (MIM) which is a stable coin that you can swap for any other traditional stable coin.',
    documentation: 'https://docs.abracadabra.money/',
    bridge: 'layer-zero',
  },
  cbETH: {
    name: 'Coinbase Wrapped Staked ETH',
    symbol: 'cbETH',
    oracleId: 'cbETH',
    address: '0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22.svg',
    website: 'https://help.coinbase.com/en/coinbase/trading-and-funding/staking-rewards/cbeth',
    description:
      "Coinbase Wrapped Staked ETH (“cbETH”) is a utility token that represents Ethereum 2 (ETH2), which is ETH staked through Coinbase. Over time, the price of cbETH will likely deviate from ETH because cbETH represents 1 staked ETH plus all of its accrued staking interest starting from when cbETH's conversion rate and balance were initialized (June 16, 2022 19:34 UTC). cbETH is minted exclusively by Coinbase.",
    documentation:
      'https://help.coinbase.com/en/coinbase/trading-and-funding/staking-rewards/cbeth',
    bridge: 'native',
  },
  axlUSDC: {
    name: 'Axelar Wrapped USDC',
    symbol: 'axlUSDC',
    oracleId: 'axlUSDC',
    address: '0xEB466342C4d449BC9f53A865D5Cb90586f405215',
    chainId: 8453,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0xEB466342C4d449BC9f53A865D5Cb90586f405215.svg',
    website: 'https://www.axelar.network/',
    bridge: 'axelar',
    description:
      'axlUSDC is a cross-chain representation of USDC, secured by a validator set using delegated Proof-of-Stake and multi-party cryptography. It allows USDC to move seamlessly across different blockchain ecosystems, minted by depositing USDC into an Axelar Gateway on Ethereum, and can be acquired through DEXs, cross-chain swaps via Squid, or bridging via Satellite.money.',
    documentation: 'https://docs.axelar.dev/learn/axlusdc',
  },
  axlUSDT: {
    name: 'USDT',
    symbol: 'axlUSDT',
    oracleId: 'axlUSDT',
    address: '0x7f5373AE26c3E8FfC4c77b7255DF7eC1A9aF52a6',
    chainId: 8453,
    decimals: 6,
    website: 'https://www.axelar.network/',
    documentation: 'https://docs.axelar.dev/',
    description:
      'axlUSDT is a cross-chain representation of USDT, secured by a validator set using delegated Proof-of-Stake and multi-party cryptography. It allows USDT to move seamlessly across different blockchain ecosystems, minted by depositing USDT into an Axelar Gateway on Ethereum, and can be acquired through DEXs, cross-chain swaps via Squid, or bridging via Satellite.money.',
    logoURI: 'https://hecoinfo.com/token/images/USDTHECO_32.png',
    bridge: 'axelar',
  },
  OGRE: {
    name: 'SHREKT',
    symbol: 'OGRE',
    oracleId: 'OGRE',
    address: '0xAB8a1c03b8E4e1D21c8Ddd6eDf9e07f26E843492',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0xAB8a1c03b8E4e1D21c8Ddd6eDf9e07f26E843492.svg',
    website: '',
    description: 'Meme coin on Base.',
    documentation: '',
    bridge: 'native',
  },
  USDbC: {
    name: 'USD Base Coin',
    address: '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA',
    symbol: 'USDbC',
    oracleId: 'USDbC',
    decimals: 6,
    website: 'https://www.centre.io/',
    description: 'USDC.e is an Ethereum-based USDC bridged via the official Base Bridge.',
    chainId: 8453,
    logoURI: '',
    documentation: 'https://www.circle.com/blog/usdc-now-available-natively-on-base',
    bridge: 'base-canonical',
  },
  USDC: {
    name: 'USD Circle',
    address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    symbol: 'USDC',
    oracleId: 'USDC',
    decimals: 6,
    website: 'https://www.centre.io/',
    description:
      'USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
    chainId: 8453,
    logoURI: '',
    documentation: 'https://developers.circle.com/docs',
    bridge: 'native',
  },
  DAI: {
    name: 'DAI Stablecoin',
    symbol: 'DAI',
    oracleId: 'DAI',
    address: '0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://makerdao.com/en/',
    bridge: 'base-canonical',
    documentation:
      'https://docs.makerdao.com/smart-contract-modules/dai-module/dai-detailed-documentation',
    description:
      'Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain',
  },
  AERO: {
    name: 'Aerodrome',
    symbol: 'AERO',
    oracleId: 'AERO',
    address: '0x940181a94A35A4569E4529A3CDfB74e38FD98631',
    chainId: 8453,
    decimals: 18,
    website: 'https://aerodrome.finance/',
    documentation: 'https://aerodrome.finance/docs',
    description:
      "Aerodrome Finance is a next-generation AMM designed to serve as Base's central liquidity hub, combining a powerful liquidity incentive engine, vote-lock governance model, and friendly user experience. Aerodrome inherits the latest features from Velodrome V2.",
    logoURI: '',
    bridge: 'native',
  },
  DOLA: {
    name: 'Dola USD Stablecoin',
    symbol: 'DOLA',
    oracleId: 'baseDOLA',
    address: '0x4621b7A9c75199271F773Ebd9A499dbd165c3191',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.inverse.finance/',
    description:
      'Inverse.finance is a suite of permissionless decentralized finance tools governed by Inverse DAO, a decentralized autonomous organization running on the Ethereum blockchain.',
    bridge: 'base-canonical',
    documentation: 'https://docs.inverse.finance/',
  },
  MAI: {
    name: 'Mai Stablecoin',
    symbol: 'MAI',
    oracleId: 'bMAI',
    address: '0xbf1aeA8670D2528E08334083616dD9C5F3B087aE',
    chainId: 8453,
    decimals: 18,
    website: 'https://www.mai.finance/',
    description:
      "MAI is a stablecoin collateralized by your crypto holdings. It's powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.",
    logoURI: 'https://raw.githubusercontent.com/0xlaozi/qidao/main/images/mimatic-red.png',
    documentation: 'https://docs.mai.finance/',
    bridge: 'native',
  },
  wUSDR: {
    name: 'Real USD',
    symbol: 'wUSDR',
    oracleId: 'bawUSDR',
    address: '0x9483ab65847A447e36d21af1CaB8C87e9712ff93',
    chainId: 8453,
    decimals: 9,
    website: 'https://www.tangible.store/realusd',
    documentation: 'https://docs.tangible.store/',
    description:
      'Real USD (USDR) is the world’s first stablecoin collateralized by tokenized, yield-producing real estate. USDR has a value accrual system built into its design. Using a consistent stream of dependable yield derived from rental revenue, Real USD delivers a native yield to holders.',
    logoURI: '',
    bridge: 'layer-zero',
  },
  tBTC: {
    name: 'tBTC v2',
    symbol: 'tBTC',
    oracleId: 'tBTC',
    address: '0x236aa50979D5f3De3Bd1Eeb40E81137F22ab794b',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://threshold.network/',
    documentation: 'https://docs.threshold.network/',
    description:
      'Threshold is the first ever on-chain merge between two existing networks and communities, Keep and NuCypher. Threshold provides a suite of threshold cryptography services that power user sovereignty on the blockchain.',
    bridge: 'wormhole',
  },
  BASED: {
    name: 'based.markets',
    symbol: 'BASED',
    oracleId: 'BASED',
    address: '0xBa5E6fa2f33f3955f0cef50c63dCC84861eAb663',
    chainId: 8453,
    decimals: 18,
    website: 'https://www.based.markets/',
    description:
      'Based offers intent-based P2P derivatives with deep liquidity sourced from centralized exchanges.',
    logoURI: '',
    bridge: 'native',
  },
  crvUSD: {
    name: 'Curve.Fi USD Stablecoin',
    symbol: 'crvUSD',
    oracleId: 'crvUSD',
    address: '0x417Ac0e078398C154EdFadD9Ef675d30Be60Af93',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://crvusd.curve.fi/',
    description:
      'crvUSD is a collateralized-debt-position (CDP) stablecoin pegged to the US Dollar',
    documentation: 'https://docs.curve.fi/crvUSD/overview/',
    bridge: 'base-canonical',
  },
  bsUSD: {
    name: 'Balancer Stable Pool',
    symbol: 'bsUSD',
    oracleId: 'balancer-base-usdbc-dai',
    address: '0x6FbFcf88DB1aADA31F34215b2a1Df7fafb4883e9',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    bridge: 'native',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer composable pool that consist of USDbC and DAI. bbTokens are boosted linear pools.',
  },
  BVM: {
    name: 'Base Velocimeter',
    symbol: 'BVM',
    oracleId: 'BVM',
    address: '0xd386a121991E51Eab5e3433Bf5B1cF4C8884b47a',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://base.velocimeter.xyz',
    description:
      'BVM is the native token for Velocimeter on Base (BVM), a project providing liquidity on the chain where it is needed most. The BVM token can be staked as or locked to earn rewards on the BVM platform.',
    documentation: 'https://docs.velocimeter.xyz/FVMtokenomics',
    bridge: 'native',
  },
  oBVM: {
    name: 'Option to buy BVM',
    symbol: 'oBVM',
    oracleId: 'oBVM',
    address: '0x762eb51D2e779EeEc9B239FFB0B2eC8262848f3E',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://base.velocimeter.xyz',
    description:
      'oBVM is an options token that helps to reduce sell pressure on the native BVM token. It is earned by liquidity providers (LPs) who provide liquidity to the BVM pools. oBVM can be redeemed for BVM at a discount, or it can be locked up for a period of time as veBVM. veBVM is a governance token that allows holders to vote on the distribution of emissions, as well as receive weekly bribes and fees.',
    documentation: 'https://docs.velocimeter.xyz/oFVMmech',
    bridge: 'native',
  },
  rETH: {
    name: 'Rocket Pool ETH',
    symbol: 'rETH',
    oracleId: 'rETH',
    address: '0xB6fe221Fe9EeF5aBa221c348bA20A1Bf5e73624c',
    chainId: 8453,
    decimals: 18,
    website: 'https://rocketpool.net/',
    description:
      'As a Rocket Pool staker, your role is to deposit ETH into the deposit pool which will enable a node operator to create a new Beacon Chain validator. You can stake as little as 0.01 ETH. In doing so, you will be given a token called rETH. rETH represents both how much ETH you deposited, and when you deposited it.',
    bridge: 'base-canonical',
    logoURI: '',
    documentation: 'https://docs.rocketpool.net/guides/',
  },
  FTW: {
    name: 'FriendTech33',
    symbol: 'FTW',
    oracleId: 'FTW',
    address: '0x3347453Ced85bd288D783d85cDEC9b01Ab90f9D8',
    chainId: 8453,
    decimals: 9,
    logoURI: '',
    website: 'https://friendtech33.xyz',
    description:
      'FriendTech33 combines the metas of Friend Tech into a DAO format backing a deeply liquid reserve currency with Friend Tech assets including keys, wrapped keys, ecosystem related project tokens, and finally the airdropped token itself.',
    bridge: 'native',
  },
  SCALE: {
    name: 'Scale',
    symbol: 'SCALE',
    oracleId: 'SCALE',
    address: '0x54016a4848a38f257B6E96331F7404073Fd9c32C',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://base.equalizer.exchange/',
    description:
      'Equalizer was derived from the initial concept of Andre Cronje. The mechanism that was used to create a perpetual decentralized exchange was unique and ingenious. The launch of this platform is to take the concept and apply it to a more natural style DEX. Equalizer will become the trading mechanism for the Fantom network, utilizing the Solidly perpetual model with some tweaks to fee structures and emissions. ',
    documentation: 'https://docs.equalizer.exchange/',
    bridge: 'native',
  },
  hyUSD: {
    name: 'High Yield USD',
    symbol: 'hyUSD',
    oracleId: 'hyUSD',
    address: '0xCc7FF230365bD730eE4B352cC2492CEdAC49383e',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://linktr.ee/hyusd',
    description:
      'A decentralized flatcoin that provides convenient access to DeFi yields, enabling holders to earn passive income on their capital. Governance should aim to take low to moderate risk to return high DeFi yields in order to mitigate against inflation.',
    documentation: '',
    bridge: 'native',
  },
  eUSD: {
    name: 'Electronic Dollar',
    symbol: 'eUSD',
    oracleId: 'eUSD',
    address: '0xCfA3Ef56d303AE4fAabA0592388F19d7C3399FB4',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website:
      'https://app.reserve.org/ethereum/token/0xa0d69e286b938e21cbf7e51d71f6a4c8918f482f/overview',
    description:
      'The Electronic Dollar (eUSD) is a decentralized 1:1 asset-backed stablecoin built with Reserve Protocol, available on the Ethereum and MobileCoin blockchains. It sets itself apart from other stablecoins due to its decentralized, community-governed, and censorship-resistant nature.',
    documentation: 'https://reserve.org/protocol/',
    bridge: 'base-canonical',
  },
  wstETH: {
    name: 'Wrapped liquid staked Ether 2.0',
    symbol: 'wstETH',
    oracleId: 'wstETH',
    address: '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.',
    documentation: 'https://docs.lido.fi/',
    bridge: 'base-canonical',
  },
  CRV: {
    name: 'Curve DAO Token',
    symbol: 'CRV',
    oracleId: 'CRV',
    address: '0x8Ee73c484A26e0A5df2Ee2a4960B789967dd0415',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://curve.fi/',
    description:
      'Curve is an exchange liquidity pool on Ethereum. Curve is designed for extremely efficient stablecoin trading and low risk, supplemental fee income for liquidity providers, without an opportunity cost.',
    documentation: 'https://curve.readthedocs.io/',
    bridge: 'base-canonical',
  },
  'USDC+': {
    name: 'USDC Plus',
    symbol: 'USDC+',
    oracleId: 'bUSDC+',
    address: '0x85483696Cc9970Ad9EdD786b2C5ef735F38D156f',
    chainId: 8453,
    decimals: 6,
    logoURI: '',
    bridge: 'native',
    website: 'https://overnight.fi/',
    description:
      'A risk-minimised USDC-pegged crypto asset backed by an underlying basket of USD stablecoins',
    documentation: 'https://docs.overnight.fi/',
  },
  bsdETH: {
    name: 'Based ETH',
    symbol: 'bsdETH',
    oracleId: 'bsdETH',
    address: '0xCb327b99fF831bF8223cCEd12B1338FF3aA322Ff',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website:
      'https://app.reserve.org/base/token/0xcb327b99ff831bf8223cced12b1338ff3aa322ff/overview',
    description:
      'A yield generating Ethereum Liquid Staking Token basket with over-collateralization protection. ',
    documentation: 'https://reserve.org/protocol/',
    bridge: 'native',
  },
  TYBG: {
    name: 'Base God',
    symbol: 'TYBG',
    oracleId: 'TYBG',
    address: '0x0d97F261b1e88845184f678e2d1e7a98D9FD38dE',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://basegod.fun/',
    description:
      'In the spirit of being based and fair, $TYBG was stealth launched with no tax or team/presale tokens. Memecoin.',
    documentation: '',
    bridge: 'native',
  },
  axlOP: {
    name: 'Axelar Wrapped OP',
    symbol: 'axlOP',
    oracleId: 'axlOP',
    address: '0x994ac01750047B9d35431a7Ae4Ed312ee955E030',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://app.optimism.io/governance',
    description:
      'Optimistic Rollup is a layer 2 scaling solution that scales both transaction throughput and computation on Ethereum. The backbone of our implementation is the Optimistic Virtual Machine (OVM), which is fully compatible with the EVM.',
    documentation: '',
    bridge: 'axelar',
  },
  DOG: {
    name: 'Basic Dog Meme',
    symbol: 'DOG',
    oracleId: 'DOG',
    address: '0x9E53e88dCff56d3062510A745952DEC4cEFDff9E',
    chainId: 8453,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x9E53e88dCff56d3062510A745952DEC4cEFDff9E.svg',
    website: 'https://basicdog.xyz/',
    description: 'The first meme coin on Base. Fairly Launched. Organic Growth. Good Vibes.',
    documentation: 'https://basicdog.gitbook.io/basic-meme-chain/',
    bridge: 'native',
  },
  SNX: {
    name: 'Synthetix Network Token',
    symbol: 'SNX',
    address: '0x22e6966B799c4D5B13BE962E1D117b56327FDa66',
    chainId: 8453,
    oracleId: 'SNX',
    decimals: 18,
    logoURI: '',
    website: 'https://www.synthetix.io/',
    description:
      'Synthetix is the backbone for derivatives trading in DeFi, allowing anyone, anywhere to gain on-chain exposure to a vast range of assets.',
    documentation:
      'https://docs.synthetix.io/synthetix-protocol/the-synthetix-protocol/synthetix-token-snx',
    bridge: 'base-canonical',
  },
  T: {
    name: 'Threshold Network Token',
    symbol: 'T',
    address: '0x26f3901aC8a79c50fb0d8289C74f0d09AdC42E29',
    chainId: 8453,
    decimals: 18,
    oracleId: 'T',
    logoURI: '',
    website: 'https://threshold.network/',
    description:
      'Threshold is the first ever on-chain merge between two existing networks and communities, Keep and NuCypher. Threshold provides a suite of threshold cryptography services that power user sovereignty on the blockchain.',
    documentation:
      'https://docs.threshold.network/app-development/staking-contract-and-dao/staking-contract-and-dao-api/t',
    bridge: 'base-canonical',
  },
  DEGEN: {
    name: 'Degen',
    symbol: 'DEGEN',
    address: '0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed',
    chainId: 8453,
    decimals: 18,
    oracleId: 'DEGEN',
    logoURI: '',
    website: 'https://www.degen.tips/',
    description:
      'Degen is an unofficial token that were distributed to the community on the decentralized social network, Farcaster.',
    documentation: 'https://www.degen.tips/faq',
    bridge: 'native',
  },
  doginme: {
    name: 'doginme',
    symbol: 'doginme',
    address: '0x6921B130D297cc43754afba22e5EAc0FBf8Db75b',
    chainId: 8453,
    decimals: 18,
    oracleId: 'doginme',
    logoURI: '',
    website: 'https://dogin.meme/',
    description:
      'The $doginme memecoin roots were established when a Farcaster user inquired if Dan Romero (DWR), the founder of the decentralized social media platform, owned a dog.',
    bridge: 'native',
  },
  RSR: {
    name: 'Reserve Rights',
    symbol: 'RSR',
    address: '0xaB36452DbAC151bE02b16Ca17d8919826072f64a',
    chainId: 8453,
    decimals: 18,
    oracleId: 'RSR',
    logoURI: '',
    website: 'https://reserve.org/',
    description:
      'The Reserve protocol is the first platform that allows for the permissionless creation of asset-backed, yield-bearing & overcollateralized stablecoins. Reserve Rights (RSR) exists as an overcollateralization mechanism to protect RToken holders in the unlikely event of a collateral token default.',
    documentation: 'https://reserve.org/protocol/reserve_rights_rsr/',
    bridge: 'base-canonical',
  },
  rgUSD: {
    name: 'Revenue Generating USD',
    symbol: 'rgUSD',
    address: '0x8E5E9DF4F0EA39aE5270e79bbABFCc34203A3470',
    chainId: 8453,
    oracleId: 'rgUSD',
    decimals: 18,
    logoURI: '',
    website:
      'https://app.reserve.org/ethereum/token/0x78da5799cf427fee11e9996982f4150ece7a99a7/overview',
    description:
      'rgUSD is an overcollateralized stablecoin launched on Reserve Protocol that acts as a collective point for DeFi users to negotiate with stablecoin yield providers for the best returns.',
    documentation: 'https://reserve.org/protocol/',
    bridge: 'base-canonical',
  },
  TN100x: {
    name: 'The Next 100x Memecoin on Base',
    symbol: 'TN100x',
    address: '0x5B5dee44552546ECEA05EDeA01DCD7Be7aa6144A',
    chainId: 8453,
    decimals: 18,
    oracleId: 'TN100x',
    logoURI: '',
    website: 'https://ham.fun/',
    description:
      'TN100x is the coin that powers the HAM ecosystem, an upcoming layer 3 blockchain. More than a memecoin, it’s a social token, and a driving force behind everything Ham.',
    bridge: 'native',
    risks: ['NO_TIMELOCK'],
  },
  CHAD: {
    name: 'Based Chad',
    symbol: 'CHAD',
    address: '0xecaF81Eb42cd30014EB44130b89Bcd6d4Ad98B92',
    chainId: 8453,
    decimals: 18,
    oracleId: 'CHAD',
    logoURI: '',
    website: 'https://basedchad.io/',
    description:
      'You can’t say anything is more based than putting the best meme of all time on the most based L2.',
    bridge: 'native',
  },
  ANIME: {
    name: 'Anime',
    symbol: 'ANIME',
    address: '0x0e0c9756a3290cD782CF4aB73ac24D25291c9564',
    chainId: 8453,
    decimals: 18,
    oracleId: 'ANIME',
    logoURI: '',
    website: 'https://www.animeonbase.art/',
    description:
      '$ANIME has grown into a movement uniting people from around the world by their love of art and anime. No VCs, influencers, or utility. Just art and memes.',
    bridge: 'native',
  },
  L2VE: {
    name: 'Cupid Inu',
    symbol: 'L2VE',
    address: '0xA19328fb05ce6FD204D16c2a2A98F7CF434c12F4',
    chainId: 8453,
    decimals: 18,
    oracleId: 'L2VE',
    logoURI: '',
    website: 'https://www.l2ve.me/',
    description:
      'The Cupid Inu memecoin has landed on BASE, with a mission to scatter as much $L2VE as possible.',
    bridge: 'native',
  },
  SEXY: {
    name: 'Settled ETHXY Token',
    symbol: 'SEXY',
    address: '0xD1917629B3E6A72E6772Aab5dBe58Eb7FA3C2F33',
    chainId: 8453,
    decimals: 18,
    oracleId: 'SEXY',
    logoURI: '',
    website: 'https://docs.ethxy.com/',
    description:
      'EthXY is a MMORPG built on top of Telegram. SEXY is a game token used for a variety of game mechanics and weapon + armor purchases.',
    documentation: 'https://ethxy.com/',
    bridge: 'base-canonical',
    risks: ['NO_TIMELOCK'],
  },
  sFRAX: {
    name: 'Staked FRAX',
    symbol: 'sFRAX',
    address: '0xe4796cCB6bB5DE2290C417Ac337F2b66CA2E770E',
    chainId: 8453,
    decimals: 18,
    oracleId: 'sFRAX',
    logoURI: '',
    website: 'https://app.frax.finance/sfrax/stake',
    description:
      'Staked FRAX (sFRAX) is an ERC4626 staking vault that distributes part of the Frax Protocol yield weekly to stakers denominated in FRAX stablecoins. The sFRAX token represents pro rata deposits within the vault and is always withdrawable for FRAX stablecoins at the pro rata rate at all times. sFRAX APY attempts to roughly track the interest on reserve balances (IORB) rate of the United States Federal Reserve using the IORB oracle. This benchmark rate is generally accepted as the “risk free rate” of the US Dollar. The FRAX staking vault attempts, but does not guarantee in any way, to target this rate.',
    documentation: 'https://docs.frax.finance/frax-v3/sfrax',
    bridge: 'layer-zero',
    risks: ['NO_TIMELOCK'],
  },
  sfrxETH: {
    name: 'Staked Frax Ether',
    symbol: 'sfrxETH',
    address: '0x1f55a02A049033E3419a8E2975cF3F572F4e6E9A',
    chainId: 8453,
    decimals: 18,
    oracleId: 'sfrxETH',
    logoURI: '',
    website: 'https://app.frax.finance/frxeth/mint',
    description:
      'sfrxETH is a ERC-4626 vault designed to accrue the staking yield of the Frax ETH validators. At any time, frxETH can be exchanged for sfrxETH by depositing it into the sfrxETH vault, which allows users to earn staking yield on their frxETH. Over time, as validators accrue staking yield, an equivalent amount of frxETH is minted and added to the vault, allowing users to redeem their sfrxETH for an greater amount of frxETH than they deposited.',
    documentation: 'https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth',
    bridge: 'layer-zero',
    risks: ['NO_TIMELOCK'],
  },
  FXS: {
    name: 'Frax Share',
    symbol: 'FXS',
    address: '0x23432452B720C80553458496D4D9d7C5003280d0',
    chainId: 8453,
    decimals: 18,
    oracleId: 'FXS',
    logoURI: 'https://app.sushi.com/images/tokens/fxs-square.jpg',
    website: 'https://frax.finance/',
    description:
      'The Frax Share token (FXS) is the non-stable, utility token in the protocol. It is meant to be volatile and hold rights to governance and all utility of the system. It is important to note that we take a highly governance-minimized approach to designing trustless money in the same ethos as Bitcoin. We eschew DAO-like active management such as MakerDAO. The less parameters for a community to be able to actively manage, the less there is to disagree on. Parameters that are up for governance through FXS include adding/adjusting collateral pools, adjusting various fees (like minting or redeeming), and refreshing the rate of the collateral ratio. No other actions such as active management of collateral or addition of human-modifiable parameters are possible other than a hardfork that would require voluntarily moving to a new implementation entirely. ',
    documentation: 'https://docs.frax.finance/',
    bridge: 'layer-zero',
    risks: ['NO_TIMELOCK'],
  },
  ezETH: {
    name: 'Renzo Restaked ETH',
    symbol: 'ezETH',
    address: '0x2416092f143378750bb29b79eD961ab195CcEea5',
    chainId: 8453,
    decimals: 18,
    oracleId: 'ezETH',
    logoURI: '',
    website: 'https://www.renzoprotocol.com/',
    description:
      'Renzo ezETH is a Liquid Restaking Token (LRT) and Strategy Manager for EigenLayer. It is the interface to the EigenLayer ecosystem securing Actively Validated Services (AVSs) and offering a higher yield than ETH staking.',
    documentation: 'https://docs.renzoprotocol.com/docs/',
    bridge: 'connext',
    risks: ['NO_TIMELOCK'],
  },
  bWELL: {
    name: 'WELL',
    symbol: 'WELL',
    oracleId: 'bWELL',
    address: '0xA88594D404727625A9437C3f886C7643872296AE',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://moonwell.fi/',
    description: 'WELL is the native governance token of the Moonwell protocol.',
    bridge: 'native',
    documentation: 'https://docs.moonwell.fi/moonwell/discover/about-moonwell',
  },
  wBaseDOGE: {
    name: 'Wrapped BaseDOGE',
    symbol: 'wBaseDOGE',
    oracleId: 'wBaseDOGE',
    address: '0x373504DA48418C67E6FCD071F33Cb0b3B47613C7',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.basedoge.xyz/',
    description: 'Meme dog token on base.',
    bridge: 'native',
    documentation: 'https://www.basedoge.xyz/',
  },
  baseQI: {
    name: 'Qi Dao',
    symbol: 'QI',
    oracleId: 'baseQI',
    address: '0xD3FDCb837DAfdb7C9C3eBD48FE22a53F6Dd3d7D7',
    chainId: 8453,
    decimals: 18,
    logoURI: 'https://raw.githubusercontent.com/0xlaozi/qidao/main/images/qi.png',
    website: 'https://www.mai.finance/',
    description:
      'QiDao is a self-sustaining, community-governed protocol that allows you to borrow stablecoins against your crypto assets used as collateral. Loans are paid out and repaid in MAI (stablecoin soft pegged to the USD).',
    documentation: 'https://docs.mai.finance/',
    bridge: 'layer-zero',
  },
  JARVIS: {
    name: 'Jarvis',
    symbol: 'JARVIS',
    oracleId: 'JARVIS',
    address: '0x777b2839832982B35213063d850848369390EE16',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://jarvis.network/',
    description:
      'Jarvis provides stablecoins (jFIATs) are over-collateralized, stable and liquid on-chain fiat currencies that anyone can use to gain exposure to many fiat currencies, access liquidity, credit, yield and other financial services.',
    documentation: 'https://jarvis.network/protocol',
    bridge: 'wormhole',
  },
  NPC: {
    name: 'Non-Playable Coin',
    symbol: 'NPC',
    oracleId: 'NPC',
    address: '0xB166E8B140D35D9D8226E40C09f757BAC5A4d87d',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.nonplayablecoin.io/',
    description:
      'Non-Playable Coin (NPC) is a memecoin actually backed by one of the most recognizable memes on the internet. Trade it as an NFT or as a memecoin, it doesn’t matter. It’s the first memecoin-NFT hybrid.',
    bridge: 'wormhole',
  },
  Mog: {
    name: 'Mog Coin',
    symbol: 'Mog',
    oracleId: 'Mog',
    address: '0x2Da56AcB9Ea78330f947bD57C54119Debda7AF71',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://mogcoin.xyz/',
    description:
      '$Mog is the internet’s first culture coin. Starting as a meme among friends in the summer of 2023 it has set itself apart from other projects through its open-ended memetic branding and unique content.',
    bridge: 'base-canonical',
  },
  HPC: {
    name: 'Happy Puppy Club',
    symbol: 'HPC',
    oracleId: 'HPC',
    address: '0x1f3BA804eFB9CFe17D595e7262CEA4782dbF6e4E',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.happypuppyclub.xyz/',
    description:
      'The Happy Puppy Club ($HPC) memecoin embodies the spirit of "we in the club, onchain".',
    bridge: 'native',
  },
  ROCK: {
    name: 'BLACK ROCK',
    symbol: 'ROCK',
    oracleId: 'ROCK',
    address: '0xEcE7B98bD817ee5B1F2f536dAf34D0B6af8Bb542',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.blackrockonbase.com/',
    description:
      "Just a black rock on Base. BLACK ROCK is NOT in any way associated with BlackRock, the financial institution with $9 trillion USD AUM. If you're looking for financial incentives, look elsewhere. It's literally just a black rock on Base.",
    documentation:
      'https://www.blackrockonbase.com/_files/ugd/74fb19_6213d516db434175ba850c5ae29213bf.pdf?index=true',
    bridge: 'native',
  },
  MTA: {
    name: 'Meta',
    symbol: 'MTA',
    oracleId: 'MTA',
    address: '0xba7D47f471ADD16875e765edEe0858C3413A56Fd',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://mstable.org/',
    description:
      'Meta Vault is a composable architecture for yield-bearing tokens. It combines, optimizes and allocates yield in a diversified manner.',
    bridge: 'base-canonical',
    documentation: 'https://docs.mstable.org/',
  },
  HOP: {
    name: 'HOP Protocol',
    symbol: 'HOP',
    oracleId: 'HOP',
    address: '0xc5102fE9359FD9a28f877a67E36B0F050d81a3CC',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://app.hop.exchange',
    description:
      'Hop Protocol is a blockchain bridge protocol that allows users to move tokens from one chain to another without having to wait for a challenge period',
    bridge: 'hop',
    documentation: 'https://docs.hop.exchange/',
  },
  NORMILIO: {
    name: 'Normilio',
    symbol: 'NORMILIO',
    oracleId: 'NORMILIO',
    address: '0xcDE90558fc317C69580DeeAF3eFC509428Df9080',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.normilio.com/',
    description:
      'A community driven project that aims to bring the normalest memecoin to the base.',
    bridge: 'native',
  },
  POOL: {
    name: 'PoolTogether',
    symbol: 'POOL',
    oracleId: 'POOL',
    address: '0xd652C5425aea2Afd5fb142e120FeCf79e18fafc3',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://pooltogether.com/',
    description: 'PoolTogether is a prize savings protocol, enabling you to win by saving.',
    documentation: 'https://docs.pooltogether.com/',
    bridge: 'base-canonical',
  },
  LUSD: {
    name: 'LUSD Stablecoin',
    symbol: 'LUSD',
    oracleId: 'LUSD',
    address: '0x368181499736d0c0CC614DBB145E2EC1AC86b8c6',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.liquity.org/',
    description:
      'Liquity is a decentralized borrowing protocol that allows you to draw interest-free loans against Ether used as collateral. Loans are paid out in LUSD (a USD pegged stablecoin) and need to maintain a minimum collateral ratio of 110%.',
    bridge: 'base-canonical',
    documentation: 'https://docs.liquity.org/',
  },
  GENOME: {
    name: 'GENOME',
    symbol: 'GENOME',
    oracleId: 'GENOME',
    address: '0x1db0c569ebb4a8b57AC01833B9792F526305e062',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://genomes.io/',
    description:
      'GENOME is the utility and governance token of the GenomesDAO. The token is used for value transfer in the Genomes.io platform as well as being used for all payments and actions across the GenomesDAO infrastructure.',
    bridge: 'base-canonical',
  },
  wrsETH: {
    name: 'rsETHWrapper',
    symbol: 'wrsETH',
    oracleId: 'wrsETH',
    address: '0xEDfa23602D0EC14714057867A78d01e94176BEA0',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://kelpdao.xyz/',
    description:
      'The rsETHWrapper contract serves as a standardized interface for rsETH tokens, which are Liquid Restaked Tokens (LRT) issued by Kelp DAO. Designed to offer liquidity to illiquid assets deposited into restaking platforms like EigenLayer, users can interact with these tokens seamlessly.',
    documentation: 'https://kelp.gitbook.io/kelp',
    bridge: 'stargate',
    risks: ['NO_TIMELOCK'],
  },
  weETH: {
    name: 'Wrapped eETH',
    symbol: 'weETH',
    oracleId: 'weETH',
    address: '0x04C0599Ae5A44757c0af6F9eC3b93da8976c150A',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://ether.fi/',
    description:
      'Stake ETH, get eETH - a natively restaked liquid staking token that fuels DeFi and decentralizes Ethereum.',
    documentation: 'https://etherfi.gitbook.io/etherfi',
    bridge: 'stargate',
    risks: ['NO_TIMELOCK'],
  },
  KLIMA: {
    name: 'Klima DAO',
    symbol: 'KLIMA',
    oracleId: 'KLIMA',
    address: '0xDCEFd8C8fCc492630B943ABcaB3429F12Ea9Fea2',
    chainId: 8453,
    decimals: 9,
    logoURI: '',
    website: 'https://www.klimadao.finance/',
    documentation: 'https://docs.klimadao.finance/',
    description:
      'KlimaDAO and its partners in the Klima ecosystem fosters the adoption of a new category of real world assets (RWA) on the blockchain: environmental assets like carbon credits.',
    bridge: 'axelar',
  },
  USDz: {
    name: 'Anzen USDz',
    symbol: 'USDz',
    oracleId: 'USDz',
    address: '0x04D5ddf5f3a8939889F11E97f8c4BB48317F1938',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description:
      'USDz is a stablecoin supported by a diversified portfolio of private credit assets. These assets are meticulously underwritten in collaboration with Percent, a US licensed broker-dealer. Percent has structured and serviced over $1.7B in credit deals since 2018. Anzen invests capital alongside institutional fiat investors. The yield from its credit portfolio offers a sustainable income stream, which supports staking rewards for on-chain USDz holders.',
    website: 'https://anzen.finance/',
    documentation: 'https://docs.anzen.finance/',
    bridge: 'layer-zero',
    risks: ['NO_TIMELOCK'],
  },
  GHST: {
    name: 'Aavegotchi GHST Token',
    symbol: 'GHST',
    oracleId: 'GHST',
    address: '0xcD2F22236DD9Dfe2356D7C543161D4d260FD9BcB',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.aavegotchi.com/',
    description:
      'Aavegotchis are crypto-collectibles living on the Ethereum blockchain, backed by the ERC721 standard used in popular blockchain games.',
    documentation: 'https://docs.aavegotchi.com/',
    bridge: 'base-canonical',
  },
  HBR: {
    name: 'Harbor Token',
    symbol: 'HBR',
    oracleId: 'HBR',
    address: '0x416bd43Bc76D496ff49923c20eCaf86b52Ab078d',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.harbor.market/',
    description:
      'HBR is the governance token of Harbor Market, a lending platform on BSC forked from Aave V2.',
    documentation: 'https://docs.harbor.market/harbor-market',
    bridge: 'wormhole',
  },
  USDT: {
    name: 'Tether USD',
    symbol: 'USDT',
    oracleId: 'USDT',
    address: '0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2',
    chainId: 8453,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://tether.to/',
    documentation: 'https://tether.to/en/how-it-works',
    description:
      'Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
    bridge: 'base-canonical',
  },
  UNI: {
    name: 'Uniswap',
    symbol: 'UNI',
    oracleId: 'UNI',
    address: '0xc3De830EA07524a0761646a6a4e4be0e114a3C83',
    chainId: 8453,
    decimals: 18,
    website: 'https://uniswap.org/',
    description:
      'UNI is the governance token for Uniswap. UNI was introduced on 16th September 2020 through a retrospective airdrop to users who have interacted with the protocol either by swapping tokens or by providing liquidity.',
    bridge: 'base-canonical',
    logoURI: '',
    documentation: 'https://docs.uniswap.org/concepts/governance/overview',
  },
  ZRO: {
    name: 'LayerZero',
    symbol: 'ZRO',
    oracleId: 'ZRO',
    address: '0x6985884C4392D348587B19cb9eAAf157F13271cd',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://layerzero.network/',
    documentation: 'https://docs.layerzero.network/v2',
    description:
      'ZRO is the native asset of the LayerZero protocol. LayerZero is an omnichain interoperability protocol that supports censorship-resistant messages and permissionless development through immutable smart contracts called Endpoints.',
    bridge: 'layer-zero',
  },
  NORMUS: {
    name: 'NORMUS',
    symbol: 'NORMUS',
    oracleId: 'NORMUS',
    address: '0xBA5EDE8d98ab88CEa9f0D69918ddE28Dc23c2553',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.basednormus.com/',
    documentation: 'https://www.basednormus.com/',
    description:
      'NORMUS is the governance token of the launchpad eNORMUSPUMP, a pump.fun fork on Base.',
    bridge: 'native',
  },
  jEUR: {
    name: 'Jarvis Synthetic Euro',
    symbol: 'jEUR',
    oracleId: 'jEUR',
    address: '0x4154550f4Db74Dc38d1FE98e1F3F28ed6daD627d',
    chainId: 8453,
    decimals: 18,
    website: 'https://jarvis.network/',
    description:
      'jEUR is a multi-collateralized synthetic token tracking the price of Euro. It is built on the top of UMA and Chainlink.',
    bridge: 'chainlink-ccip',
    logoURI: 'https://i.imgur.com/ZvP634G.png',
    documentation: 'https://learn.jarvis.network/',
  },
  sUSDz: {
    name: 'Staked USDz',
    symbol: 'sUSDz',
    oracleId: 'sUSDz',
    address: '0xe31eE12bDFDD0573D634124611e85338e2cBF0cF',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description:
      'sUSDz is a token that represents staked USDz. It accumulates value from USDz staking rewards sent by the protocol and backed by the protocols portfolio of private credit assets. sUSDz is a reward-bearing token, similar to sUSDe or sDAI. Unlike rebasing tokens such as stETH, the price of sUSDz increases over time.',
    website: 'https://anzen.finance/',
    documentation: 'https://docs.anzen.finance/',
    bridge: 'layer-zero',
    risks: ['NO_TIMELOCK'],
  },
  msUSD: {
    name: 'Metronome Synth USD',
    symbol: 'msUSD',
    oracleId: 'basemsUSD',
    address: '0x526728DBc96689597F85ae4cd716d4f7fCcBAE9d',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description:
      'msUSD represents Metronome Synth USD. Through the Metronome dApp, users are able to deposit crypto assets as collateral, and use that collateral to mint popular crypto synthetics.',
    website: 'https://metronome.io/',
    documentation: 'https://docs.metronome.io/',
    bridge: 'layer-zero',
    risks: ['NO_TIMELOCK'],
  },
  msETH: {
    name: 'Metronome Synth ETH',
    symbol: 'msETH',
    oracleId: 'msETH',
    address: '0x7Ba6F01772924a82D9626c126347A28299E98c98',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description:
      'msETH represents Metronome Synth ETH. Through the Metronome dApp, users are able to deposit crypto assets as collateral, and use that collateral to mint popular crypto synthetics.',
    website: 'https://metronome.io/',
    documentation: 'https://docs.metronome.io/',
    bridge: 'layer-zero',
    risks: ['NO_TIMELOCK'],
  },
  CHOMP: {
    name: 'ChompCoin',
    symbol: 'CHOMP',
    oracleId: 'CHOMP',
    address: '0xebfF2db643Cf955247339c8c6bCD8406308ca437',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description: 'CHOMP is the fiercest little fuzzball on Base. Meme coin on Base.',
    website: 'https://www.chompcoin.xyz/',
    bridge: 'native',
  },
  MIGGLES: {
    name: 'Mister Miggles',
    symbol: 'MIGGLES',
    oracleId: 'MIGGLES',
    address: '0xB1a03EdA10342529bBF8EB700a06C60441fEf25d',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description: 'Mr. Miggles, The Coinbase Cat Mascot. Meme coin on Base.',
    website: 'https://mrmigglesbase.com/',
    bridge: 'native',
  },
  mfer: {
    name: 'mfercoin',
    symbol: 'mfer',
    oracleId: 'mfer',
    address: '0xE3086852A4B125803C815a158249ae468A3254Ca',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description: 'Meme coin for every crypto mfer on Base.',
    website: 'https://linktr.ee/Mfercoin',
    bridge: 'native',
  },
  EURC: {
    name: 'EURO',
    symbol: 'EURC',
    oracleId: 'EURC',
    address: '0x60a3E35Cc302bFA44Cb288Bc5a4F316Fdb1adb42',
    chainId: 8453,
    decimals: 6,
    logoURI: '',
    description:
      'EURC is a euro-backed stablecoin that’s accessible globally on Avalanche, Ethereum, Base and Stellar. Similar to USDC, EURC is issued by Circle under a full-reserve model.',
    website: 'https://www.circle.com/en/eurc',
    bridge: 'native',
  },
  PEPE: {
    name: 'BasedPepe',
    symbol: 'PEPE',
    oracleId: 'basePEPE',
    address: '0x52b492a33E447Cdb854c7FC19F1e57E8BfA1777D',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description:
      'Based Pepe was launched quietly with no presale, zero taxes, locked LP, and a renounced contract – ensuring it remains a token for the people, forever. Meme coin on Base.',
    website: 'https://basedpepe.vip/',
    bridge: 'native',
  },
  COMP: {
    name: 'Compound',
    symbol: 'COMP',
    oracleId: 'COMP',
    address: '0x9e1028F5F1D5eDE59748FFceE5532509976840E0',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description:
      'COMP is the governance token of Compound, a decentralized protocol that enables supplying of crypto assets as collateral in order to borrow a base asset.',
    website: 'https://compound.finance/',
    documentation: 'https://docs.compound.finance/',
    bridge: 'base-canonical',
  },
  KEYCAT: {
    name: 'KeyBoard Cat',
    symbol: 'KEYCAT',
    oracleId: 'KEYCAT',
    address: '0x9a26F5433671751C3276a065f57e5a02D2817973',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description:
      'Keyboard Cat is an iconic internet meme featuring a cat named Fatso, who plays a keyboard with surprising musical talent! Meme coin on Base.',
    website: 'https://www.keyboardcat.fun/',
    documentation: 'https://en.wikipedia.org/wiki/Keyboard_Cat',
    bridge: 'native',
  },
  TOSHI: {
    name: 'Toshi',
    symbol: 'TOSHI',
    oracleId: 'TOSHI',
    address: '0xAC1Bd2486aAf3B5C0fc3Fd868558b082a531B2B4',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description:
      "TOSHI is a memecoin named after Coinbase co-founder Brian Armstrong's cat and the pseudonymous creator of Bitcoin, Satoshi Nakamoto. It serves as the face and mascot of the Base blockchain. Meme coin on Base.",
    website: 'https://www.toshithecat.com/',
    documentation: 'https://www.toshithecat.com/#FAQs',
    bridge: 'native',
  },
  OwO: {
    name: 'SoMon',
    symbol: 'OwO',
    oracleId: 'OwO',
    address: '0x5D559eA7bB2DAE4B694A079cb8328a2145Fd32f6',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description:
      'OwO is the community token of Social Monster! It is a way to redistribute the value created by the social app to the most engaged and loyal community members.',
    website: 'https://www.social.monster/',
    documentation: 'https://gitbook.social.monster/',
    bridge: 'native',
  },
  cbBTC: {
    name: 'Coinbase Wrapped WBTC',
    symbol: 'cbBTC',
    oracleId: 'cbBTC',
    address: '0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf',
    chainId: 8453,
    decimals: 8,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x1a35EE4640b0A3B87705B0A4B45D227Ba60Ca2ad.svg',
    website: 'https://www.coinbase.com/',
    description:
      'Coinbase Wrapped Bitcoin (cbBTC) is backed 1:1 with Bitcoin, custodied with Coinbase.',
    documentation: 'https://www.coinbase.com/blog/coinbase-wrapped-btc-cbbtc-is-now-live',
    bridge: 'native',
  },
  ETHFI: {
    name: 'ether.fi Governance Token',
    symbol: 'ETHFI',
    oracleId: 'baseETHFI',
    address: '0x6C240DDA6b5c336DF09A4D011139beAAa1eA2Aa2',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    website: 'https://www.ether.fi/',
    documentation: 'https://etherfi.gitbook.io/etherfi',
    bridge: 'wormhole',
    description:
      'ETHFI is the governance token of ether.fi, a restaking protocol on Ethereum. Token holders will have a say in the future of the protocol.',
    risks: ['NO_TIMELOCK'],
  },
  WIF: {
    name: 'dogwifhat',
    symbol: 'WIF',
    oracleId: 'WIF',
    address: '0x1fba65dE0a9cBD2D1DF82d141897042d36Bb6c86',
    chainId: 8453,
    decimals: 18,
    logoURI: '',
    description: 'LITERALLY JUST A DOG WIF A HAT',
    website: 'https://dogwifcoin.org/',
    bridge: 'layer-zero',
  },
} as const satisfies Record<string, Token>;
