export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped MOVR";
        readonly address: "0x98878B06940aE243284CA214f92Bb71a2b032B8A";
        readonly symbol: "WMOVR";
        readonly oracleId: "WMOVR";
        readonly decimals: 18;
        readonly chainId: 1285;
        readonly website: "https://moonbeam.network/networks/moonriver/";
        readonly description: "Moonriver is a companion network to Moonbeam and provides a permanently incentivized canary network. New code ships to Moonriver first, where it can be tested and verified under real economic conditions. Once proven, the same code ships to Moonbeam on Polkadot.";
        readonly bridge: "native";
        readonly documentation: "https://moonbeam.foundation/moonriver-token/";
    };
    readonly FEES: {
        readonly name: "Wrapped MOVR";
        readonly address: "0x98878B06940aE243284CA214f92Bb71a2b032B8A";
        readonly symbol: "WMOVR";
        readonly oracleId: "WMOVR";
        readonly decimals: 18;
        readonly chainId: 1285;
        readonly website: "https://moonbeam.network/networks/moonriver/";
        readonly description: "Moonriver is a companion network to Moonbeam and provides a permanently incentivized canary network. New code ships to Moonriver first, where it can be tested and verified under real economic conditions. Once proven, the same code ships to Moonbeam on Polkadot.";
        readonly bridge: "native";
        readonly documentation: "https://moonbeam.foundation/moonriver-token/";
    };
    readonly MOVR: {
        readonly name: "Wrapped MOVR";
        readonly address: "0x98878B06940aE243284CA214f92Bb71a2b032B8A";
        readonly symbol: "WMOVR";
        readonly oracleId: "WMOVR";
        readonly decimals: 18;
        readonly chainId: 1285;
        readonly website: "https://moonbeam.network/networks/moonriver/";
        readonly description: "Moonriver is a companion network to Moonbeam and provides a permanently incentivized canary network. New code ships to Moonriver first, where it can be tested and verified under real economic conditions. Once proven, the same code ships to Moonbeam on Polkadot.";
        readonly bridge: "native";
        readonly documentation: "https://moonbeam.foundation/moonriver-token/";
    };
    readonly WMOVR: {
        readonly name: "Wrapped MOVR";
        readonly address: "0x98878B06940aE243284CA214f92Bb71a2b032B8A";
        readonly symbol: "WMOVR";
        readonly oracleId: "WMOVR";
        readonly decimals: 18;
        readonly chainId: 1285;
        readonly website: "https://moonbeam.network/networks/moonriver/";
        readonly description: "Moonriver is a companion network to Moonbeam and provides a permanently incentivized canary network. New code ships to Moonriver first, where it can be tested and verified under real economic conditions. Once proven, the same code ships to Moonbeam on Polkadot.";
        readonly bridge: "native";
        readonly documentation: "https://moonbeam.foundation/moonriver-token/";
    };
    readonly WMOVR_SUSHI: {
        readonly name: "Wrapped MOVR on Sushiswap";
        readonly address: "0xf50225a84382c74CbdeA10b0c176f71fc3DE0C4d";
        readonly symbol: "WMOVR";
        readonly oracleId: "WMOVR";
        readonly decimals: 18;
        readonly chainId: 1285;
        readonly website: "https://moonbeam.network/networks/moonriver/";
        readonly description: "Moonriver is a companion network to Moonbeam and provides a permanently incentivized canary network. New code ships to Moonriver first, where it can be tested and verified under real economic conditions. Once proven, the same code ships to Moonbeam on Polkadot.";
    };
    readonly WNATIVE_SUSHI: {
        readonly name: "Wrapped MOVR on Sushiswap";
        readonly address: "0xf50225a84382c74CbdeA10b0c176f71fc3DE0C4d";
        readonly symbol: "WMOVR";
        readonly oracleId: "WMOVR";
        readonly decimals: 18;
        readonly chainId: 1285;
        readonly website: "https://moonbeam.network/networks/moonriver/";
        readonly description: "Moonriver is a companion network to Moonbeam and provides a permanently incentivized canary network. New code ships to Moonriver first, where it can be tested and verified under real economic conditions. Once proven, the same code ships to Moonbeam on Polkadot.";
    };
    readonly oldBIFI: {
        readonly chainId: 1285;
        readonly address: "0x173fd7434B8B50dF08e3298f173487ebDB35FD14";
        readonly decimals: 18;
        readonly name: "Beefy.Finance";
        readonly symbol: "oldBIFI";
        readonly oracleId: "oldBIFI";
        readonly website: "https://www.beefy.finance/";
        readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
        readonly documentation: "https://docs.beefy.finance/";
    };
    readonly MAI: {
        readonly name: "MAI";
        readonly symbol: "Mai Stablecoin";
        readonly oracleId: "mrMAI";
        readonly address: "0xFb2019DfD635a03cfFF624D210AEe6AF2B00fC2C";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.mai.finance/";
        readonly description: "MAI is a stablecoin collateralized by your crypto holdings. It's powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.";
        readonly documentation: "https://docs.mai.finance/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly DOGE: {
        readonly name: "Doge Token";
        readonly symbol: "DOGE";
        readonly oracleId: "DOGE";
        readonly address: "0xb668Cd490a4421F993f93be2819A922DBbB32804";
        readonly chainId: 1285;
        readonly decimals: 8;
        readonly website: "https://dogecoin.com/";
        readonly description: "Dogecoin is an open source peer-to-peer digital currency, favored by Shiba Inus worldwide.";
        readonly tags: readonly ["MEMECOIN"];
    };
    readonly XRP: {
        readonly name: "XRP Token";
        readonly symbol: "XRP";
        readonly oracleId: "XRP";
        readonly address: "0x9D5bc9B873AeD984e2B6A64d4792249D68BbA2Fe";
        readonly chainId: 1285;
        readonly decimals: 6;
        readonly website: "https://ripple.com/xrp/";
        readonly description: "XRP is a digital asset built for payments. It is the native digital asset on the XRP Ledger—an open-source, permissionless and decentralized blockchain technology that can settle transactions in 3-5 seconds.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly WAN: {
        readonly name: "WAN Token";
        readonly symbol: "WAN";
        readonly oracleId: "WAN";
        readonly address: "0x41562ae242d194247389152aCAa7a9397136b09F";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.wanchain.org/";
        readonly description: "Wanchain is a distributed ledger that allows for cross-chain transactions and the interoperability of multiple chains. Although Wanchain facilitates transactions between blockchains, it is also a stand-alone blockchain that runs autonomously.";
    };
    readonly FINN: {
        readonly name: "FINN Token";
        readonly symbol: "FINN";
        readonly oracleId: "FINN";
        readonly address: "0x9A92B5EBf1F6F6f7d93696FCD44e5Cf75035A756";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.huckleberry.finance/#/swap";
        readonly description: "Huckleberry is a community driven AMM crosschain DEX built on Moonriver.";
        readonly bridge: "native";
        readonly documentation: "https://huckleberry.gitbook.io/introduction/the-little-things/tokenomics";
    };
    readonly DOTm: {
        readonly name: "Polkadot Token";
        readonly symbol: "DOTm";
        readonly oracleId: "DOTm";
        readonly address: "0x15B9CA9659F5dfF2b7d35a98dd0790a3CBb3D445";
        readonly chainId: 1285;
        readonly decimals: 10;
        readonly website: "https://polkadot.network/";
        readonly description: "Polkadot is an open source, blockchain-based distributed computing platform that enables the blockchains built on top of it, known as \"parachains\", to execute atomic inter-chain transactions between themselves in a trust-minimized way, thereby creating an interconnected internet of blockchains.";
    };
    readonly USDCm: {
        readonly name: "USD Coin";
        readonly symbol: "USDCm";
        readonly oracleId: "USDCm";
        readonly address: "0x748134b5F553F2bcBD78c6826De99a70274bDEb3";
        readonly chainId: 1285;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://developers.circle.com/docs";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly SOLAR: {
        readonly name: "SolarBeam Token";
        readonly symbol: "SOLAR";
        readonly oracleId: "SOLAR";
        readonly address: "0x6bD193Ee6D2104F14F94E2cA6efefae561A4334B";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://app.solarbeam.io/exchange/swap";
        readonly description: "Solarbeam is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Moonriver Network. We are currently the leading DEX on the network. The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.";
        readonly bridge: "native";
        readonly documentation: "https://docs.solarbeam.io/tokenomics";
    };
    readonly RIB: {
        readonly name: "RiverBoat";
        readonly symbol: "RIB";
        readonly oracleId: "RIB";
        readonly address: "0xbD90A6125a84E5C512129D622a75CDDE176aDE5E";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://seascape.finance/#/swap";
        readonly description: "Scapes are Seascapes original series of NFTs. Unlike many of their predecessors, they are designed to be true financial assets. Players can mint, stake, and burn them in exchange for Crowns or other rewards.";
    };
    readonly USDC: {
        readonly name: "USD Coin";
        readonly symbol: "USDC";
        readonly oracleId: "mrmultiUSDC";
        readonly address: "0xE3F5a90F9cb311505cd691a46596599aA1A0AD7D";
        readonly chainId: 1285;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://developers.circle.com/docs";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly bridge: "multichain";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly DAI: {
        readonly name: "Dai Stablecoin";
        readonly symbol: "DAI";
        readonly oracleId: "mrmultiDAI";
        readonly address: "0x80A16016cC4A2E6a2CACA8a4a498b1699fF0f844";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://makerdao.com/en/";
        readonly description: "Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly BUSD: {
        readonly name: "Binance-Peg BUSD Token";
        readonly symbol: "BUSD";
        readonly oracleId: "mrmultiBUSD";
        readonly address: "0x5D9ab5522c64E1F6ef5e3627ECCc093f56167818";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/en/busd";
        readonly description: "Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos). BUSD is approved and regulated by the New York State Department of Financial Services (NYDFS). The BUSD Monthly Audit Report can be viewed from the official website.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly ETH: {
        readonly name: "Ethereum";
        readonly symbol: "ETH";
        readonly oracleId: "mrmultiETH";
        readonly address: "0x639A647fbe20b6c8ac19E48E2de44ea792c62c5C";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "multichain";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly BNB: {
        readonly name: "Binance";
        readonly symbol: "BNB";
        readonly oracleId: "mrmultiBNB";
        readonly address: "0x2bF9b864cdc97b08B6D79ad4663e71B8aB65c45c";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/";
        readonly description: "Binance Coin (BNB) is an exchange-based token created and issued by the cryptocurrency exchange Binance. Initially created on the Ethereum blockchain as an ERC-20 token in July 2017, BNB was migrated over to Binance Chain in February 2019 and became the native coin of the Binance Chain.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly WBTC: {
        readonly name: "Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "mrmultiWBTC";
        readonly address: "0x6aB6d61428fde76768D7b45D8BFeec19c6eF91A8";
        readonly chainId: 1285;
        readonly decimals: 8;
        readonly website: "https://wbtc.network/";
        readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly USDT: {
        readonly name: "Tether USD";
        readonly symbol: "USDT";
        readonly oracleId: "mrmultiUSDT";
        readonly address: "0xB44a9B6905aF7c801311e8F4E76932ee959c663C";
        readonly chainId: 1285;
        readonly decimals: 6;
        readonly website: "https://tether.to/";
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly MATIC: {
        readonly name: "Matic Token";
        readonly symbol: "MATIC";
        readonly oracleId: "MATIC";
        readonly address: "0x682F81e57EAa716504090C3ECBa8595fB54561D8";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://polygon.technology/";
        readonly description: "The MATIC token serves dual purposes: securing the Polygon network via staking and being used for the payment of transaction fees.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly AVAX: {
        readonly name: "Avalanche Token";
        readonly symbol: "AVAX";
        readonly oracleId: "AVAX";
        readonly address: "0x14a0243C333A5b238143068dC3A7323Ba4C30ECB";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.avalabs.org/";
        readonly description: "Avalanche is the fastest smart contracts platform in the blockchain industry, as measured by time-to-finality, and has the most validators securing its activity of any proof-of-stake protocol.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly RELAY: {
        readonly name: "Relay Token";
        readonly symbol: "RELAY";
        readonly oracleId: "RELAY";
        readonly address: "0xAd7F1844696652ddA7959a49063BfFccafafEfe7";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.relaychain.com/";
        readonly description: "Cross-chain token transfers on the worlds top blockchains using Relays fast, secure chain bridge";
    };
    readonly miMatic: {
        readonly name: "MAI";
        readonly symbol: "miMatic";
        readonly oracleId: "mrmiMatic";
        readonly address: "0x7f5a79576620C046a293F54FFCdbd8f2468174F1";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.mai.finance/";
        readonly description: "MAI is a stablecoin collateralized by your crypto holdings. It's powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.";
        readonly documentation: "https://docs.mai.finance/";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly FTM: {
        readonly name: "Fantom Token";
        readonly symbol: "FTM";
        readonly oracleId: "FTM";
        readonly address: "0xaD12daB5959f30b9fF3c2d6709f53C335dC39908";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://fantom.foundation/defi/?__cf_chl_jschl_tk__=pmd_vfkYw1Z8PZor5oxGKrd9bxYd66paY0bLiQmy1dKOLpY-1633331752-0-gqNtZGzNAdCjcnBszQlR";
        readonly description: "Fantom offers the first DeFi stack built on an aBFT consensus. It’s much faster, cheaper, and more reliable and secure than its predecessors.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly MIM: {
        readonly name: "Magic Internet Money";
        readonly symbol: "MIM";
        readonly oracleId: "mrmultiMIM";
        readonly address: "0x0caE51e1032e8461f4806e26332c030E34De3aDb";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://abracadabra.money/";
        readonly description: "You, the Spellcaster, can provide collateral in the form of various interest bearing crypto assets such as yvYFI, yvUSDT, yvUSDC, xSUSHI and more. With this, you can borrow magic internet money (MIM) which is a stable coin that you can swap for any other traditional stable coin.";
        readonly documentation: "https://docs.abracadabra.money/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly PETS: {
        readonly name: "PETS Token";
        readonly symbol: "PETS";
        readonly oracleId: "PETS";
        readonly address: "0x1e0F2A75Be02c025Bd84177765F89200c04337Da";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.polkapet.world/";
        readonly description: "An immersive NFT collection created in partnership with the biggest and best Polkadot projects";
    };
    readonly SUSHI: {
        readonly name: "SUSHI";
        readonly address: "0xf390830DF829cf22c53c8840554B98eafC5dCBc2";
        readonly symbol: "SUSHI";
        readonly oracleId: "SUSHI";
        readonly decimals: 18;
        readonly chainId: 1285;
        readonly website: "https://sushi.com/";
        readonly description: "Sushi is the home of DeFi. Their community is building a comprehensive, decentralized trading platform for the future of finance. Swap, earn, stack yields, lend, borrow, leverage all on one decentralized, community driven platform.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly mSUSHI: {
        readonly symbol: "mSUSHI";
        readonly name: "SUSHI";
        readonly address: "0xf390830DF829cf22c53c8840554B98eafC5dCBc2";
        readonly oracleId: "SUSHI";
        readonly decimals: 18;
        readonly chainId: 1285;
        readonly website: "https://sushi.com/";
        readonly description: "Sushi is the home of DeFi. Their community is building a comprehensive, decentralized trading platform for the future of finance. Swap, earn, stack yields, lend, borrow, leverage all on one decentralized, community driven platform.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly anyFRAX: {
        readonly name: "FRAX";
        readonly symbol: "FRAX";
        readonly oracleId: "mrmultiFRAX";
        readonly address: "0x965f84D915a9eFa2dD81b653e3AE736555d945f4";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://frax.finance/";
        readonly description: "The Frax Protocol introduced the world to the concept of a cryptocurrency being partially backed by collateral and partially stabilized algorithmically.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly FRAX: {
        readonly name: "FRAX";
        readonly symbol: "FRAX";
        readonly oracleId: "FRAX";
        readonly address: "0x1A93B23281CC1CDE4C4741353F3064709A16197d";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://frax.finance/";
        readonly description: "The Frax Protocol introduced the world to the concept of a cryptocurrency being partially backed by collateral and partially stabilized algorithmically.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly aROME: {
        readonly name: "Alpha Rome";
        readonly symbol: "aROME";
        readonly oracleId: "aROME";
        readonly address: "0x3D2D044E8C6dAd46b4F7896418d3d4DFaAD902bE";
        readonly chainId: 1285;
        readonly decimals: 9;
        readonly website: "https://romedao.finance/";
        readonly description: "RomeDAO is a community project with no central team. It’s a community project built by and for the community. This means it’s up to the community contributors to build a prospering Rome.";
    };
    readonly ROME: {
        readonly name: "Rome";
        readonly symbol: "ROME";
        readonly oracleId: "ROME";
        readonly address: "0x4a436073552044D5f2f49B176853ad3Ad473d9d6";
        readonly chainId: 1285;
        readonly decimals: 9;
        readonly website: "https://romedao.finance/";
        readonly description: "RomeDAO is a community project with no central team. It’s a community project built by and for the community. This means it’s up to the community contributors to build a prospering Rome.";
    };
    readonly BNBbsc: {
        readonly name: "Binance";
        readonly symbol: "BNBbsc";
        readonly oracleId: "BNBbsc";
        readonly address: "0x868892CCcEdbfF0B028F3b3595205Ea91b99376B";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/";
        readonly description: "BNB from BSC wrapped by passport.meter.io";
    };
    readonly WBTCeth: {
        readonly name: "Wrapped Bitcoin";
        readonly symbol: "WBTCeth";
        readonly oracleId: "WBTCeth";
        readonly address: "0xE6a991Ffa8CfE62B0bf6BF72959A3d4f11B2E0f5";
        readonly chainId: 1285;
        readonly decimals: 8;
        readonly website: "https://passport.meter.io/transfer#/ ";
        readonly description: "WBTC from Etherem wrapped by passport.meter.io";
    };
    readonly xcKSM: {
        readonly name: "xcKSM";
        readonly symbol: "xcKSM";
        readonly oracleId: "xcKSM";
        readonly address: "0xFfFFfFff1FcaCBd218EDc0EbA20Fc2308C778080";
        readonly chainId: 1285;
        readonly decimals: 12;
        readonly website: "https://kusama.network/";
        readonly description: "xcKSM is the Moonriver bridged verison of KSM from Kusama. Kusama is an experimental and development environment for features that will eventually be deployed to Polkadot.";
        readonly bridge: "kusama";
        readonly documentation: "https://guide.kusama.network/docs/kusama-getting-started";
    };
    readonly xcRMRK: {
        readonly name: "xcRMRK";
        readonly symbol: "xcRMRK";
        readonly oracleId: "xcRMRK";
        readonly address: "0xffffffFF893264794d9d57E1E0E21E0042aF5A0A";
        readonly chainId: 1285;
        readonly decimals: 10;
        readonly website: "https://www.rmrk.app/";
        readonly description: "ETERNALLY liquid. FORWARD compatible.Nested, conditional, & Multi-resourced NFTs.";
    };
    readonly stKSM: {
        readonly name: "stKSM";
        readonly symbol: "stKSM";
        readonly oracleId: "stKSM";
        readonly address: "0xFfc7780C34B450d917d557E728f033033CB4fA8C";
        readonly chainId: 1285;
        readonly decimals: 12;
        readonly website: "https://kusama.lido.fi/";
        readonly description: "Lido for Moonriver is a liquid staking solution for KSM backed by industry-leading staking providers.";
    };
    readonly xcKBTC: {
        readonly name: "Kintsugi Wrapped BTC";
        readonly symbol: "xcKBTC";
        readonly oracleId: "xcKBTC";
        readonly address: "0xFFFfFfFfF6E528AD57184579beeE00c5d5e646F0";
        readonly chainId: 1285;
        readonly decimals: 8;
        readonly website: "https://kusama.network/";
        readonly description: "xckBTC is the Moonriver bridged verison of kBTC. kBTC is an overcollaterized Bitcoin stablecoin asset on Kusama.";
    };
    readonly wstKSM: {
        readonly name: "Wrapped Staked KSM";
        readonly symbol: "wstKSM";
        readonly oracleId: "wstKSM";
        readonly address: "0x3bfd113ad0329a7994a681236323fb16E16790e3";
        readonly chainId: 1285;
        readonly decimals: 12;
        readonly website: "https://kusama.lido.fi/";
        readonly description: "Staked KSM (stKSM) is a liquid staking solution for KSM backed by industry-leading staking providers. stKSM rebases daily to receive rewards, wrapping stKSM for wstKSM will stop the rebasing mechanism, and will allow users to continue accruing staking rewards.";
        readonly bridge: "kusama";
    };
    readonly 'oldBIFI-WMOVR LP': {
        readonly name: "oldBIFI-WMOVR LP";
        readonly symbol: "oldBIFI-WMOVR LP";
        readonly address: "0xaC726ee53edFAe5f8f4C2c0d611Fd71D58E743bA";
        readonly chainId: 1285;
        readonly decimals: 18;
        readonly website: "https://app.beefy.com/";
        readonly oracleId: "sushi-mr-bifi-wmovr";
        readonly oracle: "lps";
    };
};
