const SiloV2IncentivesController = [
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_notifier', type: 'address' },
      { internalType: 'address', name: '_siloShareToken', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'ClaimerUnauthorized', type: 'error' },
  { inputs: [], name: 'DifferentRewardsTokens', type: 'error' },
  { inputs: [], name: 'EmptyShareToken', type: 'error' },
  { inputs: [], name: 'IncentivesProgramAlreadyExists', type: 'error' },
  { inputs: [], name: 'IncentivesProgramNotFound', type: 'error' },
  { inputs: [], name: 'IndexOverflowAtEmissionsPerSecond', type: 'error' },
  { inputs: [], name: 'InvalidConfiguration', type: 'error' },
  { inputs: [], name: 'InvalidDistributionEnd', type: 'error' },
  { inputs: [], name: 'InvalidIncentivesProgramName', type: 'error' },
  { inputs: [], name: 'InvalidRewardToken', type: 'error' },
  { inputs: [], name: 'InvalidToAddress', type: 'error' },
  { inputs: [], name: 'InvalidUserAddress', type: 'error' },
  { inputs: [], name: 'OnlyNotifier', type: 'error' },
  { inputs: [], name: 'OnlyNotifierOrOwner', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'value', type: 'uint256' },
      { internalType: 'uint256', name: 'length', type: 'uint256' },
    ],
    name: 'StringsInsufficientHexLength',
    type: 'error',
  },
  { inputs: [], name: 'TooLongProgramName', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'asset', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'emission', type: 'uint256' },
    ],
    name: 'AssetConfigUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'asset', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'index', type: 'uint256' },
    ],
    name: 'AssetIndexUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'address', name: 'claimer', type: 'address' },
    ],
    name: 'ClaimerSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'string', name: 'incentivesProgram', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'newDistributionEnd', type: 'uint256' },
    ],
    name: 'DistributionEndUpdated',
    type: 'event',
  },
  { anonymous: false, inputs: [], name: 'GaugeKilled', type: 'event' },
  { anonymous: false, inputs: [], name: 'GaugeUnKilled', type: 'event' },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'string', name: 'name', type: 'string' }],
    name: 'IncentivesProgramCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'string', name: 'incentivesProgram', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'newIndex', type: 'uint256' },
    ],
    name: 'IncentivesProgramIndexUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'string', name: 'name', type: 'string' }],
    name: 'IncentivesProgramUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'address', name: 'rewardToken', type: 'address' },
      { indexed: true, internalType: 'string', name: 'programName', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'RewardsAccrued',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      { indexed: true, internalType: 'address', name: 'rewardToken', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'programId', type: 'bytes32' },
      { indexed: false, internalType: 'address', name: 'claimer', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'RewardsClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: false, internalType: 'string', name: 'incentivesProgram', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'newIndex', type: 'uint256' },
    ],
    name: 'UserIndexUpdated',
    type: 'event',
  },
  {
    inputs: [],
    name: 'NOTIFIER',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'PRECISION',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SHARE_TOKEN',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'TEN_POW_PRECISION',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'acceptOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'address', name: '_sender', type: 'address' },
      { internalType: 'uint256', name: '_senderBalance', type: 'uint256' },
      { internalType: 'address', name: '_recipient', type: 'address' },
      { internalType: 'uint256', name: '_recipientBalance', type: 'uint256' },
      { internalType: 'uint256', name: '_totalSupply', type: 'uint256' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'afterTokenTransfer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'string[]', name: '_programNames', type: 'string[]' },
    ],
    name: 'claimRewards',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'bytes32', name: 'programId', type: 'bytes32' },
          { internalType: 'address', name: 'rewardToken', type: 'address' },
        ],
        internalType: 'struct IDistributionManager.AccruedRewards[]',
        name: 'accruedRewards',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_to', type: 'address' }],
    name: 'claimRewards',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'bytes32', name: 'programId', type: 'bytes32' },
          { internalType: 'address', name: 'rewardToken', type: 'address' },
        ],
        internalType: 'struct IDistributionManager.AccruedRewards[]',
        name: 'accruedRewards',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'string[]', name: '_programNames', type: 'string[]' },
    ],
    name: 'claimRewardsOnBehalf',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'bytes32', name: 'programId', type: 'bytes32' },
          { internalType: 'address', name: 'rewardToken', type: 'address' },
        ],
        internalType: 'struct IDistributionManager.AccruedRewards[]',
        name: 'accruedRewards',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'address', name: 'rewardToken', type: 'address' },
          { internalType: 'uint104', name: 'emissionPerSecond', type: 'uint104' },
          { internalType: 'uint40', name: 'distributionEnd', type: 'uint40' },
        ],
        internalType: 'struct DistributionTypes.IncentivesProgramCreationInput',
        name: '_incentivesProgramInput',
        type: 'tuple',
      },
    ],
    name: 'createIncentivesProgram',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAllProgramsNames',
    outputs: [{ internalType: 'string[]', name: 'programsNames', type: 'string[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getClaimer',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_incentivesProgram', type: 'string' }],
    name: 'getDistributionEnd',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_programName', type: 'string' }],
    name: 'getProgramId',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '_programId', type: 'bytes32' }],
    name: 'getProgramName',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'string[]', name: '_programNames', type: 'string[]' },
    ],
    name: 'getRewardsBalance',
    outputs: [{ internalType: 'uint256', name: 'unclaimedRewards', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'string', name: '_programName', type: 'string' },
    ],
    name: 'getRewardsBalance',
    outputs: [{ internalType: 'uint256', name: 'unclaimedRewards', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'string', name: '_incentivesProgram', type: 'string' },
    ],
    name: 'getUserData',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'string', name: '_programName', type: 'string' },
    ],
    name: 'getUserUnclaimedRewards',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_tokenToDistribute', type: 'address' },
      { internalType: 'uint104', name: '_amount', type: 'uint104' },
    ],
    name: 'immediateDistribution',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_incentivesProgram', type: 'string' }],
    name: 'incentivesProgram',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'index', type: 'uint256' },
          { internalType: 'address', name: 'rewardToken', type: 'address' },
          { internalType: 'uint104', name: 'emissionPerSecond', type: 'uint104' },
          { internalType: 'uint40', name: 'lastUpdateTimestamp', type: 'uint40' },
          { internalType: 'uint40', name: 'distributionEnd', type: 'uint40' },
        ],
        internalType: 'struct IDistributionManager.IncentiveProgramDetails',
        name: 'details',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'incentivesPrograms',
    outputs: [
      { internalType: 'uint256', name: 'index', type: 'uint256' },
      { internalType: 'address', name: 'rewardToken', type: 'address' },
      { internalType: 'uint104', name: 'emissionPerSecond', type: 'uint104' },
      { internalType: 'uint40', name: 'lastUpdateTimestamp', type: 'uint40' },
      { internalType: 'uint40', name: 'distributionEnd', type: 'uint40' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'is_killed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'killGauge', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pendingOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'address', name: '_caller', type: 'address' },
    ],
    name: 'setClaimer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_incentivesProgram', type: 'string' },
      { internalType: 'uint40', name: '_distributionEnd', type: 'uint40' },
    ],
    name: 'setDistributionEnd',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'share_token',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'unkillGauge', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'string', name: '_incentivesProgram', type: 'string' },
      { internalType: 'uint40', name: '_distributionEnd', type: 'uint40' },
      { internalType: 'uint104', name: '_emissionPerSecond', type: 'uint104' },
    ],
    name: 'updateIncentivesProgram',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
export default SiloV2IncentivesController;
