import type { Token } from '../../../types/token.js';

const BERA = {
  name: 'Wrapped Bera',
  address: '0x6969696969696969696969696969696969696969',
  symbol: 'WBERA',
  oracleId: 'WBERA',
  decimals: 18,
  chainId: 80094,
  website: 'https://www.berachainchain.com/',
  description: 'Learn, integrate, and build on a new modular EVM with Berachain.',
  bridge: 'berachain-canonical',
  logoURI: '',
  documentation: 'https://docs.berachainchain.com/',
} as const satisfies Token;

export const tokens = {
  BERA,
  WBERA: BERA,
  WNATIVE: BERA,
  WETH: {
    name: 'WETH',
    symbol: 'WETH',
    oracleId: 'WETH',
    address: '0x2F6F07CDcf3588944Bf4C42aC74ff24bF56e7590',
    chainId: 80094,
    decimals: 18,
    website: 'https://weth.io/',
    description: 'Ether or ETH is the native currency built on the Ethereum blockchain.',
    logoURI: 'https://arbiscan.io/token/images/weth_28.png',
    documentation: 'https://ethereum.org/en/developers/docs/',
    bridge: 'layerzero',
  },
  HONEY: {
    name: 'Honey',
    symbol: 'HONEY',
    oracleId: 'HONEY',
    address: '0xFCBD14DC51f0A4d49d5E53C2E0950e0bC26d0Dce',
    chainId: 80094,
    decimals: 18,
    logoURI: '',
    website: 'https://bartio.honey.berachain.com/',
    description:
      'Turn your favorite stables into Honey. Leverage liquidity incentives on various platforms.',
    documentation: 'https://docs.berachain.com/',
    bridge: 'native',
  },
  USDCe: {
    name: 'Bridged USDC (Stargate)',
    symbol: 'USDCe',
    oracleId: 'USDCe',
    address: '0x549943e04f40284185054145c6E4e9568C1D3241',
    chainId: 80094,
    decimals: 6,
    logoURI: '',
    website: 'https://www.centre.io/',
    description:
      'USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
    documentation: '',
    bridge: 'layerzero',
  },
  WBTC: {
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    oracleId: 'WBTC',
    address: '0x0555E30da8f98308EdB960aa94C0Db47230d2B9c',
    chainId: 80094,
    decimals: 8,
    logoURI: '',
    website: 'https://wbtc.network/',
    description:
      'Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.',
    documentation: '',
    bridge: 'layerzero',
  },
} as const satisfies Record<string, Token>;
