export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped Ether";
        readonly address: "0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 59144;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "linea-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly FEES: {
        readonly name: "Wrapped Ether";
        readonly address: "0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 59144;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "linea-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly ETH: {
        readonly name: "Wrapped Ether";
        readonly address: "0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 59144;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "linea-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly WETH: {
        readonly name: "Wrapped Ether";
        readonly address: "0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 59144;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "linea-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly USDC: {
        readonly name: "USD Coin";
        readonly symbol: "USDC";
        readonly oracleId: "USDC";
        readonly address: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff";
        readonly chainId: 59144;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://developers.circle.com/docs";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly bridge: "linea-canonical";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly USDT: {
        readonly name: "USDT";
        readonly symbol: "USDT";
        readonly oracleId: "USDT";
        readonly address: "0xA219439258ca9da29E9Cc4cE5596924745e12B93";
        readonly chainId: 59144;
        readonly decimals: 6;
        readonly website: "https://tether.to/";
        readonly documentation: "https://tether.to/en/how-it-works";
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly bridge: "linea-canonical";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly DAI: {
        readonly name: "Dai Stablecoin";
        readonly symbol: "DAI";
        readonly oracleId: "DAI";
        readonly address: "0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://makerdao.com/";
        readonly documentation: "https://docs.makerdao.com/";
        readonly description: "Multi-Collateral Dai, brings a lot of new and exciting features, such as support for new CDP collateral types and Dai Savings Rate.";
        readonly bridge: "linea-canonical";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly WBTC: {
        readonly name: "Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "WBTC";
        readonly address: "0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4";
        readonly chainId: 59144;
        readonly decimals: 8;
        readonly website: "https://wbtc.network/";
        readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
        readonly bridge: "linea-canonical";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly wstETH: {
        readonly name: "Lido Wrapped Staked ETH";
        readonly symbol: "wstETH";
        readonly oracleId: "wstETH";
        readonly address: "0xB5beDd42000b71FddE22D3eE8a79Bd49A568fC8F";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://lido.fi/";
        readonly documentation: "https://docs.lido.fi/";
        readonly description: "Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.";
        readonly bridge: "linea-canonical";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly MENDI: {
        readonly name: "MENDI";
        readonly symbol: "MENDI";
        readonly oracleId: "MENDI";
        readonly address: "0x43E8809ea748EFf3204ee01F08872F063e44065f";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://mendi.finance/";
        readonly description: "MENDI is the reward token of Mendi Finance, a lending/borrowing protocol on Linea forked from Compound V2.";
        readonly documentation: "https://docs.mendi.finance/";
        readonly bridge: "native";
    };
    readonly LYNX: {
        readonly name: "Lynex Token";
        readonly symbol: "LYNX";
        readonly oracleId: "LYNX";
        readonly address: "0x1a51b19CE03dbE0Cb44C1528E34a7EDD7771E9Af";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.lynex.fi/";
        readonly description: "Lynex democratizes sophisticated liquidity strategies, seamlessly connecting everyday traders with expert-level capabilities. Our platform features a competitive ecosystem of Automated Liquidity Managers (ALMs) and strategists, all striving to optimize returns, minimize risks like impermanent loss, and boost overall efficiency for every user.";
        readonly documentation: "https://lynex.gitbook.io/lynex-docs/protocol-overview/about-lynex";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly oLYNX: {
        readonly name: "Option LYNX Token";
        readonly symbol: "oLYNX";
        readonly oracleId: "oLYNX";
        readonly address: "0x63349BA5E1F71252eCD56E8F950D1A518B400b60";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.lynex.fi/";
        readonly description: "Lynex democratizes sophisticated liquidity strategies, seamlessly connecting everyday traders with expert-level capabilities. Our platform features a competitive ecosystem of Automated Liquidity Managers (ALMs) and strategists, all striving to optimize returns, minimize risks like impermanent loss, and boost overall efficiency for every user.";
        readonly documentation: "https://lynex.gitbook.io/lynex-docs/protocol-overview/about-lynex";
        readonly bridge: "native";
    };
    readonly MAI: {
        readonly name: "Mai Stablecoin";
        readonly symbol: "MAI";
        readonly oracleId: "lMAI";
        readonly address: "0xf3B001D64C656e30a62fbaacA003B1336b4ce12A";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.mai.finance/";
        readonly description: "MAI is a stablecoin collateralized by your crypto holdings. It's powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.";
        readonly documentation: "https://docs.mai.finance/";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly DUSD: {
        readonly name: "Davos.xyz USD";
        readonly symbol: "DUSD";
        readonly oracleId: "DUSD";
        readonly address: "0xA88B54E6b76Fb97CdB8eCAE868f1458e18a953F4";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://davos.xyz/";
        readonly description: "The Davos Protocol is an innovative collateralised debt position (CDP) protocol designed to facilitate the seamless minting of DUSD, an inflation-proof omnichain stablecoin, by leveraging Liquid Staking Tokens (LSTs). The protocol aims to address the challenges faced by traditional CDPs in decentralised finance (DeFi) by incorporating an unbiased monetary policy and fair borrowing rates, thereby enhancing user protection and promoting broader DeFi adoption. ";
        readonly documentation: "https://davos.xyz/assets/davos_whitepaper.pdf";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly 'USD+': {
        readonly name: "USD+";
        readonly symbol: "USD+";
        readonly oracleId: "lineaUSD+";
        readonly address: "0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376";
        readonly chainId: 59144;
        readonly decimals: 6;
        readonly website: "https://overnight.fi/";
        readonly description: "USD+ is USDC that pays you yield daily via rebase.  It is 100% collateralized with assets immediately convertible into USDC.  Yield is generated via strategies such as lending and stable-to-stable pools. Initial strategies include Aave, Rubicon, and Pika.";
        readonly bridge: "native";
        readonly documentation: "https://docs.overnight.fi/";
        readonly tags: readonly ["CURATED", "STABLECOIN"];
    };
    readonly 'USDT+': {
        readonly name: "USDT+";
        readonly symbol: "USDT+";
        readonly oracleId: "lineaUSDT+";
        readonly address: "0x1E1F509963A6D33e169D9497b11c7DbFe73B7F13";
        readonly chainId: 59144;
        readonly decimals: 6;
        readonly website: "https://overnight.fi/";
        readonly description: "USDT+ is USDT that pays you yield daily via rebase.  It is 100% collateralized with assets immediately convertible into USDT.  Yield is generated via strategies such as lending and stable-to-stable pools. Initial strategies include Aave, Rubicon, and Pika.";
        readonly bridge: "native";
        readonly documentation: "https://docs.overnight.fi/";
        readonly tags: readonly ["CURATED"];
    };
    readonly ezETH: {
        readonly name: "Renzo Restaked ETH Token";
        readonly symbol: "ezETH";
        readonly oracleId: "ezETH";
        readonly address: "0x2416092f143378750bb29b79eD961ab195CcEea5";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.renzoprotocol.com/";
        readonly description: "Renzo ezETH is a Liquid Restaking Token (LRT) and Strategy Manager for EigenLayer. It is the interface to the EigenLayer ecosystem securing Actively Validated Services (AVSs) and offering a higher yield than ETH staking.";
        readonly documentation: "https://docs.renzoprotocol.com/docs/";
        readonly bridge: "connext";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly STONE: {
        readonly name: "StakeStone Ether";
        readonly symbol: "STONE";
        readonly oracleId: "STONE";
        readonly address: "0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://stakestone.io/";
        readonly description: "StakeStone is an omni-chain LST (Liquid Staking Token) protocol aiming to bring native staking yields and liquidity to Layer 2s in a decentralized manner.";
        readonly documentation: "https://docs.stakestone.io/stakestone";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly NILE: {
        readonly name: "NILE Token";
        readonly symbol: "NILE";
        readonly oracleId: "NILE";
        readonly address: "0xAAAac83751090C6ea42379626435f805DDF54DC8";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.thenile.exchange/swap";
        readonly description: "NILE is a next-gen liquidity protocol optimizing for high-frequency LPs and Layer 2 cost structures, inheriting efficiency from RAMSES on Arbitrum.";
        readonly documentation: "https://docs.thenile.exchange/";
        readonly bridge: "native";
    };
    readonly LUSD: {
        readonly name: "LUSD Stablecoin";
        readonly symbol: "LUSD";
        readonly oracleId: "LUSD";
        readonly address: "0x63bA74893621d3d12F13CEc1e86517eC3d329837";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.liquity.org/";
        readonly description: "Liquity is a decentralized borrowing protocol that allows you to draw interest-free loans against Ether used as collateral. Loans are paid out in LUSD (a USD pegged stablecoin) and need to maintain a minimum collateral ratio of 110%.";
        readonly bridge: "linea-canonical";
        readonly documentation: "https://docs.liquity.org/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly weETH: {
        readonly name: "Wrapped eETH";
        readonly symbol: "weETH";
        readonly oracleId: "weETH";
        readonly address: "0x1Bf74C010E6320bab11e2e5A532b5AC15e0b8aA6";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://ether.fi/";
        readonly description: "Stake ETH, get eETH - a natively restaked liquid staking token that fuels DeFi and decentralizes Ethereum.";
        readonly bridge: "stargate";
        readonly documentation: "https://etherfi.gitbook.io/etherfi";
        readonly tags: readonly ["BLUECHIP", "NO_TIMELOCK"];
    };
    readonly inETH: {
        readonly name: "Inception ETH";
        readonly symbol: "inETH";
        readonly oracleId: "lineainETH";
        readonly address: "0x5A7a183B6B44Dc4EC2E3d2eF43F98C5152b1d76d";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.inceptionlrt.com/";
        readonly description: "Inception ETH is a pioneering DeFi platform that provides a full solution for liquid restaking. Inception ETH is designed to streamline and improve the restaking process by combining Isolated and Native Liquid Restaking and a diverse array of Liquid Restaking Tokens.";
        readonly bridge: "inception";
        readonly documentation: "https://docs.inceptionlrt.com/";
        readonly tags: readonly ["NO_TIMELOCK", "SYNTHETIC"];
    };
    readonly wrsETH: {
        readonly name: "rsETHWrapper";
        readonly symbol: "wrsETH";
        readonly oracleId: "wrsETH";
        readonly address: "0xD2671165570f41BBB3B0097893300b6EB6101E6C";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://kelpdao.xyz/";
        readonly description: "The rsETHWrapper contract serves as a standardized interface for rsETH tokens, which are Liquid Restaked Tokens (LRT) issued by Kelp DAO. Designed to offer liquidity to illiquid assets deposited into restaking platforms like EigenLayer, users can interact with these tokens seamlessly.";
        readonly bridge: "stargate";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly FOXY: {
        readonly name: "Foxy";
        readonly symbol: "FOXY";
        readonly oracleId: "FOXY";
        readonly address: "0x5FBDF89403270a1846F5ae7D113A989F850d1566";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.welikethefox.io/";
        readonly description: "Foxy is the mascot of the Linea blockchain. Every chain needs a champion, and we like the fox.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "LARGE_HOLDERS"];
    };
    readonly REX: {
        readonly name: "Etherex";
        readonly symbol: "REX";
        readonly oracleId: "REX";
        readonly address: "0xEfD81eeC32B9A8222D1842ec3d99c7532C31e348";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.etherex.finance/trade";
        readonly description: "Etherex is a concentrated liquidity layer and exchange built on the Linea network, powered by the latest metaDEX x(3,3) methodology—a more fluid and accessible version of the popular ve(3,3) model.";
        readonly documentation: "https://docs.etherex.finance/";
        readonly bridge: "native";
    };
    readonly asUSD: {
        readonly name: "Astera USD";
        readonly symbol: "asUSD";
        readonly oracleId: "asUSD";
        readonly address: "0xa500000000e482752f032eA387390b6025a2377b";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://astera.fi/";
        readonly documentation: "https://github.com/Astera-Finance/whitepapers";
        readonly description: "Pioneering Ethereum-native credit rails on linea";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly REX33: {
        readonly name: "Etherex Liquid Staking Token";
        readonly symbol: "REX33";
        readonly oracleId: "REX33";
        readonly address: "0xe4eEB461Ad1e4ef8b8EF71a33694CCD84Af051C4";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://www.etherex.finance/trade";
        readonly description: "Liquid Staked REX. Etherex is a concentrated liquidity layer and exchange built on the Linea network, powered by the latest metaDEX x(3,3) methodology—a more fluid and accessible version of the popular ve(3,3) model.";
        readonly documentation: "https://docs.etherex.finance/";
        readonly bridge: "native";
    };
    readonly aLinUSDC: {
        readonly name: "Aave Linea USDC";
        readonly symbol: "aLinUSDC";
        readonly oracleId: "aLinUSDC";
        readonly address: "0x374D7860c4f2f604De0191298dD393703Cce84f3";
        readonly chainId: 59144;
        readonly decimals: 6;
        readonly website: "https://aave.com";
        readonly description: "Aave interest bearing native USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly bridge: "native";
        readonly staked: true;
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly LINEA: {
        readonly name: "Linea";
        readonly symbol: "LINEA";
        readonly oracleId: "LINEA";
        readonly address: "0x1789e0043623282D5DCc7F213d703C6D8BAfBB04";
        readonly chainId: 59144;
        readonly decimals: 18;
        readonly website: "https://linea.build/";
        readonly description: "Linea is the Layer 2 network built from first principles to strengthen Ethereum and the entire ETH economy.";
        readonly documentation: "https://docs.linea.build/";
        readonly bridge: "native";
    };
};
