export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped XPL";
        readonly address: "0x6100E367285b01F48D07953803A2d8dCA5D19873";
        readonly symbol: "WXPL";
        readonly oracleId: "WXPL";
        readonly decimals: 18;
        readonly chainId: 9745;
        readonly website: "https://www.plasma.to/";
        readonly description: "Plasma is a high-performance layer 1 blockchain purpose-built for stablecoins.";
        readonly bridge: "canonical";
        readonly documentation: "https://docs.plasma.to/docs/get-started/introduction/start-here";
    };
    readonly FEES: {
        readonly name: "Wrapped XPL";
        readonly address: "0x6100E367285b01F48D07953803A2d8dCA5D19873";
        readonly symbol: "WXPL";
        readonly oracleId: "WXPL";
        readonly decimals: 18;
        readonly chainId: 9745;
        readonly website: "https://www.plasma.to/";
        readonly description: "Plasma is a high-performance layer 1 blockchain purpose-built for stablecoins.";
        readonly bridge: "canonical";
        readonly documentation: "https://docs.plasma.to/docs/get-started/introduction/start-here";
    };
    readonly XPL: {
        readonly name: "Wrapped XPL";
        readonly address: "0x6100E367285b01F48D07953803A2d8dCA5D19873";
        readonly symbol: "WXPL";
        readonly oracleId: "WXPL";
        readonly decimals: 18;
        readonly chainId: 9745;
        readonly website: "https://www.plasma.to/";
        readonly description: "Plasma is a high-performance layer 1 blockchain purpose-built for stablecoins.";
        readonly bridge: "canonical";
        readonly documentation: "https://docs.plasma.to/docs/get-started/introduction/start-here";
    };
    readonly WXPL: {
        readonly name: "Wrapped XPL";
        readonly address: "0x6100E367285b01F48D07953803A2d8dCA5D19873";
        readonly symbol: "WXPL";
        readonly oracleId: "WXPL";
        readonly decimals: 18;
        readonly chainId: 9745;
        readonly website: "https://www.plasma.to/";
        readonly description: "Plasma is a high-performance layer 1 blockchain purpose-built for stablecoins.";
        readonly bridge: "canonical";
        readonly documentation: "https://docs.plasma.to/docs/get-started/introduction/start-here";
    };
    readonly USDT0: {
        readonly name: "USDT0";
        readonly symbol: "USDT0";
        readonly oracleId: "USDT0";
        readonly address: "0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb";
        readonly chainId: 9745;
        readonly decimals: 6;
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://tether.to/en/how-it-works";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly WETH: {
        readonly name: "Wrapped ETH";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly address: "0x9895D81bB462A195b4922ED7De0e3ACD007c32CB";
        readonly chainId: 9745;
        readonly decimals: 18;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly XAUt0: {
        readonly name: "XAUt0";
        readonly symbol: "XAUt0";
        readonly oracleId: "XAUt0";
        readonly address: "0x1B64B9025EEbb9A6239575dF9Ea4b9Ac46D4d193";
        readonly chainId: 9745;
        readonly decimals: 6;
        readonly website: "https://gold.usdt0.to/transfer";
        readonly description: "Tether Gold tokens (XAUt) represents ownership of one troy ounce of physical gold held in a Swiss vault, combining the stability of precious metals with the utility of digital assets. It has become a trusted store of value for individuals and institutions seeking the security of gold without the burdens of physical custody. However, as the blockchain ecosystem expands, the movement of XAUT across chains remains disjointed and dependent on inconsistent bridging solutions, fragmented liquidity, and opaque backend processes that limit usability and access.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://usdt0.gitbook.io/xaut0";
    };
    readonly USDe: {
        readonly name: "USDe";
        readonly symbol: "USDe";
        readonly oracleId: "USDe";
        readonly address: "0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34";
        readonly chainId: 9745;
        readonly decimals: 18;
        readonly website: "https://ethena.fi/";
        readonly documentation: "https://ethena-labs.gitbook.io/ethena-labs";
        readonly description: "Ethenas USDe is not the same as a fiat stablecoin like USDC or USDT. USDe is a synthetic dollar, backed with crypto assets and corresponding short futures positions.";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly sUSDe: {
        readonly name: "Staked USDe";
        readonly symbol: "sUSDe";
        readonly oracleId: "sUSDe";
        readonly address: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2";
        readonly chainId: 9745;
        readonly decimals: 18;
        readonly website: "https://ethena.fi/";
        readonly documentation: "https://ethena-labs.gitbook.io/ethena-labs";
        readonly description: "Users are able to stake their USDe for sUSDe through the Ethena front-end. sUSDe is a reward-bearing token that accrues value from the yield that Ethena’s underlying delta-neutral position generates. sUSDe is subject to a 7-day un-staking period.";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly PlasmaUSD: {
        readonly name: "Plasma USD Vault (PlasmaUSD)";
        readonly symbol: "PlasmaUSD";
        readonly oracleId: "PlasmaUSD";
        readonly address: "0xd1074E0AE85610dDBA0147e29eBe0D8E5873a000";
        readonly chainId: 9745;
        readonly decimals: 6;
        readonly website: "https://app.plasma.to/";
        readonly description: "The PlasmaUSD Vault is the flagship Plasma vault managed by Veda. Deposits are deployed into blue-chip lending protocols such as Aave to generate yield.";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly syrupUSDT: {
        readonly name: "Syrup USDT";
        readonly symbol: "syrupUSDT";
        readonly oracleId: "syrupUSDT";
        readonly address: "0xC4374775489CB9C56003BF2C9b12495fC64F0771";
        readonly chainId: 9745;
        readonly decimals: 6;
        readonly website: "https://app.maple.finance/";
        readonly documentation: "https://docs.maple.finance/integrate/syrupusd-crosschain";
        readonly description: "Syrup makes consistent high yield available to everyone in DeFi. The yield is generated by Maple’s digital asset lending platform that provides fixed-rate, overcollateralised loans to institutional borrowers. These short duration loans enable Syrup to provide consistent high yield as well as short term liquidity for Syrup users.";
        readonly bridge: "chainlink-ccip";
    };
    readonly msUSD: {
        readonly name: "Metronome Synth USD";
        readonly symbol: "msUSD";
        readonly oracleId: "msUSD";
        readonly address: "0x29AD7fE4516909b9e498B5a65339e54791293234";
        readonly chainId: 9745;
        readonly decimals: 18;
        readonly website: "https://app.metronome.io/";
        readonly description: "msUSD represents Metronome Synth USD. Through the Metronome dApp, users are able to deposit crypto assets as collateral, and use that collateral to mint popular crypto synthetics.";
        readonly documentation: "https://docs.metronome.io/metronome-2.0/master";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly splUSD: {
        readonly name: "Staked Plasma USD";
        readonly symbol: "splUSD";
        readonly oracleId: "splUSD";
        readonly address: "0x616185600989Bf8339b58aC9e539d49536598343";
        readonly chainId: 9745;
        readonly decimals: 18;
        readonly website: "https://plasma.earn.trevee.xyz/";
        readonly description: "splUSD represents the vault receipt token of Trevee. The vault is powered by Midas infrastructure. Deposits into splUSD is then deployed into DeFi (e.g. Aave and Fluid) strategies to generate yield.";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly LITH: {
        readonly name: "Lithos";
        readonly symbol: "LITH";
        readonly oracleId: "LITH";
        readonly address: "0xAbB48792A3161E81B47cA084c0b7A22a50324A44";
        readonly chainId: 9745;
        readonly decimals: 18;
        readonly website: "https://lithos.to/";
        readonly description: "Lithos is a 3,3 DEX built on the Plasma blockchain.";
        readonly documentation: "https://docs.lithos.to";
        readonly bridge: "native";
    };
    readonly weETH: {
        readonly name: "Wrapped eETH";
        readonly symbol: "weETH";
        readonly oracleId: "weETH";
        readonly address: "0xA3D68b74bF0528fdD07263c60d6488749044914b";
        readonly chainId: 9745;
        readonly decimals: 18;
        readonly website: "https://www.ether.fi/";
        readonly description: "ether.fi is a decentralized, non-custodial delegated staking protocol with a Liquid Staking token. One of the distinguishing characteristics of ether.fi is that stakers control their keys. The ether.fi mechanism also allows for the creation of a node services marketplace where stakers and node operators can enroll nodes to provide infrastructure services.";
        readonly documentation: "https://etherfi.gitbook.io/etherfi";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["BLUECHIP", "NO_TIMELOCK"];
    };
};
