import type { Token } from '../../../types/token.js';

const USDC = {
  name: 'USDC',
  address: '0xfc960C233B8E98e0Cf282e29BDE8d3f105fc24d5',
  symbol: 'WUSDC',
  oracleId: 'USDC',
  decimals: 6,
  chainId: 5464,
  website: 'https://www.centre.io/',
  description:
    'USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
  bridge: 'saga-canonical',
  logoURI: 'https://ftmscan.com/token/images/USDC_32.png',
  documentation: 'https://www.circle.com/en/usdc-multichain/arbitrum',
} as const satisfies Token;

export const tokens = {
  GAS: USDC,
  WGAS: USDC,
  WNATIVE: USDC,
  USDC,
  SAGA: {
    name: 'Saga',
    address: '0xA19377761FED745723B90993988E04d641c2CfFE',
    symbol: 'SAGA',
    oracleId: 'SAGA',
    decimals: 6,
    chainId: 5464,
    website: 'https://www.saga.xyz/',
    description:
      'The blockchain revolution started with Bitcoin but Vitalik Buterin saw the potential for blockchain technology to not just create a decentralized currency but also decentralized applications. This was the start of Ethereum. ',
    bridge: 'saga-canonical',
    logoURI: '',
    documentation: 'https://www.saga.xyz/saga-protocol',
  },
  WETH: {
    name: 'Wrapped Ether',
    symbol: 'WETH',
    oracleId: 'WETH',
    address: '0xeb41D53F14Cb9a67907f2b8b5DBc223944158cCb',
    chainId: 5464,
    decimals: 18,
    logoURI: '',
    website: 'https://weth.io/',
    description: 'Ether or ETH is the native currency built on the Ethereum blockchain.',
    bridge: 'saga-canonical',
    documentation: 'https://ethereum.org/en/developers/docs/',
  },
  USDT: {
    name: 'Tether',
    symbol: 'USDT',
    oracleId: 'USDT',
    address: '0xC8fe3C1de344854f4429bB333AFFAeF97eF88CEa',
    chainId: 5464,
    decimals: 6,
    logoURI: '',
    website: 'https://www.tether.to/',
    description:
      'Tether is a stablecoin pegged to the US dollar. Tether is issued by Tether Limited, a Gibraltar-based company.',
    bridge: 'saga-canonical',
    documentation: 'https://www.tether.to/',
  },
  UNI: {
    name: 'Uniswap',
    symbol: 'UNI',
    oracleId: 'UNI',
    address: '0x4E33613adD93463E82A14080021f2FfaF1e062CF',
    chainId: 5464,
    decimals: 18,
    logoURI: '',
    website: 'https://www.uniswap.org/',
    description: 'Uniswap is a decentralized exchange (DEX) on the Ethereum blockchain.',
    bridge: 'saga-canonical',
    documentation: 'https://www.uniswap.org/',
  },
} as const satisfies Record<string, Token>;
