import type { Token } from '../../../types/token.js';

const ETH = {
  name: 'Wrapped Ether',
  address: '0x5300000000000000000000000000000000000004',
  symbol: 'WETH',
  oracleId: 'WETH',
  decimals: 18,
  chainId: 534352,
  website: 'https://weth.io/',
  description: 'Ether or ETH is the native currency built on the Ethereum blockchain.',
  bridge: 'scroll-canonical',
  logoURI: '',
  documentation: 'https://ethereum.org/en/developers/docs/',
} as const satisfies Token;

export const tokens = {
  WNATIVE: ETH,
  FEES: ETH,
  ETH,
  WETH: ETH,
  USDC: {
    name: 'USD Coin',
    address: '0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4',
    symbol: 'USDC',
    oracleId: 'USDC',
    decimals: 6,
    website: 'https://www.centre.io/',
    description:
      'USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
    bridge: 'scroll-canonical',
    chainId: 534352,
    logoURI: 'https://ftmscan.com/token/images/USDC_32.png',
    documentation: 'https://www.circle.com/en/usdc-multichain/arbitrum',
  },
  WBTC: {
    chainId: 534352,
    address: '0x3C1BCa5a656e69edCD0D4E36BEbb3FcDAcA60Cf1',
    decimals: 8,
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    oracleId: 'WBTC',
    website: 'https://wbtc.network/',
    description:
      'Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.',
    bridge: 'scroll-canonical',
    logoURI:
      'https://raw.githubusercontent.com/ava-labs/bridge-tokens/main/avalanche-tokens/0x408D4cD0ADb7ceBd1F1A1C33A0Ba2098E1295bAB/logo.png',
  },
  USDT: {
    name: 'USDT',
    symbol: 'USDT',
    oracleId: 'USDT',
    address: '0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df',
    chainId: 534352,
    decimals: 6,
    website: 'https://tether.to/',
    description:
      'Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
    bridge: 'scroll-canonical',
    logoURI: 'https://hecoinfo.com/token/images/USDTHECO_32.png',
    documentation: 'https://tether.to/en/how-it-works',
  },
  NURI: {
    name: 'NURI Token',
    symbol: 'NURI',
    oracleId: 'NURI',
    address: '0xAAAE8378809bb8815c08D3C59Eb0c7D1529aD769',
    chainId: 534352,
    decimals: 18,
    logoURI: '',
    website: 'https://www.nuri.exchange/',
    description:
      'NURI takes concentrated liquidity to the next level, optimizing for high frequency LPs and Layer 2 cost structures. The result is a hyper-efficient liquidity layer designed to attract the most effective liquidity providers, while delivering a clean and simple UX for traders.',
    documentation: 'https://docs.nuri.exchange/',
    bridge: 'native',
  },
  loreUSD: {
    name: 'Lore USD',
    symbol: 'loreUSD',
    oracleId: 'loreUSD',
    address: '0x77fbf86399ed764A084F77B9acCb049F3DbC32d2',
    chainId: 534352,
    decimals: 18,
    logoURI: '',
    website: 'https://www.lore.finance/',
    description:
      'Lore is a decentralized non-custodial liquidity market protocol on Scroll where users can participate as depositors or borrowers. Depositors provide liquidity to the market to earn a passive income, while borrowers are able to borrow in an overcollateralized (perpetually) or undercollateralized (one-block liquidity) fashion.',
    documentation: 'https://docs.lore.finance/',
    bridge: 'native',
    risks: ['NO_TIMELOCK'],
  },
  LORE: {
    name: 'Lore Token',
    symbol: 'LORE',
    oracleId: 'LORE',
    address: '0x549423E69576b80E91dC836ae37e04209660c4ec',
    chainId: 534352,
    decimals: 18,
    logoURI: '',
    website: 'https://www.lore.finance/',
    description:
      'Lore is a decentralized non-custodial liquidity market protocol on Scroll where users can participate as depositors or borrowers. Depositors provide liquidity to the market to earn a passive income, while borrowers are able to borrow in an overcollateralized (perpetually) or undercollateralized (one-block liquidity) fashion.',
    documentation: 'https://docs.lore.finance/',
    bridge: 'native',
  },
  TKN: {
    name: 'Tokan',
    symbol: 'TKN',
    oracleId: 'TKN',
    address: '0x1a2fCB585b327fAdec91f55D45829472B15f17a4',
    chainId: 534352,
    decimals: 18,
    logoURI: '',
    website: 'https://www.tokan.exchange/',
    description:
      'Tokan is a DEX and Liquidity Layer driven by the community and centered around the ecosystem. Built on the Scroll network, Tokan serves as the exchange layer and addresses liquidity issues at the protocol level within the network.',
    documentation: 'https://docs.tokan.exchange/',
    bridge: 'native',
    risks: ['NO_TIMELOCK'],
  },
  wstETH: {
    name: 'Wrapped liquid staked Ether 2.0',
    symbol: 'wstETH',
    oracleId: 'wstETH',
    address: '0xf610A9dfB7C89644979b4A0f27063E9e7d7Cda32',
    chainId: 534352,
    decimals: 18,
    website: 'https://lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.',
    logoURI: '',
    documentation: 'https://docs.lido.fi/',
    bridge: 'scroll-canonical',
  },
  SCR: {
    name: 'Scroll',
    symbol: 'SCR',
    oracleId: 'SCR',
    address: '0xd29687c813D741E2F938F4aC377128810E217b1b',
    chainId: 534352,
    decimals: 18,
    logoURI: '',
    website: 'https://scroll.io/',
    description: 'Scroll is the leading zero-knowledge rollup. Scaling Ethereum for good.',
    documentation: 'https://docs.scroll.io/en/home/',
    bridge: 'native',
  },
} as const satisfies Record<string, Token>;
