import type { Token } from '../../../types/token.js';

const MON = {
  name: 'Wrapped Monad',
  address: '0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A',
  symbol: 'WMON',
  oracleId: 'WMON',
  decimals: 18,
  chainId: 143,
  website: 'https://www.monad.xyz/',
  description:
    'Monad is a next-generation, Ethereum-compatible chain delivering 10,000 TPS, sub-second finality, low fees, and scalable decentralization. All in one.',
  bridge: 'canonical',
  documentation: 'https://www.monad.xyz/build',
} as const satisfies Token;

export const tokens = {
  WNATIVE: MON,
  FEES: MON,
  MON,
  WMON: MON,
  USDC: {
    name: 'USD Coin',
    address: '0x754704Bc059F8C67012fEd69BC8A327a5aafb603',
    symbol: 'USDC',
    oracleId: 'USDC',
    decimals: 6,
    website: 'https://www.centre.io/',
    description:
      'USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
    bridge: 'native',
    chainId: 143,
    documentation: 'https://www.circle.com/en/usdc-multichain/arbitrum',
    tags: ['STABLECOIN'],
  },
  WETH: {
    name: 'Wrapped Ether',
    address: '0xEE8c0E9f1BFFb4Eb878d8f15f368A02a35481242',
    symbol: 'WETH',
    oracleId: 'WETH',
    decimals: 18,
    chainId: 143,
    website: 'https://weth.io/',
    description: 'Ether or ETH is the native currency built on the Ethereum blockchain.',
    bridge: 'wormhole',
    documentation: 'https://ethereum.org/en/developers/docs/',
    tags: ['BLUECHIP'],
  },
  AUSD: {
    name: 'Agora Dollar',
    symbol: 'AUSD',
    oracleId: 'AUSD',
    address: '0x00000000eFE302BEAA2b3e6e1b18d08D69a9012a',
    chainId: 143,
    decimals: 6,
    website: 'https://agora.finance/',
    documentation: 'https://developer.agora.finance/',
    description:
      'AUSD is backed 100% by Agora’s Reserves. The Agora Reserve Fund is composed of cash, overnight repurchase and reverse repurchase agreements, and short-term U.S. Treasury securities.',
    bridge: 'native',
    tags: ['NO_TIMELOCK', 'STABLECOIN'],
  },
  USDT0: {
    name: 'USDT0',
    symbol: 'USDT0',
    oracleId: 'USDT0',
    address: '0xe7cd86e13AC4309349F30B3435a9d337750fC82D',
    chainId: 143,
    decimals: 6,
    description:
      'Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
    bridge: 'layer-zero',
    documentation: 'https://tether.to/en/how-it-works',
    tags: ['STABLECOIN'],
  },
  WBTC: {
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    oracleId: 'WBTC',
    address: '0x0555E30da8f98308EdB960aa94C0Db47230d2B9c',
    chainId: 143,
    decimals: 8,
    website: 'https://wbtc.network/',
    description:
      'Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.',
    documentation: '',
    bridge: 'layer-zero',
    tags: ['BLUECHIP'],
  },
  wstETH: {
    name: 'Wrapped liquid staked Ether 2.0',
    symbol: 'wstETH',
    oracleId: 'wstETH',
    address: '0x10Aeaf63194db8d453d4D85a06E5eFE1dd0b5417',
    chainId: 143,
    decimals: 18,
    website: 'https://lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.',
    bridge: 'monad-canonical',
    documentation: 'https://docs.lido.fi/',
    tags: ['BLUECHIP'],
  },
  cWMON: {
    name: 'Curvance WMON',
    symbol: 'cWMON',
    oracleId: 'cWMON',
    address: '0xE01d426B589c7834a5F6B20D7e992A705d3c22ED',
    chainId: 143,
    decimals: 18,
    website: 'https://curvance.com/',
    description:
      'Curvance WMON is a yield-bearing receipt for WMON deposited in the WMON-AUSD market on Curvance. cWMON earns interest and Merkl rewards from Curvance and can be redeemed for WMON.',
    bridge: 'native',
    documentation: 'https://docs.curvance.com/',
  },
  LBTC: {
    name: 'Lombard Staked Bitcoin',
    symbol: 'LBTC',
    oracleId: 'LBTC',
    address: '0xecAc9C5F704e954931349Da37F60E39f515c11c1',
    chainId: 143,
    decimals: 8,
    website: 'https://www.lombard.finance/app/',
    description:
      "LBTC is liquid Bitcoin; it's yield-bearing, cross-chain, and 1:1 backed by BTC. LBTC enables yield-bearing BTC to move cross-chain without fragmenting liquidity, and is designed to seamlessly integrate Bitcoin into the decentralized finance (DeFi) ecosystem while maintaining the security and integrity of the underlying asset.",
    bridge: 'native',
    documentation: 'https://docs.lombard.finance/lbtc-liquid-bitcoin/introduction-to-lbtc',
    tags: ['NO_TIMELOCK', 'LARGE_HOLDERS'],
  },
  BTCb: {
    name: 'Bridged Bitcoin',
    symbol: 'BTCb',
    oracleId: 'BTCb',
    address: '0xB0F70C0bD6FD87dbEb7C10dC692a2a6106817072',
    chainId: 143,
    decimals: 8,
    website: 'https://www.lombard.finance/',
    documentation: 'https://docs.lombard.finance/lbtc-liquid-bitcoin/btc.b-bridged-bitcoin',
    description: 'official AVAX BRIDGE bridged BTC',
    bridge: 'native',
    tags: ['BLUECHIP', 'NO_TIMELOCK'],
  },
  AZND: {
    name: 'Asian Dollar',
    symbol: 'AZND',
    oracleId: 'AZND',
    address: '0x4917a5ec9fCb5e10f47CBB197aBe6aB63be81fE8',
    chainId: 143,
    decimals: 18,
    website: 'https://mudigital.net/',
    documentation: 'https://docs.mudigital.net/',
    description:
      'AZND (the "Asian Dollar") is a synthetic dollar backed by Asia\'s best RWAs, designed for stability and steady yield.  AZND is suitable for users seeking predictable returns while retaining full DeFi composability',
    bridge: 'native',
    tags: ['NO_TIMELOCK', 'STABLECOIN'],
  },
  muBOND: {
    name: 'mu Bond',
    symbol: 'muBOND',
    oracleId: 'muBOND',
    address: '0x336D414754967C6682B5A665C7DAF6F1409E63e8',
    chainId: 143,
    decimals: 18,
    website: 'https://mudigital.net/',
    documentation: 'https://docs.mudigital.net/',
    description:
      "muBOND is a high yield token backed by Asia's best RWAs, designed for higher potential returns in exchange for providing insurance to AZND holders.",
    bridge: 'native',
    tags: ['NO_TIMELOCK', 'SYNTHETIC', 'STABLECOIN'],
  },
  shMON: {
    name: 'ShMonad',
    symbol: 'shMON',
    oracleId: 'shMON',
    address: '0x1B68626dCa36c7fE922fD2d55E4f631d962dE19c',
    chainId: 143,
    decimals: 18,
    website: 'https://shmonad.xyz/',
    documentation: 'https://docs.shmonad.xyz/',
    description:
      "ShMonad is a liquid staking token for the Monad blockchain. When you stake MON (Monad's gas token), you receive shMON—a token representing your stake plus all future rewards it earns.",
    bridge: 'native',
    tags: ['NO_TIMELOCK'],
  },
  sMON: {
    name: 'Kintsu Staked Monad',
    symbol: 'sMON',
    oracleId: 'sMON',
    address: '0xA3227C5969757783154C60bF0bC1944180ed81B9',
    chainId: 143,
    decimals: 18,
    website: 'https://kintsu.xyz/',
    documentation: 'https://docs.kintsu.xyz/',
    description:
      'The Kintsu Liquid Staking protocol automates the process by which users can pool their MON tokens together for network staking via non-custodial smart contracts. By leveraging a decentralized Registry of Validators controlled by the DAO, Kintsu creates sMON, a liquid version of the core MON gas token.',
    bridge: 'native',
    tags: ['NO_TIMELOCK'],
  },
  gMON: {
    name: 'gMON',
    symbol: 'gMON',
    oracleId: 'gMON',
    address: '0x8498312A6B3CbD158bf0c93AbdCF29E6e4F55081',
    chainId: 143,
    decimals: 18,
    website: 'https://www.magmastaking.xyz/',
    documentation: 'https://docs.hydrogenlabs.xyz/magma/',
    description:
      "Magma is a community-owned Liquid Staking Protocol on Monad, designed for equitable token distribution via our Points Programs and the with MEV-boosted yield powered by the fastest block engine in crypto. Magma's staking pool allows users to stake their Monad tokens in exchange for liquid staked Monad tokens (gMON). ",
    bridge: 'native',
    tags: ['NO_TIMELOCK'],
  },
  loAZND: {
    name: 'Locked Asian Dollar',
    symbol: 'loAZND',
    oracleId: 'loAZND',
    address: '0x9c82eB49B51F7Dc61e22Ff347931CA32aDc6cd90',
    chainId: 143,
    decimals: 18,
    website: 'https://mudigital.net/',
    documentation: 'https://docs.mudigital.net/',
    description:
      'loAZND (the "Locked Asian Dollar") is a synthetic dollar backed by Asia\'s best RWAs, designed for stability and steady yield. loAZND is the yield-bearing version of AZND, earning up to 7% interest.',
    bridge: 'native',
    tags: ['NO_TIMELOCK', 'SYNTHETIC', 'STABLECOIN'],
  },
  USD1: {
    name: 'World Liberty Financial USD',
    symbol: 'USD1',
    oracleId: 'USD1',
    address: '0x111111d2bf19e43C34263401e0CAd979eD1cdb61',
    chainId: 143,
    decimals: 6,
    website: 'https://worldlibertyfinancial.com/usd1',
    description:
      'Digital dollar stablecoins that are accepted both on-chain and in the real world.',
    documentation: 'https://worldlibertyfinancial.com/about',
    bridge: 'chainlink',
    tags: ['STABLECOIN'],
  },
  earnAUSD: {
    name: 'Earn Agora Dollar',
    symbol: 'earnAUSD',
    oracleId: 'earnAUSD',
    address: '0x103222f020e98Bba0AD9809A011FDF8e6F067496',
    chainId: 143,
    decimals: 6,
    website: 'https://www.upshift.finance/',
    documentation: 'https://docs.upshift.finance/',
    description:
      'The primary liquid yield token on Monad, systematically allocating AUSD across top DeFi opportunities.',
    bridge: 'native',
    tags: ['NO_TIMELOCK', 'STABLECOIN'],
  },
  DUST: {
    name: 'Pixie Dust',
    symbol: 'DUST',
    oracleId: 'DUST',
    address: '0xAD96C3dffCD6374294e2573A7fBBA96097CC8d7c',
    chainId: 143,
    decimals: 18,
    website: 'https://neverland.money/',
    documentation: 'https://docs.neverland.money/',
    description:
      'Pixie Dust (DUST), powers every aspect of the Neverland protocol — from governance participation through veDUST, to liquidity incentives and deflationary mechanisms that strengthen value over time.',
    bridge: 'native',
    tags: ['NO_TIMELOCK', 'LARGE_HOLDERS'],
  },
} as const satisfies Record<string, Token>;
