import type { Token } from '../../../types/token.js';

const MON = {
  name: 'Wrapped Monad',
  address: '0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A',
  symbol: 'WMON',
  oracleId: 'WMON',
  decimals: 18,
  chainId: 143,
  website: 'https://www.monad.xyz/',
  description:
    'Monad is a next-generation, Ethereum-compatible chain delivering 10,000 TPS, sub-second finality, low fees, and scalable decentralization. All in one.',
  bridge: 'canonical',
  logoURI: '',
  documentation: 'https://www.monad.xyz/build',
} as const satisfies Token;

export const tokens = {
  WNATIVE: MON,
  FEES: MON,
  MON,
  WMON: MON,
  USDC: {
    name: 'USD Coin',
    address: '0x754704Bc059F8C67012fEd69BC8A327a5aafb603',
    symbol: 'USDC',
    oracleId: 'USDC',
    decimals: 6,
    website: 'https://www.centre.io/',
    description:
      'USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
    bridge: 'native',
    chainId: 143,
    logoURI: 'https://ftmscan.com/token/images/USDC_32.png',
    documentation: 'https://www.circle.com/en/usdc-multichain/arbitrum',
  },
  WETH: {
    name: 'Wrapped Ether',
    address: '0xEE8c0E9f1BFFb4Eb878d8f15f368A02a35481242',
    symbol: 'WETH',
    oracleId: 'WETH',
    decimals: 18,
    chainId: 143,
    website: 'https://weth.io/',
    description: 'Ether or ETH is the native currency built on the Ethereum blockchain.',
    bridge: 'wormhole',
    logoURI: 'https://arbiscan.io/token/images/weth_28.png',
    documentation: 'https://ethereum.org/en/developers/docs/',
  },
  AUSD: {
    name: 'Agora Dollar',
    symbol: 'AUSD',
    oracleId: 'AUSD',
    address: '0x00000000eFE302BEAA2b3e6e1b18d08D69a9012a',
    chainId: 143,
    decimals: 6,
    logoURI: '',
    website: 'https://agora.finance/',
    documentation: 'https://developer.agora.finance/',
    description:
      'AUSD is backed 100% by Agora’s Reserves. The Agora Reserve Fund is composed of cash, overnight repurchase and reverse repurchase agreements, and short-term U.S. Treasury securities.',
    bridge: 'native',
    risks: ['NO_TIMELOCK'],
  },
  USDT0: {
    name: 'USDT0',
    symbol: 'USDT0',
    oracleId: 'USDT0',
    address: '0xe7cd86e13AC4309349F30B3435a9d337750fC82D',
    chainId: 143,
    decimals: 6,
    logoURI: '',
    description:
      'Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
    bridge: 'layer-zero',
    documentation: 'https://tether.to/en/how-it-works',
  },
  WBTC: {
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    oracleId: 'WBTC',
    address: '0x0555E30da8f98308EdB960aa94C0Db47230d2B9c',
    chainId: 143,
    decimals: 8,
    logoURI: '',
    website: 'https://wbtc.network/',
    description:
      'Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.',
    documentation: '',
    bridge: 'layer-zero',
  },
  wstETH: {
    name: 'Wrapped liquid staked Ether 2.0',
    symbol: 'wstETH',
    oracleId: 'wstETH',
    address: '0x10Aeaf63194db8d453d4D85a06E5eFE1dd0b5417',
    chainId: 143,
    decimals: 18,
    website: 'https://lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.',
    bridge: 'monad-canonical',
    logoURI: '',
    documentation: 'https://docs.lido.fi/',
  },
  cWMON: {
    name: 'Curvance WMON',
    symbol: 'cWMON',
    oracleId: 'cWMON',
    address: '0xE01d426B589c7834a5F6B20D7e992A705d3c22ED',
    chainId: 143,
    decimals: 18,
    website: 'https://curvance.com/',
    description:
      'Curvance WMON is a yield-bearing receipt for WMON deposited in the WMON-AUSD market on Curvance. cWMON earns interest and Merkl rewards from Curvance and can be redeemed for WMON.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.curvance.com/',
  },
  LBTC: {
    name: 'Lombard Staked Bitcoin',
    symbol: 'LBTC',
    oracleId: 'LBTC',
    address: '0xecAc9C5F704e954931349Da37F60E39f515c11c1',
    chainId: 143,
    decimals: 8,
    logoURI: '',
    website: 'https://www.lombard.finance/app/',
    description:
      "LBTC is liquid Bitcoin; it's yield-bearing, cross-chain, and 1:1 backed by BTC. LBTC enables yield-bearing BTC to move cross-chain without fragmenting liquidity, and is designed to seamlessly integrate Bitcoin into the decentralized finance (DeFi) ecosystem while maintaining the security and integrity of the underlying asset.",
    bridge: 'native',
    documentation: 'https://docs.lombard.finance/lbtc-liquid-bitcoin/introduction-to-lbtc',
    risks: ['NO_TIMELOCK', 'LARGE_HOLDERS'],
  },
  BTCb: {
    name: 'Bridged Bitcoin',
    symbol: 'BTCb',
    oracleId: 'BTCb',
    address: '0xB0F70C0bD6FD87dbEb7C10dC692a2a6106817072',
    chainId: 143,
    decimals: 8,
    website: 'https://www.lombard.finance/',
    documentation: 'https://docs.lombard.finance/lbtc-liquid-bitcoin/btc.b-bridged-bitcoin',
    description: 'official AVAX BRIDGE bridged BTC',
    bridge: 'native',
    risks: ['NO_TIMELOCK'],
  },
} as const satisfies Record<string, Token>;
