export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped Monad";
        readonly address: "0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A";
        readonly symbol: "WMON";
        readonly oracleId: "WMON";
        readonly decimals: 18;
        readonly chainId: 143;
        readonly website: "https://www.monad.xyz/";
        readonly description: "Monad is a next-generation, Ethereum-compatible chain delivering 10,000 TPS, sub-second finality, low fees, and scalable decentralization. All in one.";
        readonly bridge: "canonical";
        readonly documentation: "https://www.monad.xyz/build";
    };
    readonly FEES: {
        readonly name: "Wrapped Monad";
        readonly address: "0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A";
        readonly symbol: "WMON";
        readonly oracleId: "WMON";
        readonly decimals: 18;
        readonly chainId: 143;
        readonly website: "https://www.monad.xyz/";
        readonly description: "Monad is a next-generation, Ethereum-compatible chain delivering 10,000 TPS, sub-second finality, low fees, and scalable decentralization. All in one.";
        readonly bridge: "canonical";
        readonly documentation: "https://www.monad.xyz/build";
    };
    readonly MON: {
        readonly name: "Wrapped Monad";
        readonly address: "0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A";
        readonly symbol: "WMON";
        readonly oracleId: "WMON";
        readonly decimals: 18;
        readonly chainId: 143;
        readonly website: "https://www.monad.xyz/";
        readonly description: "Monad is a next-generation, Ethereum-compatible chain delivering 10,000 TPS, sub-second finality, low fees, and scalable decentralization. All in one.";
        readonly bridge: "canonical";
        readonly documentation: "https://www.monad.xyz/build";
    };
    readonly WMON: {
        readonly name: "Wrapped Monad";
        readonly address: "0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A";
        readonly symbol: "WMON";
        readonly oracleId: "WMON";
        readonly decimals: 18;
        readonly chainId: 143;
        readonly website: "https://www.monad.xyz/";
        readonly description: "Monad is a next-generation, Ethereum-compatible chain delivering 10,000 TPS, sub-second finality, low fees, and scalable decentralization. All in one.";
        readonly bridge: "canonical";
        readonly documentation: "https://www.monad.xyz/build";
    };
    readonly USDC: {
        readonly name: "USD Coin";
        readonly address: "0x754704Bc059F8C67012fEd69BC8A327a5aafb603";
        readonly symbol: "USDC";
        readonly oracleId: "USDC";
        readonly decimals: 6;
        readonly website: "https://www.centre.io/";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly bridge: "native";
        readonly chainId: 143;
        readonly documentation: "https://www.circle.com/en/usdc-multichain/arbitrum";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly WETH: {
        readonly name: "Wrapped Ether";
        readonly address: "0xEE8c0E9f1BFFb4Eb878d8f15f368A02a35481242";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 143;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "wormhole";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly AUSD: {
        readonly name: "Agora Dollar";
        readonly symbol: "AUSD";
        readonly oracleId: "AUSD";
        readonly address: "0x00000000eFE302BEAA2b3e6e1b18d08D69a9012a";
        readonly chainId: 143;
        readonly decimals: 6;
        readonly website: "https://agora.finance/";
        readonly documentation: "https://developer.agora.finance/";
        readonly description: "AUSD is backed 100% by Agora’s Reserves. The Agora Reserve Fund is composed of cash, overnight repurchase and reverse repurchase agreements, and short-term U.S. Treasury securities.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN"];
    };
    readonly USDT0: {
        readonly name: "USDT0";
        readonly symbol: "USDT0";
        readonly oracleId: "USDT0";
        readonly address: "0xe7cd86e13AC4309349F30B3435a9d337750fC82D";
        readonly chainId: 143;
        readonly decimals: 6;
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://tether.to/en/how-it-works";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly WBTC: {
        readonly name: "Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "WBTC";
        readonly address: "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c";
        readonly chainId: 143;
        readonly decimals: 8;
        readonly website: "https://wbtc.network/";
        readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
        readonly documentation: "";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly wstETH: {
        readonly name: "Wrapped liquid staked Ether 2.0";
        readonly symbol: "wstETH";
        readonly oracleId: "wstETH";
        readonly address: "0x10Aeaf63194db8d453d4D85a06E5eFE1dd0b5417";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://lido.fi/";
        readonly description: "Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.";
        readonly bridge: "monad-canonical";
        readonly documentation: "https://docs.lido.fi/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly cWMON: {
        readonly name: "Curvance WMON";
        readonly symbol: "cWMON";
        readonly oracleId: "cWMON";
        readonly address: "0xE01d426B589c7834a5F6B20D7e992A705d3c22ED";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://curvance.com/";
        readonly description: "Curvance WMON is a yield-bearing receipt for WMON deposited in the WMON-AUSD market on Curvance. cWMON earns interest and Merkl rewards from Curvance and can be redeemed for WMON.";
        readonly bridge: "native";
        readonly documentation: "https://docs.curvance.com/";
    };
    readonly LBTC: {
        readonly name: "Lombard Staked Bitcoin";
        readonly symbol: "LBTC";
        readonly oracleId: "LBTC";
        readonly address: "0xecAc9C5F704e954931349Da37F60E39f515c11c1";
        readonly chainId: 143;
        readonly decimals: 8;
        readonly website: "https://www.lombard.finance/app/";
        readonly description: "LBTC is liquid Bitcoin; it's yield-bearing, cross-chain, and 1:1 backed by BTC. LBTC enables yield-bearing BTC to move cross-chain without fragmenting liquidity, and is designed to seamlessly integrate Bitcoin into the decentralized finance (DeFi) ecosystem while maintaining the security and integrity of the underlying asset.";
        readonly bridge: "native";
        readonly documentation: "https://docs.lombard.finance/lbtc-liquid-bitcoin/introduction-to-lbtc";
        readonly tags: readonly ["NO_TIMELOCK", "LARGE_HOLDERS"];
    };
    readonly BTCb: {
        readonly name: "Bridged Bitcoin";
        readonly symbol: "BTCb";
        readonly oracleId: "BTCb";
        readonly address: "0xB0F70C0bD6FD87dbEb7C10dC692a2a6106817072";
        readonly chainId: 143;
        readonly decimals: 8;
        readonly website: "https://www.lombard.finance/";
        readonly documentation: "https://docs.lombard.finance/lbtc-liquid-bitcoin/btc.b-bridged-bitcoin";
        readonly description: "official AVAX BRIDGE bridged BTC";
        readonly bridge: "native";
        readonly tags: readonly ["BLUECHIP", "NO_TIMELOCK"];
    };
    readonly AZND: {
        readonly name: "Asian Dollar";
        readonly symbol: "AZND";
        readonly oracleId: "AZND";
        readonly address: "0x4917a5ec9fCb5e10f47CBB197aBe6aB63be81fE8";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://mudigital.net/";
        readonly documentation: "https://docs.mudigital.net/";
        readonly description: "AZND (the \"Asian Dollar\") is a synthetic dollar backed by Asia's best RWAs, designed for stability and steady yield.  AZND is suitable for users seeking predictable returns while retaining full DeFi composability";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN"];
    };
    readonly muBOND: {
        readonly name: "mu Bond";
        readonly symbol: "muBOND";
        readonly oracleId: "muBOND";
        readonly address: "0x336D414754967C6682B5A665C7DAF6F1409E63e8";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://mudigital.net/";
        readonly documentation: "https://docs.mudigital.net/";
        readonly description: "muBOND is a high yield token backed by Asia's best RWAs, designed for higher potential returns in exchange for providing insurance to AZND holders.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "SYNTHETIC", "STABLECOIN"];
    };
    readonly shMON: {
        readonly name: "ShMonad";
        readonly symbol: "shMON";
        readonly oracleId: "shMON";
        readonly address: "0x1B68626dCa36c7fE922fD2d55E4f631d962dE19c";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://shmonad.xyz/";
        readonly documentation: "https://docs.shmonad.xyz/";
        readonly description: "ShMonad is a liquid staking token for the Monad blockchain. When you stake MON (Monad's gas token), you receive shMON—a token representing your stake plus all future rewards it earns.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly sMON: {
        readonly name: "Kintsu Staked Monad";
        readonly symbol: "sMON";
        readonly oracleId: "sMON";
        readonly address: "0xA3227C5969757783154C60bF0bC1944180ed81B9";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://kintsu.xyz/";
        readonly documentation: "https://docs.kintsu.xyz/";
        readonly description: "The Kintsu Liquid Staking protocol automates the process by which users can pool their MON tokens together for network staking via non-custodial smart contracts. By leveraging a decentralized Registry of Validators controlled by the DAO, Kintsu creates sMON, a liquid version of the core MON gas token.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly gMON: {
        readonly name: "gMON";
        readonly symbol: "gMON";
        readonly oracleId: "gMON";
        readonly address: "0x8498312A6B3CbD158bf0c93AbdCF29E6e4F55081";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://www.magmastaking.xyz/";
        readonly documentation: "https://docs.hydrogenlabs.xyz/magma/";
        readonly description: "Magma is a community-owned Liquid Staking Protocol on Monad, designed for equitable token distribution via our Points Programs and the with MEV-boosted yield powered by the fastest block engine in crypto. Magma's staking pool allows users to stake their Monad tokens in exchange for liquid staked Monad tokens (gMON). ";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly loAZND: {
        readonly name: "Locked Asian Dollar";
        readonly symbol: "loAZND";
        readonly oracleId: "loAZND";
        readonly address: "0x9c82eB49B51F7Dc61e22Ff347931CA32aDc6cd90";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://mudigital.net/";
        readonly documentation: "https://docs.mudigital.net/";
        readonly description: "loAZND (the \"Locked Asian Dollar\") is a synthetic dollar backed by Asia's best RWAs, designed for stability and steady yield. loAZND is the yield-bearing version of AZND, earning up to 7% interest.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "SYNTHETIC", "STABLECOIN"];
    };
    readonly USD1: {
        readonly name: "World Liberty Financial USD";
        readonly symbol: "USD1";
        readonly oracleId: "USD1";
        readonly address: "0x111111d2bf19e43C34263401e0CAd979eD1cdb61";
        readonly chainId: 143;
        readonly decimals: 6;
        readonly website: "https://worldlibertyfinancial.com/usd1";
        readonly description: "Digital dollar stablecoins that are accepted both on-chain and in the real world.";
        readonly documentation: "https://worldlibertyfinancial.com/about";
        readonly bridge: "chainlink";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly GHO: {
        readonly name: "GHO Token";
        readonly symbol: "GHO";
        readonly oracleId: "GHO";
        readonly address: "0xfc421aD3C883Bf9E7C4f42dE845C4e4405799e73";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly documentation: "https://docs.aave.com/faq/gho-stablecoin";
        readonly description: "GHO is a decentralized multi-collateral stablecoin that is fully backed, transparent and native to the Aave Protocol.";
        readonly bridge: "chainlink-ccip";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly mUSD: {
        readonly name: "MetaMask USD";
        readonly symbol: "mUSD";
        readonly oracleId: "MetaMaskUSD";
        readonly address: "0xacA92E438df0B2401fF60dA7E4337B687a2435DA";
        readonly chainId: 143;
        readonly decimals: 6;
        readonly website: "https://metamask.io/";
        readonly documentation: "https://metamask.io/";
        readonly description: "MetaMask USD (mUSD) is a stablecoin issued by MetaMask, designed to maintain a 1:1 peg with the US dollar and integrate across MetaMask products.";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly earnAUSD: {
        readonly name: "Earn Agora Dollar";
        readonly symbol: "earnAUSD";
        readonly oracleId: "earnAUSD";
        readonly address: "0x103222f020e98Bba0AD9809A011FDF8e6F067496";
        readonly chainId: 143;
        readonly decimals: 6;
        readonly website: "https://www.upshift.finance/";
        readonly documentation: "https://docs.upshift.finance/";
        readonly description: "The primary liquid yield token on Monad, systematically allocating AUSD across top DeFi opportunities.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN"];
    };
    readonly cbBTC: {
        readonly name: "Coinbase Wrapped WBTC";
        readonly symbol: "cbBTC";
        readonly oracleId: "cbBTC";
        readonly address: "0xd18B7EC58Cdf4876f6AFebd3Ed1730e4Ce10414b";
        readonly chainId: 143;
        readonly decimals: 8;
        readonly website: "https://www.coinbase.com/";
        readonly description: "Coinbase Wrapped Bitcoin (cbBTC) is backed 1:1 with Bitcoin, custodied with Coinbase.";
        readonly documentation: "https://www.coinbase.com/blog/coinbase-wrapped-btc-cbbtc-is-now-live";
        readonly bridge: "chainlink-ccip";
    };
    readonly DUST: {
        readonly name: "Pixie Dust";
        readonly symbol: "DUST";
        readonly oracleId: "DUST";
        readonly address: "0xAD96C3dffCD6374294e2573A7fBBA96097CC8d7c";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://neverland.money/";
        readonly documentation: "https://docs.neverland.money/";
        readonly description: "Pixie Dust (DUST), powers every aspect of the Neverland protocol — from governance participation through veDUST, to liquidity incentives and deflationary mechanisms that strengthen value over time.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "LARGE_HOLDERS"];
    };
    readonly wnUSDT0: {
        readonly name: "Wrapped Neverland USDT0";
        readonly symbol: "wnUSDT0";
        readonly oracleId: "wnUSDT0";
        readonly address: "0x4e8aaecCE10ad9394e96fE5f2bd4e587A7B04298";
        readonly chainId: 143;
        readonly decimals: 6;
        readonly description: "Wrapped Neverland USDT0.";
        readonly bridge: "native";
        readonly website: "https://neverland.money/";
        readonly documentation: "https://docs.neverland.money/";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly wnAUSD: {
        readonly name: "Wrapped Neverland AUSD";
        readonly symbol: "wnAUSD";
        readonly oracleId: "wnAUSD";
        readonly address: "0x82c370ba90E38ef6Acd8b1b078d34fD86FC6bAC9";
        readonly chainId: 143;
        readonly decimals: 6;
        readonly description: "Wrapped Neverland AUSD.";
        readonly bridge: "native";
        readonly website: "https://neverland.money/";
        readonly documentation: "https://docs.neverland.money/";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN"];
    };
    readonly wnUSDC: {
        readonly name: "Wrapped Neverland USDC";
        readonly symbol: "wnUSDC";
        readonly oracleId: "wnUSDC";
        readonly address: "0x8d5c2Df3Eef09088Fcccf3376D8EcD0Dd505f642";
        readonly chainId: 143;
        readonly decimals: 6;
        readonly website: "https://neverland.money/";
        readonly description: "Wrapped Neverland USDC.";
        readonly documentation: "https://docs.neverland.money/";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly wnWMON: {
        readonly name: "Wrapped Neverland MON";
        readonly symbol: "wnWMON";
        readonly oracleId: "wnWMON";
        readonly address: "0xdB39A9D4a1f1b4e93A5684d602207628aD60613C";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://neverland.money/";
        readonly description: "Wrapped Neverland MON.";
        readonly bridge: "native";
        readonly documentation: "https://docs.neverland.money/";
    };
    readonly wngMON: {
        readonly name: "Wrapped Neverland gMON";
        readonly symbol: "wngMON";
        readonly oracleId: "wngMON";
        readonly address: "0x29D2075E5151B1A6863bDC40EA86bD5e8aFd1705";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://neverland.money/";
        readonly description: "Wrapped Neverland gMON.";
        readonly bridge: "native";
        readonly documentation: "https://docs.neverland.money/";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly wnshMON: {
        readonly name: "Wrapped Neverland sMON";
        readonly symbol: "wnshMON";
        readonly oracleId: "wnshMON";
        readonly address: "0x5e073494678fB7FA4a05bB17d45941Dd9Dc469c1";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://neverland.money/";
        readonly description: "Wrapped Neverland shMON.";
        readonly bridge: "native";
        readonly documentation: "https://docs.neverland.money/";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly wnsMON: {
        readonly name: "Wrapped Neverland sMON";
        readonly symbol: "wnsMON";
        readonly oracleId: "wnsMON";
        readonly address: "0x08139339dd9A480CEB84D9C7CcE48BE436dB20b3";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://neverland.money/";
        readonly description: "Wrapped Neverland sMON.";
        readonly bridge: "native";
        readonly documentation: "https://docs.neverland.money/";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly wnloAZND: {
        readonly name: "Wrapped Neverland loAZND";
        readonly symbol: "wnloAZND";
        readonly oracleId: "wnloAZND";
        readonly address: "0xD786F7569C39A9F64E6A54Eb77db21364E90F279";
        readonly chainId: 143;
        readonly decimals: 18;
        readonly website: "https://neverland.money/";
        readonly description: "Wrapped Neverland loAZND.";
        readonly bridge: "native";
        readonly documentation: "https://docs.neverland.money/";
        readonly tags: readonly ["NO_TIMELOCK", "SYNTHETIC", "STABLECOIN"];
    };
    readonly avUSD: {
        readonly name: "avUSD";
        readonly symbol: "avUSD";
        readonly oracleId: "avUSD";
        readonly address: "0x0D9D741FE423Cd5419e4BCb6cB2FfA87AFa93bA4";
        readonly chainId: 1;
        readonly decimals: 18;
        readonly website: "https://app.avantprotocol.com/products";
        readonly documentation: "https://docs.avantprotocol.com/overview/core-tokens#avusd";
        readonly description: "avUSD is the primary stable token of the Avant Protocol, acting as the entry point for USD-denominated yield.";
        readonly bridge: "chainlink-ccip";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
};
