import { ConstRecord } from '../../../types/const';
import Token from '../../../types/token';

const ETH = {
  name: 'Wrapped Ether',
  address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
  symbol: 'WETH',
  oracleId: 'WETH',
  decimals: 18,
  chainId: 1,
  website: 'https://weth.io/',
  description: 'Ether or ETH is the native currency built on the Ethereum blockchain. ',
  bridge: 'native',
  logoURI: 'https://arbiscan.io/token/images/weth_28.png',
  documentation: 'https://ethereum.org/en/developers/docs/',
} as const;

const _tokens = {
  ETH,
  WETH: ETH,
  WNATIVE: ETH,
  BIFI: {
    name: 'Beefy',
    symbol: 'BIFI',
    oracleId: 'BIFI',
    address: '0xB1F1ee126e9c96231Cc3d3fAD7C08b4cf873b1f1',
    chainId: 1,
    decimals: 18,
    website: 'https://www.beefy.finance/',
    documentation: 'https://docs.beefy.finance/',
    description:
      "The Beefy Token (BIFI) is the governance token of the Beefy DAO. Holders of the token are entitled to submit and vote on proposals on all areas affecting the DAO through the Beefy Snapshot Space, as well as to participate in Beefy's governance incentives programme through the BIFI Pool or BIFI Vault.",
    logoURI: 'https://beefy.com/icons/128/BIFI.png',
    bridge: 'native',
  },
  rBIFI: {
    name: 'BIFI Pool Receipt',
    symbol: 'rBIFI',
    oracleId: 'rBIFI',
    address: '0xb1F131437e314614313aAb3a3016FA05c1b0e087',
    chainId: 1,
    decimals: 18,
    website: 'https://www.beefy.finance/',
    documentation: 'https://docs.beefy.finance/',
    description:
      "The Beefy Token (BIFI) is the governance token of the Beefy DAO. Holders of the token are entitled to submit and vote on proposals on all areas affecting the DAO through the Beefy Snapshot Space, as well as to participate in Beefy's governance incentives programme through the BIFI Pool or BIFI Vault.",
    logoURI: 'https://beefy.com/icons/128/BIFI.png',
    bridge: 'native',
  },
  mooBIFI: {
    name: 'BIFI Vault Receipt',
    symbol: 'mooBIFI',
    oracleId: 'mooBIFI',
    address: '0xBEEF8e0982874e0292E6C5751C5A4092b3e1BEEF',
    chainId: 1,
    decimals: 18,
    website: 'https://www.beefy.finance/',
    documentation: 'https://docs.beefy.finance/',
    description:
      "The incentive-bearing Beefy Token (mooBIFI) applies the magic of Beefy's autocompounding technology to the BIFI token. It is the vault token for the BIFI Vault, which automatically claims and swaps governance incentives into more BIFI, and redeposits to unlock exponential growth. On chains other than Ethereum, mooBIFI is a bridged copy of the native Ethereum token, and cannot be returned to BIFI without first bridging back to Ethereum. mooBIFI holders on all chains retain their full voting power corresponding to the underlying amount of BIFI deposited and compounding on Ethereum.",
    logoURI: 'https://beefy.com/icons/128/mooBIFI.png',
    bridge: 'native',
  },
  xmooBIFI: {
    name: 'BIFI Vault Receipt xERC20',
    symbol: 'xmooBIFI',
    oracleId: 'xmooBIFI',
    address: '0xb1feA302f3B2E93FA04E46dCCE35F2Fc522d7bB9',
    chainId: 1,
    decimals: 18,
    website: 'https://www.beefy.finance/',
    documentation: 'https://docs.beefy.finance/',
    description:
      "The incentive-bearing Beefy Token (mooBIFI) applies the magic of Beefy's autocompounding technology to the BIFI token. It is the vault token for the BIFI Vault, which automatically claims and swaps governance incentives into more BIFI, and redeposits to unlock exponential growth. On chains other than Ethereum, mooBIFI is a bridged copy of the native Ethereum token, and cannot be returned to BIFI without first bridging back to Ethereum. mooBIFI holders on all chains retain their full voting power corresponding to the underlying amount of BIFI deposited and compounding on Ethereum.",
    logoURI: 'https://beefy.com/icons/128/mooBIFI.png',
    bridge: 'native',
  },
  oldBIFI: {
    name: 'Beefy.Finance',
    symbol: 'oldBIFI',
    oracleId: 'oldBIFI',
    address: '0x5870700f1272a1AdbB87C3140bD770880a95e55D',
    chainId: 1,
    decimals: 18,
    website: 'https://www.beefy.finance/',
    documentation: 'https://docs.beefy.finance/',
    description:
      'Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.',
    logoURI:
      'https://raw.githubusercontent.com/beefyfinance/beefy-app/prod/src/images/single-assets/BIFI.png',
  },
  USDC: {
    name: 'USD Coin',
    address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    symbol: 'USDC',
    oracleId: 'USDC',
    decimals: 6,
    website: 'https://www.circle.com/usdc',
    description:
      'USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
    bridge: 'native',
    chainId: 1,
    logoURI: 'https://ftmscan.com/token/images/USDC_32.png',
    documentation: 'https://developers.circle.com/docs',
  },
  STG: {
    name: 'Stargate',
    symbol: 'STG',
    oracleId: 'STG',
    address: '0xAf5191B0De278C7286d6C7CC6ab6BB8A73bA2Cd6',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://raw.githubusercontent.com/traderjoe-xyz/joe-tokenlists/main/logos/0x2F6F07CDcf3588944Bf4C42aC74ff24bF56e7590/logo.png',
    website: 'https://stargate.finance/',
    description:
      'Stargate is a community-driven organization building the first fully composable native asset bridge, and the first dApp built on LayerZero.',
    documentation: 'https://stargateprotocol.gitbook.io/stargate/v/user-docs/',
  },
  CNC: {
    name: 'Conic Finance Token',
    symbol: 'CNC',
    oracleId: 'CNC',
    address: '0x9aE380F0272E2162340a5bB646c354271c0F5cFC',
    chainId: 1,
    decimals: 18,
    website: 'https://conic.finance/',
    description:
      'Conic Finance is an easy-to-use platform built for liquidity providers to easily diversify their exposure to multiple Curve pools. Any user can provide liquidity into a Conic Omnipool which allocates funds across Curve in proportion to protocol controlled pool weights.',
    bridge: 'native',
    documentation: 'https://docs.conic.finance/conic-finance/',
  },
  CTR: {
    name: 'Concentrator Token',
    symbol: 'CTR',
    oracleId: 'CTR',
    address: '0xb3Ad645dB386D7F6D753B2b9C3F4B853DA6890B8',
    chainId: 1,
    decimals: 18,
    website: 'https://concentrator.aladdin.club/',
    description:
      'Concentrator by Aladdin DAO maximizes Convex APYs and earns yield in the best DeFi tokens. Concentrator is a yield enhancer that boosts yields on Convex vaults by concentrating all rewards into auto-compounding top-tier tokens like aCRV (cvxCRV) and aFXS (cvxFXS/FXS).',
    bridge: 'native',
    documentation: 'https://docs.aladdin.club/concentrator',
  },
  MATIC: {
    name: 'Matic Token',
    symbol: 'MATIC',
    oracleId: 'MATIC',
    address: '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0',
    chainId: 1,
    decimals: 18,
    website: 'https://polygon.technology/',
    description:
      'Polygon is a protocol and a framework for building and connecting Ethereum-compatible blockchain networks. Aggregating scalable solutions on Ethereum supporting a multi-chain Ethereum ecosystem.',
    bridge: 'native',
  },
  wstETH: {
    name: 'Lido Wrapped Staked ETH',
    symbol: 'wstETH',
    oracleId: 'wstETH',
    address: '0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0',
    chainId: 1,
    decimals: 18,
    website: 'https://lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.lido.fi/',
  },
  stETH: {
    name: 'Lido Wrapped Staked ETH',
    symbol: 'stETH',
    oracleId: 'stETH',
    address: '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84',
    chainId: 1,
    decimals: 18,
    website: 'https://lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.lido.fi/',
  },
  pETH: {
    name: "JPEG'd ETH",
    symbol: 'pETH',
    oracleId: 'pETH',
    address: '0x836A808d4828586A69364065A1e064609F5078c7',
    chainId: 1,
    decimals: 18,
    website: 'https://jpegd.io/',
    description:
      "pETH is an Ethereum derivative supported by the JPEG'd protocol. It is minted when a user borrows against their NFT and burned when they decide to repay their loan. Unlike the 2% interest rate for borrowing PUSd, minting $pETH against an NFT has a 5% interest rate.",
    documentation: 'https://docs.jpegd.io/tokenomics/usdpeth',
  },
  FRAX: {
    chainId: 1,
    address: '0x853d955aCEf822Db058eb8505911ED77F175b99e',
    decimals: 18,
    name: 'Frax',
    symbol: 'FRAX',
    oracleId: 'FRAX',
    website: 'https://frax.finance/',
    description: 'Frax is the first fractional-algorithmic stablecoin protocol.',
    bridge: 'native',
    logoURI:
      'https://raw.githubusercontent.com/pangolindex/tokens/main/assets/0xD24C2Ad096400B6FBcd2ad8B24E7acBc21A1da64/logo.png',
    documentation: 'https://docs.frax.finance/',
  },
  WBTC: {
    chainId: 1,
    address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    decimals: 8,
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    oracleId: 'WBTC',
    website: 'https://wbtc.network/',
    description:
      'Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.',
    bridge: 'wbtc-dao',
    logoURI:
      'https://raw.githubusercontent.com/ava-labs/bridge-tokens/main/avalanche-tokens/0x408D4cD0ADb7ceBd1F1A1C33A0Ba2098E1295bAB/logo.png',
  },
  sBTC: {
    chainId: 1,
    address: '0xfE18be6b3Bd88A2D2A7f928d00292E7a9963CfC6',
    decimals: 18,
    name: 'Synthetix: sBTC',
    symbol: 'sBTC',
    oracleId: 'sBTC',
    website: 'https://www.synthetix.io/',
    description:
      'sBTC is a synthetic Bitcoin token enabled by the Synthetix protocol. It tracks the price of Bitcoin through price feeds supplied by Chainlink’s decentralized network of oracles.',
    bridge: 'native',
    logoURI:
      'https://raw.githubusercontent.com/ava-labs/bridge-tokens/main/avalanche-tokens/0x408D4cD0ADb7ceBd1F1A1C33A0Ba2098E1295bAB/logo.png',
  },
  multiBTC: {
    chainId: 1,
    address: '0x66eFF5221ca926636224650Fd3B9c497FF828F7D',
    decimals: 8,
    name: 'Multichain BTC',
    symbol: 'multiBTC',
    oracleId: 'multiBTC',
    website: 'https://app.multichain.org/',
    description: 'Multichain supports to swap BTC to MultiBTC (Multichain BTC) 1:1.',
    bridge: 'multichain',
    documentation: 'https://docs.multichain.org/getting-started/introduction',
  },
  alETH: {
    name: 'Alchemix ETH',
    symbol: 'alETH',
    oracleId: 'alETH',
    address: '0x0100546F2cD4C9D97f798fFC9755E47865FF7Ee6',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://alchemix.fi/',
    documentation: 'https://alchemix-finance.gitbook.io/v2/',
    description:
      'Alchemix Self-Repaying Loans allow you to leverage a range of tokens without risk of liquidation.',
  },
  alUSD: {
    name: 'Alchemix USD',
    symbol: 'alUSD',
    oracleId: 'alUSD',
    address: '0xBC6DA0FE9aD5f3b0d58160288917AA56653660E9',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://alchemix.fi/',
    description:
      'Alchemix Self-Repaying Loans allow you to leverage a range of tokens without risk of liquidation.',
    bridge: 'native',
    documentation: 'https://alchemix-finance.gitbook.io/user-docs/',
  },
  MIM: {
    name: 'Magic Internet Money',
    address: '0x99D8a9C45b2ecA8864373A26D1459e3Dff1e17F3',
    symbol: 'MIM',
    oracleId: 'MIM',
    decimals: 18,
    chainId: 1,
    website: 'https://abracadabra.money/',
    description:
      'You, the Spellcaster, can provide collateral in the form of various interest bearing crypto assets such as yvYFI, yvUSDT, yvUSDC, xSUSHI and more. With this, you can borrow magic internet money (MIM) which is a stable coin that you can swap for any other traditional stable coin.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.abracadabra.money/',
  },
  ApeUSD: {
    name: 'ApeUSD',
    address: '0xfF709449528B6fB6b88f557F7d93dEce33bca78D',
    symbol: 'ApeUSD',
    oracleId: 'ApeUSD',
    decimals: 18,
    chainId: 1,
    website: 'https://ape.fi/',
    documentation: 'https://github.com/ape-fi/ape-finance',
    description:
      'Ape Finance is building DeFi tools for metaverse dwellers, proud PFP owners, and digital collectible enthusiasts in all of us. We appreciate culture, art, and games. Ape Finance begins with the creation of the ApeUSD.',
    bridge: 'native',
    logoURI: '',
  },
  auraBAL: {
    name: 'Aura Staked BAL BPT',
    symbol: 'auraBAL',
    oracleId: 'auraBAL',
    address: '0x616e8BfA43F920657B3497DBf40D6b1A02D4608d',
    chainId: 1,
    decimals: 18,
    website: 'https://aura.finance/',
    description: "auraBAL is Aura's liquid staking locked BAL (80 BAL / 20 ETH) BPT",
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.aura.finance/aura/what-is-aura/for-usdbal-stakers',
  },
  BAL: {
    name: 'Balancer',
    symbol: 'BAL',
    oracleId: 'BAL',
    address: '0xba100000625a3754423978a60c9317c58a424e3D',
    chainId: 1,
    decimals: 18,
    website: 'https://balancer.fi/',
    description:
      'Balancer turns the concept of an index fund on its head: instead of a paying fees to portfolio managers to rebalance your portfolio, you collect fees from traders, who rebalance your portfolio by following arbitrage opportunities. ',
    logoURI: '',
    documentation: 'https://docs.balancer.fi/',
  },
  AURA: {
    name: 'Aura',
    symbol: 'AURA',
    oracleId: 'AURA',
    address: '0xC0c293ce456fF0ED870ADd98a0828Dd4d2903DBF',
    chainId: 1,
    decimals: 18,
    website: 'https://aura.finance/',
    description:
      'Aura Finance is a protocol built on top of the Balancer system to provide maximum incentives to Balancer liquidity providers and BAL stakers (into veBAL) through social aggregation of BAL deposits and Aura’s native token. For BAL stakers, Aura provides a seamless onboarding process to veBAL, by creating a tokenised wrapper token called auraBAL that represents the 80/20 BPT locked up for the maximum time in VotingEscrow (read more about what this means). This can be staked to receive existing rewards (BAL and bbaUSD) from Balancer, in addition to a share of any BAL earned by Aura (read more about the fees), and additional AURA. This minting process is irreversible however users can trade their auraBAL back to BAL through an incentivised liquidity pool.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.aura.finance/',
  },
  MAI: {
    name: 'Mai Stablecoin',
    symbol: 'MAI',
    oracleId: 'MAI',
    address: '0x8D6CeBD76f18E1558D4DB88138e2DeFB3909fAD6',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://mai.finance/',
    documentation: 'https://docs.mai.finance/',
    description:
      'MAI is a stable coin collateralized by your MATIC holdings. Its powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.',
  },
  tBTC: {
    name: 'tBTC v2',
    symbol: 'tBTC',
    oracleId: 'tBTC',
    address: '0x18084fbA666a33d37592fA2633fD49a74DD93a88',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://threshold.network/',
    documentation: 'https://docs.threshold.network/',
    description:
      'Threshold is the first ever on-chain merge between two existing networks and communities, Keep and NuCypher. Threshold provides a suite of threshold cryptography services that power user sovereignty on the blockchain.',
    bridge: 'threshold',
  },
  T: {
    name: 'Threshold Network Token',
    symbol: 'T',
    oracleId: 'T',
    address: '0xCdF7028ceAB81fA0C6971208e83fa7872994beE5',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://threshold.network/',
    description:
      'Threshold is the first ever on-chain merge between two existing networks and communities, Keep and NuCypher. Threshold provides a suite of threshold cryptography services that power user sovereignty on the blockchain.',
    bridge: 'native',
    documentation:
      'https://docs.threshold.network/app-development/staking-contract-and-dao/staking-contract-and-dao-api/t',
  },
  eCFX: {
    name: 'ethereum Conflux',
    symbol: 'eCFX',
    oracleId: 'eCFX',
    address: '0xA1f82E14bc09A1b42710dF1A8a999B62f294e592',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://confluxnetwork.org/',
    description:
      'Conflux’s token economy is built around the $CFX token, a unit of value on the platform that enables token holders to pay transaction fees, earn rewards through staking, rent storage, and participate in network governance. CFX also incentivizes and rewards miners, who ensure the secure operation of the Network.',
  },
  USDP: {
    name: 'Pax Dollar',
    symbol: 'USDP',
    oracleId: 'USDP',
    address: '0x8E870D67F660D95d5be530380D0eC0bd388289E1',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://paxos.com/usdp/',
    description:
      'Pax Dollar (USDP) is a stablecoin created by Paxos, a licenced trust firm and financial institution that ensures the backing of the tokens with US dollar deposits. With the USDP, Paxos created a token that combines the confidence and stability of fiat money with the usefulness and immediacy of digital assets.',
  },
  CRV: {
    name: 'CRV',
    address: '0xD533a949740bb3306d119CC777fa900bA034cd52',
    symbol: 'CRV',
    oracleId: 'CRV',
    decimals: 18,
    chainId: 1,
    website: 'https://curve.fi/',
    description:
      'Curve is an exchange liquidity pool on Ethereum. Curve is designed for extremely efficient stablecoin trading and low risk, supplemental fee income for liquidity providers, without an opportunity cost.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://curve.readthedocs.io/',
  },
  CVX: {
    name: 'CVX',
    address: '0x4e3FBD56CD56c3e72c1403e103b45Db9da5B9D2B',
    symbol: 'CVX',
    oracleId: 'CVX',
    decimals: 18,
    chainId: 1,
    website: 'https://www.convexfinance.com/',
    documentation: 'https://docs.convexfinance.com/',
    description:
      'Convex allows Curve.fi liquidity providers to earn trading fees and claim boosted CRV without locking CRV themselves. Liquidity providers can receive boosted CRV and liquidity mining rewards with minimal effort.',
    bridge: 'native',
    logoURI: '',
  },
  cvxCRV: {
    name: 'cvxCRV',
    address: '0x62B9c7356A2Dc64a1969e19C23e4f579F9810Aa7',
    symbol: 'cvxCRV',
    oracleId: 'cvxCRV',
    decimals: 18,
    chainId: 1,
    website: 'https://www.convexfinance.com/',
    documentation: 'https://docs.convexfinance.com/',
    description:
      'Convex allows Curve.fi liquidity providers to earn trading fees and claim boosted CRV without locking CRV themselves. Liquidity providers can receive boosted CRV and liquidity mining rewards with minimal effort.',
    bridge: 'native',
    logoURI: '',
  },
  cvxFXS: {
    name: 'Convex FXS',
    address: '0xFEEf77d3f69374f66429C91d732A244f074bdf74',
    symbol: 'cvxFXS',
    oracleId: 'cvxFXS',
    decimals: 18,
    chainId: 1,
    website: 'https://frax.convexfinance.com/',
    documentation: 'https://docs.convexfinance.com/',
    description:
      'Convex Finance has expanded to optimize opportunities for liquidity providers on Frax the same way it has done so for Curve.fi LPs.',
    bridge: 'native',
    logoURI: '',
  },
  cvxFPIS: {
    name: 'Convex FPIS',
    address: '0xa2847348b58CEd0cA58d23c7e9106A49f1427Df6',
    symbol: 'cvxFPIS',
    oracleId: 'cvxFPIS',
    decimals: 18,
    chainId: 1,
    website: 'https://frax.convexfinance.com/',
    documentation: 'https://docs.convexfinance.com/',
    description:
      "Convex also now supports Frax Finance's FPIS token, the governance token for the FPI stablecoin launched by Frax. Frax documentation explains the mechanisms behind the FPI stablecoin and the FPIS governance token in detail.",
    bridge: 'native',
    logoURI: '',
  },
  sethUSDC: {
    name: 'Stargate USD Coin LP',
    symbol: 'sethUSDC',
    oracleId: 'stargate-eth-usdc',
    address: '0xdf0770dF86a8034b3EFEf0A1Bb3c889B8332FF56',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0xef4229c8c3250C675F21BCefa42f58EfbfF6002a.svg',
    website: 'https://stargate.finance/',
    description:
      'Stargate allows users and dApps to bridge native tokens with instant guaranteed finality. USDC is deposited in a LP pool to enable high liquidity for bridging.',
    documentation: 'https://stargateprotocol.gitbook.io/stargate/v/user-docs/',
  },
  sethUSDT: {
    name: 'Stargate Tether USD LP',
    symbol: 'sethUSDT',
    oracleId: 'stargate-eth-usdt',
    address: '0x38EA452219524Bb87e18dE1C24D3bB59510BD783',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://tether.to/',
    description:
      'Stargate allows users and dApps to bridge native tokens with instant guaranteed finality. USDT is deposited in a LP pool to enable high liquidity for bridging.',
    documentation: 'https://stargateprotocol.gitbook.io/stargate/v/user-docs/',
  },
  rETH: {
    name: 'Rocket Pool ETH',
    symbol: 'rETH',
    oracleId: 'rETH',
    address: '0xae78736Cd615f374D3085123A210448E74Fc6393',
    chainId: 1,
    decimals: 18,
    website: 'https://rocketpool.net/',
    description:
      'As a Rocket Pool staker, your role is to deposit ETH into the deposit pool which will enable a node operator to create a new Beacon Chain validator. You can stake as little as 0.01 ETH. In doing so, you will be given a token called rETH. rETH represents both how much ETH you deposited, and when you deposited it.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.rocketpool.net/guides/',
  },
  USDT: {
    name: 'Tether USD',
    symbol: 'USDT',
    oracleId: 'USDT',
    address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://tether.to/',
    documentation: 'https://tether.to/en/how-it-works',
    description:
      'Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
    bridge: 'native',
  },
  DOLA: {
    name: 'Dola USD Stablecoin',
    symbol: 'DOLA',
    oracleId: 'DOLA',
    address: '0x865377367054516e17014CcdED1e7d814EDC9ce4',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.inverse.finance/',
    documentation: 'https://docs.inverse.finance/inverse-finance/using-dola/how-to-acquire-dola',
    description:
      'Inverse.finance is a suite of permissionless decentralized finance tools governed by Inverse DAO, a decentralized autonomous organization running on the Ethereum blockchain.',
    bridge: 'native',
  },
  sETH: {
    name: 'Synth sETH',
    symbol: 'sETH',
    oracleId: 'sETH',
    address: '0x5e74C9036fb86BD7eCdcb084a0673EFc32eA31cb',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://synthetix.io/',
    description:
      'Synths are derivative tokens providing exposure to a range of assets. They can be traded with infinite liquidity and zero slippage by leveraging the Synthetix protocol’s unique pooled collateral model. Trades between Synths generate a small fee that is distributed to SNX collateral providers.',
    bridge: 'native',
  },
  cbETH: {
    name: 'Coinbase Wrapped Staked ETH',
    symbol: 'cbETH',
    oracleId: 'cbETH',
    address: '0xBe9895146f7AF43049ca1c1AE358B0541Ea49704',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://help.coinbase.com/en/coinbase/trading-and-funding/staking-rewards/cbeth',
    description:
      "Coinbase Wrapped Staked ETH (“cbETH”) is a utility token that represents Ethereum 2 (ETH2), which is ETH staked through Coinbase. Over time, the price of cbETH will likely deviate from ETH because cbETH represents 1 staked ETH plus all of its accrued staking interest starting from when cbETH's conversion rate and balance were initialized (June 16, 2022 19:34 UTC). cbETH is minted exclusively by Coinbase.",
    bridge: 'native',
    documentation: 'https://www.coinbase.com/price/coinbase-wrapped-staked-eth#AboutSection',
  },
  USDD: {
    name: 'Decentralized USD',
    symbol: 'USDD',
    oracleId: 'USDD',
    address: '0x0C10bF8FcB7Bf5412187A595ab97a3609160b5c6',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://usdd.io/',
    description:
      'The USDD protocol aims to provide the blockchain industry with the most stable, decentralized, tamper-proof, and freeze-free stablecoin system, a perpetual system independent from any centralized entity.',
    bridge: 'bittorent',
    documentation: 'https://usdd.io/docs/',
  },
  aUSDT: {
    name: 'Aave Tether USD',
    symbol: 'aUSDT',
    oracleId: 'aUSDT',
    address: '0x23878914EFE38d27C4D67Ab83ed1b93A74D4086a',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://tether.to/',
    description:
      'Aave interest bearing USDT. Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
  },
  sethETH: {
    name: 'Stargate Ethereum LP',
    symbol: 'sethETH',
    oracleId: 'stargate-eth-eth',
    address: '0x101816545F6bd2b1076434B54383a1E633390A2E',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x2170ed0880ac9a755fd29b2688956bd959f933f8.png',
    website: 'https://stargate.finance/',
    description:
      'Stargate allows users and dApps to bridge native tokens with instant guaranteed finality. ETH is deposited in a LP pool to enable high liquidity for bridging.',
    documentation: 'https://stargateprotocol.gitbook.io/stargate/v/user-docs/',
  },
  waUSDT: {
    name: 'Wrapped Aave Tether USD',
    symbol: 'waUSDT',
    oracleId: 'waUSDT',
    address: '0x65799b9fD4206CdaA4A1DB79254FCbc2Fd2fFEe6',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://tether.to/',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Wrapped Aave interest bearing USDT. Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
  },
  bbaUSDT: {
    name: 'Balancer Aave USDT Linear Pool',
    symbol: 'bbaUSDT',
    oracleId: 'bbaUSDT',
    address: '0xcfAE6E251369467F465f13836Ac8135bd42f8A56',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 USDT and wrapped Aave Interest Bearing USDT.',
  },
  aUSDC: {
    name: 'Aave USDC',
    symbol: 'aUSDC',
    oracleId: 'aUSDC',
    address: '0x98C23E9d8f34FEFb1B7BD6a91B7FF122F4e16F5c',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://www.circle.com/usdc',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Aave interest bearing USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
  },
  waUSDC: {
    name: 'Wrapped Aave Tether USD',
    symbol: 'waUSDC',
    oracleId: 'waUSDC',
    address: '0x02c2d189b45CE213a40097b62D311cf0dD16eC92',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://www.circle.com/usdc',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Wrapped Aave interest bearing USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
  },
  bbaUSDC: {
    name: 'Balancer Aave USDC Linear Pool',
    symbol: 'bbaUSDC',
    oracleId: 'bbaUSDC',
    address: '0xc50d4347209F285247BDa8A09Fc1C12CE42031c3',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 USDC and wrapped Aave Interest Bearing USDC.',
  },
  DAI: {
    name: 'DAI Stablecoin',
    symbol: 'DAI',
    oracleId: 'DAI',
    address: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://makerdao.com/en/',
    documentation:
      'https://docs.makerdao.com/smart-contract-modules/dai-module/dai-detailed-documentation',
    description:
      'Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain',
    bridge: 'native',
  },
  aDAI: {
    name: 'Aave DAI',
    symbol: 'aDAI',
    oracleId: 'aDAI',
    address: '0x018008bfb33d285247A21d44E50697654f754e63',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://makerdao.com/en/',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Aave interest bearing DAI. Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain.',
  },
  waDAI: {
    name: 'Wrapped Aave Tether DAI',
    symbol: 'waDAI',
    oracleId: 'waDAI',
    address: '0xEb708639E8e518B86a916db3685f90216b1C1c67',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://makerdao.com/en/',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Wrapped Aave interest bearing DAI. Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain.',
  },
  bbaDAI: {
    name: 'Balancer Aave DAI Linear Pool',
    symbol: 'bbaDAI',
    oracleId: 'bbaDAI',
    address: '0xfa24A90A3F2bBE5FEEA92B95cD0d14Ce709649f9',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 DAI and wrapped Aave Interest Bearing DAI.',
  },
  aETH: {
    name: 'Aave ETH',
    symbol: 'aETH',
    oracleId: 'aETH',
    address: '0x4d5F47FA6A74757f35C14fD3a6Ef8E3C9BC514E8',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://weth.io/',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Aave interest bearing DAI. Ether or ETH is the native currency built on the Ethereum blockchain.',
    bridge: 'native',
  },
  waETH: {
    name: 'Wrapped Aave Tether ETH',
    symbol: 'waETH',
    oracleId: 'waETH',
    address: '0x03928473f25bb2da6Bc880b07eCBaDC636822264',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://weth.io/',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Wrapped Aave interest bearing ETH. Ether or ETH is the native currency built on the Ethereum blockchain.',
    bridge: 'native',
  },
  bbaETH: {
    name: 'Balancer Aave ETH Linear Pool',
    symbol: 'bbaETH',
    oracleId: 'bbaETH',
    address: '0xbB6881874825E60e1160416D6C426eae65f2459E',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description: 'Balancer linear pool that consist of ETH and wrapped Aave Interest Bearing ETH.',
    bridge: 'native',
  },
  bbaUSD: {
    name: 'Balancer Aave Stable Composable Pool',
    symbol: 'bbaUSD',
    oracleId: 'bbaUSD',
    address: '0xc443C15033FCB6Cf72cC24f1BDA0Db070DdD9786',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    bridge: 'native',
    description:
      'Balancer composable pool that consist of bbaUSDT, bbaUSDC, and bbaDAI. bbTokens are Aave boosted linear pools.',
  },
  frxETH: {
    name: 'Frax Ether',
    symbol: 'frxETH',
    oracleId: 'frxETH',
    address: '0x5E8422345238F34275888049021821E8E08CAa1f',
    chainId: 1,
    decimals: 18,
    website: 'https://app.frax.finance/frxeth/mint',
    description:
      'frxETH acts as a stablecoin loosely pegged to ETH, so that 1 frxETH always represents 1 ETH and the amount of frxETH in circulation matches the amount of ETH in the Frax ETH system. When ETH is sent to the frxETHMinter, an equivalent amount of frxETH is minted. Holding frxETH on its own is not eligible for staking yield and should be thought of as analogous as holding ETH.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth',
  },
  sfrxETH: {
    name: 'Staked Frax Ether',
    symbol: 'sfrxETH',
    oracleId: 'sfrxETH',
    address: '0xac3E018457B222d93114458476f3E3416Abbe38F',
    chainId: 1,
    decimals: 18,
    website: 'https://app.frax.finance/frxeth/mint',
    description:
      'sfrxETH is a ERC-4626 vault designed to accrue the staking yield of the Frax ETH validators. At any time, frxETH can be exchanged for sfrxETH by depositing it into the sfrxETH vault, which allows users to earn staking yield on their frxETH. Over time, as validators accrue staking yield, an equivalent amount of frxETH is minted and added to the vault, allowing users to redeem their sfrxETH for an greater amount of frxETH than they deposited. ',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth',
  },
  INV: {
    name: 'Inverse Finance',
    symbol: 'INV',
    oracleId: 'INV',
    address: '0x41D5D79431A913C4aE7d69a668ecdfE5fF9DFB68',
    chainId: 1,
    decimals: 18,
    website: 'https://www.inverse.finance/',
    documentation: 'https://docs.inverse.finance/inverse-finance/about-inverse',
    description:
      'Inverse.finance is a suite of permissionless decentralized finance tools governed by Inverse DAO, a decentralized autonomous organization running on the Ethereum blockchain.',
    logoURI: 'https://assets.spookyswap.finance/tokens/INV.png',
  },
  ACX: {
    name: 'Across Protocol Token',
    symbol: 'ACX',
    oracleId: 'ACX',
    address: '0x44108f0223A3C3028F5Fe7AEC7f9bb2E66beF82F',
    chainId: 1,
    decimals: 18,
    website: 'https://across.to/',
    documentation: 'https://docs.across.to/',
    description:
      'Across is a cross-chain bridge for L2s and rollups secured by UMAs optimistic oracle. It is optimized for capital efficiency with a single liquidity pool, a competitive relayer landscape, and a no-slippage fee model.',
    logoURI: '',
  },
  'BAL-WETH-80-20': {
    name: 'Balancer Pool Token BAL-WETH 80/20',
    symbol: 'BAL-WETH-80-20',
    oracleId: 'BAL-WETH-80-20',
    address: '0x5c6Ee304399DBdB9C8Ef030aB642B10820DB8F56',
    chainId: 1,
    decimals: 18,
    website: 'https://app.balancer.fi/',
    description:
      'Instead of locking pure BAL, users obtain veBAL by locking 80/20 BAL/WETH Balancer Pool Tokens (BPTs). This ensures that even if a large portion of BAL tokens are locked, there is deep trading liquidity.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.balancer.fi/ecosystem/vebal-and-gauges/vebal',
  },
  SUSHI: {
    name: 'SushiToken',
    symbol: 'SUSHI',
    oracleId: 'SUSHI',
    address: '0x6B3595068778DD592e39A122f4f5a5cF09C90fE2',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x6B3595068778DD592e39A122f4f5a5cF09C90fE2.svg',
    website: 'https://sushi.com/',
    description:
      'Sushi is the home of DeFi. Their community is building a comprehensive, decentralized trading platform for the future of finance. Swap, earn, stack yields, lend, borrow, leverage all on one decentralized, community driven platform.',
    bridge: 'native',
    documentation: 'https://dev.sushi.com/',
  },
  ILV: {
    name: 'Illuvium',
    symbol: 'ILV',
    oracleId: 'ILV',
    address: '0x767FE9EDC9E0dF98E07454847909b5E959D7ca0E',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x767FE9EDC9E0dF98E07454847909b5E959D7ca0E.svg',
    website: 'https://illuvium.io/',
    description:
      'A fully decentralized protocol, Illuvium represents a new age in gaming. It has been engineered from the ground-up to support the long-term sustainability of the Illuvium game and governance and provide players with a AAA-rated blockchain gaming experience. What makes Illuvium unique is that stakers receive regular distributions and can vote on everything from tokenomics related issues to the features in the game itself. With Illuvium, the power to define the project into the future is purposefully left to those who stake in the protocol.',
    documentation: 'https://docs.illuvium.io/',
  },
  LDO: {
    name: 'Lido DAO Token',
    symbol: 'LDO',
    oracleId: 'LDO',
    address: '0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32.svg',
    website: 'https://stake.lido.fi/',
    documentation: 'https://docs.lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH 2.0 backed by industry-leading staking providers.',
    bridge: 'native',
  },
  SYN: {
    name: 'Synapse',
    symbol: 'SYN',
    oracleId: 'SYN',
    address: '0x0f2D719407FdBeFF09D87557AbB7232601FD9F29',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x0f2D719407FdBeFF09D87557AbB7232601FD9F29.svg',
    website: 'https://synapseprotocol.com/landing',
    description:
      'Synapse is a universal interoperability protocol that enables secure cross-chain communication. Synapse connects blockchains by offering an extensible cross-chain messaging protocol that supports assets, smart contract calls, and more. By leveraging Synapse, blockchains can easily and securely interoperate with each other and developers can build truly cross-chain applications including cross-chain DEX, lending platforms, margining systems, derivatives markets, yield aggregators, and much more.',
    bridge: 'native',
    documentation: 'https://docs.synapseprotocol.com/',
  },
  SOLID: {
    name: 'Solidly',
    symbol: 'SOLID',
    oracleId: 'SOLID',
    address: '0x777172D858dC1599914a1C4c6c9fC48c99a60990',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://solidly.com/',
    description:
      'Solidly is an AMM allowing fully decentralized token swapping with support for low slippage trades between pegged assets like stablecoins.',
    bridge: 'native',
    documentation: '',
  },
  SNX: {
    name: 'Synthetix Network Token',
    symbol: 'SNX',
    oracleId: 'SNX',
    address: '0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.synthetix.io/',
    description:
      'Synthetix is the backbone for derivatives trading in DeFi, allowing anyone, anywhere to gain on-chain exposure to a vast range of assets',
    documentation: 'https://docs.synthetix.io/synthetix-protocol/welcome-to-synthetix',
  },
  HEX: {
    name: 'HEX',
    symbol: 'HEX',
    oracleId: 'HEX',
    address: '0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39',
    chainId: 1,
    decimals: 8,
    logoURI: '',
    website: 'https://hex.com/',
    description: 'HEX is the first high-yield blockchain certificate of deposit',
    documentation: 'https://hex.com/faq/',
  },
  moSOLID: {
    name: 'moSOLID: Tokenized veSOLID',
    symbol: 'moSOLID',
    oracleId: 'moSOLID',
    address: '0x848578e351D25B6Ec0d486E42677891521c3d743',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://alpha.mono.farm/home',
    description: 'A tokenized version of veSOLID, moSOLID, is returned to the user at a 1:1 rate.',
    documentation: 'https://docs.mono.farm/monolith-documentation/',
  },
  FTM: {
    name: 'Fantom Token',
    symbol: 'FTM',
    oracleId: 'FTM',
    address: '0x4E15361FD6b4BB609Fa63C81A2be19d873717870',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://fantom.foundation/',
    description:
      'Fantom is a fast, high-throughput open-source smart contract platform for digital assets and dApps.',
    documentation: '',
  },
  DEUS: {
    name: 'DEUS',
    symbol: 'DEUS',
    oracleId: 'DEUS',
    address: '0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44',
    chainId: 1,
    decimals: 18,
    website: 'https://deus.finance/',
    description:
      'DEUS Finance Evolution is a marketplace of decentralized financial services. We provide the infrastructure for others to build financial instruments, such as synthetic stock trading platforms, options and futures trading, and more.',
    logoURI: 'https://app.deus.finance/tokens/deus.svg',
    documentation: 'https://docs.deus.finance/',
  },
  GEAR: {
    name: 'Gearbox',
    symbol: 'GEAR',
    oracleId: 'GEAR',
    address: '0xBa3335588D9403515223F109EdC4eB7269a9Ab5D',
    chainId: 1,
    decimals: 18,
    website: 'https://gearbox.fi/',
    description:
      'Gearbox Protocol allows anyone to take DeFi-native leverage and then use it across various (DeFi & more) protocols. This enables you to compose your position as you want. You take leverage with Gearbox and then use it on other protocols you already love: Uniswap, Curve, Convex, Lido, etc. For example, you can leverage trade on Uniswap, leverage farm on Yearn, make delta-neutral strategies, hedge your exposure, get Leverage-as-a-Service for your structured product, and more... ',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.gearbox.finance/',
  },
  TUSD: {
    name: 'TrueUSD',
    symbol: 'TUSD',
    oracleId: 'TUSD',
    address: '0x0000000000085d4780B73119b644AE5ecd22b376',
    chainId: 1,
    decimals: 18,
    website: 'https://trueusd.com/',
    description: 'The first regulated stablecoin fully backed by the US Dollar.',
    bridge: 'native',
    logoURI: '',
  },
  CLEV: {
    name: 'CLever Token',
    symbol: 'CLEV',
    oracleId: 'CLEV',
    address: '0x72953a5C32413614d24C29c84a66AE4B59581Bbf',
    chainId: 1,
    decimals: 18,
    website: 'https://clever.aladdin.club/',
    description:
      'Deposit top quality tokens to CLever in high-yielding collateral strategies, then claim your future yields today. Your future yields can be farmed, re-deposited to create leverage, or used wherever you need them.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.aladdin.club/clever',
  },
  clevCVX: {
    name: 'CLever CVX',
    symbol: 'clevCVX',
    oracleId: 'clevCVX',
    address: '0xf05e58fCeA29ab4dA01A495140B349F8410Ba904',
    chainId: 1,
    decimals: 18,
    website: 'https://clever.aladdin.club/',
    description:
      'Deposit top quality tokens to CLever in high-yielding collateral strategies, then claim your future yields today. Your future yields can be farmed, re-deposited to create leverage, or used wherever you need them.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.aladdin.club/clever',
  },
  yCRV: {
    name: 'Yearn: yCRV Token',
    symbol: 'yCRV',
    oracleId: 'yCRV',
    address: '0xFCc5c47bE19d06BF83eB04298b026F81069ff65b',
    chainId: 1,
    decimals: 18,
    website: 'https://yearn.finance/ycrv',
    description:
      "yCRV is Yearn's new and improved veCRV wrapper system designed to tokenize the different benefits of Yearn's veCRV position.",
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.yearn.finance/getting-started/products/ycrv/overview',
  },
  eUSD: {
    name: 'Electronic USD',
    symbol: 'eUSD',
    oracleId: 'eUSD',
    address: '0xA0d69E286B938e21CBf7E51D71F6A4c8918f482F',
    chainId: 1,
    decimals: 18,
    website: 'https://register.app/',
    description:
      'Electronic Dollar (eUSD) is a safety-first stablecoin that brings together diversified, highly liquid backing with extra anti-bank run overcollateralization. \neUSD is asset-backed by yield bearing Aave USDT, Compound USDT, Aave USDC and Compound USDC. eUSD is available natively on Ethereum mainnet and the MobileCoin L1, and can be bridged to any blockchain.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://reserve.org/protocol/',
  },
  msETH: {
    name: 'Metronome Synth ETH',
    symbol: 'msETH',
    oracleId: 'msETH',
    address: '0x64351fC9810aDAd17A690E4e1717Df5e7e085160',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.metronome.io/',
    description:
      'A complete synthetic protocol that enables users to generate a variety of synthetics using crypto assets as collateral',
    documentation: 'https://docs.metronome.io/metronome-2.0/master',
  },
  BLUR: {
    name: 'Blur',
    symbol: 'BLUR',
    oracleId: 'BLUR',
    address: '0x5283D291DBCF85356A21bA090E6db59121208b44',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://blur.io/',
    description:
      'Sweep NFTs across multiple marketplaces, snipe reveals faster than others, and manage your portfolio with advanced analytics. Zero fees.',
  },
  msUSD: {
    name: 'Metronome Synth USD',
    symbol: 'msUSD',
    oracleId: 'msUSD',
    address: '0xab5eB14c09D416F0aC63661E57EDB7AEcDb9BEfA',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.metronome.io/',
    description:
      'A complete synthetic protocol that enables users to generate a variety of synthetics using crypto assets as collateral',
    documentation: 'https://docs.metronome.io/metronome-2.0/master',
  },
  UZD: {
    name: 'UZD Zunami Stable',
    symbol: 'UZD',
    oracleId: 'UZD',
    address: '0xb40b6608B2743E691C9B54DdBDEe7bf03cd79f1c',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.zunami.io/',
    description:
      'UZD is a rebase token that increases in value in proportion to the APY of the Zunami Protocol. It is over-collateralized by stablecoins allocated in Curve Finance pools and minted using ZLP. UZD is secure from depeg as it can be redeemed with USDT, USDC, or DAI at any time. Users can receive UZD by minting it through the Zunami interface or by swapping it in the Curve.',
    documentation: 'https://zunamilab.gitbook.io/product-docs/',
  },
  lvUSD: {
    name: 'lvUSD',
    symbol: 'lvUSD',
    oracleId: 'lvUSD',
    address: '0x94A18d9FE00bab617fAD8B49b11e9F1f64Db6b36',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://archimedesfi.com/',
    description:
      'The stablecoin lvUSD is pegged to the USD and is used for lending and repaying loans.\n' +
      'When liquidity providers (LPs) deposit 3CRV, Archimedes borrows lvUSD on behalf of leverage takers (LTs) and uses it to enter a strategy. Investing in the 3CRV/lvUSD pool gives LPs exposure to both 3CRV and the collateral provided by LTs. This allows the market to decide on the best investment strategy.',
    bridge: 'native',
    documentation: 'https://docs.archimedesfi.com/',
  },
  bbeUSDT: {
    name: 'Balancer Euler USDT Linear Pool',
    symbol: 'bbeUSDT',
    oracleId: 'bbeUSDT',
    address: '0x3C640f0d3036Ad85Afa2D5A9E32bE651657B874F',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description: 'Balancer linear pool that consist of 50/50 USDT and Euler Interest Bearing USDT.',
  },
  bbeUSDC: {
    name: 'Balancer Euler USDC Linear Pool',
    symbol: 'bbeUSDC',
    oracleId: 'bbeUSDC',
    address: '0xD4e7C1F3DA1144c9E2CfD1b015eDA7652b4a4399',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 USDC and wrapped Euler Interest Bearing USDC.',
  },
  bbeDAI: {
    name: 'Balancer Euler DAI Linear Pool',
    symbol: 'bbeDAI',
    oracleId: 'bbeDAI',
    address: '0xeB486AF868AeB3b6e53066abc9623b1041b42bc0',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 DAI and wrapped Euler Interest Bearing DAI.',
  },
  bbeUSD: {
    name: 'Balancer Euler Stable Composable Pool',
    symbol: 'bbeUSD',
    oracleId: 'bbeUSD',
    address: '0x50Cf90B954958480b8DF7958A9E965752F627124',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer composable pool that consist of bbeUSDT, bbeUSDC, and bbeDAI. bbTokens are Euler boosted linear pools.',
  },
  VERSE: {
    name: 'Verse',
    symbol: 'VERSE',
    oracleId: 'VERSE',
    address: '0x249cA82617eC3DfB2589c4c17ab7EC9765350a18',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://verse.bitcoin.com/',
    description:
      'At Bitcoin.com our mission is to create more economic freedom in the world. We define economic freedom as the ability to make choices with respect to one’s personal resources, unencumbered by trusted third parties or borders or lack of access. We believe economic freedom is the foundation of peace and prosperity, and by creating more of it for people, we are reducing suffering in the world. We strive to help everyone, everywhere be more economically free.',
    bridge: 'native',
    documentation: 'https://www.getverse.com/verse-whitepaper.pdf',
  },
  APE: {
    name: 'ApeCoin',
    address: '0x4d224452801ACEd8B2F0aebE155379bb5D594381',
    symbol: 'APE',
    oracleId: 'APE',
    decimals: 18,
    chainId: 1,
    website: 'https://apecoin.com/',
    description:
      'ApeCoin is the APE Ecosystems governance token, allowing token holders to participate in ApeCoin DAO and giving its participants a shared and open currency that can be used without centralized intermediaries.',
    bridge: 'native',
    logoURI: '',
  },
  OHM: {
    name: 'Olympus',
    address: '0x64aa3364F17a4D01c6f1751Fd97C2BD3D7e7f1D5',
    symbol: 'OHM',
    oracleId: 'OHM',
    decimals: 9,
    chainId: 1,
    website: 'https://www.olympusdao.finance/',
    description:
      'Olympus is building OHM, a community-owned, decentralized and censorship-resistant reserve currency that is asset-backed, deeply liquid and used widely across Web3.',
    bridge: 'native',
    logoURI: '',
    documentation: 'https://docs.olympusdao.finance/',
  },
  SD: {
    name: 'Stader',
    symbol: 'SD',
    oracleId: 'SD',
    address: '0x30D20208d987713f46DFD34EF128Bb16C404D10f',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x3BC5AC0dFdC871B365d159f728dd1B9A0B5481E8.svg',
    website: 'https://staderlabs.com/',
    description: 'Stader (SD) token is the native governance and value accrual token for Stader.',
    bridge: 'native',
    documentation: 'https://docs-new.staderlabs.com/intro',
  },
  FXS: {
    name: 'Frax Share',
    symbol: 'FXS',
    oracleId: 'FXS',
    address: '0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://frax.finance/',
    description:
      'The Frax Protocol introduced the world to the concept of a cryptocurrency being partially backed by collateral and partially stabilized algorithmically.',
    bridge: 'native',
  },
  wBETH: {
    name: 'Wrapped Binance Beacon ETH',
    symbol: 'wBETH',
    oracleId: 'wBETH',
    address: '0xa2E3356610840701BDf5611a53974510Ae27E2e1',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.binance.com/en',
    documentation: 'https://www.binance.com/en/wbeth',
    description:
      'Wrapped Beacon ETH ("WBETH") is a wrapped version of BETH. Wrapped, WBETH is reward-bearing in nature. It accumulates ETH2.0 staking rewards not by growing in number, but by growing in value in relation to BETH. Unlike BETH, the value of WBETH will increase despite not being held in Binance Spot Wallet. That means WBETH provides you with double yield potential by (i) holding it to earn staking rewards, and (ii) moving it on-chain and exploring exciting DeFi and other dapps opportunities.',
    bridge: 'native',
  },
  OETH: {
    name: 'Origin Ether',
    symbol: 'OETH',
    oracleId: 'OETH',
    address: '0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.oeth.com/',
    documentation: 'https://docs.oeth.com/',
    description:
      'OETH is a yield-bearing, ether-pegged token, offering an easy way to maximize yield from ETH staking using protocols, such as Curve Finance.',
    bridge: 'native',
  },
  crvUSD: {
    name: 'Curve.Fi USD Stablecoin',
    symbol: 'crvUSD',
    oracleId: 'crvUSD',
    address: '0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://crvusd.curve.fi/',
    description:
      'crvUSD is a collateralized-debt-position (CDP) stablecoin pegged to the US Dollar',
    bridge: 'native',
    documentation: 'https://docs.curve.fi/crvUSD/overview/',
  },
  hyUSD: {
    name: 'High Yield USD',
    symbol: 'hyUSD',
    oracleId: 'hyUSD',
    address: '0xaCdf0DBA4B9839b96221a8487e9ca660a48212be',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://register.app/#/overview?token=0xaCdf0DBA4B9839b96221a8487e9ca660a48212be',
    description:
      'High yield USD (hyUSD), is a decentralized flatcoin initially pegged to $1 USD that provides convenient access to DeFi yields, enabling holders to grow and preserve their wealth. hyUSD is 1:1 asset backed by a basket of other yield bearing tokens including eUSD as well as tokenized lending with exposure to US Treasuries. Given the unique design and current market conditions it is estimated to yield 8% or better to anyone holding hyUSD in any wallet, outpacing the rate of inflation in over 100 countries around the world and providing safe refuge for purchasing power everywhere.',
  },
  ETHx: {
    name: 'ETHx',
    symbol: 'ETHx',
    oracleId: 'ETHx',
    address: '0xA35b1B31Ce002FBF2058D22F30f95D405200A15b',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.staderlabs.com/eth/',
    bridge: 'native',
    description:
      "ETHx is an innovative liquid staking token developed by Stader, designed to revolutionize Ethereum staking. Stader's vision for ETHx is to transform the staking experience, providing users with the unprecedented freedom to move and utilize their staked ETH while continuing to earn rewards and engage with the growing DeFi ecosystem.",
    documentation: 'https://staderlabs.gitbook.io/ethereum',
  },
  'ETH+': {
    name: 'ETHPlus',
    symbol: 'ETH+',
    oracleId: 'ETH+',
    address: '0xE72B141DF173b999AE7c1aDcbF60Cc9833Ce56a8',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://register.app/#/overview?token=0xE72B141DF173b999AE7c1aDcbF60Cc9833Ce56a8',
    bridge: 'native',
    description:
      'Safety-first diversified ETH staking index with up to 4.5% APY backed by Lido Staked ETH and Rocket Pool ETH.',
  },
  'USDC+': {
    name: 'USDC Plus',
    symbol: 'USDC+',
    oracleId: 'USDC+',
    address: '0xFc0B1EEf20e4c68B3DCF36c4537Cfa7Ce46CA70b',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://register.app/#/overview?token=0xFc0B1EEf20e4c68B3DCF36c4537Cfa7Ce46CA70b',
    bridge: 'native',
    description:
      'USDC PLUS (USDC+): A community governed yield bearing USDC index optimized for yield to holders and overcollateralization protection.',
  },
  '3CRV': {
    name: 'Curve.fi DAI/USDC/USDT',
    symbol: '3CRV',
    address: '0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://curve.fi/',
    oracle: 'lps',
    oracleId: 'convex-3pool',
    description: 'Curve base 3pool consisting of DAI, USDC and USDT',
    bridge: 'native',
  },
  R: {
    name: 'R Stablecoin',
    symbol: 'R',
    oracleId: 'R',
    address: '0x183015a9bA6fF60230fdEaDc3F43b3D788b13e21',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://raft.fi',
    documentation: 'https://docs.raft.fi/',
    bridge: 'native',
    description:
      'Raft is a governance-minimized, decentralized protocol that allows people to generate R (a USD stablecoin) by depositing  capital-efficient collateral.',
  },
  GHO: {
    name: 'GHO Token',
    symbol: 'GHO',
    oracleId: 'GHO',
    address: '0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://aave.com/',
    documentation: 'https://docs.aave.com/faq/gho-stablecoin',
    bridge: 'native',
    description:
      'GHO is a decentralized multi-collateral stablecoin that is fully backed, transparent and native to the Aave Protocol.',
  },
  mkUSD: {
    name: 'Prisma mkUSD',
    symbol: 'mkUSD',
    oracleId: 'mkUSD',
    address: '0x4591DBfF62656E7859Afe5e45f6f47D3669fBB28',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.prismafinance.com/',
    documentation: 'https://docs.prismafinance.com/',
    bridge: 'native',
    description:
      'Prisma is a decentralized borrowing protocol that allows users to mint a stablecoin, mkUSD, that is fully collateralized by liquid staking tokens.',
  },
  ULTRA: {
    name: 'ULTRA',
    symbol: 'ULTRA',
    oracleId: 'ULTRA',
    address: '0x35282d87011f87508D457F08252Bc5bFa52E10A0',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.prismafinance.com/',
    documentation: 'https://docs.prismafinance.com/',
    bridge: 'native',
    description:
      'ULTRA is a new stablecoin issued by PrismaLRT, a new borrowing protocol developed by Prisma focused on unlocking liquidity for Liquid Restaking Tokens (LRTs).',
  },
  PYUSD: {
    name: 'PayPal USD',
    symbol: 'PYUSD',
    oracleId: 'PYUSD',
    address: '0x6c3ea9036406852006290770BEdFcAbA0e23A0e8',
    chainId: 1,
    decimals: 6,
    logoURI: '',
    website: 'https://www.paypal.com/us/digital-wallet/manage-money/crypto/pyusd',
    bridge: 'native',
    description: 'PayPal USD (PYUSD) is a stablecoin backed by secure and highly liquid assets.',
  },
  PYUSDUSDC: {
    name: 'PayPool',
    symbol: 'PYUSDUSDC',
    oracle: 'lps',
    oracleId: 'curve-paypool',
    address: '0x383E6b4437b59fff47B619CBA855CA29342A8559',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://curve.fi/#/ethereum/pools/factory-stable-ng-43/deposit',
    description: 'Curve base pool consisting of PYUSD and USDC',
    bridge: 'native',
  },
  PRISMA: {
    name: 'Prisma Governance Token',
    symbol: 'PRISMA',
    oracleId: 'PRISMA',
    address: '0xdA47862a83dac0c112BA89c6abC2159b95afd71C',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.prismafinance.com/',
    documentation: 'https://docs.prismafinance.com/',
    bridge: 'native',
    description:
      'Prisma is a decentralized borrowing protocol that allows users to mint a stablecoin, mkUSD, that is fully collateralized by liquid staking tokens.',
  },
  cvxPRISMA: {
    name: 'Convex Prisma',
    symbol: 'cvxPRISMA',
    oracleId: 'cvxPRISMA',
    address: '0x34635280737b5BFe6c7DC2FC3065D60d66e78185',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://prisma.convexfinance.com/',
    documentation:
      'https://docs.convexfinance.com/convexfinance/general-information/convex-for-prisma-finance',
    bridge: 'native',
    description:
      'Convex Finance has expanded to optimize opportunities for liquidity providers on Prisma the same way it has done so for Curve.fi LPs.',
  },
  yPRISMA: {
    name: 'Yearn Prisma',
    symbol: 'yPRISMA',
    oracleId: 'yPRISMA',
    address: '0xe3668873D944E4A949DA05fc8bDE419eFF543882',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://yprisma.yearn.fi/',
    documentation: 'https://docs.yearn.fi/getting-started/products/ylockers/yprisma/overview',
    bridge: 'native',
    description:
      "yPRISMA is Yearn's latest liquid locker, built for Prisma Finance's governance token.",
  },
  LUSD: {
    name: 'LUSD Stablecoin',
    symbol: 'LUSD',
    oracleId: 'LUSD',
    address: '0x5f98805A4E8be255a32880FDeC7F6728C6568bA0',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.liquity.org/',
    bridge: 'native',
    description:
      'Liquity is a decentralized borrowing protocol that allows you to draw interest-free loans against Ether used as collateral. Loans are paid out in LUSD (a USD pegged stablecoin) and need to maintain a minimum collateral ratio of 110%.',
    documentation: 'https://docs.liquity.org/',
  },
  sDAI: {
    name: 'Savings DAI',
    symbol: 'sDAI',
    oracleId: 'sDAI',
    address: '0x83F20F44975D03b1b09e64809B757c47f942BEeA',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.sparkprotocol.io/sdai/',
    documentation: 'https://docs.sparkprotocol.io/hub/',
    description:
      'sDAI is similar to DAI but with the added benefit of earning interest. You can use it just like DAI - own, transfer, and use it in the DeFi ecosystem. Swapping between sDAI and DAI incurs no additional costs and no slippage as is deposited or withdrawn from the DSR contract.',
    bridge: 'native',
  },
  bbsDAI: {
    name: 'Balancer Aave sDAI Linear Pool',
    symbol: 'bbsDAI',
    oracleId: 'bbsDAI',
    address: '0x2B218683178d029BAB6c9789b1073aA6c96E5176',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description: 'Balancer linear pool that consist of DAI and sDAI.',
    bridge: 'native',
  },
  acUSDC: {
    name: 'Across USD Coin LP',
    address: '0xC9b09405959f63F72725828b5d449488b02be1cA',
    symbol: 'acUSDC',
    oracle: 'lps',
    oracleId: 'across-usdc',
    decimals: 6,
    website: 'https://across.to/',
    description:
      "acUSDC is the LP receipt for providing USDC liquidity to the Across bridge. Across is a cross-chain bridge for L2s and rollups secured by UMA's optimistic oracle.",
    bridge: 'native',
    chainId: 1,
    logoURI: '',
    documentation: 'https://docs.across.to/how-to-use-across/providing-liquidity',
  },
  acWETH: {
    name: 'Across WETH LP',
    address: '0x28F77208728B0A45cAb24c4868334581Fe86F95B',
    symbol: 'acWETH',
    oracle: 'lps',
    oracleId: 'across-weth',
    decimals: 18,
    website: 'https://across.to/',
    description:
      "acWETH is the LP receipt for providing WETH liquidity to the Across bridge. Across is a cross-chain bridge for L2s and rollups secured by UMA's optimistic oracle.",
    bridge: 'native',
    chainId: 1,
    logoURI: '',
    documentation: 'https://docs.across.to/how-to-use-across/providing-liquidity',
  },
  acDAI: {
    name: 'Across DAI LP',
    address: '0x4FaBacAC8C41466117D6A38F46d08ddD4948A0cB',
    symbol: 'acDAI',
    oracle: 'lps',
    oracleId: 'across-dai',
    decimals: 18,
    website: 'https://across.to/',
    description:
      "acDAI is the LP receipt for providing DAI liquidity to the Across bridge. Across is a cross-chain bridge for L2s and rollups secured by UMA's optimistic oracle.",
    bridge: 'native',
    chainId: 1,
    logoURI: '',
    documentation: 'https://docs.across.to/how-to-use-across/providing-liquidity',
  },
  acUSDT: {
    name: 'Across USDT LP',
    address: '0xC2faB88f215f62244d2E32c8a65E8F58DA8415a5',
    symbol: 'acUSDT',
    oracle: 'lps',
    oracleId: 'across-usdt',
    decimals: 6,
    website: 'https://across.to/',
    description:
      "acUSDT is the LP receipt for providing USDT liquidity to the Across bridge. Across is a cross-chain bridge for L2s and rollups secured by UMA's optimistic oracle.",
    bridge: 'native',
    chainId: 1,
    logoURI: '',
    documentation: 'https://docs.across.to/how-to-use-across/providing-liquidity',
  },
  acWBTC: {
    name: 'Across WBTC LP',
    address: '0x59C1427c658E97a7d568541DaC780b2E5c8affb4',
    symbol: 'acWBTC',
    oracle: 'lps',
    oracleId: 'across-wbtc',
    decimals: 8,
    website: 'https://across.to/',
    description:
      "acWBTC is the LP receipt for providing WBTC liquidity to the Across bridge. Across is a cross-chain bridge for L2s and rollups secured by UMA's optimistic oracle.",
    bridge: 'native',
    chainId: 1,
    logoURI: '',
    documentation: 'https://docs.across.to/how-to-use-across/providing-liquidity',
  },
  acACX: {
    name: 'Across ACX LP',
    address: '0xb0C8fEf534223B891D4A430e49537143829c4817',
    symbol: 'acACX',
    oracle: 'lps',
    oracleId: 'across-acx',
    decimals: 18,
    website: 'https://across.to/',
    description:
      "acACX is the LP receipt for providing ACX liquidity to the Across bridge. Across is a cross-chain bridge for L2s and rollups secured by UMA's optimistic oracle.",
    bridge: 'native',
    chainId: 1,
    logoURI: '',
    documentation: 'https://docs.across.to/how-to-use-across/providing-liquidity',
  },
  bpt3POOL: {
    name: 'Balancer 3Pool BPT',
    symbol: 'bpt3POOL',
    oracleId: 'bpt-3POOL',
    address: '0x79c58f70905F734641735BC61e45c19dD9Ad60bC',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/concepts/pools/composable-stable.html',
    description:
      'Composable Stable Pools are designed for assets that are either expected to consistently swap at near parity, or at a known exchange rate. Composable Stable Pools use Stable Math (based on StableSwap, popularized by Curve) which allows for swaps of significant size before encountering substantial price impact, vastly increasing capital efficiency for like-kind and correlated-kind swaps.',
    bridge: 'native',
  },
  ALCX: {
    name: 'Alchemix',
    symbol: 'ALCX',
    oracleId: 'ALCX',
    address: '0xdBdb4d16EdA451D0503b854CF79D55697F90c8DF',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://alchemix.fi/',
    documentation: 'https://alchemix-finance.gitbook.io/user-docs/',
    description:
      'Alchemix Finance is a future-yield-backed synthetic asset protocol and community DAO. The protocol gives you advances on various yield farming strategies via a synthetic token. The token represents a fungible claim on the underlying collateral in the Alchemix protocol, where the claim has to be made by a depositor of that collateral. The DAO will focus on funding projects that will help the Alchemix ecosystem grow, as well as the greater Ethereum community.',
    bridge: 'native',
  },
  RPL: {
    name: 'Rocket Pool',
    symbol: 'RPL',
    oracleId: 'RPL',
    address: '0xD33526068D116cE69F19A9ee46F0bd304F21A51f',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://rocketpool.net/',
    documentation: 'https://rocketpool.net/protocol/about',
    description:
      'Rocket Pool is the oldest, most trusted & only decentralised staking protocol on Ethereum today.',
    bridge: 'native',
  },
  GYD: {
    name: 'Gyro Dollar',
    symbol: 'GYD',
    oracleId: 'GYD',
    address: '0xe07F9D810a48ab5c3c914BA3cA53AF14E4491e8A',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://gyro.finance/',
    documentation: 'https://docs.gyro.finance/gyroscope-protocol/stablecoin',
    description:
      'A fully backed stablecoin: the Gyroscope stablecoin aims at a long-term reserve ratio of 100%, where every unit of stablecoin is backed by 1 USD worth of collateral.',
    bridge: 'native',
  },
  SILO: {
    name: 'Silo Governance Token',
    symbol: 'SILO',
    oracleId: 'SILO',
    address: '0x6f80310CA7F2C654691D1383149Fa1A57d8AB1f8',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.silo.finance/',
    documentation: 'https://devdocs.silo.finance/protocol-architecture/protocol-overview',
    description:
      'Silo is a non-custodial lending protocol to borrow any crypto asset with another.',
    bridge: 'native',
  },
  vETH: {
    name: 'Vector ETH',
    symbol: 'vETH',
    oracleId: 'vETH',
    address: '0x38D64ce1Bdf1A9f24E0Ec469C9cAde61236fB4a0',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.vectorreserve.com/',
    description:
      'vETH is a tokenized asset or index of ETH denominated Liquidity Positions (LP) against Liquid Staked Tokens (LST) and Liquid Restaked Tokens (LRT), that encapsulates both ETH and additional yield-generating opportunities.',
    documentation:
      'https://vector-reserve.gitbook.io/vector-reserve/introduction/what-is-vector-reserve',
    bridge: 'native',
  },
  ankrETH: {
    name: 'Ankr Staked ETH',
    symbol: 'ankrETH',
    oracleId: 'ankrETH',
    address: '0xE95A203B1a91a908F9B9CE46459d101078c2c3cb',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.ankr.com/',
    description:
      'ankrETH is a liquid staking solution that lets users earn Ethereum staking rewards while remaining liquid. The value of ankrETH tokens appreciates over time in relation to ETH due to reward accumulation, enhancing capital efficiency and preserving liquidity.',
    documentation: 'https://www.ankr.com/docs/liquid-staking/eth/overview/',
    bridge: 'native',
  },
  ezETH: {
    name: 'Renzo Restaked ETH Token',
    symbol: 'ezETH',
    oracleId: 'ezETH',
    address: '0xbf5495Efe5DB9ce00f80364C8B423567e58d2110',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.renzoprotocol.com/',
    description:
      'Renzo ezETH is a Liquid Restaking Token (LRT) and Strategy Manager for EigenLayer. It is the interface to the EigenLayer ecosystem securing Actively Validated Services (AVSs) and offering a higher yield than ETH staking.',
    documentation: 'https://docs.renzoprotocol.com/docs/',
    bridge: 'native',
    risks: ['NO_TIMELOCK'],
  },
  weETH: {
    name: 'Wrapped eETH',
    symbol: 'weETH',
    oracleId: 'weETH',
    address: '0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.ether.fi/',
    description:
      'ether.fi is a decentralized, non-custodial delegated staking protocol with a Liquid Staking token. One of the distinguishing characteristics of ether.fi is that stakers control their keys. The ether.fi mechanism also allows for the creation of a node services marketplace where stakers and node operators can enroll nodes to provide infrastructure services.',
    documentation: 'https://etherfi.gitbook.io/etherfi',
    bridge: 'native',
    risks: ['NO_TIMELOCK'],
  },
  QIv2: {
    name: 'QiDao',
    symbol: 'QI',
    oracleId: 'QIv2',
    address: '0x559b7bfC48a5274754b08819F75C5F27aF53D53b',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.mai.finance/',
    description:
      'QiDao is an overcollateralized stablecoin protocol that allows users to mint stablecoins (MAI) against the value of their decentralized token collaterals. Minting occurs through loans, denomimated in MAI stablecoins. Most loans have 0% interest, meaning the value of the related debt does not change over time.',
    documentation: 'https://docs.mai.finance/introduction-1',
    bridge: 'native',
  },
  qiBPT: {
    name: 'QiDao Governance Pool',
    symbol: 'QI BPT',
    oracleId: 'beQIv2',
    address: '0x39eB558131E5eBeb9f76a6cbf6898f6E6DCe5e4E',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.mai.finance/',
    description:
      'QiDao is an overcollateralized stablecoin protocol that allows users to mint stablecoins (MAI) against the value of their decentralized token collaterals. Minting occurs through loans, denomimated in MAI stablecoins. Most loans have 0% interest, meaning the value of the related debt does not change over time.',
    documentation: 'https://docs.mai.finance/introduction-1',
    bridge: 'native',
  },
  beQI: {
    name: 'Beefy QI',
    symbol: 'beQI',
    oracleId: 'beQIv2',
    address: '0x6c9D885B37b131aa68794ee1549fFB80be381Fa9',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.mai.finance/',
    description:
      'Beefy QI is perpetually lock QI/ETH Balancer Pool Token. QiDao is an overcollateralized stablecoin protocol that allows users to mint stablecoins (MAI) against the value of their decentralized token collaterals. Minting occurs through loans, denomimated in MAI stablecoins. Most loans have 0% interest, meaning the value of the related debt does not change over time.',
    documentation: 'https://docs.mai.finance/introduction-1',
    bridge: 'native',
  },
  rsETH: {
    chainId: 1,
    address: '0xA1290d69c65A6Fe4DF752f95823fae25cB99e5A7',
    decimals: 18,
    name: 'KelpDao Restaked ETH',
    symbol: 'rsETH',
    oracleId: 'rsETH',
    logoURI: '',
    website: 'https://kelpdao.xyz/',
    documentation: 'https://kelp.gitbook.io/kelp',
    description:
      'rsETH is a Liquid Restaked Token (LRT) issued by Kelp DAO designed to offer liquidity to illiquid assets deposited into restaking platforms, such as EigenLayer.',
    bridge: 'native',
    risks: ['NO_TIMELOCK'],
  },
  rswETH: {
    chainId: 1,
    address: '0xFAe103DC9cf190eD75350761e95403b7b8aFa6c0',
    decimals: 18,
    name: 'KelpDao Restaked ETH',
    symbol: 'rswETH',
    oracleId: 'rswETH',
    logoURI: '',
    website: 'https://www.swellnetwork.io/liquid-restaking',
    documentation: 'https://docs.swellnetwork.io/swell/rsweth-liquid-restaking',
    description:
      'rswETH is a Liquid Restaked Token (LRT) issued by Swell network designed to offer liquidity to illiquid assets deposited into restaking platforms, such as EigenLayer.',
    bridge: 'native',
    risks: ['NO_TIMELOCK'],
  },
} as const;

export const tokens: ConstRecord<typeof _tokens, Token> = _tokens;
