import { ConstRecord } from '../../../types/const';
import Token from '../../../types/token';

const ETH = {
  name: 'Wrapped Ether',
  address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
  symbol: 'WETH',
  decimals: 18,
  chainId: 1,
  website: 'https://weth.io/',
  description: 'Ether or ETH is the native currency built on the Ethereum blockchain. ',
  logoURI: 'https://arbiscan.io/token/images/weth_28.png',
  documentation: 'https://ethereum.org/en/developers/docs/',
} as const;

const _tokens = {
  ETH,
  WETH: ETH,
  WNATIVE: ETH,
  BIFI: {
    name: 'Beefy.Finance',
    symbol: 'BIFI',
    address: '0x5870700f1272a1AdbB87C3140bD770880a95e55D',
    chainId: 1,
    decimals: 18,
    website: 'https://www.beefy.finance/',
    documentation: 'https://docs.beefy.finance/',
    description:
      'Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.',
    logoURI:
      'https://raw.githubusercontent.com/beefyfinance/beefy-app/prod/src/images/single-assets/BIFI.png',
  },
  USDC: {
    name: 'USD Coin',
    address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    symbol: 'USDC',
    decimals: 6,
    website: 'https://www.circle.com/usdc',
    description:
      'USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
    chainId: 1,
    logoURI: 'https://ftmscan.com/token/images/USDC_32.png',
    documentation: 'https://developers.circle.com/docs',
  },
  STG: {
    name: 'Stargate',
    symbol: 'STG',
    address: '0xAf5191B0De278C7286d6C7CC6ab6BB8A73bA2Cd6',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://raw.githubusercontent.com/traderjoe-xyz/joe-tokenlists/main/logos/0x2F6F07CDcf3588944Bf4C42aC74ff24bF56e7590/logo.png',
    website: 'https://stargate.finance/',
    description:
      'Stargate is a community-driven organization building the first fully composable native asset bridge, and the first dApp built on LayerZero.',
    documentation: 'https://stargateprotocol.gitbook.io/stargate/v/user-docs/',
  },
  CNC: {
    name: 'Conic Finance Token',
    symbol: 'CNC',
    address: '0x9aE380F0272E2162340a5bB646c354271c0F5cFC',
    chainId: 1,
    decimals: 18,
    website: 'https://conic.finance/',
    description:
      'Conic Finance is an easy-to-use platform built for liquidity providers to easily diversify their exposure to multiple Curve pools. Any user can provide liquidity into a Conic Omnipool which allocates funds across Curve in proportion to protocol controlled pool weights.',
    documentation: 'https://docs.conic.finance/conic-finance/',
  },
  CTR: {
    name: 'Concentrator Token',
    symbol: 'CTR',
    address: '0xb3Ad645dB386D7F6D753B2b9C3F4B853DA6890B8',
    chainId: 1,
    decimals: 18,
    website: 'https://concentrator.aladdin.club/',
    description:
      'Concentrator by Aladdin DAO maximizes Convex APYs and earns yield in the best DeFi tokens. Concentrator is a yield enhancer that boosts yields on Convex vaults by concentrating all rewards into auto-compounding top-tier tokens like aCRV (cvxCRV) and aFXS (cvxFXS/FXS).',
    documentation: 'https://docs.aladdin.club/concentrator',
  },
  MATIC: {
    name: 'Matic Token',
    symbol: 'MATIC',
    address: '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0',
    chainId: 1,
    decimals: 18,
    website: 'https://polygon.technology/',
    description:
      'Polygon is a protocol and a framework for building and connecting Ethereum-compatible blockchain networks. Aggregating scalable solutions on Ethereum supporting a multi-chain Ethereum ecosystem.',
  },
  wstETH: {
    name: 'Lido Wrapped Staked ETH',
    symbol: 'wstETH',
    address: '0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0',
    chainId: 1,
    decimals: 18,
    website: 'https://lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.',
    logoURI: '',
    documentation: 'https://docs.lido.fi/',
  },
  stETH: {
    name: 'Lido Wrapped Staked ETH',
    symbol: 'stETH',
    address: '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84',
    chainId: 1,
    decimals: 18,
    website: 'https://lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.',
    logoURI: '',
    documentation: 'https://docs.lido.fi/',
  },
  pETH: {
    name: "JPEG'd ETH",
    symbol: 'pETH',
    address: '0x836A808d4828586A69364065A1e064609F5078c7',
    chainId: 1,
    decimals: 18,
    website: 'https://jpegd.io/',
    description:
      "pETH is an Ethereum derivative supported by the JPEG'd protocol. It is minted when a user borrows against their NFT and burned when they decide to repay their loan. Unlike the 2% interest rate for borrowing PUSd, minting $pETH against an NFT has a 5% interest rate.",
    documentation: 'https://docs.jpegd.io/tokenomics/usdpeth',
  },
  FRAX: {
    chainId: 1,
    address: '0x853d955aCEf822Db058eb8505911ED77F175b99e',
    decimals: 18,
    name: 'Frax',
    symbol: 'FRAX',
    website: 'https://frax.finance/',
    description: 'Frax is the first fractional-algorithmic stablecoin protocol.',
    logoURI:
      'https://raw.githubusercontent.com/pangolindex/tokens/main/assets/0xD24C2Ad096400B6FBcd2ad8B24E7acBc21A1da64/logo.png',
    documentation: 'https://docs.frax.finance/',
  },
  WBTC: {
    chainId: 1,
    address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    decimals: 8,
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    website: 'https://wbtc.network/',
    description:
      'Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.',
    logoURI:
      'https://raw.githubusercontent.com/ava-labs/bridge-tokens/main/avalanche-tokens/0x408D4cD0ADb7ceBd1F1A1C33A0Ba2098E1295bAB/logo.png',
  },
  sBTC: {
    chainId: 1,
    address: '0xfE18be6b3Bd88A2D2A7f928d00292E7a9963CfC6',
    decimals: 18,
    name: 'Synthetix: sBTC',
    symbol: 'sBTC',
    website: 'https://www.synthetix.io/',
    description:
      'sBTC is a synthetic Bitcoin token enabled by the Synthetix protocol. It tracks the price of Bitcoin through price feeds supplied by Chainlink’s decentralized network of oracles.',
    logoURI:
      'https://raw.githubusercontent.com/ava-labs/bridge-tokens/main/avalanche-tokens/0x408D4cD0ADb7ceBd1F1A1C33A0Ba2098E1295bAB/logo.png',
  },
  multiBTC: {
    chainId: 1,
    address: '0x66eFF5221ca926636224650Fd3B9c497FF828F7D',
    decimals: 8,
    name: 'Multichain BTC',
    symbol: 'multiBTC',
    website: 'https://app.multichain.org/',
    description: 'Multichain supports to swap BTC to MultiBTC (Multichain BTC) 1:1.',
    documentation: 'https://docs.multichain.org/getting-started/introduction',
  },
  alETH: {
    name: 'Alchemix ETH',
    symbol: 'alETH',
    address: '0x0100546F2cD4C9D97f798fFC9755E47865FF7Ee6',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://alchemix.fi/',
    documentation: 'https://alchemix-finance.gitbook.io/v2/',
    description:
      'Alchemix Self-Repaying Loans allow you to leverage a range of tokens without risk of liquidation.',
  },
  MIM: {
    name: 'Magic Internet Money',
    address: '0x99D8a9C45b2ecA8864373A26D1459e3Dff1e17F3',
    symbol: 'MIM',
    decimals: 18,
    chainId: 1,
    website: 'https://abracadabra.money/',
    description:
      'You, the Spellcaster, can provide collateral in the form of various interest bearing crypto assets such as yvYFI, yvUSDT, yvUSDC, xSUSHI and more. With this, you can borrow magic internet money (MIM) which is a stable coin that you can swap for any other traditional stable coin.',
    logoURI: '',
    documentation: 'https://docs.abracadabra.money/',
  },
  ApeUSD: {
    name: 'ApeUSD',
    address: '0xfF709449528B6fB6b88f557F7d93dEce33bca78D',
    symbol: 'ApeUSD',
    decimals: 18,
    chainId: 1,
    website: 'https://ape.fi/',
    documentation: 'https://github.com/ape-fi/ape-finance',
    description:
      'Ape Finance is building DeFi tools for metaverse dwellers, proud PFP owners, and digital collectible enthusiasts in all of us. We appreciate culture, art, and games. Ape Finance begins with the creation of the ApeUSD.',
    logoURI: '',
  },
  auraBAL: {
    name: 'Aura Staked BAL BPT',
    symbol: 'auraBAL',
    address: '0x616e8BfA43F920657B3497DBf40D6b1A02D4608d',
    chainId: 1,
    decimals: 18,
    website: 'https://aura.finance/',
    description: "auraBAL is Aura's liquid staking locked BAL (80 BAL / 20 ETH) BPT",
    logoURI: '',
    documentation: 'https://docs.aura.finance/aura/what-is-aura/for-usdbal-stakers',
  },
  BAL: {
    name: 'Balancer',
    symbol: 'BAL',
    address: '0xba100000625a3754423978a60c9317c58a424e3D',
    chainId: 1,
    decimals: 18,
    website: 'https://balancer.fi/',
    description:
      'Balancer turns the concept of an index fund on its head: instead of a paying fees to portfolio managers to rebalance your portfolio, you collect fees from traders, who rebalance your portfolio by following arbitrage opportunities. ',
    logoURI: '',
    documentation: 'https://docs.balancer.fi/',
  },
  AURA: {
    name: 'Aura',
    symbol: 'AURA',
    address: '0xC0c293ce456fF0ED870ADd98a0828Dd4d2903DBF',
    chainId: 1,
    decimals: 18,
    website: 'https://aura.finance/',
    description:
      'Aura Finance is a protocol built on top of the Balancer system to provide maximum incentives to Balancer liquidity providers and BAL stakers (into veBAL) through social aggregation of BAL deposits and Aura’s native token. For BAL stakers, Aura provides a seamless onboarding process to veBAL, by creating a tokenised wrapper token called auraBAL that represents the 80/20 BPT locked up for the maximum time in VotingEscrow (read more about what this means). This can be staked to receive existing rewards (BAL and bbaUSD) from Balancer, in addition to a share of any BAL earned by Aura (read more about the fees), and additional AURA. This minting process is irreversible however users can trade their auraBAL back to BAL through an incentivised liquidity pool.',
    logoURI: '',
    documentation: 'https://docs.aura.finance/',
  },
  MAI: {
    name: 'Mai Stablecoin',
    symbol: 'MAI',
    address: '0x8D6CeBD76f18E1558D4DB88138e2DeFB3909fAD6',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://mai.finance/',
    documentation: 'https://docs.mai.finance/',
    description:
      'MAI is a stable coin collateralized by your MATIC holdings. Its powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.',
  },
  tBTC: {
    name: 'tBTC v2',
    symbol: 'tBTC',
    address: '0x18084fbA666a33d37592fA2633fD49a74DD93a88',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://threshold.network/',
    description:
      'Threshold is the first ever on-chain merge between two existing networks and communities, Keep and NuCypher. Threshold provides a suite of threshold cryptography services that power user sovereignty on the blockchain.',
  },
  T: {
    name: 'Threshold Network Token',
    symbol: 'T',
    address: '0xCdF7028ceAB81fA0C6971208e83fa7872994beE5',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://threshold.network/',
    description:
      'Threshold is the first ever on-chain merge between two existing networks and communities, Keep and NuCypher. Threshold provides a suite of threshold cryptography services that power user sovereignty on the blockchain.',
  },
  eCFX: {
    name: 'ethereum Conflux',
    symbol: 'eCFX',
    address: '0xA1f82E14bc09A1b42710dF1A8a999B62f294e592',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://confluxnetwork.org/',
    description:
      'Conflux’s token economy is built around the $CFX token, a unit of value on the platform that enables token holders to pay transaction fees, earn rewards through staking, rent storage, and participate in network governance. CFX also incentivizes and rewards miners, who ensure the secure operation of the Network.',
  },
  USDP: {
    name: 'Pax Dollar',
    symbol: 'USDP',
    address: '0x8E870D67F660D95d5be530380D0eC0bd388289E1',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://paxos.com/usdp/',
    description:
      'Pax Dollar (USDP) is a stablecoin created by Paxos, a licenced trust firm and financial institution that ensures the backing of the tokens with US dollar deposits. With the USDP, Paxos created a token that combines the confidence and stability of fiat money with the usefulness and immediacy of digital assets.',
  },
  CRV: {
    name: 'CRV',
    address: '0xD533a949740bb3306d119CC777fa900bA034cd52',
    symbol: 'CRV',
    decimals: 18,
    chainId: 1,
    website: 'https://curve.fi/',
    description:
      'Curve is an exchange liquidity pool on Ethereum. Curve is designed for extremely efficient stablecoin trading and low risk, supplemental fee income for liquidity providers, without an opportunity cost.',
    logoURI: '',
    documentation: 'https://curve.readthedocs.io/',
  },
  CVX: {
    name: 'CVX',
    address: '0x4e3FBD56CD56c3e72c1403e103b45Db9da5B9D2B',
    symbol: 'CVX',
    decimals: 18,
    chainId: 1,
    website: 'https://www.convexfinance.com/',
    documentation: 'https://docs.convexfinance.com/',
    description:
      'Convex allows Curve.fi liquidity providers to earn trading fees and claim boosted CRV without locking CRV themselves. Liquidity providers can receive boosted CRV and liquidity mining rewards with minimal effort.',
    logoURI: '',
  },
  cvxCRV: {
    name: 'cvxCRV',
    address: '0x62B9c7356A2Dc64a1969e19C23e4f579F9810Aa7',
    symbol: 'cvxCRV',
    decimals: 18,
    chainId: 1,
    website: 'https://www.convexfinance.com/',
    documentation: 'https://docs.convexfinance.com/',
    description:
      'Convex allows Curve.fi liquidity providers to earn trading fees and claim boosted CRV without locking CRV themselves. Liquidity providers can receive boosted CRV and liquidity mining rewards with minimal effort.',
    logoURI: '',
  },
  cvxFXS: {
    name: 'Convex FXS',
    address: '0xFEEf77d3f69374f66429C91d732A244f074bdf74',
    symbol: 'cvxFXS',
    decimals: 18,
    chainId: 1,
    website: 'https://frax.convexfinance.com/',
    documentation: 'https://docs.convexfinance.com/',
    description:
      'Convex Finance has expanded to optimize opportunities for liquidity providers on Frax the same way it has done so for Curve.fi LPs.',
    logoURI: '',
  },
  cvxFPIS: {
    name: 'Convex FPIS',
    address: '0xa2847348b58CEd0cA58d23c7e9106A49f1427Df6',
    symbol: 'cvxFPIS',
    decimals: 18,
    chainId: 1,
    website: 'https://frax.convexfinance.com/',
    documentation: 'https://docs.convexfinance.com/',
    description:
      "Convex also now supports Frax Finance's FPIS token, the governance token for the FPI stablecoin launched by Frax. Frax documentation explains the mechanisms behind the FPI stablecoin and the FPIS governance token in detail.",
    logoURI: '',
  },
  sethUSDC: {
    name: 'Stargate USD Coin LP',
    symbol: 'sethUSDC',
    address: '0xdf0770dF86a8034b3EFEf0A1Bb3c889B8332FF56',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0xef4229c8c3250C675F21BCefa42f58EfbfF6002a.svg',
    website: 'https://stargate.finance/',
    description:
      'Stargate allows users and dApps to bridge native tokens with instant guaranteed finality. USDC is deposited in a LP pool to enable high liquidity for bridging.',
    documentation: 'https://stargateprotocol.gitbook.io/stargate/v/user-docs/',
  },
  sethUSDT: {
    name: 'Stargate Tether USD LP',
    symbol: 'sethUSDT',
    address: '0x38EA452219524Bb87e18dE1C24D3bB59510BD783',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://tether.to/',
    description:
      'Stargate allows users and dApps to bridge native tokens with instant guaranteed finality. USDT is deposited in a LP pool to enable high liquidity for bridging.',
    documentation: 'https://stargateprotocol.gitbook.io/stargate/v/user-docs/',
  },
  rETH: {
    name: 'Rocket Pool ETH',
    symbol: 'rETH',
    address: '0xae78736Cd615f374D3085123A210448E74Fc6393',
    chainId: 1,
    decimals: 18,
    website: 'https://rocketpool.net/',
    description:
      'As a Rocket Pool staker, your role is to deposit ETH into the deposit pool which will enable a node operator to create a new Beacon Chain validator. You can stake as little as 0.01 ETH. In doing so, you will be given a token called rETH. rETH represents both how much ETH you deposited, and when you deposited it.',
    logoURI: '',
    documentation: 'https://docs.rocketpool.net/guides/',
  },
  USDT: {
    name: 'Tether USD',
    symbol: 'USDT',
    address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://tether.to/',
    documentation: 'https://tether.to/en/how-it-works',
    description:
      'Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold.Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
  },
  DOLA: {
    name: 'Dola USD Stablecoin',
    symbol: 'DOLA',
    address: '0x865377367054516e17014CcdED1e7d814EDC9ce4',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.inverse.finance/',
    documentation: 'https://docs.inverse.finance/inverse-finance/using-dola/how-to-acquire-dola',
    description:
      'Inverse.finance is a suite of permissionless decentralized finance tools governed by Inverse DAO, a decentralized autonomous organization running on the Ethereum blockchain.',
  },
  sETH: {
    name: 'Synth sETH',
    symbol: 'sETH',
    address: '0x5e74C9036fb86BD7eCdcb084a0673EFc32eA31cb',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://synthetix.io/',
    description:
      'Synths are derivative tokens providing exposure to a range of assets. They can be traded with infinite liquidity and zero slippage by leveraging the Synthetix protocol’s unique pooled collateral model. Trades between Synths generate a small fee that is distributed to SNX collateral providers.',
  },
  cbETH: {
    name: 'Coinbase Wrapped Staked ETH',
    symbol: 'cbETH',
    address: '0xBe9895146f7AF43049ca1c1AE358B0541Ea49704',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://help.coinbase.com/en/coinbase/trading-and-funding/staking-rewards/cbeth',
    description:
      "Coinbase Wrapped Staked ETH (“cbETH”) is a utility token that represents Ethereum 2 (ETH2), which is ETH staked through Coinbase. Over time, the price of cbETH will likely deviate from ETH because cbETH represents 1 staked ETH plus all of its accrued staking interest starting from when cbETH's conversion rate and balance were initialized (June 16, 2022 19:34 UTC). cbETH is minted exclusively by Coinbase.",
  },
  USDD: {
    name: 'Decentralized USD',
    symbol: 'USDD',
    address: '0x0C10bF8FcB7Bf5412187A595ab97a3609160b5c6',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://usdd.io/',
    description:
      'The USDD protocol aims to provide the blockchain industry with the most stable, decentralized, tamper-proof, and freeze-free stablecoin system, a perpetual system independent from any centralized entity.',
    documentation: 'https://usdd.io/docs/',
  },
  aUSDT: {
    name: 'Aave Tether USD',
    symbol: 'aUSDT',
    address: '0x3Ed3B47Dd13EC9a98b44e6204A523E766B225811',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://tether.to/',
    description:
      'Aave interest bearing USDT. Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold.Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
  },
  sethETH: {
    name: 'Stargate Ethereum LP',
    symbol: 'sethETH',
    address: '0x101816545F6bd2b1076434B54383a1E633390A2E',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x2170ed0880ac9a755fd29b2688956bd959f933f8.png',
    website: 'https://stargate.finance/',
    description:
      'Stargate allows users and dApps to bridge native tokens with instant guaranteed finality. ETH is deposited in a LP pool to enable high liquidity for bridging.',
    documentation: 'https://stargateprotocol.gitbook.io/stargate/v/user-docs/',
  },
  waUSDT: {
    name: 'Wrapped Aave Tether USD',
    symbol: 'waUSDT',
    address: '0xf8Fd466F12e236f4c96F7Cce6c79EAdB819abF58',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://tether.to/',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Wrapped Aave interest bearing USDT. Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold.Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
  },
  bbaUSDT: {
    name: 'Balancer Aave USDT Linear Pool',
    symbol: 'bbaUSDT',
    address: '0x2F4eb100552ef93840d5aDC30560E5513DFfFACb',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 USDT and wrapped Aave Interest Bearing USDT.',
  },
  aUSDC: {
    name: 'Aave USDC',
    symbol: 'aUSDC',
    address: '0xBcca60bB61934080951369a648Fb03DF4F96263C',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://www.circle.com/usdc',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Aave interest bearing USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
  },
  waUSDC: {
    name: 'Wrapped Aave Tether USD',
    symbol: 'waUSDC',
    address: '0xd093fA4Fb80D09bB30817FDcd442d4d02eD3E5de',
    chainId: 1,
    decimals: 6,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://www.circle.com/usdc',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Wrapped Aave interest bearing USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
  },
  bbaUSDC: {
    name: 'Balancer Aave USDC Linear Pool',
    symbol: 'bbaUSDC',
    address: '0x82698aeCc9E28e9Bb27608Bd52cF57f704BD1B83',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 USDC and wrapped Aave Interest Bearing USDC.',
  },
  DAI: {
    name: 'DAI Stablecoin',
    symbol: 'DAI',
    address: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://makerdao.com/en/',
    documentation:
      'https://docs.makerdao.com/smart-contract-modules/dai-module/dai-detailed-documentation',
    description:
      'Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain',
  },
  aDAI: {
    name: 'Aave DAI',
    symbol: 'aDAI',
    address: '0x028171bCA77440897B824Ca71D1c56caC55b68A3',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://makerdao.com/en/',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Aave interest bearing DAI. Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain.',
  },
  waDAI: {
    name: 'Wrapped Aave Tether DAI',
    symbol: 'waDAI',
    address: '0x02d60b84491589974263d922D9cC7a3152618Ef6',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://makerdao.com/en/',
    documentation: 'https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens',
    description:
      'Wrapped Aave interest bearing DAI. Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain.',
  },
  bbaDAI: {
    name: 'Balancer Aave DAI Linear Pool',
    symbol: 'bbaDAI',
    address: '0xae37D54Ae477268B9997d4161B96b8200755935c',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 DAI and wrapped Aave Interest Bearing DAI.',
  },
  bbaUSD: {
    name: 'Balancer Aave Stable Composable Pool',
    symbol: 'bbaUSD',
    address: '0xA13a9247ea42D743238089903570127DdA72fE44',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x4988a896b1227218e4A686fdE5EabdcAbd91571f.svg',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer composable pool that consist of bbaUSDT, bbaUSDC, and bbaDAI. bbTokens are Aave boosted linear pools.',
  },
  frxETH: {
    name: 'Frax Ether',
    symbol: 'frxETH',
    address: '0x5E8422345238F34275888049021821E8E08CAa1f',
    chainId: 1,
    decimals: 18,
    website: 'https://app.frax.finance/frxeth/mint',
    description:
      'frxETH acts as a stablecoin loosely pegged to ETH, so that 1 frxETH always represents 1 ETH and the amount of frxETH in circulation matches the amount of ETH in the Frax ETH system. When ETH is sent to the frxETHMinter, an equivalent amount of frxETH is minted. Holding frxETH on its own is not eligible for staking yield and should be thought of as analogous as holding ETH.',
    logoURI: '',
    documentation: 'https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth',
  },
  sfrxETH: {
    name: 'Staked Frax Ether',
    symbol: 'sfrxETH',
    address: '0xac3E018457B222d93114458476f3E3416Abbe38F',
    chainId: 1,
    decimals: 18,
    website: 'https://app.frax.finance/frxeth/mint',
    description:
      'sfrxETH is a ERC-4626 vault designed to accrue the staking yield of the Frax ETH validators. At any time, frxETH can be exchanged for sfrxETH by depositing it into the sfrxETH vault, which allows users to earn staking yield on their frxETH. Over time, as validators accrue staking yield, an equivalent amount of frxETH is minted and added to the vault, allowing users to redeem their sfrxETH for an greater amount of frxETH than they deposited. ',
    logoURI: '',
    documentation: 'https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth',
  },
  INV: {
    name: 'Inverse Finance',
    symbol: 'INV',
    address: '0x41D5D79431A913C4aE7d69a668ecdfE5fF9DFB68',
    chainId: 1,
    decimals: 18,
    website: 'https://www.inverse.finance/',
    documentation: 'https://docs.inverse.finance/inverse-finance/about-inverse',
    description:
      'Inverse.finance is a suite of permissionless decentralized finance tools governed by Inverse DAO, a decentralized autonomous organization running on the Ethereum blockchain.',
    logoURI: 'https://assets.spookyswap.finance/tokens/INV.png',
  },
  ACX: {
    name: 'Across Protocol Token',
    symbol: 'ACX',
    address: '0x44108f0223A3C3028F5Fe7AEC7f9bb2E66beF82F',
    chainId: 1,
    decimals: 18,
    website: 'https://across.to/',
    documentation: 'https://docs.across.to/',
    description:
      'Across is a cross-chain bridge for L2s and rollups secured by UMAs optimistic oracle. It is optimized for capital efficiency with a single liquidity pool, a competitive relayer landscape, and a no-slippage fee model.',
    logoURI: '',
  },
  'BAL-WETH-80-20': {
    name: 'Balancer Pool Token BAL-WETH 80/20',
    symbol: 'BAL-WETH-80-20',
    address: '0x5c6Ee304399DBdB9C8Ef030aB642B10820DB8F56',
    chainId: 1,
    decimals: 18,
    website: 'https://app.balancer.fi/',
    description:
      'Instead of locking pure BAL, users obtain veBAL by locking 80/20 BAL/WETH Balancer Pool Tokens (BPTs). This ensures that even if a large portion of BAL tokens are locked, there is deep trading liquidity.',
    logoURI: '',
    documentation: 'https://docs.balancer.fi/ecosystem/vebal-and-gauges/vebal',
  },
  SUSHI: {
    name: 'SushiToken',
    symbol: 'SUSHI',
    address: '0x6B3595068778DD592e39A122f4f5a5cF09C90fE2',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x6B3595068778DD592e39A122f4f5a5cF09C90fE2.svg',
    website: 'https://sushi.com/',
    description:
      'Sushi is the home of DeFi. Their community is building a comprehensive, decentralized trading platform for the future of finance. Swap, earn, stack yields, lend, borrow, leverage all on one decentralized, community driven platform.',
    documentation: 'https://dev.sushi.com/',
  },
  ILV: {
    name: 'Illuvium',
    symbol: 'ILV',
    address: '0x767FE9EDC9E0dF98E07454847909b5E959D7ca0E',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x767FE9EDC9E0dF98E07454847909b5E959D7ca0E.svg',
    website: 'https://illuvium.io/',
    description:
      'A fully decentralized protocol, Illuvium represents a new age in gaming. It has been engineered from the ground-up to support the long-term sustainability of the Illuvium game and governance and provide players with a AAA-rated blockchain gaming experience. What makes Illuvium unique is that stakers receive regular distributions and can vote on everything from tokenomics related issues to the features in the game itself. With Illuvium, the power to define the project into the future is purposefully left to those who stake in the protocol.',
    documentation: 'https://docs.illuvium.io/',
  },
  LDO: {
    name: 'Lido DAO Token',
    symbol: 'LDO',
    address: '0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32.svg',
    website: 'https://stake.lido.fi/',
    documentation: 'https://docs.lido.fi/',
    description:
      'Lido is a liquid staking solution for ETH 2.0 backed by industry-leading staking providers.',
  },
  SYN: {
    name: 'Synapse',
    symbol: 'SYN',
    address: '0x0f2D719407FdBeFF09D87557AbB7232601FD9F29',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x0f2D719407FdBeFF09D87557AbB7232601FD9F29.svg',
    website: 'https://synapseprotocol.com/landing',
    description:
      'Synapse is a universal interoperability protocol that enables secure cross-chain communication. Synapse connects blockchains by offering an extensible cross-chain messaging protocol that supports assets, smart contract calls, and more. By leveraging Synapse, blockchains can easily and securely interoperate with each other and developers can build truly cross-chain applications including cross-chain DEX, lending platforms, margining systems, derivatives markets, yield aggregators, and much more.',
    documentation: 'https://docs.synapseprotocol.com/',
  },
  SOLID: {
    name: 'Solidly',
    symbol: 'SOLID',
    address: '0x777172D858dC1599914a1C4c6c9fC48c99a60990',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://solidly.com/',
    description:
      'Solidly is an AMM allowing fully decentralized token swapping with support for low slippage trades between pegged assets like stablecoins.',
    documentation: '',
  },
  SNX: {
    name: 'Synthetix Network Token',
    symbol: 'SNX',
    address: '0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.synthetix.io/',
    description:
      'Synthetix is the backbone for derivatives trading in DeFi, allowing anyone, anywhere to gain on-chain exposure to a vast range of assets',
    documentation: 'https://docs.synthetix.io/synthetix-protocol/welcome-to-synthetix',
  },
  HEX: {
    name: 'HEX',
    symbol: 'HEX',
    address: '0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39',
    chainId: 1,
    decimals: 8,
    logoURI: '',
    website: 'https://hex.com/',
    description: 'HEX is the first high-yield blockchain certificate of deposit',
    documentation: 'https://hex.com/faq/',
  },
  moSOLID: {
    name: 'moSOLID: Tokenized veSOLID',
    symbol: 'moSOLID',
    address: '0x848578e351D25B6Ec0d486E42677891521c3d743',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://alpha.mono.farm/home',
    description: 'A tokenized version of veSOLID, moSOLID, is returned to the user at a 1:1 rate.',
    documentation: 'https://docs.mono.farm/monolith-documentation/',
  },
  FTM: {
    name: 'Fantom Token',
    symbol: 'FTM',
    address: '0x4E15361FD6b4BB609Fa63C81A2be19d873717870',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://fantom.foundation/',
    description:
      'Fantom is a fast, high-throughput open-source smart contract platform for digital assets and dApps.',
    documentation: '',
  },
  DEUS: {
    name: 'DEUS',
    symbol: 'DEUS',
    address: '0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44',
    chainId: 1,
    decimals: 18,
    website: 'https://deus.finance/',
    description:
      'DEUS Finance Evolution is a marketplace of decentralized financial services. We provide the infrastructure for others to build financial instruments, such as synthetic stock trading platforms, options and futures trading, and more.',
    logoURI: 'https://app.deus.finance/tokens/deus.svg',
    documentation: 'https://docs.deus.finance/',
  },
  GEAR: {
    name: 'Gearbox',
    symbol: 'GEAR',
    address: '0xBa3335588D9403515223F109EdC4eB7269a9Ab5D',
    chainId: 1,
    decimals: 18,
    website: 'https://gearbox.fi/',
    description:
      'Gearbox Protocol allows anyone to take DeFi-native leverage and then use it across various (DeFi & more) protocols. This enables you to compose your position as you want. You take leverage with Gearbox and then use it on other protocols you already love: Uniswap, Curve, Convex, Lido, etc. For example, you can leverage trade on Uniswap, leverage farm on Yearn, make delta-neutral strategies, hedge your exposure, get Leverage-as-a-Service for your structured product, and more... ',
    logoURI: '',
    documentation: 'https://docs.gearbox.finance/',
  },
  TUSD: {
    name: 'TrueUSD',
    symbol: 'TUSD',
    address: '0x0000000000085d4780B73119b644AE5ecd22b376',
    chainId: 1,
    decimals: 18,
    website: 'https://trueusd.com/',
    description: 'The first regulated stablecoin fully backed by the US Dollar.',
    logoURI: '',
  },
  CLEV: {
    name: 'CLever Token',
    symbol: 'CLEV',
    address: '0x72953a5C32413614d24C29c84a66AE4B59581Bbf',
    chainId: 1,
    decimals: 18,
    website: 'https://clever.aladdin.club/',
    description:
      'Deposit top quality tokens to CLever in high-yielding collateral strategies, then claim your future yields today. Your future yields can be farmed, re-deposited to create leverage, or used wherever you need them.',
    logoURI: '',
    documentation: 'https://docs.aladdin.club/clever',
  },
  clevCVX: {
    name: 'CLever CVX',
    symbol: 'clevCVX',
    address: '0xf05e58fCeA29ab4dA01A495140B349F8410Ba904',
    chainId: 1,
    decimals: 18,
    website: 'https://clever.aladdin.club/',
    description:
      'Deposit top quality tokens to CLever in high-yielding collateral strategies, then claim your future yields today. Your future yields can be farmed, re-deposited to create leverage, or used wherever you need them.',
    logoURI: '',
    documentation: 'https://docs.aladdin.club/clever',
  },
  yCRV: {
    name: 'Yearn: yCRV Token',
    symbol: 'yCRV',
    address: '0xFCc5c47bE19d06BF83eB04298b026F81069ff65b',
    chainId: 1,
    decimals: 18,
    website: 'https://yearn.finance/ycrv',
    description:
      "yCRV is Yearn's new and improved veCRV wrapper system designed to tokenize the different benefits of Yearn's veCRV position.",
    logoURI: '',
    documentation: 'https://docs.yearn.finance/getting-started/products/ycrv/overview',
  },
  eUSD: {
    name: 'Electronic USD',
    symbol: 'eUSD',
    address: '0xA0d69E286B938e21CBf7E51D71F6A4c8918f482F',
    chainId: 1,
    decimals: 18,
    website: 'https://register.app/',
    description:
      'The Reserve Protocol is the first platform that allows for the permissionless creation of asset-backed, yield-bearing & overcollateralized stablecoins on Ethereum. The end goal of the Reserve Protocol is to provide highly scalable, decentralized, stable money in contrast to volatile cryptocurrencies such as Bitcoin and Ether.',
    logoURI: '',
    documentation: 'https://reserve.org/protocol/',
  },
  msETH: {
    name: 'Metronome Synth ETH',
    symbol: 'msETH',
    address: '0x64351fC9810aDAd17A690E4e1717Df5e7e085160',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.metronome.io/',
    description:
      'A complete synthetic protocol that enables users to generate a variety of synthetics using crypto assets as collateral',
    documentation: 'https://docs.metronome.io/metronome-2.0/master',
  },
  BLUR: {
    name: 'Blur',
    symbol: 'BLUR',
    address: '0x5283D291DBCF85356A21bA090E6db59121208b44',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://blur.io/',
    description:
      'Sweep NFTs across multiple marketplaces, snipe reveals faster than others, and manage your portfolio with advanced analytics. Zero fees.',
  },
  msUSD: {
    name: 'Metronome Synth USD',
    symbol: 'msUSD',
    address: '0xab5eB14c09D416F0aC63661E57EDB7AEcDb9BEfA',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.metronome.io/',
    description:
      'A complete synthetic protocol that enables users to generate a variety of synthetics using crypto assets as collateral',
    documentation: 'https://docs.metronome.io/metronome-2.0/master',
  },
  UZD: {
    name: 'UZD Zunami Stable',
    symbol: 'UZD',
    address: '0xb40b6608B2743E691C9B54DdBDEe7bf03cd79f1c',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.zunami.io/',
    description:
      'UZD is a rebase token that increases in value in proportion to the APY of the Zunami Protocol. It is over-collateralized by stablecoins allocated in Curve Finance pools and minted using ZLP. UZD is secure from depeg as it can be redeemed with USDT, USDC, or DAI at any time. Users can receive UZD by minting it through the Zunami interface or by swapping it in the Curve.',
    documentation: 'https://zunamilab.gitbook.io/product-docs/',
  },
  lvUSD: {
    name: 'lvUSD',
    symbol: 'lvUSD',
    address: '0x94A18d9FE00bab617fAD8B49b11e9F1f64Db6b36',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://archimedesfi.com/',
    description:
      'The stablecoin lvUSD is pegged to the USD and is used for lending and repaying loans.\n' +
      'When liquidity providers (LPs) deposit 3CRV, Archimedes borrows lvUSD on behalf of leverage takers (LTs) and uses it to enter a strategy. Investing in the 3CRV/lvUSD pool gives LPs exposure to both 3CRV and the collateral provided by LTs. This allows the market to decide on the best investment strategy.',
    documentation: 'https://docs.archimedesfi.com/',
  },
  eUSDT: {
    name: 'Euler Tether USD',
    symbol: 'eUSDT',
    address: '0x4d19F33948b99800B6113Ff3e83beC9b537C85d2',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://tether.to/',
    description:
      'Euler interest bearing USDT. Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold.Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.',
    documentation: 'https://docs.euler.finance/',
  },
  bbeUSDT: {
    name: 'Balancer Euler USDT Linear Pool',
    symbol: 'bbeUSDT',
    address: '0x3C640f0d3036Ad85Afa2D5A9E32bE651657B874F',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description: 'Balancer linear pool that consist of 50/50 USDT and Euler Interest Bearing USDT.',
  },
  eUSDC: {
    name: 'Euler USDC',
    symbol: 'eUSDC',
    address: '0xEb91861f8A4e1C12333F42DCE8fB0Ecdc28dA716',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.circle.com/usdc',
    documentation: 'https://docs.euler.finance/',
    description:
      'Euler interest bearing USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.',
  },
  bbeUSDC: {
    name: 'Balancer Euler USDC Linear Pool',
    symbol: 'bbeUSDC',
    address: '0xD4e7C1F3DA1144c9E2CfD1b015eDA7652b4a4399',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 USDC and wrapped Euler Interest Bearing USDC.',
  },
  eDAI: {
    name: 'Euler DAI',
    symbol: 'eDAI',
    address: '0xe025E3ca2bE02316033184551D4d3Aa22024D9DC',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://makerdao.com/en/',
    documentation: 'https://docs.euler.finance/',
    description:
      'Euler interest bearing DAI. Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain.',
  },
  bbeDAI: {
    name: 'Balancer Euler DAI Linear Pool',
    symbol: 'bbeDAI',
    address: '0xeB486AF868AeB3b6e53066abc9623b1041b42bc0',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer linear pool that consist of 50/50 DAI and wrapped Euler Interest Bearing DAI.',
  },
  bbeUSD: {
    name: 'Balancer Euler Stable Composable Pool',
    symbol: 'bbeUSD',
    address: '0x50Cf90B954958480b8DF7958A9E965752F627124',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://app.balancer.fi/#/',
    documentation: 'https://docs.balancer.fi/products/balancer-pools/boosted-pools',
    description:
      'Balancer composable pool that consist of bbeUSDT, bbeUSDC, and bbeDAI. bbTokens are Euler boosted linear pools.',
  },
  VERSE: {
    name: 'Verse',
    symbol: 'VERSE',
    address: '0x249cA82617eC3DfB2589c4c17ab7EC9765350a18',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://verse.bitcoin.com/',
    description:
      'At Bitcoin.com our mission is to create more economic freedom in the world. We define economic freedom as the ability to make choices with respect to one’s personal resources, unencumbered by trusted third parties or borders or lack of access. We believe economic freedom is the foundation of peace and prosperity, and by creating more of it for people, we are reducing suffering in the world. We strive to help everyone, everywhere be more economically free.',
    documentation: 'https://www.getverse.com/verse-whitepaper.pdf',
  },
  APE: {
    name: 'ApeCoin',
    address: '0x4d224452801ACEd8B2F0aebE155379bb5D594381',
    symbol: 'APE',
    decimals: 18,
    chainId: 1,
    website: 'https://apecoin.com/',
    description:
      'ApeCoin is the APE Ecosystems governance token, allowing token holders to participate in ApeCoin DAO and giving its participants a shared and open currency that can be used without centralized intermediaries.',
    logoURI: '',
  },
  OHM: {
    name: 'Olympus',
    address: '0x64aa3364F17a4D01c6f1751Fd97C2BD3D7e7f1D5',
    symbol: 'OHM',
    decimals: 9,
    chainId: 1,
    website: 'https://www.olympusdao.finance/',
    description:
      'Olympus is building OHM, a community-owned, decentralized and censorship-resistant reserve currency that is asset-backed, deeply liquid and used widely across Web3.',
    logoURI: '',
    documentation: 'https://docs.olympusdao.finance/',
  },
  SD: {
    name: 'Stader',
    symbol: 'SD',
    address: '0x30D20208d987713f46DFD34EF128Bb16C404D10f',
    chainId: 1,
    decimals: 18,
    logoURI:
      'https://tokens.pancakeswap.finance/images/0x3BC5AC0dFdC871B365d159f728dd1B9A0B5481E8.svg',
    website: 'https://staderlabs.com/',
    description: 'Stader (SD) token is the native governance and value accrual token for Stader.',
    documentation: 'https://docs-new.staderlabs.com/intro',
  },
  FXS: {
    name: 'Frax Share',
    symbol: 'FXS',
    address: '0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://frax.finance/',
    description:
      'The Frax Protocol introduced the world to the concept of a cryptocurrency being partially backed by collateral and partially stabilized algorithmically.',
  },
  wBETH: {
    name: 'Wrapped Binance Beacon ETH',
    symbol: 'wBETH',
    address: '0xa2E3356610840701BDf5611a53974510Ae27E2e1',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.binance.com/en',
    documentation: 'https://www.binance.com/en/wbeth',
    description:
      'Wrapped Beacon ETH ("WBETH") is a wrapped version of BETH. Wrapped, WBETH is reward-bearing in nature. It accumulates ETH2.0 staking rewards not by growing in number, but by growing in value in relation to BETH. Unlike BETH, the value of WBETH will increase despite not being held in Binance Spot Wallet. That means WBETH provides you with double yield potential by (i) holding it to earn staking rewards, and (ii) moving it on-chain and exploring exciting DeFi and other dapps opportunities.',
  },
  OETH: {
    name: 'Origin Ether',
    symbol: 'OETH',
    address: '0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://www.oeth.com/',
    documentation: 'https://docs.oeth.com/',
    description:
      'OETH is a yield-bearing, ether-pegged token, offering an easy way to maximize yield from ETH staking using protocols, such as Curve Finance.',
  },
  crvUSD: {
    name: 'Curve.Fi USD Stablecoin',
    symbol: 'crvUSD',
    address: '0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://crvusd.curve.fi/',
    description:
      'crvUSD is a collateralized-debt-position (CDP) stablecoin pegged to the US Dollar',
  },
  '3CRV': {
    name: 'Curve.fi DAI/USDC/USDT',
    symbol: '3CRV',
    address: '0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://curve.fi/',
    oracle: 'lps',
    oracleId: 'convex-3pool',
    description: 'Curve base 3pool consisting of DAI, USDC and USDT',
  },
  R: {
    name: 'R Stablecoin',
    symbol: 'R',
    address: '0x183015a9bA6fF60230fdEaDc3F43b3D788b13e21',
    chainId: 1,
    decimals: 18,
    logoURI: '',
    website: 'https://raft.fi',
    documentation: 'https://docs.raft.fi/',
    description:
      'Raft is a governance-minimized, decentralized protocol that allows people to generate R (a USD stablecoin) by depositing  capital-efficient collateral.',
  },
} as const;

export const tokens: ConstRecord<typeof _tokens, Token> = _tokens;
