export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped Bera";
        readonly address: "0x6969696969696969696969696969696969696969";
        readonly symbol: "WBERA";
        readonly oracleId: "WBERA";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://www.berachain.com/";
        readonly description: "Learn, integrate, and build on a new modular EVM with Berachain.";
        readonly bridge: "berachain-canonical";
        readonly documentation: "https://docs.berachain.com/";
    };
    readonly FEES: {
        readonly name: "Wrapped Bera";
        readonly address: "0x6969696969696969696969696969696969696969";
        readonly symbol: "WBERA";
        readonly oracleId: "WBERA";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://www.berachain.com/";
        readonly description: "Learn, integrate, and build on a new modular EVM with Berachain.";
        readonly bridge: "berachain-canonical";
        readonly documentation: "https://docs.berachain.com/";
    };
    readonly BERA: {
        readonly name: "Wrapped Bera";
        readonly address: "0x6969696969696969696969696969696969696969";
        readonly symbol: "WBERA";
        readonly oracleId: "WBERA";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://www.berachain.com/";
        readonly description: "Learn, integrate, and build on a new modular EVM with Berachain.";
        readonly bridge: "berachain-canonical";
        readonly documentation: "https://docs.berachain.com/";
    };
    readonly WBERA: {
        readonly name: "Wrapped Bera";
        readonly address: "0x6969696969696969696969696969696969696969";
        readonly symbol: "WBERA";
        readonly oracleId: "WBERA";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://www.berachain.com/";
        readonly description: "Learn, integrate, and build on a new modular EVM with Berachain.";
        readonly bridge: "berachain-canonical";
        readonly documentation: "https://docs.berachain.com/";
    };
    readonly WETH: {
        readonly name: "WETH";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly address: "0x2F6F07CDcf3588944Bf4C42aC74ff24bF56e7590";
        readonly chainId: 80094;
        readonly decimals: 18;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly bridge: "layerzero";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly HONEY: {
        readonly name: "Honey";
        readonly symbol: "HONEY";
        readonly oracleId: "HONEY";
        readonly address: "0xFCBD14DC51f0A4d49d5E53C2E0950e0bC26d0Dce";
        readonly chainId: 80094;
        readonly decimals: 18;
        readonly website: "https://honey.berachain.com/";
        readonly description: "Turn your favorite stables into Honey. Leverage liquidity incentives on various platforms.";
        readonly documentation: "https://docs.berachain.com/";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly BGT: {
        readonly name: "Bera Governance Token";
        readonly symbol: "BGT";
        readonly oracleId: "BGT";
        readonly address: "0x656b95E550C07a9ffe548bd4085c72418Ceb1dba";
        readonly chainId: 80094;
        readonly decimals: 18;
        readonly website: "https://www.berachain.com/";
        readonly description: "$BGT is earned by performing certain actions in dApps with whitelisted Reward Vaults. Most of the time, this is related to providing liquidity, but it is not limited to this. Reward Vault deposits correspond to some form of productive activity on Berachain.";
        readonly documentation: "https://docs.berachain.com/learn/pol/tokens/bgt";
        readonly bridge: "native";
    };
    readonly USDCe: {
        readonly name: "Bridged USDC (Stargate)";
        readonly symbol: "USDCe";
        readonly oracleId: "USDCe";
        readonly address: "0x549943e04f40284185054145c6E4e9568C1D3241";
        readonly chainId: 80094;
        readonly decimals: 6;
        readonly website: "https://www.centre.io/";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly documentation: "";
        readonly bridge: "layerzero";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly BYUSD: {
        readonly name: "Bera pyUSD";
        readonly symbol: "BYUSD";
        readonly oracleId: "BYUSD";
        readonly address: "0x688e72142674041f8f6Af4c808a4045cA1D6aC82";
        readonly chainId: 80094;
        readonly decimals: 6;
        readonly website: "https://www.paypal.com/us/digital-wallet/manage-money/crypto/pyusd";
        readonly description: "Bera LayerZero Bridged PYUSD. PayPal USD (PYUSD) is a stablecoin backed by secure and highly liquid assets.";
        readonly documentation: "";
        readonly bridge: "layerzero";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly WBTC: {
        readonly name: "Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "WBTC";
        readonly address: "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c";
        readonly chainId: 80094;
        readonly decimals: 8;
        readonly website: "https://wbtc.network/";
        readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
        readonly documentation: "";
        readonly bridge: "layerzero";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly iBGT: {
        readonly name: "Infrared Bera Governance Token";
        readonly symbol: "iBGT";
        readonly oracleId: "iBGT";
        readonly address: "0xac03CABA51e17c86c921E1f6CBFBdC91F8BB2E6b";
        readonly chainId: 80094;
        readonly decimals: 18;
        readonly website: "https://infrared.finance/ibgt";
        readonly description: "Infrared’s iBGT, a liquid version of Berachain’s Governance Token (BGT), helps you maximize Proof of Liquidity (PoL) rewards.";
        readonly documentation: "https://infrared.finance/docs/ibgt-rewards";
        readonly bridge: "native";
    };
    readonly iBERA: {
        readonly name: "Infrared Bera";
        readonly symbol: "iBERA";
        readonly oracleId: "iBERA";
        readonly address: "0x9b6761bf2397Bb5a6624a856cC84A3A14Dcd3fe5";
        readonly chainId: 80094;
        readonly decimals: 18;
        readonly website: "https://infrared.finance/ibera";
        readonly description: "iBERA is Infrared’s liquid staking solution that makes staking BERA tokens accessible to everyone.";
        readonly documentation: "https://infrared.finance/education/ibera";
    };
    readonly OHM: {
        readonly name: "Olympus";
        readonly address: "0x18878Df23e2a36f81e820e4b47b4A40576D3159C";
        readonly symbol: "OHM";
        readonly oracleId: "OHM";
        readonly decimals: 9;
        readonly chainId: 80094;
        readonly website: "https://www.olympusdao.finance/";
        readonly description: "Olympus is building OHM, a community-owned, decentralized and censorship-resistant reserve currency that is asset-backed, deeply liquid and used widely across Web3.";
        readonly documentation: "https://docs.olympusdao.finance/";
        readonly bridge: "layerzero";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly NAV: {
        readonly name: "NavFinance";
        readonly address: "0x6536cEAD649249cae42FC9bfb1F999429b3ec755";
        readonly symbol: "NAV";
        readonly oracleId: "NAV";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://nav.finance/";
        readonly documentation: "https://docs.nav.finance/";
        readonly description: "NAV Finance is a regulated on-chain hedge fund offering Structured Investment Products (SIPs) designed for high-growth opportunities in DeFi.";
        readonly bridge: "native";
    };
    readonly bm: {
        readonly name: "bm";
        readonly address: "0xb749584F9fC418Cf905d54f462fdbFdC7462011b";
        readonly symbol: "bm";
        readonly oracleId: "bm";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://www.bmbm.lol/";
        readonly description: "bm, short for Bera Morning, is a widely recognized term in the Berachain community and the first meme coin ever launched on Berachain.";
        readonly bridge: "native";
        readonly tags: readonly ["LARGE_HOLDERS"];
    };
    readonly LBGT: {
        readonly name: "Liquid BGT";
        readonly address: "0xBaadCC2962417C01Af99fb2B7C75706B9bd6Babe";
        readonly symbol: "LBGT";
        readonly oracleId: "LBGT";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://www.berapaw.com/";
        readonly documentation: "https://docs.berapaw.com/";
        readonly description: "The Liquid Bera Governance Token ($LBGT) is a core component of BeraPaw. It tokenizes Berachain’s native Governance, BGT, into a liquid, transferable asset. This innovation simplifies participation in Berachain’s Proof of Liquidity (PoL) by automating rewards and delegations while providing users with the flexibility to trade and utilize $LBGT across decentralized finance (DeFi) ecosystems.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly YEET: {
        readonly name: "YEET";
        readonly address: "0x08A38Caa631DE329FF2DAD1656CE789F31AF3142";
        readonly symbol: "YEET";
        readonly oracleId: "YEET";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://www.yeetit.xyz/";
        readonly documentation: "https://docs.yeetit.xyz/";
        readonly description: "Yeet offers three core products: the Yeet Game, YeetBonds, and Vault. The Yeet Game combines DeFi and on-chain gaming, allowing players to win $BERA and $YEET prizes. YeetBonds is an open marketplace for OTC sales where users can buy Berachain ecosystem tokens at a discount, in collaboration with Bond Protocol. The Vault is a yield product that farms liquidity and compounds rewards using a complex DeFi yield farming strategy, simplified for users.";
        readonly bridge: "native";
        readonly tags: readonly ["LARGE_HOLDERS"];
    };
    readonly RAMEN: {
        readonly name: "Ramen Token";
        readonly address: "0xb8B1Af593Dc37B33a2c87C8Db1c9051FC32858B7";
        readonly symbol: "RAMEN";
        readonly oracleId: "RAMEN";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://ramen.finance/";
        readonly description: "Token launchpad powering liquidity for next-gen protocols on Berachain";
        readonly bridge: "native";
        readonly tags: readonly ["LARGE_HOLDERS"];
    };
    readonly SolvBTC: {
        readonly name: "SolvBTC";
        readonly symbol: "SolvBTC";
        readonly oracleId: "SolvBTC";
        readonly address: "0x541FD749419CA806a8bc7da8ac23D346f2dF8B77";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://app.solv.finance/solvbtc";
        readonly description: "SolvBTC is a universal Bitcoin reserve token that connects Bitcoin’s value across multiple blockchains. Backed 1:1 by a transparent reserve, it allows you to use your Bitcoin in DeFi, CeFi, and TradFi markets for lending, trading, or yield generation while maintaining full control.";
        readonly documentation: "https://docs.solv.finance/key-products/solvbtc";
        readonly bridge: "layerzero";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly xSolvBTC: {
        readonly name: "xSolvBTC";
        readonly symbol: "xSolvBTC";
        readonly oracleId: "xSolvBTC";
        readonly address: "0xCC0966D8418d412c599A6421b760a847eB169A8c";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://app.solv.finance/xsolvbtc";
        readonly description: "xSolvBTC is a yield-bearing Bitcoin token representing staked Bitcoin in the Babylon ecosystem. Pegged 1:1 with Bitcoin, it enables users to earn staking rewards from Babylon while unlocking liquidity and additional yields in the DeFi ecosystem.";
        readonly documentation: "https://docs.solv.finance/key-products/solvbtc";
        readonly bridge: "layerzero";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly BREAD: {
        readonly name: "BREAD";
        readonly symbol: "BREAD";
        readonly oracleId: "BREAD";
        readonly address: "0x0003eEDFdd020bf60D10cf684ABAc7C4534B7eAd";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://www.bakerdao.io/";
        readonly documentation: "https://documentation.bakerdao.io/";
        readonly description: "BakerDAO combines token economics, collateralized lending, leverage, and Proof-of-Liquidity into a single cohesive financial ecosystem. The $BREAD token features a mathematically-enforced upward price trajectory, backed by $BERA tokens.";
        readonly bridge: "native";
    };
    readonly OOGA: {
        readonly name: "OOGA";
        readonly symbol: "OOGA";
        readonly oracleId: "OOGA";
        readonly address: "0x009af46Df68DB0E76BFe9EA35663f6Ed17877956";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://app.oogabooga.io/";
        readonly documentation: "https://docs.oogabooga.io/";
        readonly description: "Ooga Booga is a decentralized exchange aggregator built on Berachain, designed to help traders find the most cost-effective crypto swaps across various exchanges. It serves as Berachain's native liquidity aggregator, enhancing the efficiency and accessibility of decentralized trading on the platform.";
        readonly bridge: "native";
        readonly tags: readonly ["LARGE_HOLDERS"];
    };
    readonly USDbr: {
        readonly name: "USDbr";
        readonly address: "0x6d4223DAE2a8744a85a6d44e97f3F61679f87ee6";
        readonly symbol: "USDbr";
        readonly oracleId: "USDbr";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://nome.gg/";
        readonly documentation: "https://nome-protocol.gitbook.io/nomeprotocol";
        readonly description: "Nome Protocol is a synthetic asset protocol designed to provide scalable, algorithmic liquidity for the Berachain ecosystem. It operates through $USDbr, an elastic, algorithmic stablecoin, and $NOME, its governance and staking asset.";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly DOLO: {
        readonly name: "Dolomite";
        readonly symbol: "DOLO";
        readonly oracleId: "DOLO";
        readonly address: "0x0F81001eF0A83ecCE5ccebf63EB302c70a39a654";
        readonly decimals: 18;
        readonly chainId: 80094;
        readonly website: "https://dolomite.io/";
        readonly documentation: "https://docs.dolomite.io/";
        readonly description: "Dolomite is a next-generation decentralized money market protocol and DEX that offers broad token support and capital efficiency with its virtual liquidity system. The DOLO token can be used for various purposes, including over-collateralized loans, margin trading, spot trading, and other financial instruments.";
        readonly bridge: "native";
    };
    readonly USDe: {
        readonly name: "USDe";
        readonly symbol: "USDe";
        readonly oracleId: "USDe";
        readonly address: "0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34";
        readonly chainId: 80094;
        readonly decimals: 18;
        readonly website: "https://ethena.fi/";
        readonly documentation: "https://ethena-labs.gitbook.io/ethena-labs";
        readonly description: "Ethenas USDe is not the same as a fiat stablecoin like USDC or USDT. USDe is a synthetic dollar, backed with crypto assets and corresponding short futures positions.";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly sUSDe: {
        readonly name: "Staked USDe";
        readonly symbol: "sUSDe";
        readonly oracleId: "sUSDe";
        readonly address: "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2";
        readonly chainId: 80094;
        readonly decimals: 18;
        readonly website: "https://ethena.fi/";
        readonly documentation: "https://ethena-labs.gitbook.io/ethena-labs";
        readonly description: "Users are able to stake their USDe for sUSDe through the Ethena front-end. sUSDe is a reward-bearing token that accrues value from the yield that Ethena’s underlying delta-neutral position generates. sUSDe is subject to a 7-day un-staking period.";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
};
