const CantoLendAbi = [
  { type: 'constructor', stateMutability: 'nonpayable', inputs: [] },
  {
    type: 'event',
    name: 'ActionPaused',
    inputs: [
      { type: 'string', name: 'action', internalType: 'string', indexed: false },
      { type: 'bool', name: 'pauseState', internalType: 'bool', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ActionPaused',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: false },
      { type: 'string', name: 'action', internalType: 'string', indexed: false },
      { type: 'bool', name: 'pauseState', internalType: 'bool', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CompAccruedAdjusted',
    inputs: [
      { type: 'address', name: 'user', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'oldCompAccrued', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'newCompAccrued', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CompBorrowSpeedUpdated',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: true },
      { type: 'uint256', name: 'newSpeed', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CompGranted',
    inputs: [
      { type: 'address', name: 'recipient', internalType: 'address', indexed: false },
      { type: 'uint256', name: 'amount', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CompReceivableUpdated',
    inputs: [
      { type: 'address', name: 'user', internalType: 'address', indexed: true },
      {
        type: 'uint256',
        name: 'oldCompReceivable',
        internalType: 'uint256',
        indexed: false,
      },
      {
        type: 'uint256',
        name: 'newCompReceivable',
        internalType: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CompSupplySpeedUpdated',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: true },
      { type: 'uint256', name: 'newSpeed', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ContributorCompSpeedUpdated',
    inputs: [
      { type: 'address', name: 'contributor', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'newSpeed', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DistributedBorrowerComp',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: true },
      { type: 'address', name: 'borrower', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'compDelta', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'compBorrowIndex', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DistributedSupplierComp',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: true },
      { type: 'address', name: 'supplier', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'compDelta', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'compSupplyIndex', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Failure',
    inputs: [
      { type: 'uint256', name: 'error', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'info', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'detail', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketEntered',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: false },
      { type: 'address', name: 'account', internalType: 'address', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketExited',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: false },
      { type: 'address', name: 'account', internalType: 'address', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketListed',
    inputs: [{ type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewBorrowCap',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: true },
      { type: 'uint256', name: 'newBorrowCap', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewBorrowCapGuardian',
    inputs: [
      {
        type: 'address',
        name: 'oldBorrowCapGuardian',
        internalType: 'address',
        indexed: false,
      },
      {
        type: 'address',
        name: 'newBorrowCapGuardian',
        internalType: 'address',
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewCloseFactor',
    inputs: [
      {
        type: 'uint256',
        name: 'oldCloseFactorMantissa',
        internalType: 'uint256',
        indexed: false,
      },
      {
        type: 'uint256',
        name: 'newCloseFactorMantissa',
        internalType: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewCollateralFactor',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken', indexed: false },
      {
        type: 'uint256',
        name: 'oldCollateralFactorMantissa',
        internalType: 'uint256',
        indexed: false,
      },
      {
        type: 'uint256',
        name: 'newCollateralFactorMantissa',
        internalType: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewLiquidationIncentive',
    inputs: [
      {
        type: 'uint256',
        name: 'oldLiquidationIncentiveMantissa',
        internalType: 'uint256',
        indexed: false,
      },
      {
        type: 'uint256',
        name: 'newLiquidationIncentiveMantissa',
        internalType: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewPauseGuardian',
    inputs: [
      {
        type: 'address',
        name: 'oldPauseGuardian',
        internalType: 'address',
        indexed: false,
      },
      { type: 'address', name: 'newPauseGuardian', internalType: 'address', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewPriceOracle',
    inputs: [
      {
        type: 'address',
        name: 'oldPriceOracle',
        internalType: 'contract PriceOracle',
        indexed: false,
      },
      {
        type: 'address',
        name: 'newPriceOracle',
        internalType: 'contract PriceOracle',
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'WethAddr',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: '_become',
    inputs: [{ type: 'address', name: 'unitroller', internalType: 'contract Unitroller' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: '_borrowGuardianPaused',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: '_grantComp',
    inputs: [
      { type: 'address', name: 'recipient', internalType: 'address' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: '_mintGuardianPaused',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: '_setBorrowCapGuardian',
    inputs: [{ type: 'address', name: 'newBorrowCapGuardian', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: '_setBorrowPaused',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken' },
      { type: 'bool', name: 'state', internalType: 'bool' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: '_setCloseFactor',
    inputs: [{ type: 'uint256', name: 'newCloseFactorMantissa', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: '_setCollateralFactor',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken' },
      { type: 'uint256', name: 'newCollateralFactorMantissa', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: '_setCompSpeeds',
    inputs: [
      { type: 'address[]', name: 'cTokens', internalType: 'contract CToken[]' },
      { type: 'uint256[]', name: 'supplySpeeds', internalType: 'uint256[]' },
      { type: 'uint256[]', name: 'borrowSpeeds', internalType: 'uint256[]' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: '_setContributorCompSpeed',
    inputs: [
      { type: 'address', name: 'contributor', internalType: 'address' },
      { type: 'uint256', name: 'compSpeed', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: '_setLiquidationIncentive',
    inputs: [{ type: 'uint256', name: 'newLiquidationIncentiveMantissa', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: '_setMarketBorrowCaps',
    inputs: [
      { type: 'address[]', name: 'cTokens', internalType: 'contract CToken[]' },
      { type: 'uint256[]', name: 'newBorrowCaps', internalType: 'uint256[]' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: '_setMintPaused',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'contract CToken' },
      { type: 'bool', name: 'state', internalType: 'bool' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: '_setPauseGuardian',
    inputs: [{ type: 'address', name: 'newPauseGuardian', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: '_setPriceOracle',
    inputs: [{ type: 'address', name: 'newOracle', internalType: 'contract PriceOracle' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: '_setSeizePaused',
    inputs: [{ type: 'bool', name: 'state', internalType: 'bool' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: '_setTransferPaused',
    inputs: [{ type: 'bool', name: 'state', internalType: 'bool' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: '_supportMarket',
    inputs: [{ type: 'address', name: 'cToken', internalType: 'contract CToken' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'contract CToken' }],
    name: 'accountAssets',
    inputs: [
      { type: 'address', name: '', internalType: 'address' },
      { type: 'uint256', name: '', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'admin',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'contract CToken' }],
    name: 'allMarkets',
    inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'borrowAllowed',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'borrower', internalType: 'address' },
      { type: 'uint256', name: 'borrowAmount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'borrowCapGuardian',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'borrowCaps',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'borrowGuardianPaused',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'borrowVerify',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'borrower', internalType: 'address' },
      { type: 'uint256', name: 'borrowAmount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'checkMembership',
    inputs: [
      { type: 'address', name: 'account', internalType: 'address' },
      { type: 'address', name: 'cToken', internalType: 'contract CToken' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'claimComp',
    inputs: [
      { type: 'address', name: 'holder', internalType: 'address' },
      { type: 'address[]', name: 'cTokens', internalType: 'contract CToken[]' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'claimComp',
    inputs: [
      { type: 'address[]', name: 'holders', internalType: 'address[]' },
      { type: 'address[]', name: 'cTokens', internalType: 'contract CToken[]' },
      { type: 'bool', name: 'borrowers', internalType: 'bool' },
      { type: 'bool', name: 'suppliers', internalType: 'bool' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'claimComp',
    inputs: [{ type: 'address', name: 'holder', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'closeFactorMantissa',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'compAccrued',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'compBorrowSpeeds',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'uint224', name: 'index', internalType: 'uint224' },
      { type: 'uint32', name: 'block', internalType: 'uint32' },
    ],
    name: 'compBorrowState',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'compBorrowerIndex',
    inputs: [
      { type: 'address', name: '', internalType: 'address' },
      { type: 'address', name: '', internalType: 'address' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'compContributorSpeeds',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint224', name: '', internalType: 'uint224' }],
    name: 'compInitialIndex',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'compRate',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'compReceivable',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'compSpeeds',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'compSupplierIndex',
    inputs: [
      { type: 'address', name: '', internalType: 'address' },
      { type: 'address', name: '', internalType: 'address' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'compSupplySpeeds',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'uint224', name: 'index', internalType: 'uint224' },
      { type: 'uint32', name: 'block', internalType: 'uint32' },
    ],
    name: 'compSupplyState',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'comptrollerImplementation',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256[]', name: '', internalType: 'uint256[]' }],
    name: 'enterMarkets',
    inputs: [{ type: 'address[]', name: 'cTokens', internalType: 'address[]' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'exitMarket',
    inputs: [{ type: 'address', name: 'cTokenAddress', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'fixBadAccruals',
    inputs: [
      { type: 'address[]', name: 'affectedUsers', internalType: 'address[]' },
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'uint256', name: '', internalType: 'uint256' },
    ],
    name: 'getAccountLiquidity',
    inputs: [{ type: 'address', name: 'account', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address[]', name: '', internalType: 'contract CToken[]' }],
    name: 'getAllMarkets',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address[]', name: '', internalType: 'contract CToken[]' }],
    name: 'getAssetsIn',
    inputs: [{ type: 'address', name: 'account', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'getBlockNumber',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'uint256', name: '', internalType: 'uint256' },
    ],
    name: 'getHypotheticalAccountLiquidity',
    inputs: [
      { type: 'address', name: 'account', internalType: 'address' },
      { type: 'address', name: 'cTokenModify', internalType: 'address' },
      { type: 'uint256', name: 'redeemTokens', internalType: 'uint256' },
      { type: 'uint256', name: 'borrowAmount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'getWETHAddress',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'isComptroller',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'isDeprecated',
    inputs: [{ type: 'address', name: 'cToken', internalType: 'contract CToken' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'lastContributorBlock',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'liquidateBorrowAllowed',
    inputs: [
      { type: 'address', name: 'cTokenBorrowed', internalType: 'address' },
      { type: 'address', name: 'cTokenCollateral', internalType: 'address' },
      { type: 'address', name: 'liquidator', internalType: 'address' },
      { type: 'address', name: 'borrower', internalType: 'address' },
      { type: 'uint256', name: 'repayAmount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'liquidateBorrowVerify',
    inputs: [
      { type: 'address', name: 'cTokenBorrowed', internalType: 'address' },
      { type: 'address', name: 'cTokenCollateral', internalType: 'address' },
      { type: 'address', name: 'liquidator', internalType: 'address' },
      { type: 'address', name: 'borrower', internalType: 'address' },
      { type: 'uint256', name: 'actualRepayAmount', internalType: 'uint256' },
      { type: 'uint256', name: 'seizeTokens', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'uint256', name: '', internalType: 'uint256' },
    ],
    name: 'liquidateCalculateSeizeTokens',
    inputs: [
      { type: 'address', name: 'cTokenBorrowed', internalType: 'address' },
      { type: 'address', name: 'cTokenCollateral', internalType: 'address' },
      { type: 'uint256', name: 'actualRepayAmount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'liquidationIncentiveMantissa',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'bool', name: 'isListed', internalType: 'bool' },
      { type: 'uint256', name: 'collateralFactorMantissa', internalType: 'uint256' },
      { type: 'bool', name: 'isComped', internalType: 'bool' },
    ],
    name: 'markets',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'maxAssets',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'mintAllowed',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'minter', internalType: 'address' },
      { type: 'uint256', name: 'mintAmount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'mintGuardianPaused',
    inputs: [{ type: 'address', name: '', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'mintVerify',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'minter', internalType: 'address' },
      { type: 'uint256', name: 'actualMintAmount', internalType: 'uint256' },
      { type: 'uint256', name: 'mintTokens', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'contract PriceOracle' }],
    name: 'oracle',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'pauseGuardian',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'pendingAdmin',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'pendingComptrollerImplementation',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'proposal65FixExecuted',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'redeemAllowed',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'redeemer', internalType: 'address' },
      { type: 'uint256', name: 'redeemTokens', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'redeemVerify',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'redeemer', internalType: 'address' },
      { type: 'uint256', name: 'redeemAmount', internalType: 'uint256' },
      { type: 'uint256', name: 'redeemTokens', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'repayBorrowAllowed',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'payer', internalType: 'address' },
      { type: 'address', name: 'borrower', internalType: 'address' },
      { type: 'uint256', name: 'repayAmount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'repayBorrowVerify',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'payer', internalType: 'address' },
      { type: 'address', name: 'borrower', internalType: 'address' },
      { type: 'uint256', name: 'actualRepayAmount', internalType: 'uint256' },
      { type: 'uint256', name: 'borrowerIndex', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'seizeAllowed',
    inputs: [
      { type: 'address', name: 'cTokenCollateral', internalType: 'address' },
      { type: 'address', name: 'cTokenBorrowed', internalType: 'address' },
      { type: 'address', name: 'liquidator', internalType: 'address' },
      { type: 'address', name: 'borrower', internalType: 'address' },
      { type: 'uint256', name: 'seizeTokens', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'seizeGuardianPaused',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'seizeVerify',
    inputs: [
      { type: 'address', name: 'cTokenCollateral', internalType: 'address' },
      { type: 'address', name: 'cTokenBorrowed', internalType: 'address' },
      { type: 'address', name: 'liquidator', internalType: 'address' },
      { type: 'address', name: 'borrower', internalType: 'address' },
      { type: 'uint256', name: 'seizeTokens', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'setWETHAddress',
    inputs: [{ type: 'address', name: 'wethAddr', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'transferAllowed',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'src', internalType: 'address' },
      { type: 'address', name: 'dst', internalType: 'address' },
      { type: 'uint256', name: 'transferTokens', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'transferGuardianPaused',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'transferVerify',
    inputs: [
      { type: 'address', name: 'cToken', internalType: 'address' },
      { type: 'address', name: 'src', internalType: 'address' },
      { type: 'address', name: 'dst', internalType: 'address' },
      { type: 'uint256', name: 'transferTokens', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'updateContributorRewards',
    inputs: [{ type: 'address', name: 'contributor', internalType: 'address' }],
  },
] as const;

export default CantoLendAbi;
