export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped Ether";
        readonly address: "0x4200000000000000000000000000000000000006";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 10;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly FEES: {
        readonly name: "Wrapped Ether";
        readonly address: "0x4200000000000000000000000000000000000006";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 10;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly ETH: {
        readonly name: "Wrapped Ether";
        readonly address: "0x4200000000000000000000000000000000000006";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 10;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly WETH: {
        readonly name: "Wrapped Ether";
        readonly address: "0x4200000000000000000000000000000000000006";
        readonly symbol: "WETH";
        readonly oracleId: "WETH";
        readonly decimals: 18;
        readonly chainId: 10;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly mooBIFI: {
        readonly name: "Bridged BIFI Vault Receipt";
        readonly symbol: "mooBIFI";
        readonly oracleId: "opmooBIFI";
        readonly address: "0xc55E93C62874D8100dBd2DfE307EDc1036ad5434";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://beefy.com";
        readonly description: "The incentive-bearing Beefy Token (mooBIFI) applies the magic of Beefy's autocompounding technology to the BIFI token. It is the vault token for the BIFI Vault, which automatically claims and swaps governance incentives into more BIFI, and redeposits to unlock exponential growth. On chains other than Ethereum, mooBIFI is a bridged copy of the native Ethereum token, and cannot be returned to BIFI without first bridging back to Ethereum. mooBIFI holders on all chains retain their full voting power corresponding to the underlying amount of BIFI deposited and compounding on Ethereum.";
        readonly documentation: "https://docs.beefy.finance/";
        readonly bridge: "beefy";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly oldBIFI: {
        readonly name: "Beefy.Finance";
        readonly symbol: "oldBIFI";
        readonly oracleId: "oldBIFI";
        readonly address: "0x4E720DD3Ac5CFe1e1fbDE4935f386Bb1C66F4642";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://beefy.com";
        readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
        readonly documentation: "https://docs.beefy.finance/";
    };
    readonly omultiwUSDR: {
        readonly name: "Real USD";
        readonly symbol: "omultiwUSDR";
        readonly oracleId: "omultiwUSDR";
        readonly address: "0x340fE1D898ECCAad394e2ba0fC1F93d27c7b717A";
        readonly chainId: 10;
        readonly decimals: 9;
        readonly website: "https://www.tangible.store/realusd";
        readonly documentation: "https://docs.tangible.store/";
        readonly description: "Real USD (USDR) is the world’s first stablecoin collateralized by tokenized, yield-producing real estate. USDR has a value accrual system built into its design. Using a consistent stream of dependable yield derived from rental revenue, Real USD delivers a native yield to holders. The token on Optimism is bridged via Multichain from Polygon.";
        readonly bridge: "multichain";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly beOPX: {
        readonly name: "Beefy Escrowed OPX";
        readonly symbol: "beOPX";
        readonly oracleId: "beOPX";
        readonly address: "0xEDFBeC807304951785b581dB401fDf76b4bAd1b0";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.opx.finance/";
        readonly description: "Beefy Escrowed OPX is a liquid staking solution to earn maximum governance rewards from the OPX platform using the highest tier NFT and maximum lock.";
    };
    readonly OPX: {
        readonly name: "OPX";
        readonly symbol: "OPX";
        readonly oracleId: "OPX";
        readonly address: "0xcdB4bB51801A1F399d4402c61bC098a72c382E65";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.opx.finance/";
        readonly description: "OPX is the utility and governance token of the OPX decentralized spot and perpetual exchange that supports low swap fees, zero price impact trades and up to 30x leverage. Locked OPX earns trading fees and upto 35% of platform fees in the form of ETH.";
    };
    readonly jEUR: {
        readonly name: "Jarvis Synthetic Euro";
        readonly symbol: "jEUR";
        readonly oracleId: "jEUR";
        readonly address: "0x79AF5dd14e855823FA3E9ECAcdF001D99647d043";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://jarvis.network/";
        readonly description: "jEUR is a multi-collateralized synthetic token tracking the price of Euro. It is built on the top of UMA and Chainlink.";
        readonly bridge: "native";
        readonly documentation: "https://learn.jarvis.network/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly HOP: {
        readonly name: "HOP Protocol";
        readonly symbol: "HOP";
        readonly oracleId: "HOP";
        readonly address: "0xc5102fE9359FD9a28f877a67E36B0F050d81a3CC";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.hop.exchange";
        readonly description: "Hop Protocol is a blockchain bridge protocol that allows users to move tokens from one chain to another without having to wait for a challenge period";
        readonly bridge: "hop";
        readonly documentation: "https://docs.hop.exchange/";
    };
    readonly BEETS: {
        readonly name: "Beethoven X Token";
        readonly symbol: "BEETS";
        readonly oracleId: "BEETS";
        readonly address: "0x97513e975a7fA9072c72C92d8000B0dB90b163c5";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://beethovenx.io/";
        readonly description: "BEETS is the governance token for the Beethoven X protocol. Built on Balancer V2, Beethoven X is the first next-generation AMM protocol on Fantom.";
        readonly bridge: "multichain";
    };
    readonly OP: {
        readonly name: "Optimism Token";
        readonly symbol: "OP";
        readonly oracleId: "OP";
        readonly address: "0x4200000000000000000000000000000000000042";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.optimism.io/governance";
        readonly description: "Optimistic Rollup is a layer 2 scaling solution that scales both transaction throughput and computation on Ethereum. The backbone of our implementation is the Optimistic Virtual Machine (OVM), which is fully compatible with the EVM.";
        readonly bridge: "native";
        readonly documentation: "https://help.optimism.io/hc/en-us/articles/5497354656283-What-is-the-Optimism-Token";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly opUSDCe: {
        readonly name: "USD Coin";
        readonly symbol: "USDCe";
        readonly oracleId: "opUSDCe";
        readonly address: "0x7F5c764cBc14f9669B88837ca1490cCa17c31607";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://www.circle.com/blog/now-available-usdc-on-op-mainnet";
        readonly description: "USDC.e is an Ethereum-based USDC bridged via the official Optimism Bridge.";
        readonly bridge: "optimism-canonical";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly USDC: {
        readonly name: "USD Coin";
        readonly symbol: "USDC";
        readonly oracleId: "USDC";
        readonly address: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://developers.circle.com/docs";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly sUSD: {
        readonly name: "Synth sUSD";
        readonly symbol: "sUSD";
        readonly oracleId: "opsUSD";
        readonly address: "0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.synthetix.io/";
        readonly description: "sUSD is a synthetic USD token enabled by the Synthetix protocol. It tracks the price of the US Dollar through price feeds supplied by Chainlink’s decentralized network of oracles";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.synthetix.io/synthetix-protocol/readme";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly WBTC: {
        readonly chainId: 10;
        readonly address: "0x68f180fcCe6836688e9084f035309E29Bf0A2095";
        readonly decimals: 8;
        readonly name: "Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "WBTC";
        readonly website: "https://wbtc.network/";
        readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
        readonly bridge: "optimism-canonical";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly sBTC: {
        readonly chainId: 10;
        readonly address: "0x298B9B95708152ff6968aafd889c6586e9169f1D";
        readonly decimals: 18;
        readonly name: "Synthetix: sBTC";
        readonly symbol: "sBTC";
        readonly oracleId: "sBTC";
        readonly website: "https://www.synthetix.io/";
        readonly description: "sBTC is a synthetic Bitcoin token enabled by the Synthetix protocol. It tracks the price of Bitcoin through price feeds supplied by Chainlink’s decentralized network of oracles.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.synthetix.io/synthetix-protocol/readme";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly LYRA: {
        readonly chainId: 10;
        readonly address: "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb";
        readonly decimals: 18;
        readonly name: "Lyra Token";
        readonly symbol: "LYRA";
        readonly oracleId: "LYRA";
        readonly website: "https://www.lyra.finance/";
        readonly description: "Lyra’s decentralized exchange is the easiest place to buy and sell options on cryptocurrencies.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.lyra.finance/docs/token";
    };
    readonly QI: {
        readonly chainId: 10;
        readonly address: "0x3F56e0c36d275367b8C502090EDF38289b3dEa0d";
        readonly decimals: 18;
        readonly name: "Qi Dao";
        readonly symbol: "QI";
        readonly oracleId: "QI";
        readonly website: "https://www.mai.finance/";
        readonly description: "QiDao is a self-sustaining, community-governed protocol that allows you to borrow stablecoins interest-free against your crypto assets used as collateral. Loans are paid out and repaid in miTokens (stablecoin soft pegged to the USD).";
        readonly documentation: "https://docs.mai.finance/";
    };
    readonly SNX: {
        readonly name: "Synthetix";
        readonly symbol: "SNX";
        readonly oracleId: "SNX";
        readonly address: "0x8700dAec35aF8Ff88c16BdF0418774CB3D7599B4";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.synthetix.io/";
        readonly description: "Synthetix is the backbone for derivatives trading in DeFi, allowing anyone, anywhere to gain on-chain exposure to a vast range of assets.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.synthetix.io/synthetix-protocol/the-synthetix-protocol/synthetix-token-snx";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly PERP: {
        readonly name: "Perpetual Protocol";
        readonly symbol: "PERP";
        readonly oracleId: "PERP";
        readonly address: "0x9e1028F5F1D5eDE59748FFceE5532509976840E0";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.perp.com/";
        readonly description: "Cross margin DeFi trading with up to 10×-leverage.";
        readonly bridge: "optimism-canonical";
    };
    readonly BAL: {
        readonly name: "Balancer";
        readonly symbol: "BAL";
        readonly oracleId: "BAL";
        readonly address: "0xFE8B128bA8C78aabC59d4c64cEE7fF28e9379921";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://balancer.fi/";
        readonly description: "Balancer turns the concept of an index fund on its head: instead of a paying fees to portfolio managers to rebalance your portfolio, you collect fees from traders, who rebalance your portfolio by following arbitrage opportunities.";
        readonly bridge: "optimism-canonical";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly MAI: {
        readonly chainId: 10;
        readonly address: "0xdFA46478F9e5EA86d57387849598dbFB2e964b02";
        readonly decimals: 18;
        readonly name: "Mai Stablecoin";
        readonly symbol: "MAI";
        readonly oracleId: "oMAI";
        readonly website: "https://www.mai.finance/";
        readonly description: "MAI is a stablecoin collateralized by your crypto holdings. It's powered by Qi Dao, a protocol that enables any cryptocurrency community to create stablecoins backed by their native tokens.";
        readonly bridge: "native";
        readonly documentation: "https://docs.mai.finance/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly FRAX: {
        readonly name: "Frax";
        readonly address: "0x2E3D870790dC77A83DD1d18184Acc7439A53f475";
        readonly symbol: "FRAX";
        readonly oracleId: "FRAX";
        readonly decimals: 18;
        readonly chainId: 10;
        readonly website: "https://frax.finance/";
        readonly description: "The Frax Protocol introduced the world to the concept of a cryptocurrency being partially backed by collateral and partially stabilized algorithmically.";
        readonly bridge: "frax";
        readonly documentation: "https://docs.frax.finance/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly VELO: {
        readonly chainId: 10;
        readonly address: "0x3c8B650257cFb5f272f799F5e2b4e65093a11a05";
        readonly decimals: 18;
        readonly name: "Velodrome";
        readonly symbol: "VELO";
        readonly oracleId: "VELO";
        readonly website: "https://velodrome.finance/";
        readonly description: "Velodrome Finance, at its core, is a solution for protocols on Optimism to properly incentivize liquidity for their own use cases. Building on top of the groundwork laid out by Solidly, our team has addressed that first iteration's core issues to realize its full potential.";
        readonly bridge: "native";
        readonly documentation: "https://velodrome.finance/docs";
    };
    readonly sETH: {
        readonly name: "Synth sETH";
        readonly symbol: "sETH";
        readonly oracleId: "sETH";
        readonly address: "0xE405de8F52ba7559f9df3C368500B6E6ae6Cee49";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://synthetix.io/";
        readonly description: "Synths are derivative tokens providing exposure to a range of assets. They can be traded with infinite liquidity and zero slippage by leveraging the Synthetix protocol’s unique pooled collateral model. Trades between Synths generate a small fee that is distributed to SNX collateral providers.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.synthetix.io/synthetix-protocol/readme";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly DAI: {
        readonly name: "DAI Stablecoin";
        readonly symbol: "DAI";
        readonly oracleId: "DAI";
        readonly address: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://makerdao.com/en/";
        readonly description: "Dai is a stablecoin cryptocurrency which aims to keep its value as close to one United States dollar as possible through an automated system of smart contracts on the Ethereum blockchain";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.makerdao.com/smart-contract-modules/dai-module/dai-detailed-documentation";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly LUSD: {
        readonly name: "LUSD Stablecoin";
        readonly symbol: "LUSD";
        readonly oracleId: "LUSD";
        readonly address: "0xc40F949F8a4e094D1b49a23ea9241D289B7b2819";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.liquity.org/";
        readonly description: "Liquity is a decentralized borrowing protocol that allows you to draw interest-free loans against Ether used as collateral. Loans are paid out in LUSD (a USD pegged stablecoin) and need to maintain a minimum collateral ratio of 110%.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.liquity.org/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly soUSDC: {
        readonly name: "Stargate USD Coin LP";
        readonly symbol: "soUSDC";
        readonly oracleId: "stargate-op-usdc";
        readonly address: "0xDecC0c09c3B5f6e92EF4184125D5648a66E35298";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://stargate.finance/";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly documentation: "https://stargateprotocol.gitbook.io/stargate/v/user-docs/";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly soETH: {
        readonly name: "Stargate Ethereum LP";
        readonly symbol: "soETH";
        readonly oracleId: "stargate-op-eth";
        readonly address: "0xd22363e3762cA7339569F3d33EADe20127D5F98C";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://stargate.finance/";
        readonly description: "The native currency that flows within the Ethereum economy is called Ether (ETH). Ether is typically used to pay for transaction fees called Gas, and it is the base currency of the network.";
        readonly documentation: "https://stargateprotocol.gitbook.io/stargate/v/user-docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly renBTC: {
        readonly name: "renBTC";
        readonly symbol: "renBTC";
        readonly oracleId: "renBTC";
        readonly address: "0x85f6583762Bc76d775eAB9A7456db344f12409F7";
        readonly chainId: 10;
        readonly decimals: 8;
        readonly website: "https://renproject.io/";
        readonly description: "RenBTC is an ERC-20 token built on the Ethereum network, pegged to Bitcoin. This means that each RenBTC can be always redeemed for one Bitcoin, and hence tends to maintain its value at close to the Bitcoin market rate.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly FXS: {
        readonly name: "Frax Share";
        readonly symbol: "FXS";
        readonly oracleId: "FXS";
        readonly address: "0x67CCEA5bb16181E7b4109c9c2143c24a1c2205Be";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://frax.finance/";
        readonly description: "The Frax Protocol introduced the world to the concept of a cryptocurrency being partially backed by collateral and partially stabilized algorithmically.";
        readonly bridge: "frax";
    };
    readonly THALES: {
        readonly name: "Thales DAO Token";
        readonly symbol: "THALES";
        readonly oracleId: "THALES";
        readonly address: "0x217D47011b23BB961eB6D93cA9945B7501a5BB11";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://thalesmarket.io/tale-of-thales";
        readonly description: "Thales is an Ethereum protocol that allows the creation of peer-to-peer parimutuel markets that anyone can join.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.thalesmarket.io/";
    };
    readonly alUSD: {
        readonly name: "Alchemix USD";
        readonly symbol: "alUSD";
        readonly oracleId: "alUSD";
        readonly address: "0xCB8FA9a76b8e203D8C3797bF438d8FB81Ea3326A";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://alchemix.fi/";
        readonly description: "Alchemix Self-Repaying Loans allow you to leverage a range of tokens without risk of liquidation.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://alchemix-finance.gitbook.io/user-docs/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly alETH: {
        readonly name: "Alchemix ETH";
        readonly symbol: "alETH";
        readonly oracleId: "alETH";
        readonly address: "0x3E29D3A9316dAB217754d13b28646B76607c5f04";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://alchemix.fi/";
        readonly description: "Alchemix Self-Repaying Loans allow you to leverage a range of tokens without risk of liquidation.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://alchemix-finance.gitbook.io/user-docs/";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly DOLA: {
        readonly name: "Dola USD Stablecoin";
        readonly symbol: "DOLA";
        readonly oracleId: "DOLA";
        readonly address: "0x8aE125E8653821E851F12A49F7765db9a9ce7384";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.inverse.finance/";
        readonly description: "Inverse.finance is a suite of permissionless decentralized finance tools governed by Inverse DAO, a decentralized autonomous organization running on the Ethereum blockchain.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.inverse.finance/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly HND: {
        readonly name: "Hundred Finance";
        readonly symbol: "HND";
        readonly oracleId: "HND";
        readonly address: "0x10010078a54396F62c96dF8532dc2B4847d47ED3";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://hundred.finance/";
        readonly description: "Hundred Finance is a decentralized application (dApp) that enables the lending and borrowing of cryptocurrencies.";
    };
    readonly beVELO: {
        readonly name: "Beefy Velo ";
        readonly symbol: "beVELO";
        readonly oracleId: "BeVELO";
        readonly address: "0xfDeFFc7Ad816BF7867C642dF7eBC2CC5554ec265";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://beefy.com";
        readonly description: "beVELO is Beefy-wrapped VELO that earns more VELO over time. Beefy distributes trading fees and bribe rewards weekly to beVELO holders, swapping VELO to beVELO. beVELO holders receive the same rewards as max-locked veNFT VELO holders.";
        readonly documentation: "https://docs.beefy.finance/beefy-products/beefy-escrowed-tokens/bevelo";
        readonly bridge: "native";
    };
    readonly EURA: {
        readonly name: "EURA (previously agEUR)";
        readonly symbol: "EURA";
        readonly oracleId: "agEUR";
        readonly address: "0x9485aca5bbBE1667AD97c7fE7C4531a624C8b1ED";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.angle.money/";
        readonly description: "EURA (previously agEUR) is pegged to the value of the Euro (€) and is a product of Angle, a decentralized, capital-efficient and over-collateralized stablecoins protocol.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.angle.money/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly USDA: {
        readonly name: "USDA";
        readonly symbol: "USDA";
        readonly oracleId: "USDA";
        readonly address: "0x0000206329b97DB379d5E1Bf586BbDB969C63274";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.angle.money/";
        readonly description: "USDA is pegged to the value of the Dollar ($) and is a product of Angle, a decentralized, capital-efficient and over-collateralized stablecoins protocol.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.angle.money/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly L2DAO: {
        readonly name: "Layer2DAO";
        readonly symbol: "L2DAO";
        readonly oracleId: "L2DAO";
        readonly address: "0xd52f94DF742a6F4B4C8b033369fE13A41782Bf44";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.layer2dao.org/#/";
        readonly description: "Layer2DAO is expanding the Ethereum L2 ecosystem and investing in L2 ecosystem projects. The DAO uses its treasury to invest into high-impact L2 protocols and ecosystem plays, serving as a diversified venture fund for investors looking to gain exposure to the L2 ecosystem growth. It also provides liquidity, depositing, and staking, perpetually reinvesting proceeds back into the DAO.";
    };
    readonly AELIN: {
        readonly name: "Aelin Token";
        readonly symbol: "AELIN";
        readonly oracleId: "AELIN";
        readonly address: "0x61BAADcF22d2565B0F471b291C475db5555e0b76";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://aelin.xyz/";
        readonly description: "A permissionless multi-chain protocol for capital raises and OTC deals. No need for VCs, Aelin decentralizes fundraising";
        readonly bridge: "native";
    };
    readonly pETHo: {
        readonly name: "pETHo";
        readonly symbol: "pETHo";
        readonly oracleId: "pETHo";
        readonly address: "0x6ca558bd3eaB53DA1B25aB97916dd14bf6CFEe4E";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://ripae.finance/";
        readonly description: "Ripae Finance’s full focus is to build a true cross-chain algorithmic stable coin protocol that is stabilized with true use-cases all around the DeFi Ecosystem.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly sETHo: {
        readonly name: "sETHo";
        readonly symbol: "sETHo";
        readonly oracleId: "sETHo";
        readonly address: "0x09448876068907827ec15F49A8F1a58C70b04d45";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://ripae.finance/";
        readonly description: "Ripae Finance’s full focus is to build a true cross-chain algorithmic stable coin protocol that is stabilized with true use-cases all around the DeFi Ecosystem.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly rETH: {
        readonly name: "Rocket Pool ETH";
        readonly symbol: "rETH";
        readonly oracleId: "rETH";
        readonly address: "0x9Bcef72be871e61ED4fBbc7630889beE758eb81D";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://rocketpool.net/";
        readonly description: "As a Rocket Pool staker, your role is to deposit ETH into the deposit pool which will enable a node operator to create a new Beacon Chain validator. You can stake as little as 0.01 ETH. In doing so, you will be given a token called rETH. rETH represents both how much ETH you deposited, and when you deposited it.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.rocketpool.net/guides/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly 'USD+': {
        readonly name: "USD+ Stablecoin";
        readonly symbol: "USD+";
        readonly oracleId: "oUSD+";
        readonly address: "0x73cb180bf0521828d8849bc8CF2B920918e23032";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://overnight.fi/";
        readonly description: "USD+ is USDC that pays you yield daily via rebase.  It is 100% collateralized with assets immediately convertible into USDC.  Yield is generated via strategies such as lending and stable-to-stable pools. Initial strategies include Aave, Rubicon, and Pika.";
        readonly bridge: "native";
        readonly documentation: "https://docs.overnight.fi/";
        readonly tags: readonly ["CURATED", "STABLECOIN"];
    };
    readonly 'DAI+': {
        readonly name: "DAI+ Stablecoin";
        readonly symbol: "DAI+";
        readonly oracleId: "DAI+";
        readonly address: "0x970D50d09F3a656b43E11B0D45241a84e3a6e011";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://overnight.fi/";
        readonly description: "DAI+ is DAI that pays you yield daily via rebase.  It is 100% collateralized with assets immediately convertible into DAI.  Yield is generated via strategies such as lending and stable-to-stable pools. Initial strategies include Aave, Rubicon, and Pika.";
        readonly bridge: "native";
        readonly documentation: "https://docs.overnight.fi/";
        readonly tags: readonly ["CURATED", "STABLECOIN"];
    };
    readonly TUSD: {
        readonly name: "TrueUSD";
        readonly symbol: "TUSD";
        readonly oracleId: "TUSD";
        readonly address: "0xcB59a0A753fDB7491d5F3D794316F1adE197B21E";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.trueusd.com/";
        readonly description: "TrueUSD (TUSD) is the first independently-verified digital asset redeemable 1-for-1 for US Dollars.";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly BOND: {
        readonly name: "BarnBridge Governance Token (Optimism)";
        readonly symbol: "BOND";
        readonly oracleId: "BOND";
        readonly address: "0x3e7eF8f50246f725885102E8238CBba33F276747";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://barnbridge.com/";
        readonly description: "BarnBridge v2 is an open source, fixed-income, decentralized protocol that allows users to earn a fixed return on their deposits by swapping variable APYs from money markets for a fixed APY.";
        readonly documentation: "https://docs.barnbridge.com/";
    };
    readonly SONNE: {
        readonly name: "Sonne";
        readonly symbol: "SONNE";
        readonly oracleId: "SONNE";
        readonly address: "0x1DB2466d9F5e10D7090E7152B68d62703a2245F0";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://sonne.finance/";
        readonly description: "Sonne Finance is an EVM compatible lending/borrowing protocol that launched on Optimism. Sonne Finance provides peer-to-peer lending solutions that are fully decentralized, transparent and non-custodial. ";
        readonly bridge: "native";
        readonly documentation: "https://docs.sonne.finance/";
    };
    readonly USX: {
        readonly name: "dForce USD";
        readonly symbol: "USX";
        readonly oracleId: "USX";
        readonly address: "0xbfD291DA8A403DAAF7e5E9DC1ec0aCEaCd4848B9";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://dforce.network/";
        readonly description: "USX is the most important DeFi primitive within dForce’s protocol matrix, starting off with an over-collateralization design, where supported assets can be used as collaterals to mint USX within the respective approved LTV ratio (similar to DAI).";
        readonly documentation: "https://docs.dforce.network/protocols/usx";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly MIM: {
        readonly name: "Magic Internet Money";
        readonly symbol: "MIM";
        readonly oracleId: "MIM";
        readonly address: "0xB153FB3d196A8eB25522705560ac152eeEc57901";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://abracadabra.money/";
        readonly description: "You, the Spellcaster, can provide collateral in the form of various interest bearing crypto assets such as yvYFI, yvUSDT, yvUSDC, xSUSHI and more. With this, you can borrow magic internet money (MIM) which is a stable coin that you can swap for any other traditional stable coin.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.abracadabra.money/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly rfaWETH: {
        readonly name: "Reaper.Farm Aave WETH";
        readonly symbol: "rfaWETH";
        readonly oracleId: "rfaWETH";
        readonly address: "0xdf2D2c477078D2cD563648abbb913dA3Db247c00";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.reaper.farm/";
        readonly description: "ETH deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.reaper.farm/reaper-farms/general-knowledge/types-of-strategies/ltv-looping";
    };
    readonly bbrfaWETH: {
        readonly name: "Beets Reaper.Farm Boosted Aave WETH";
        readonly symbol: "bbrfaWETH";
        readonly oracleId: "bbrfaWETH";
        readonly address: "0xDD89C7cd0613C1557B2DaAC6Ae663282900204f1";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://op.beets.fi/pools";
        readonly description: "Composable Pool with ETH deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.beets.fi/balancer-v2-1/pools";
    };
    readonly bbrfaUSDC: {
        readonly name: "Beets Reaper.Farm Boosted Aave USDC";
        readonly symbol: "bbrfaUSDC";
        readonly oracleId: "bbrfaUSDC";
        readonly address: "0xba7834bb3cd2DB888E6A06Fb45E82b4225Cd0C71";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://op.beets.fi/pools";
        readonly description: "Composable Pool with USDC deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.beets.fi/balancer-v2-1/pools";
    };
    readonly rfaUSDC: {
        readonly name: "Reaper.Farm Aave USDC";
        readonly symbol: "rfaUSDC";
        readonly oracleId: "rfaUSDC";
        readonly address: "0x7ecc9D0eE071C7b86d0Ae2101231A3615564009e";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.reaper.farm/";
        readonly description: "USDC deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.reaper.farm/reaper-farms/general-knowledge/types-of-strategies/ltv-looping";
    };
    readonly bbrfaUSDT: {
        readonly name: "Beets Reaper.Farm Boosted Aave USDT";
        readonly symbol: "bbrfaUSDT";
        readonly oracleId: "bbrfaUSDT";
        readonly address: "0x9253d7e1B42fa01eDE2c53f3A21b3B4d13239cD4";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://op.beets.fi/pools";
        readonly description: "Composable Pool with USDT deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.beets.fi/balancer-v2-1/pools";
    };
    readonly bbrfaUSD: {
        readonly name: "Steady Beets, Boosted";
        readonly symbol: "bbrfaUSD";
        readonly oracleId: "bbrfaUSD";
        readonly address: "0x6222ae1d2a9f6894dA50aA25Cb7b303497f9BEbd";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://op.beets.fi/pools";
        readonly description: "Composable Pool with Reaper.Farm USDT, USDC and DAI deposited into different Reaper.Farm vaults and leveraged through Aave";
        readonly documentation: "https://docs.beets.fi/balancer-v2-1/pools";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly rfaUSDT: {
        readonly name: "Reaper.Farm Aave USDT";
        readonly symbol: "rfaUSDT";
        readonly oracleId: "rfaUSDT";
        readonly address: "0x61cbcb4278D737471EE54dc689de50E4455978D8";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.reaper.farm/";
        readonly description: "USDT deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.reaper.farm/reaper-farms/general-knowledge/types-of-strategies/ltv-looping";
    };
    readonly bbrfaDAI: {
        readonly name: "Beets Reaper.Farm Boosted Aave DAI";
        readonly symbol: "bbrfaDAI";
        readonly oracleId: "bbrfaDAI";
        readonly address: "0x888a6195D42a95e80D81e1c506172772a80b80Bc";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://op.beets.fi/pools";
        readonly description: "Composable Pool with DAI deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.beets.fi/balancer-v2-1/pools";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly rfaDAI: {
        readonly name: "Reaper.Farm Aave DAI";
        readonly symbol: "rfaDAI";
        readonly oracleId: "rfaDAI";
        readonly address: "0x75441c125890612F95b5FBf3f73DB0C25F5573Cd";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.reaper.farm/";
        readonly description: "DAI deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.reaper.farm/reaper-farms/general-knowledge/types-of-strategies/ltv-looping";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly bbrfaWBTC: {
        readonly name: "Beets Reaper.Farm Boosted Aave WBTC";
        readonly symbol: "bbrfaWBTC";
        readonly oracleId: "bbrfaWBTC";
        readonly address: "0xA1a77E5d7D769BFBB790a08EC976dc738bF795B9";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://op.beets.fi/pools";
        readonly description: "Composable Pool with WBTC deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.beets.fi/balancer-v2-1/pools";
    };
    readonly rfaWBTC: {
        readonly name: "Reaper.Farm Aave WBTC";
        readonly symbol: "rfaWBTC";
        readonly oracleId: "rfaWBTC";
        readonly address: "0x43cB769D5647CC56F5c1E8Df72aB9097DAB59cCe";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.reaper.farm/";
        readonly description: "WBTC deposited into Reaper.Farm and leveraged through Aave";
        readonly documentation: "https://docs.reaper.farm/reaper-farms/general-knowledge/types-of-strategies/ltv-looping";
    };
    readonly USDT: {
        readonly name: "USD Tether";
        readonly symbol: "USDT";
        readonly oracleId: "USDT";
        readonly address: "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://tether.to/";
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://tether.to/en/how-it-works";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly wstETH: {
        readonly name: "Lido Wrapped Staked ETH";
        readonly symbol: "wstETH";
        readonly oracleId: "wstETH";
        readonly address: "0x1F32b1c2345538c0c6f582fCB022739c4A194Ebb";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://lido.fi/";
        readonly description: "Lido is a liquid staking solution for ETH backed by industry-leading staking providers. Lido lets users stake their ETH - without locking assets or maintaining infrastructure - whilst participating in on-chain activities, e.g. lending. Lido attempts to solve the problems associated with initial ETH staking - illiquidity, immovability and accessibility - making staked ETH liquid and allowing for participation with any amount of ETH to improve security of the Ethereum network.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.lido.fi/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly hETH: {
        readonly name: "ETH Hop Token";
        readonly symbol: "hETH";
        readonly oracleId: "hETH";
        readonly address: "0xE38faf9040c7F09958c638bBDB977083722c5156";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.hop.exchange";
        readonly description: "hETH is the bridge token for transferring ETH via the Hop Protocol. Hop Protocol is a blockchain bridge protocol that allows users to move tokens from one chain to another without having to wait for a challenge period.";
        readonly bridge: "hop";
        readonly documentation: "https://docs.hop.exchange/";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly hUSDC: {
        readonly name: "USDC Hop Token";
        readonly symbol: "hUSDC";
        readonly oracleId: "hUSDC";
        readonly address: "0x25D8039bB044dC227f741a9e381CA4cEAE2E6aE8";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://app.hop.exchange";
        readonly description: "hUSDC is the bridge token for transferring USDC via the Hop Protocol. Hop Protocol is a blockchain bridge protocol that allows users to move tokens from one chain to another without having to wait for a challenge period.";
        readonly bridge: "hop";
        readonly documentation: "https://docs.hop.exchange/";
    };
    readonly hUSDT: {
        readonly name: "USDT Hop Token";
        readonly symbol: "hUSDT";
        readonly oracleId: "hUSDT";
        readonly address: "0x2057C8ECB70Afd7Bee667d76B4CD373A325b1a20";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://app.hop.exchange";
        readonly description: "hUSDT is the bridge token for transferring USDT via the Hop Protocol. Hop Protocol is a blockchain bridge protocol that allows users to move tokens from one chain to another without having to wait for a challenge period.";
        readonly bridge: "hop";
        readonly documentation: "https://docs.hop.exchange/";
    };
    readonly hDAI: {
        readonly name: "DAI Hop Token";
        readonly symbol: "hDAI";
        readonly oracleId: "hDAI";
        readonly address: "0x56900d66D74Cb14E3c86895789901C9135c95b16";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.hop.exchange";
        readonly description: "hDAI is the bridge token for transferring DAI via the Hop Protocol. Hop Protocol is a blockchain bridge protocol that allows users to move tokens from one chain to another without having to wait for a challenge period.";
        readonly bridge: "hop";
        readonly documentation: "https://docs.hop.exchange/";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly hSNX: {
        readonly name: "SNX Hop Token";
        readonly symbol: "hSNX";
        readonly oracleId: "hSNX";
        readonly address: "0x13B7F51BD865410c3AcC4d56083C5B56aB38D203";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.hop.exchange";
        readonly description: "hSNX is the bridge token for transferring SNX via the Hop Protocol. Hop Protocol is a blockchain bridge protocol that allows users to move tokens from one chain to another without having to wait for a challenge period.";
        readonly bridge: "hop";
        readonly documentation: "https://docs.hop.exchange/";
    };
    readonly LDO: {
        readonly name: "Lido DAO Token";
        readonly symbol: "LDO";
        readonly oracleId: "LDO";
        readonly address: "0xFdb794692724153d1488CcdBE0C56c252596735F";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://stake.lido.fi/";
        readonly description: "Lido is a liquid staking solution for ETH 2.0 backed by industry-leading staking providers.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.lido.fi/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly KWENTA: {
        readonly name: "Kwenta";
        readonly symbol: "KWENTA";
        readonly oracleId: "KWENTA";
        readonly address: "0x920Cf626a271321C151D027030D5d08aF699456b";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://kwenta.eth.limo/dashboard";
        readonly description: "Kwenta is a decentralized derivatives trading platform, live on Optimism, offering real-world and on-chain synthetic assets using the power of the Synthetix protocol.";
        readonly bridge: "native";
        readonly documentation: "https://docs.kwenta.io/";
    };
    readonly multiUNIDX: {
        readonly name: "UniDex";
        readonly symbol: "multiUNIDX";
        readonly oracleId: "multiUNIDX";
        readonly address: "0x5d47bAbA0d66083C52009271faF3F50DCc01023C";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.unidex.exchange/trading";
        readonly description: "UniDex is building on top of the existing landscape by introducing a perpetual leverage trading platform that will allow any synthetic asset to be traded in a permissionless, transparent, and trader-focused platform for any person to tap into.";
        readonly documentation: "https://unidexexchange.gitbook.io/unidex/";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly sEUR: {
        readonly name: "Synth sEUR";
        readonly symbol: "sEUR";
        readonly oracleId: "sEUR";
        readonly address: "0xFBc4198702E81aE77c06D58f81b629BDf36f0a71";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://synthetix.io/";
        readonly description: "Forex Synths track the price of forex currencies via price feeds supplied by Chainlinks oracle network of distributed node operators.";
        readonly documentation: "https://docs.synthetix.io/tokens/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly frxETH: {
        readonly name: "Frax Ether";
        readonly symbol: "frxETH";
        readonly oracleId: "frxETH";
        readonly address: "0x6806411765Af15Bddd26f8f544A34cC40cb9838B";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.frax.finance/frxeth/mint";
        readonly description: "frxETH acts as a stablecoin loosely pegged to ETH, so that 1 frxETH always represents 1 ETH and the amount of frxETH in circulation matches the amount of ETH in the Frax ETH system. When ETH is sent to the frxETHMinter, an equivalent amount of frxETH is minted. Holding frxETH on its own is not eligible for staking yield and should be thought of as analogous as holding ETH.";
        readonly bridge: "frax";
        readonly documentation: "https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth";
    };
    readonly sfrxETHold: {
        readonly name: "Staked Frax Ether";
        readonly symbol: "sfrxETH";
        readonly oracleId: "sfrxETH";
        readonly address: "0x484c2D6e3cDd945a8B2DF735e079178C1036578c";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.frax.finance/frxeth/mint";
        readonly description: "sfrxETH is a ERC-4626 vault designed to accrue the staking yield of the Frax ETH validators. At any time, frxETH can be exchanged for sfrxETH by depositing it into the sfrxETH vault, which allows users to earn staking yield on their frxETH. Over time, as validators accrue staking yield, an equivalent amount of frxETH is minted and added to the vault, allowing users to redeem their sfrxETH for an greater amount of frxETH than they deposited. ";
        readonly bridge: "frax";
        readonly documentation: "https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth";
    };
    readonly MLP: {
        readonly name: "MLP";
        readonly symbol: "MLP";
        readonly oracleId: "mmy-op-mlp";
        readonly address: "0xB280D03909Cc18640621955Cb3bC30948DF2Fa9a";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.mummy.finance/#/trade?ref=beefy";
        readonly description: "MLP consists of an index of assets used for swaps and leverage trading on Mummy Finance. MLP holders will make a profit when leverage traders make a loss and vice versa. Staked MLP also earns escrowed MMY rewards and 60% of platform fees distributed in ETH.";
        readonly documentation: "https://docs.mummy.finance/mlp";
    };
    readonly LINK: {
        readonly name: "ChainLink Token";
        readonly symbol: "LINK";
        readonly oracleId: "LINK";
        readonly address: "0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://chain.link/";
        readonly description: "Link is the currency used to pay the Chainlink node operators for their work. Chainlink node operators have to stake LINK in the network in order to participate and provide data services.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.chain.link/resources/link-token-contracts";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly BOB: {
        readonly name: "BOB";
        readonly symbol: "BOB";
        readonly oracleId: "BOB";
        readonly address: "0xB0B195aEFA3650A6908f15CdaC7D92F8a5791B0B";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.zkbob.com/";
        readonly description: "BOB is a multi-chain & multi-collateral stable token (stablecoin) enhanced with optional privacy features.";
        readonly documentation: "https://docs.zkbob.com/bob-stablecoin/bob-highlights";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly KNC: {
        readonly name: "Kyber Network Crystal v2";
        readonly symbol: "KNC";
        readonly oracleId: "KNC";
        readonly address: "0xa00E3A3511aAC35cA78530c85007AFCd31753819";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://kyberswap.com/swap/optimism";
        readonly description: "KNC is a utility and governance token and an integral part of Kyber Network and its product KyberSwap - the multi-chain decentralized exchange (DEX) protocol that provides the best rates for traders and maximizes earnings for liquidity providers";
        readonly documentation: "https://docs.kyberswap.com/";
    };
    readonly UNLOCK: {
        readonly name: "Unlock Token";
        readonly symbol: "UNLOCK";
        readonly oracleId: "UNLOCK";
        readonly address: "0x7aE97042a4A0eB4D1eB370C34BfEC71042a056B7";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://200keys.com/";
        readonly description: "The UNLOCK token is part of the 200 Keys NFT project ecosystem where it can be staked for rewards or used for minting and upgrading NFTs from The Forge";
        readonly documentation: "https://200keys.com/tokenomics.pdf";
    };
    readonly '3CRV': {
        readonly name: "Curve DAI/USDC/USDT";
        readonly symbol: "3CRV";
        readonly address: "0x1337BedC9D22ecbe766dF105c9623922A27963EC";
        readonly chainId: 1;
        readonly decimals: 18;
        readonly website: "https://curve.finance/";
        readonly oracle: "lps";
        readonly oracleId: "curve-op-3crv";
        readonly description: "Curve Optimism base 3pool consisting of DAI, USDC and USDT";
        readonly bridge: "optimism-canonical";
    };
    readonly CRV: {
        readonly name: "CRV";
        readonly address: "0x0994206dfE8De6Ec6920FF4D779B0d950605Fb53";
        readonly symbol: "CRV";
        readonly oracleId: "CRV";
        readonly decimals: 18;
        readonly chainId: 10;
        readonly website: "https://curve.finance/";
        readonly description: "Curve is an exchange liquidity pool on Ethereum. Curve is designed for extremely efficient stablecoin trading and low risk, supplemental fee income for liquidity providers, without an opportunity cost.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://curve.readthedocs.io/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly STG: {
        readonly name: "StargateToken";
        readonly symbol: "STG";
        readonly oracleId: "STG";
        readonly address: "0x296F55F8Fb28E498B858d0BcDA06D955B2Cb3f97";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://stargate.finance/";
        readonly description: "Stargate is a community-driven organization building the first fully composable native asset bridge, and the first dApp built on LayerZero.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://stargateprotocol.gitbook.io/stargate/v/user-docs/";
    };
    readonly wTBT: {
        readonly name: "wTBT(Bridge Token)";
        readonly symbol: "wTBT";
        readonly oracleId: "wTBT";
        readonly address: "0xdb4eA87fF83eB1c80b8976FC47731Da6a31D35e5";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.tprotocol.io/";
        readonly description: "The launch of TProtocol will drastically alter the current DeFi picture and add an important missing piece, making DeFi users able to benefit from the mid-term interest rate gap between the stables and rising treasury. TProtocol will provide permissionless interest bearing tokens backed by the treasury with short duration. The redemption price of this treasury token will increase over time as interest from treasury accrues into the tokens.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://tprotocol.gitbook.io/tprotocol-documentation/white-paper/tprotocol-documentation";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly MTA: {
        readonly name: "Meta";
        readonly symbol: "MTA";
        readonly oracleId: "MTA";
        readonly address: "0x929B939f8524c3Be977af57A4A0aD3fb1E374b50";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://mstable.org/";
        readonly description: "Meta Vault is a composable architecture for yield-bearing tokens. It combines, optimises and allocates yield in a diversified manner.";
        readonly bridge: "optimism-canonical";
        readonly documentation: "https://docs.mstable.org/";
    };
    readonly VELOV2: {
        readonly name: "VelodromeV2";
        readonly symbol: "VELOV2";
        readonly oracleId: "VELOV2";
        readonly address: "0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.velodrome.finance/";
        readonly description: "Velodrome Finance, at its core, is a solution for protocols on Optimism to properly incentivize liquidity for their own use cases. Building on top of the groundwork laid out by Solidly, our team has addressed that first iteration's core issues to realize its full potential.";
        readonly documentation: "https://velodrome.finance/docs";
        readonly bridge: "native";
    };
    readonly EXA: {
        readonly name: "Exactly";
        readonly symbol: "EXA";
        readonly oracleId: "EXA";
        readonly address: "0x1e925De1c68ef83bD98eE3E130eF14a50309C01B";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://exact.ly/";
        readonly description: "Exactly is a decentralized, non-custodial and open-source protocol that provides an autonomous fixed and variable interest rate market enabling users to frictionlessly exchange the time value of their assets and completing the DeFi credit market.";
        readonly documentation: "https://docs.exact.ly/";
        readonly bridge: "native";
    };
    readonly tBTC: {
        readonly name: "tBTC v2";
        readonly symbol: "tBTC";
        readonly oracleId: "tBTC";
        readonly address: "0x6c84a8f1c29108F47a79964b5Fe888D4f4D0dE40";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://threshold.network/";
        readonly documentation: "https://docs.threshold.network/";
        readonly description: "Threshold is the first ever on-chain merge between two existing networks and communities, Keep and NuCypher. Threshold provides a suite of threshold cryptography services that power user sovereignty on the blockchain.";
        readonly bridge: "optimism-canonical";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly UNIDX: {
        readonly name: "Unidex";
        readonly symbol: "UNIDX";
        readonly oracleId: "UNIDX";
        readonly address: "0x28b42698Caf46B4B012CF38b6C75867E0762186D";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.unidex.exchange/trading";
        readonly description: "UniDex is building on top of the existing landscape by introducing a perpetual leverage trading platform that will allow any synthetic asset to be traded in a permissionless, transparent, and trader-focused platform for any person to tap into.";
        readonly bridge: "synapse";
        readonly documentation: "https://unidexexchange.gitbook.io/unidex/";
    };
    readonly WLD: {
        readonly name: "Worldcoin";
        readonly symbol: "WLD";
        readonly oracleId: "WLD";
        readonly address: "0xdC6fF44d5d932Cbd77B52E5612Ba0529DC6226F1";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://worldcoin.org/";
        readonly description: "WLD is a token that is part of the Worldcoin network. It is issued to all network participants to align their incentives around the growth of the network. The currency is designed to be distributed fairly, with every human being eligible for a share of WLD simply for being human. While laws may not allow for the use of WLD as a currency in some jurisdictions, it is intended to be used as a means of exchange and store of value where possible.";
        readonly documentation: "https://whitepaper.worldcoin.org/";
        readonly bridge: "optimism-canonical";
    };
    readonly wUSDR: {
        readonly name: "Real USD";
        readonly symbol: "wUSDR";
        readonly oracleId: "owUSDR";
        readonly address: "0xC03b43d492d904406db2d7D57e67C7e8234bA752";
        readonly chainId: 137;
        readonly decimals: 9;
        readonly website: "https://www.tangible.store/realusd";
        readonly documentation: "https://docs.tangible.store/";
        readonly description: "Real USD (USDR) is the world’s first stablecoin collateralized by tokenized, yield-producing real estate. USDR has a value accrual system built into its design. Using a consistent stream of dependable yield derived from rental revenue, Real USD delivers a native yield to holders.";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly OVN: {
        readonly name: "OVN";
        readonly symbol: "OVN";
        readonly oracleId: "oOVN";
        readonly address: "0x3b08fcd15280e7B5A6e404c4abb87F7C774D1B2e";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://overnight.fi/";
        readonly description: "OVN token is a utility token that serves multiple purposes in the Overnight protocol. It is used for bribes to promote USD+ and incentivize conservative risk decisions, as well as for voting rights to establish decentralized risk monitoring and management processes.";
        readonly bridge: "native";
        readonly documentation: "https://docs.overnight.fi/";
    };
    readonly JRT: {
        readonly name: "Jarvis Reward Token";
        readonly symbol: "JRT";
        readonly oracleId: "JRT";
        readonly address: "0x15e770B95Edd73fD96b02EcE0266247D50895E76";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://jarvis.network/";
        readonly description: "Jarvis Governance Token";
        readonly documentation: "https://learn.jarvis.network/";
        readonly bridge: "optimism-canonical";
    };
    readonly PENDLE: {
        readonly name: "Pendle";
        readonly symbol: "PENDLE";
        readonly oracleId: "PENDLE";
        readonly address: "0xBC7B1Ff1c6989f006a1185318eD4E7b5796e66E1";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.pendle.finance/";
        readonly description: "Pendle is a permissionless yield-trading protocol where users can execute various yield-management strategies.";
        readonly documentation: "https://docs.pendle.finance/home?utm_source=landing&utm_medium=landing";
        readonly bridge: "optimism-canonical";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly ankrETH: {
        readonly name: "Ankr Staked ETH";
        readonly symbol: "ankrETH";
        readonly oracleId: "ankrETH";
        readonly address: "0xe05A08226c49b636ACf99c40Da8DC6aF83CE5bB3";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.ankr.com/";
        readonly description: "ankrETH is a liquid staking solution that lets users earn Ethereum staking rewards while remaining liquid. The value of ankrETH tokens appreciates over time in relation to ETH due to reward accumulation, enhancing capital efficiency and preserving liquidity.";
        readonly documentation: "https://www.ankr.com/docs/liquid-staking/eth/overview/";
        readonly bridge: "ankr";
    };
    readonly NEXT: {
        readonly name: "Connext";
        readonly symbol: "NEXT";
        readonly oracleId: "NEXT";
        readonly address: "0x58b9cB810A68a7f3e1E4f8Cb45D1B9B3c79705E8";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.connext.network";
        readonly description: "Connext is a modular protocol for securely passing funds and data between chains. Developers can use Connext to build crosschain apps (xApps) - applications that interact with multiple domains (blockchains and/or rollups) simultaneously.";
        readonly documentation: "https://dao-docs.connext.network/";
        readonly bridge: "connext";
    };
    readonly KUJI: {
        readonly name: "Kujira native asset";
        readonly symbol: "KUJI";
        readonly oracleId: "KUJI";
        readonly address: "0x3A18dcC9745eDcD1Ef33ecB93b0b6eBA5671e7Ca";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://kujira.network/";
        readonly description: "Kujira is a decentralized ecosystem revolutionizing payment infrastructure and providing sustainable FinTech solutions to protocols, builders, and web 3 users. An innovation hub of revenue-generating products with great user experience that allow retail investors to access opportunities previously only available to the wealthy and elite.";
        readonly documentation: "https://docs.kujira.app/";
        readonly bridge: "axelar";
    };
    readonly PSP: {
        readonly name: "ParaSwap";
        readonly symbol: "PSP";
        readonly oracleId: "PSP";
        readonly address: "0xd3594E879B358F430E20F82bea61e83562d49D48";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://paraswap.io/";
        readonly description: "ParaSwap aggregates decentralized exchanges and other DeFi services in one comprehensive interface to streamline and facilitate users' interactions with decentralized finance on Ethereum and EVM-compatible chains: Polygon, Avalanche, BSC & more to come.";
        readonly documentation: "https://doc.paraswap.network/";
        readonly bridge: "optimism-canonical";
    };
    readonly crvUSD: {
        readonly name: "Curve USD Stablecoin";
        readonly symbol: "crvUSD";
        readonly oracleId: "crvUSD";
        readonly address: "0xC52D7F23a2e460248Db6eE192Cb23dD12bDDCbf6";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly bridge: "optimism-canonical";
        readonly website: "https://curve.finance/crvusd";
        readonly description: "crvUSD is a collateralized-debt-position (CDP) stablecoin pegged to the US Dollar";
        readonly documentation: "https://docs.curve.finance/crvUSD/crvUSD/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly scrvUSD: {
        readonly name: "Savings crvUSD";
        readonly symbol: "scrvUSD";
        readonly oracleId: "scrvUSD";
        readonly address: "0x289f635106d5b822A505b39AC237A0AE9189335B";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.curve.finance/";
        readonly description: "Savings crvUSD, abbreviated as scrvUSD, is an interest-bearing stablecoin that earns yield simply by holding the token.";
        readonly documentation: "https://resources.curve.finance/crvusd/scrvusd";
        readonly bridge: "optimism-canonical";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly sFRAX: {
        readonly name: "Staked FRAX";
        readonly symbol: "sFRAX";
        readonly oracleId: "sFRAX";
        readonly address: "0x2Dd1B4D4548aCCeA497050619965f91f78b3b532";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.frax.finance/sfrax/stake";
        readonly description: "Staked FRAX (sFRAX) is an ERC4626 staking vault that distributes part of the Frax Protocol yield weekly to stakers denominated in FRAX stablecoins. The sFRAX token represents pro rata deposits within the vault and is always withdrawable for FRAX stablecoins at the pro rata rate at all times. sFRAX APY attempts to roughly track the interest on reserve balances (IORB) rate of the United States Federal Reserve using the IORB oracle. This benchmark rate is generally accepted as the “risk free rate” of the US Dollar. The FRAX staking vault attempts, but does not guarantee in any way, to target this rate.";
        readonly documentation: "https://docs.frax.finance/frax-v3/sfrax";
        readonly bridge: "frax";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly POOL: {
        readonly name: "PoolTogether";
        readonly symbol: "POOL";
        readonly oracleId: "POOL";
        readonly address: "0x395Ae52bB17aef68C2888d941736A71dC6d4e125";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://pooltogether.com/";
        readonly description: "PoolTogether is a prize savings protocol, enabling you to win by saving.";
        readonly documentation: "https://docs.pooltogether.com/";
        readonly bridge: "optimism-canonical";
    };
    readonly USDV: {
        readonly name: "USDV";
        readonly symbol: "USDV";
        readonly oracleId: "USDV";
        readonly address: "0x323665443CEf804A3b5206103304BD4872EA4253";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://usdv.money/";
        readonly description: "Verified USD (USDV) is the first stablecoin that rewards Verified Minters based on their contribution to the tokens active circulation.";
        readonly documentation: "https://docs.usdv.money/docs";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly sDAI: {
        readonly name: "Savings xDAI";
        readonly symbol: "sDAI";
        readonly oracleId: "sDAI";
        readonly address: "0x2218a117083f5B482B0bB821d27056Ba9c04b1D3";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://spark.fi/";
        readonly description: "Savings Dai (sDAI) is an ERC-4626 representation/wrapper of DAI in the Dai Savings Rate (DSR) module. sDAI allows users to deposit DAI to receive the yield generated by the Maker protocol while still being able to transfer, stake, lend and use it in any way you want.";
        readonly documentation: "https://docs.spark.fi/";
        readonly bridge: "optimism-canonical";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly aOptUSDCn: {
        readonly name: "Aave Optimism USDCn";
        readonly symbol: "aOptUSDCn";
        readonly oracleId: "aOptUSDCn";
        readonly address: "0x38d693cE1dF5AaDF7bC62595A37D667aD57922e5";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Aave interest bearing native USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly staked: true;
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly aOptUSDC: {
        readonly name: "Aave Optimism USDC";
        readonly symbol: "aOptUSDC";
        readonly oracleId: "aOptUSDC";
        readonly address: "0x625E7708f30cA75bfd92586e17077590C60eb4cD";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://docs.aave.com/developers/v/2.0/the-core-protocol/atokens";
        readonly description: "Aave interest bearing USDC. USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly staked: true;
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly wrsETH: {
        readonly name: "rsETHWrapper";
        readonly symbol: "wrsETH";
        readonly oracleId: "wrsETH";
        readonly address: "0x87eEE96D50Fb761AD85B1c982d28A042169d61b1";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://kelpdao.xyz/";
        readonly description: "The rsETHWrapper contract serves as a standardized interface for rsETH tokens, which are Liquid Restaked Tokens (LRT) issued by Kelp DAO. Designed to offer liquidity to illiquid assets deposited into restaking platforms like EigenLayer, users can interact with these tokens seamlessly.";
        readonly documentation: "https://kelp.gitbook.io/kelp";
        readonly bridge: "stargate";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly HAI: {
        readonly name: "HAI";
        readonly symbol: "HAI";
        readonly oracleId: "baseHAI";
        readonly address: "0x10398AbC267496E49106B07dd6BE13364D10dC71";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.letsgethai.com/";
        readonly description: "HAI is a stablecoin protocol that is backed by a variety of collaterals. It maintains its stability through the use of a PI controller which dynamically sets interest rates that affect the price of HAI. HAI is backed by the value of the various collateral assets locked by users who mint HAI, similar to how traditional currencies used to be backed by gold or other assets.";
        readonly documentation: "https://docs.letsgethai.com/";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly KITE: {
        readonly name: "KITE";
        readonly symbol: "KITE";
        readonly oracleId: "KITE";
        readonly address: "0xf467C7d5a4A9C4687fFc7986aC6aD5A4c81E1404";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.letsgethai.com/";
        readonly description: "KITE is the governance token for the HAI Protocol. Holders can participate in voting for system changes and have a say in the protocol's development (e.g., adding/removing collateral types).";
        readonly documentation: "https://docs.letsgethai.com/";
        readonly bridge: "native";
    };
    readonly rsETH: {
        readonly chainId: 10;
        readonly address: "0x4186BFC76E2E237523CBC30FD220FE055156b41F";
        readonly decimals: 18;
        readonly name: "KelpDao Restaked ETH";
        readonly symbol: "rsETH";
        readonly oracleId: "rsETH";
        readonly website: "https://kelpdao.xyz/";
        readonly documentation: "https://kelp.gitbook.io/kelp";
        readonly description: "rsETH is a Liquid Restaked Token (LRT) issued by Kelp DAO designed to offer liquidity to illiquid assets deposited into restaking platforms, such as EigenLayer.";
        readonly bridge: "stargate";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly USDM: {
        readonly name: "Mountain Protocol USD";
        readonly symbol: "USDM";
        readonly oracleId: "USDM";
        readonly address: "0x59D9356E565Ab3A36dD77763Fc0d87fEaf85508C";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://mountainprotocol.com/";
        readonly documentation: "https://docs.mountainprotocol.com/";
        readonly description: "The USDM token is a rebasing ERC20 token, redeemable at a pegged 1:1 USD value by primary users. USDM is a fully backed stablecoin, backed by \"USDM Reserves\", which are held under custody with regulated financial institutions in bankruptcy-remote accounts, segregated from the Company's operating accounts, on behalf of, and for the benefit of, Users.";
        readonly bridge: "native";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly USDe: {
        readonly name: "USDe";
        readonly symbol: "USDe";
        readonly oracleId: "USDe";
        readonly address: "0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://ethena.fi/";
        readonly documentation: "https://ethena-labs.gitbook.io/ethena-labs";
        readonly description: "Ethenas USDe is not the same as a fiat stablecoin like USDC or USDT. USDe is a synthetic dollar, backed with crypto assets and corresponding short futures positions.";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "SYNTHETIC"];
    };
    readonly weETH: {
        readonly name: "Wrapped eETH";
        readonly symbol: "weETH";
        readonly oracleId: "weETH";
        readonly address: "0x5A7fACB970D094B6C7FF1df0eA68D99E6e73CBFF";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://ether.fi/";
        readonly description: "Stake ETH, get eETH - a natively restaked liquid staking token that fuels DeFi and decentralizes Ethereum.";
        readonly documentation: "https://etherfi.gitbook.io/etherfi";
        readonly bridge: "stargate";
        readonly tags: readonly ["BLUECHIP", "NO_TIMELOCK"];
    };
    readonly ZRO: {
        readonly name: "LayerZero";
        readonly symbol: "ZRO";
        readonly oracleId: "ZRO";
        readonly address: "0x6985884C4392D348587B19cb9eAAf157F13271cd";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://layerzero.network/";
        readonly documentation: "https://docs.layerzero.network/v2";
        readonly description: "ZRO is the native asset of the LayerZero protocol. LayerZero is an omnichain interoperability protocol that supports censorship-resistant messages and permissionless development through immutable smart contracts called Endpoints.";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["BLUECHIP", "NO_TIMELOCK"];
    };
    readonly ezETH: {
        readonly name: "Renzo Restaked ETH";
        readonly symbol: "ezETH";
        readonly oracleId: "ezETH";
        readonly address: "0x2416092f143378750bb29b79eD961ab195CcEea5";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.renzoprotocol.com/";
        readonly description: "Renzo ezETH is a Liquid Restaking Token (LRT) and Strategy Manager for EigenLayer. It is the interface to the EigenLayer ecosystem securing Actively Validated Services (AVSs) and offering a higher yield than ETH staking.";
        readonly documentation: "https://docs.renzoprotocol.com/docs/";
        readonly bridge: "optimism-canonical";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly TLX: {
        readonly name: "TLX DAO Token";
        readonly symbol: "TLX";
        readonly oracleId: "TLX";
        readonly address: "0xD9cC3D70E730503E7f28c1B407389198c4B75FA2";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://tlx.fi/";
        readonly description: "TLX is the native governance token of the TLX protocol. TLX is a permissionless, non-custodial leveraged token platform built on Optimism.";
        readonly documentation: "https://docs.tlx.fi/";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly msUSD: {
        readonly name: "Metronome Synth USD";
        readonly symbol: "msUSD";
        readonly oracleId: "opmsUSD";
        readonly address: "0x9dAbAE7274D28A45F0B65Bf8ED201A5731492ca0";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly description: "msUSD represents Metronome Synth USD. Through the Metronome dApp, users are able to deposit crypto assets as collateral, and use that collateral to mint popular crypto synthetics.";
        readonly website: "https://metronome.io/";
        readonly documentation: "https://docs.metronome.io/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN", "SYNTHETIC"];
    };
    readonly msETH: {
        readonly name: "Metronome Synth ETH";
        readonly symbol: "msETH";
        readonly oracleId: "msETH";
        readonly address: "0x1610e3c85dd44Af31eD7f33a63642012Dca0C5A5";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly description: "msETH represents Metronome Synth ETH. Through the Metronome dApp, users are able to deposit crypto assets as collateral, and use that collateral to mint popular crypto synthetics.";
        readonly website: "https://metronome.io/";
        readonly documentation: "https://docs.metronome.io/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "SYNTHETIC"];
    };
    readonly uniBTC: {
        readonly name: "Universal BTC";
        readonly symbol: "uniBTC";
        readonly oracleId: "uniBTC";
        readonly address: "0x552b0C6688FCaE5cF0164F27Fd129b882a42fA05";
        readonly chainId: 10;
        readonly decimals: 8;
        readonly website: "https://app.bedrock.technology/unibtc";
        readonly description: "A brand new restaking protocol that accept wrapped BTC tokens partnership with the BTC staking protocol Babylon chain, the first supported wrapped BTC is wBTC token on Ethereum blockchain, so all the wBTC token holders will enjoy both yield on staking BTC tokens plus the security of Ethereum network.";
        readonly bridge: "native";
        readonly documentation: "https://docs.bedrock.technology/multi-asset-liquid-staking/unibtc/introduction";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly pxETH: {
        readonly name: "Pirex Ether OFT";
        readonly symbol: "pxETH";
        readonly oracleId: "pxETH";
        readonly address: "0x300d2c875C6fb8Ce4bf5480B4d34b7c9ea8a33A4";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly description: "pxETH is an Ethereum liquid staking solution that forms the foundation of the Dinero protocol.";
        readonly website: "https://dinero.xyz/";
        readonly documentation: "https://dinero.xyz/docs";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly WELL: {
        readonly name: "WELL";
        readonly symbol: "WELL";
        readonly oracleId: "oWELL";
        readonly address: "0xA88594D404727625A9437C3f886C7643872296AE";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly description: "WELL is the native governance token of the Moonwell protocol.";
        readonly website: "https://moonwell.fi/";
        readonly documentation: "https://docs.moonwell.fi/moonwell/discover/about-moonwell";
        readonly bridge: "native";
    };
    readonly msOP: {
        readonly name: "Metronome Synth OP";
        readonly symbol: "msOP";
        readonly oracleId: "msOP";
        readonly address: "0x33bCa143d9b41322479E8d26072a00a352404721";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly description: "msOP represents Metronome Synth OP. Through the Metronome dApp, users are able to deposit crypto assets as collateral, and use that collateral to mint popular crypto synthetics.";
        readonly website: "https://metronome.io/";
        readonly documentation: "https://docs.metronome.io/";
        readonly bridge: "layer-zero";
        readonly tags: readonly ["NO_TIMELOCK", "SYNTHETIC"];
    };
    readonly wUSDM: {
        readonly name: "Mountain Protocol USD";
        readonly symbol: "wUSDM";
        readonly oracleId: "opwUSDM";
        readonly address: "0x57F5E098CaD7A3D1Eed53991D4d66C45C9AF7812";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly description: "The wUSDM token is the wrapped version of USDM, redeemable at a pegged 1:1 USD value by primary users. USDM is a fully backed stablecoin, backed by \"USDM Reserves\", which are held under custody with regulated financial institutions in bankruptcy-remote accounts, segregated from the Company's operating accounts, on behalf of, and for the benefit of, Users.";
        readonly website: "https://mountainprotocol.com/";
        readonly documentation: "https://docs.mountainprotocol.com/";
        readonly bridge: "native";
        readonly tags: readonly ["NO_TIMELOCK", "STABLECOIN"];
    };
    readonly ALCX: {
        readonly name: "Alchemix";
        readonly symbol: "ALCX";
        readonly oracleId: "opALCX";
        readonly address: "0xE974B9b31dBFf4369b94a1bAB5e228f35ed44125";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly description: "Alchemix Finance is a future-yield-backed synthetic asset protocol and community DAO. The protocol gives you advances on various yield farming strategies via a synthetic token. The token represents a fungible claim on the underlying collateral in the Alchemix protocol, where the claim has to be made by a depositor of that collateral. The DAO will focus on funding projects that will help the Alchemix ecosystem grow, as well as the greater Ethereum community.";
        readonly website: "https://alchemix.fi/";
        readonly documentation: "https://alchemix-finance.gitbook.io/user-docs/";
        readonly bridge: "connext";
    };
    readonly SYN: {
        readonly name: "Synapse";
        readonly symbol: "SYN";
        readonly oracleId: "SYN";
        readonly address: "0x5A5fFf6F753d7C11A56A52FE47a177a87e431655";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://synapseprotocol.com/";
        readonly documentation: "https://synapse-3.gitbook.io/synapse-protocol";
        readonly description: "Synapse (SYN) is an interoperability protocol designed for safely and securely sending arbitrary data between blockchains.";
        readonly bridge: "synapse";
        readonly tags: readonly ["NO_TIMELOCK"];
    };
    readonly Bold: {
        readonly name: "Bold Stablecoin";
        readonly symbol: "BOLD";
        readonly oracleId: "oldBOLD";
        readonly address: "0x087C440F251Ff6Cfe62B86DdE1bE558B95b4bb9b";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.liquity.org/";
        readonly documentation: "https://docs.liquity.org/";
        readonly description: "BOLD is the USD-pegged stablecoin issued in Liquity V2. It is over-collateralized and backed only by WETH, wstETH, and rETH.";
        readonly bridge: "chainlink-ccip";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly OVER: {
        readonly name: "Overtime DAO Token";
        readonly symbol: "OVER";
        readonly oracleId: "OVER";
        readonly address: "0xedF38688b27036816A50185cAA430D5479e1C63e";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.overtime.io/";
        readonly description: "Overtime is an onchain sportsbook ecosystem with platforms for placing bets on popular sporting events and digital options trading.";
        readonly documentation: "https://docs.overtime.io/";
        readonly bridge: "chainlink-ccip";
        readonly tags: readonly ["MEMECOIN", "LARGE_HOLDERS", "NO_TIMELOCK"];
    };
    readonly BOLDV2: {
        readonly name: "BOLD Stablecoin";
        readonly symbol: "BOLD";
        readonly oracleId: "BOLD";
        readonly address: "0x03569CC076654F82679C4BA2124D64774781B01D";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://www.liquity.org/";
        readonly documentation: "https://docs.liquity.org/";
        readonly description: "BOLD is the USD-pegged stablecoin issued in Liquity V2. It is over-collateralized and backed only by WETH, wstETH, and rETH.";
        readonly bridge: "chainlink-ccip";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly waOptWETH: {
        readonly name: "Wrapped Optimism WETH Token";
        readonly symbol: "waOptWETH";
        readonly oracleId: "waOptWETH";
        readonly address: "0x464b808c2C7E04b07e860fDF7a91870620246148";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "native";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
    };
    readonly waOptrETH: {
        readonly name: "Wrapped Optimism rETH Token";
        readonly symbol: "waOptrETH";
        readonly oracleId: "waOptrETH";
        readonly address: "0x8e6a81b9d541A0CeA090818B62C4B2DE7f2A2Cf7";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly description: "Aave Staked rETH token";
        readonly bridge: "native";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
    };
    readonly waOptwstETH: {
        readonly name: "Wrapped Optimism wstETH Token";
        readonly symbol: "waOptwstETH";
        readonly oracleId: "waOptwstETH";
        readonly address: "0xbaF95bB30CDab3d5b7a11B67EDeF5631bD62be86";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://aave.com/";
        readonly description: "Aave Staked wstETH token";
        readonly bridge: "native";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
    };
    readonly waOptUSDCn: {
        readonly name: "Wrapped Optimism USDC Token";
        readonly symbol: "waOptUSDCn";
        readonly oracleId: "waOptUSDCn";
        readonly address: "0x41B334E9F2C0ED1f30fD7c351874a6071C53a78E";
        readonly chainId: 10;
        readonly decimals: 6;
        readonly website: "https://aave.com/";
        readonly description: "Aave Staked USDC token";
        readonly bridge: "native";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly sfrxUSD: {
        readonly chainId: 10;
        readonly address: "0x5Bff88cA1442c2496f7E475E9e7786383Bc070c0";
        readonly decimals: 18;
        readonly name: "Staked frax USD";
        readonly symbol: "sfrxUSD";
        readonly oracleId: "sfrxUSD";
        readonly website: "https://frax.finance/";
        readonly description: "sfrxUSD is a replacement for FRAX on Ethereum. sfrxUSD is a crypto collateralized stablecoin pegged to the US dollar.";
        readonly bridge: "layer-zero";
        readonly documentation: "https://docs.frax.finance/";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly sfrxETH: {
        readonly name: "Staked Frax Ether";
        readonly symbol: "sfrxETH";
        readonly oracleId: "sfrxETH";
        readonly address: "0x3Ec3849C33291a9eF4c5dB86De593EB4A37fDe45";
        readonly chainId: 10;
        readonly decimals: 18;
        readonly website: "https://app.frax.finance/frxeth/mint";
        readonly description: "sfrxETH is a ERC-4626 vault designed to accrue the staking yield of the Frax ETH validators. At any time, frxETH can be exchanged for sfrxETH by depositing it into the sfrxETH vault, which allows users to earn staking yield on their frxETH. Over time, as validators accrue staking yield, an equivalent amount of frxETH is minted and added to the vault, allowing users to redeem their sfrxETH for an greater amount of frxETH than they deposited. ";
        readonly bridge: "frax";
        readonly documentation: "https://docs.frax.finance/frax-ether/frxeth-and-sfrxeth";
    };
};
