#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

SRC_PATTERN="packages/address-book"
if git diff --cached --name-only | grep --quiet "$SRC_PATTERN"
then
    cd packages/address-book
    yarn test:ts
    yarn lint-staged
    yarn checksum
fi