export declare const tokens: {
    readonly WNATIVE: {
        readonly name: "Wrapped CRO";
        readonly address: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23";
        readonly symbol: "WCRO";
        readonly oracleId: "WCRO";
        readonly decimals: 18;
        readonly chainId: 25;
        readonly website: "https://cronos.crypto.org/";
        readonly description: "Crypto.com Coin";
        readonly bridge: "native";
        readonly documentation: "https://docs.cronos-pos.org/getting-started/introduction";
    };
    readonly FEES: {
        readonly name: "Wrapped CRO";
        readonly address: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23";
        readonly symbol: "WCRO";
        readonly oracleId: "WCRO";
        readonly decimals: 18;
        readonly chainId: 25;
        readonly website: "https://cronos.crypto.org/";
        readonly description: "Crypto.com Coin";
        readonly bridge: "native";
        readonly documentation: "https://docs.cronos-pos.org/getting-started/introduction";
    };
    readonly CRO: {
        readonly name: "Wrapped CRO";
        readonly address: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23";
        readonly symbol: "WCRO";
        readonly oracleId: "WCRO";
        readonly decimals: 18;
        readonly chainId: 25;
        readonly website: "https://cronos.crypto.org/";
        readonly description: "Crypto.com Coin";
        readonly bridge: "native";
        readonly documentation: "https://docs.cronos-pos.org/getting-started/introduction";
    };
    readonly WCRO: {
        readonly name: "Wrapped CRO";
        readonly address: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23";
        readonly symbol: "WCRO";
        readonly oracleId: "WCRO";
        readonly decimals: 18;
        readonly chainId: 25;
        readonly website: "https://cronos.crypto.org/";
        readonly description: "Crypto.com Coin";
        readonly bridge: "native";
        readonly documentation: "https://docs.cronos-pos.org/getting-started/introduction";
    };
    readonly FIRA: {
        readonly name: "Fira";
        readonly symbol: "FIRA";
        readonly oracleId: "FIRA";
        readonly address: "0x7ABa852082b6F763E13010CA33B5D9Ea4EeE2983";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://defira.com/";
        readonly description: "The FIRA token is the main governance token and currency for the Defiraverse. In the game world, it is known as the Fira Orb.";
    };
    readonly VERSA: {
        readonly name: "VersaGames VERSA";
        readonly symbol: "VERSA";
        readonly oracleId: "VERSA";
        readonly address: "0x00D7699b71290094CcB1a5884cD835bD65a78c17";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://versagames.io/";
        readonly description: "VersaGames is the next-generation games marketplace.";
    };
    readonly MTD: {
        readonly name: "Minted";
        readonly symbol: "MTD";
        readonly oracleId: "MTD";
        readonly address: "0x0224010BA2d567ffa014222eD960D1fa43B8C8E1";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://minted.network/";
        readonly description: "Minted network is a decentralised NFT platform that aspires to be the digital bazaar of wonders for everyone to discover, trade, and find NFT gems, native to Ethereum and Cronos.";
    };
    readonly FER: {
        readonly name: "Ferro";
        readonly symbol: "FER";
        readonly oracleId: "FER";
        readonly address: "0x39bC1e38c842C60775Ce37566D03B41A7A66C782";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://www.ferroprotocol.com/";
        readonly description: "Ferro Protocol is a StableSwap AMM protocol that allows users to exchange with low slippage and minimum fee and farm tokens by creating more efficient pools consisting of highly correlated assets, as well as allowing better composability between protocols in the Cronos ecosystem.";
    };
    readonly sCRO: {
        readonly name: "sCRO";
        readonly symbol: "sCRO";
        readonly oracleId: "sCRO";
        readonly address: "0xA01fAe0612a4786ec296Be7f87b292F05c68186B";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://cro.ripae.finance/";
        readonly description: "Ripae Finance’s full focus is to build a true cross-chain algorithmic stable coin protocol that is stabilized with true use-cases all around the DeFi Ecosystem.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly pCRO: {
        readonly name: "pCRO";
        readonly symbol: "pCRO";
        readonly oracleId: "pCRO";
        readonly address: "0xA5e6a847f79BA19AAF41b8e1B2e6C4741234C6b7";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://cro.ripae.finance/";
        readonly description: "Ripae Finance’s full focus is to build a true cross-chain algorithmic stable coin protocol that is stabilized with true use-cases all around the DeFi Ecosystem.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly APE: {
        readonly name: "APECoin";
        readonly symbol: "APE";
        readonly oracleId: "APE";
        readonly address: "0x9C62F89a8C9907582f21205Ce90443730361EA05";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://www.apecoin.com/";
        readonly description: "ApeCoin is an ERC-20 governance and utility token used within the APE ecosystem to empower a decentralized community building at the forefront of web3.";
    };
    readonly ALI: {
        readonly name: "Alethea Artificial Liquid Intelligence Token ALI";
        readonly symbol: "ALI";
        readonly oracleId: "ALI";
        readonly address: "0x45C135C1CDCE8d25A3B729A28659561385C52671";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://alethea.ai/";
        readonly description: "Alethea AI is building a decentralized protocol to create an Intelligent Metaverse inhabited by interactive and intelligent NFTs (iNFTs).";
    };
    readonly TUSD: {
        readonly name: "True USD";
        readonly symbol: "TUSD";
        readonly oracleId: "TUSD";
        readonly address: "0x87EFB3ec1576Dec8ED47e58B832bEdCd86eE186e";
        readonly decimals: 18;
        readonly chainId: 25;
        readonly website: "https://www.trueusd.com/";
        readonly description: "TrueUSD is one of a number of cryptocurrency stablecoins administered by TrustToken, a platform for tokenizing real-world assets.";
    };
    readonly SKY: {
        readonly chainId: 25;
        readonly address: "0x9D3BBb0e988D9Fb2d55d07Fe471Be2266AD9c81c";
        readonly decimals: 18;
        readonly name: "SKY";
        readonly symbol: "SKY";
        readonly oracleId: "darkSKY";
        readonly website: "https://www.darkcrypto.finance/";
        readonly description: "The first algorithmic token pegged to CRO running on the Cronos Chain";
    };
    readonly DARK: {
        readonly chainId: 25;
        readonly address: "0x83b2AC8642aE46FC2823Bc959fFEB3c1742c48B5";
        readonly decimals: 18;
        readonly name: "DARK";
        readonly symbol: "DARK";
        readonly oracleId: "DARK";
        readonly website: "https://www.darkcrypto.finance/";
        readonly description: "The first algorithmic token pegged to CRO running on the Cronos Chain";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly oldBIFI: {
        readonly chainId: 25;
        readonly address: "0xe6801928061CDbE32AC5AD0634427E140EFd05F9";
        readonly decimals: 18;
        readonly name: "Beefy.Finance";
        readonly symbol: "oldBIFI";
        readonly oracleId: "oldBIFI";
        readonly website: "https://www.beefy.finance/";
        readonly description: "Beefy Finance is a Decentralized, Multi-Chain Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings.";
        readonly documentation: "https://docs.beefy.finance/";
    };
    readonly TONIC: {
        readonly name: "Tectonic Governance Token";
        readonly symbol: "TONIC";
        readonly oracleId: "TONIC";
        readonly address: "0xDD73dEa10ABC2Bff99c60882EC5b2B81Bb1Dc5B2";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://tectonic.finance/";
        readonly description: "Tectonic is a cross-chain money market for earning passive yield and accessing instant backed loans";
        readonly bridge: "native";
    };
    readonly LIQ: {
        readonly name: "Liquidus";
        readonly symbol: "LIQ";
        readonly oracleId: "LIQ";
        readonly address: "0xABd380327Fe66724FFDa91A87c772FB8D00bE488";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://farm.liquidus.finance/";
        readonly description: "Earn interest on your decentralised crypto assets";
        readonly bridge: "multichain";
    };
    readonly ATOM: {
        readonly name: "Cosmos Token";
        readonly symbol: "ATOM";
        readonly oracleId: "ATOM";
        readonly address: "0xB888d8Dd1733d72681b30c00ee76BDE93ae7aa93";
        readonly chainId: 25;
        readonly decimals: 6;
        readonly website: "https://cosmos.network/";
        readonly description: "Cosmos is an ever-expanding ecosystem of interconnected apps and services, built for a decentralized future.";
        readonly bridge: "cronos-canonical";
        readonly documentation: "https://docs.cosmos.network/main";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly DOGE: {
        readonly name: "Doge Token";
        readonly symbol: "DOGE";
        readonly oracleId: "DOGE";
        readonly address: "0x1a8E39ae59e5556B56b76fCBA98d22c9ae557396";
        readonly chainId: 25;
        readonly decimals: 8;
        readonly website: "https://dogecoin.com/";
        readonly description: "Dogecoin is an open source peer-to-peer digital currency, favored by Shiba Inus worldwide.";
        readonly bridge: "cronos-canonical";
        readonly documentation: "https://dogecoin.com/dogepedia/#documentation";
        readonly tags: readonly ["MEMECOIN"];
    };
    readonly SHIB: {
        readonly name: "Shiba Inu";
        readonly symbol: "SHIB";
        readonly oracleId: "SHIB";
        readonly address: "0xbED48612BC69fA1CaB67052b42a95FB30C1bcFee";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://shibatoken.com/";
        readonly description: "According to the SHIBA INU website, SHIB is the “DOGECOIN KILLER” and will be listed on their own ShibaSwap, a decentralized exchange.";
        readonly bridge: "cronos-canonical";
        readonly documentation: "https://docs.shibatoken.com/";
        readonly tags: readonly ["MEMECOIN"];
    };
    readonly VVS: {
        readonly name: "VVSToken";
        readonly symbol: "VVS";
        readonly oracleId: "VVS";
        readonly address: "0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://vvs.finance";
        readonly description: "VVS is designed to be the simplest DeFi platform for users to swap tokens, earn high yields, and most importantly have fun!";
        readonly bridge: "native";
        readonly documentation: "https://docs.vvs.finance/";
    };
    readonly USDC: {
        readonly name: "USD Coin";
        readonly symbol: "USDC";
        readonly oracleId: "USDC";
        readonly address: "0xc21223249CA28397B4B6541dfFaEcC539BfF0c59";
        readonly chainId: 25;
        readonly decimals: 6;
        readonly website: "https://www.circle.com/usdc";
        readonly documentation: "https://developers.circle.com/docs";
        readonly description: "USDC is a fully collateralized US dollar stablecoin. USDC is issued by regulated financial institutions, backed by fully reserved assets, redeemable on a 1:1 basis for US dollars.";
        readonly bridge: "cronos-canonical";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly ETH: {
        readonly name: "Ethereum";
        readonly symbol: "ETH";
        readonly oracleId: "ETH";
        readonly address: "0xe44Fd7fCb2b1581822D0c862B68222998a0c299a";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://weth.io/";
        readonly description: "Ether or ETH is the native currency built on the Ethereum blockchain.";
        readonly bridge: "cronos-canonical";
        readonly documentation: "https://ethereum.org/en/developers/docs/";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly WBTC: {
        readonly name: "Wrapped BTC";
        readonly symbol: "WBTC";
        readonly oracleId: "WBTC";
        readonly address: "0x062E66477Faf219F25D27dCED647BF57C3107d52";
        readonly chainId: 25;
        readonly decimals: 8;
        readonly website: "https://wbtc.network/";
        readonly description: "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.";
        readonly bridge: "cronos-canonical";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly CRONA: {
        readonly name: "CronaSwap Token";
        readonly symbol: "CRONA";
        readonly oracleId: "CRONA";
        readonly address: "0xadbd1231fb360047525BEdF962581F3eee7b49fe";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://app.cronaswap.org/";
        readonly description: "CronaSwap is the first decentralized exchange platform on the Cronos Chain and the lowest platform transaction fees (0.25%).";
    };
    readonly USDT: {
        readonly name: "Tether USD";
        readonly symbol: "USDT";
        readonly oracleId: "USDT";
        readonly address: "0x66e428c3f67a68878562e79A0234c1F83c208770";
        readonly chainId: 25;
        readonly decimals: 6;
        readonly website: "https://tether.to/";
        readonly description: "Tether is a stablecoin pegged to the US Dollar. A stablecoin is a type of cryptocurrency whose value is pegged to another fiat currency like the US Dollar or to a commodity like Gold. Tether is the first stablecoin to be created and it is the most popular stablecoin used in the ecosystem.";
        readonly bridge: "cronos-canonical";
        readonly documentation: "https://tether.to/en/how-it-works";
        readonly tags: readonly ["STABLECOIN"];
    };
    readonly DAI: {
        readonly name: "DAI Token";
        readonly symbol: "DAI";
        readonly oracleId: "DAI";
        readonly address: "0xF2001B145b43032AAF5Ee2884e456CCd805F677D";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://makerdao.com/en/";
        readonly description: "DAI is an Ethereum-based stablecoin (stable-price cryptocurrency) whose issuance and development is managed by the Maker Protocol and the MakerDAO decentralized autonomous organization.";
        readonly bridge: "cronos-canonical";
        readonly documentation: "https://docs.makerdao.com/smart-contract-modules/dai-module/dai-detailed-documentation";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly BUSD: {
        readonly name: "BUSD Token";
        readonly symbol: "BUSD";
        readonly oracleId: "BUSD";
        readonly address: "0xC74D59A548ecf7fc1754bb7810D716E9Ac3e3AE5";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/en/busd";
        readonly description: "Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos), Approved and regulated by the New York State Department of Financial Services (NYDFS), The BUSD Monthly Audit Report can be viewed from the official website.";
        readonly tags: readonly ["STABLECOIN", "SYNTHETIC"];
    };
    readonly BUSDb: {
        readonly name: "BUSD Token (Multichain)";
        readonly symbol: "BUSD";
        readonly oracleId: "BUSDb";
        readonly address: "0x6aB6d61428fde76768D7b45D8BFeec19c6eF91A8";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/en/busd";
        readonly description: "Multichain bridged Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos), Approved and regulated by the New York State Department of Financial Services (NYDFS), The BUSD Monthly Audit Report can be viewed from the official website.";
        readonly tags: readonly ["SYNTHETIC"];
    };
    readonly MATIC: {
        readonly name: "MATIC Token";
        readonly symbol: "MATIC";
        readonly oracleId: "MATIC";
        readonly address: "0xc9BAA8cfdDe8E328787E29b4B078abf2DaDc2055";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://polygon.technology/";
        readonly description: "The MATIC token serves dual purposes: securing the Polygon network via staking and being used for the payment of transaction fees.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly AVAX: {
        readonly name: "Avalanche Token";
        readonly symbol: "AVAX";
        readonly oracleId: "AVAX";
        readonly address: "0x765277EebeCA2e31912C9946eAe1021199B39C61";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://www.avalabs.org/";
        readonly description: "Avalanche is the fastest smart contracts platform in the blockchain industry, as measured by time-to-finality, and has the most validators securing its activity of any proof-of-stake protocol.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly FTM: {
        readonly name: "Fantom Token";
        readonly symbol: "FTM";
        readonly oracleId: "FTM";
        readonly address: "0xB44a9B6905aF7c801311e8F4E76932ee959c663C";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://fantom.foundation/";
        readonly description: "Fantom is a fast, high-throughput open-source smart contract platform for digital assets and dApps.";
        readonly tags: readonly ["BLUECHIP"];
    };
    readonly BNB: {
        readonly name: "Binance Token";
        readonly symbol: "BNB";
        readonly oracleId: "BNB";
        readonly address: "0xfA9343C3897324496A05fC75abeD6bAC29f8A40f";
        readonly chainId: 25;
        readonly decimals: 18;
        readonly website: "https://www.binance.com/";
        readonly description: "Binance Coin (BNB) is an exchange-based token created and issued by the cryptocurrency exchange Binance. Initially created on the Ethereum blockchain as an ERC-20 token in July 2017, BNB was migrated over to Binance Chain in February 2019 and became the native coin of the Binance Chain.";
        readonly tags: readonly ["BLUECHIP"];
    };
};
