name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  biome:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v7
      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v6.0.9
      - name: 'Setup Node'
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: 'Install Packages'
        run: pnpm install --frozen-lockfile
      - name: 'Run Biome'
        run: pnpm biome ci --reporter github

  typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v7
      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v6.0.9
      - name: 'Setup Node'
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: 'Install Packages'
        run: pnpm install --frozen-lockfile
      - name: 'Run tsc'
        run: pnpm run test:ts
      - name: 'Run tsc (address-book)'
        run: pnpm --filter @beefyfinance/blockchain-addressbook run test:ts
